easylist_adult/adult_specific_hide.txt
hide placeholder at https://m.4tube.com/
**Mobile**
Screenshot:
=> A: [NSFW] https://m.4tube.com/

easylist/easylist_adservers.txt
Block adserver at https://kantotflix.com/
Screenshot:
=> A: [NSFW] https://kantotflix.com/

easylist/easylist_adservers.txt
Block adserver at https://wvw.123movies.college/
Screenshot:
=> A: https://wvw.123movies.college/

easylist/easylist_adservers.txt
Block adserver at https://filmy4wap.ink/
Screenshot:
=> A: https://filmy4wap.ink/

easylist/easylist_adservers.txt
Block adserver at https://www.apksforandroid.com/
Screenshot:
=> A: https://www.apksforandroid.com/

easylist/easylist_specific_hide.txt
Hide placeholders at https://www.flv2mp3.by/
Screenshot:
=> A: https://www.flv2mp3.by/

easylist/easylist_adservers.txt
Block adserver at https://1piecemanga.com/
Screenshot:
=> A: https://1piecemanga.com/

easylist/easylist_adservers.txt
Block adserver at https://anime-flix.net/
Screenshot:
=> A: https://anime-flix.net/

easylist/easylist_adservers.txt
Block adserver at https://wvw.blablastream.com/
Screenshot:
=> A: https://wvw.blablastream.com/

easylist/easylist_adservers.txt
Block adserver at https://dramacool.ac/
Screenshot:
=> A: https://dramacool.ac/

easylist/easylist_adservers.txt
Block adserver (popunders) at http://pornvideos4k.com/
Screenshot:
=> A: [NSFW] http://pornvideos4k.com/

easylist/easylist_adservers.txt
Block adserver at https://manhuascan.com/
Screenshot:
=> A: [NSFW] https://manhuascan.com/

easylist/easylist_adservers.txt
Block adserver at https://kumascans.com/
Screenshot:
=> A: https://kumascans.com/

easylist/easylist_adservers.txt
Block adserver at https://sexdicted.com/
Screenshot:
=> A: [NSFW] https://sexdicted.com/

easylist/easylist_adservers.txt
Block adserver at https://pisshamster.com/
Screenshot:
=> A: [NSFW] https://pisshamster.com/

easylist/easylist_adservers.txt
Block adserver responsible for gifs and images at https://zbporn.com/
Screenshots:
=> A: [NSFW] https://zbporn.com/

easylist_adult/adult_specific_block.txt, easylist_adult/adult_specific_hide.txt
Block popunders and block banners at http://footztube.com/
Screenshot:
=> A: [NSFW] http://footztube.com/

easylist_adult/adult_specific_hide.txt
Hide placeholders all over the page
Screenshot
=> A: [NSFW] http://alloldpics.com/

easylist/easylist_adservers.txt, easylist_adult/adult_specific_hide.txt
Block adserver related to banners + hide placeholders at https://gaypornarchive.com/
Screenshots:
=> A: [NSFW] https://gaypornarchive.com/

easylist/easylist_specific_hide.txt
Hide popups at https://mangceh.cc/
Screenshot:
=> A: https://mangceh.cc/

easylist/easylist_specific_hide.txt
Example: https://kit.co/LinusTech/intel-extreme-tech-upgrade-colin (right side)
=> A: https://kit.co/

easylist/easylist_adservers.txt
Block adserver at https://ldkmanga.com/
Screenshot:
=> A: https://ldkmanga.com/

easylist/easylist_specific_hide.txt
Hide iframe at https://herogayab.net/
Screenshot:
=> A: https://herogayab.net/

easylist/easylist_adservers.txt
Block adserver at https://nudostar.com/
Screenshot:
=> A: [NSFW] https://nudostar.com/

easylist/easylist_adservers.txt
Block adserver at https://wwv.filmstreaming01.org/
Screenshot:
=> A: https://wwv.filmstreaming01.org/

easylist_adult/adult_specific_hide.txt
Hide ads banner placeholder at https://www.cam4.com/
Screenshot:
=> A: [NSFW] https://www.cam4.com/

easylist/easylist_specific_hide.txt
Hide placeholders at https://rankedboost.com/
**Mobile**
Screenshot:
=> A: https://rankedboost.com/

easylist/easylist_adservers.txt
Block adserver at https://o2tvseries.com/
Screenshot:
=> A: https://o2tvseries.com/

easylist/easylist_adservers.txt
Block adserver at https://solarmovie.pe/
Screenshot:
=> A: https://solarmovie.pe/

easylist/easylist_adservers.txt
Block adserver at https://www.hdss.cam/
Screenshot:
=> A: https://www.hdss.cam/

easylist/easylist_thirdparty.txt
Block third-party adserver at https://m.animeflv.net/
Screenshot:
=> A: https://m.animeflv.net/

easylist/easylist_adservers.txt
Block adserver at https://leak.xxx/
Screenshot:
=> A: [NSFW] https://leak.xxx/

easylist_adult/adult_specific_hide.txt
Hide pop fade at https://www.porntrex.com/
Screenshot:
=> A: [NSFW] https://www.porntrex.com/

easyprivacy/easyprivacy_allowlist_international.txt
=> P: www.satofull.jp

easylist_adult/adult_specific_hide.txt
Hide button to close ads before video at https://teenager365.com/
Screenshot:
=> A: https://teenager365.com/

easylist_adult/adult_specific_block.txt, easylist_adult/adult_specific_hide.txt
Block popunders at https://hentai2read.com/
Screenshot:
=> A: [NSFW] https://hentai2read.com/

easylist/easylist_adservers.txt
Block adserver at https://4stream.gg/
Screenshot:
=> A: https://4stream.gg/

easylist/easylist_adservers.txt
Block adserver at http://manhwa18.net/
Screenshot:
=> A: [NSFW] http://manhwa18.net/

easylist/easylist_adservers.txt
Block adserver at https://www.1377x.to/
Screenshot:
=> A: https://www.1377x.to/

easylist/easylist_adservers.txt
Block adserver at https://www.porngo.com/
Screenshot:
=> A: [NSFW] https://www.porngo.com/

easylist/easylist_adservers.txt
Block adserver at https://inmanga.com/
Screenshot:
=> A: https://inmanga.com/

easylist/easylist_adservers.txt
Block adserver at https://mangakik.net/
Screenshot:
=> A: https://mangakik.net/

easylist/easylist_adservers.txt
Block adserver at https://tamilblasters.club/
Screenshot:
=> A: https://tamilblasters.club/

easylist/easylist_adservers.txt
Block adserver at https://everia.club/
Screenshot:
=> A: [NSFW] https://everia.club/

easylist/easylist_adservers.txt
Block adserver at https://masahub.net/
Screenshot:
=> A: [NSFW] https://masahub.net/

easylist_adult/adult_specific_hide.txt
Hide text ad at https://palimas.org/
Screenshot:
=> A: [NSFW] https://palimas.org/

easylist_adult/adult_specific_hide.txt
Block adserver at https://teenmastube.com/
Screenshot:
=> A: [NSFW] https://teenmastube.com/

easylist_adult/adult_specific_block.txt
Block side ad gifs + popups at https://www.striptube.net/
Screenshot:
=> A: [NSFW] https://www.striptube.net/

easylist/easylist_specific_hide.txt
Hide ads at https://xxxporn.tube/
Screenshot:
=> A: [NSFW] https://xxxporn.tube/

easylist_adult/adult_specific_hide.txt
Hide placeholder while pausing videos at https://anysex.com/
Screenshot:
=> A: [NSFW] https://anysex.com/

easylist_adult/adult_specific_hide.txt
Hide placeholder while pausing videos at http://www.maturesladies.com/
Screenshot:
=> A: [NSFW] http://www.maturesladies.com/

easylist/easylist_adservers.txt
Block adserver at https://www2.kickassanime.ro/
Screenshot:
=> A: https://www2.kickassanime.ro/

easylist/easylist_adservers.txt
Block adserver at https://sorrymother.video/
Screenshot:
=> A: [NSFW] https://sorrymother.video/

easylist/easylist_specific_hide.txt
Hide ad text at https://greedyfinance.com/
Screenshot:
=> A: https://greedyfinance.com/

easylist_adult/adult_specific_hide.txt
Hide placeholders at http://h2porn.com/
Screenshot:
=> A: [NSFW] http://h2porn.com/

easylist_adult/adult_specific_block.txt
Block side and footer banners at https://www.sunporno.com/
Screenshot:
=> A: [NSFW] https://www.sunporno.com/

easylist_adult/adult_specific_block.txt
Block gifs at https://www.slutdump.com/
Screenshot:
=> A: [NSFW] https://www.slutdump.com/

easylist/easylist_general_hide.txt, easylist/easylist_specific_hide.txt
Hide placeholder at https://www.detik.com/
Screenshot:
=> A: https://www.detik.com/

easylist_adult/adult_specific_block.txt
Block gifs at https://mylust.com/
Screenshot:
=> A: [NSFW] https://mylust.com/

easylist/easylist_specific_block.txt
Block gifs at https://ww1.kiss-anime.org/
Screenshot:
=> A: https://ww1.kiss-anime.org/

easylist/easylist_adservers.txt
Block adserver at https://komikcast.com/
Screenshot:
=> A: https://komikcast.com/

easylist/easylist_adservers.txt
Block adserver at https://kissasian.sk/
Screenshot:
=> A: https://kissasian.sk/

easylist/easylist_adservers.txt
Block adserver at https://www.ducine.site/
Screenshot:
=> A: https://www.ducine.site/

easylist/easylist_adservers.txt
Block adserver at https://en.viprow.me/
Screenshot:
=> A: https://en.viprow.me/

easylist_adult/adult_specific_hide.txt
Hide ads at androidadult.com
Screenshot:
=> A: [NSFW] androidadult.com

easylist/easylist_adservers.txt
Block adserver at https://www.ultrateengirls.com/
Screenshot:
=> A: [NSFW] https://www.ultrateengirls.com/

easylist/easylist_adservers.txt
Block adserver at https://ww.movies123.sbs/
Screenshot:
=> A: https://ww.movies123.sbs/

easylist/easylist_adservers.txt
block adserver at https://www.actvid.com/
Screenshot:
=> A: https://www.actvid.com/

easylist/easylist_adservers.txt, easylist/easylist_specific_block.txt
Block adserver at http://waptrick.one/
Screenshot:
=> A: http://waptrick.one/

easylist_adult/adult_specific_block.txt
Hide side and footer banners at https://xxxfetish24.com/
=> A: [NSFW] https://xxxfetish24.com/

easylist/easylist_adservers.txt
Block adserver related to side banners at https://freegaypornovids.com/
Screenshot:
=> A: [NSFW] https://freegaypornovids.com/

easylist/easylist_adservers.txt
Block adserver at https://cineb.net/
Screenshot:
=> A: https://cineb.net/

easylist/easylist_adservers.txt
Block adserver at https://cervezaporno.com/
Screenshot:
=> A: [NSFW] https://cervezaporno.com/

easylist/easylist_adservers.txt
Block adserver at https://porncomixone.net/
Screenshot:
=> A: [NSFW] https://porncomixone.net/

easylist/easylist_adservers.txt
Block adservers at https://www1.bemovies.to/
Screenshot:
=> A: https://www1.bemovies.to/

easylist/easylist_adservers.txt
Block adservers at https://mitly.us/
Screenshots:
=> A: https://mitly.us/

easylist/easylist_adservers.txt
Block adservers at https://rule34hentai.net/
Screenshot:
=> A: [NSFW] https://rule34hentai.net/

easylist/easylist_adservers.txt
Block adserver at https://w13.mangafreak.net/
Screenshots:
=> A: https://w13.mangafreak.net/

easylist/easylist_adservers.txt
Block adserver at https://platinmods.com/
Screenshot:
=> A: https://platinmods.com/

easylist/easylist_adservers.txt, easylist_adult/adult_specific_block.txt
Block script and adserver at https://www.xcity.org/
Screenshot:
=> A: [NSFW] https://www.xcity.org/

easylist/easylist_specific_block.txt
Block popup ad at https://flixtor.stream/
Screenshot:
=> A: https://flixtor.stream/

easylist/easylist_specific_hide.txt
Hide popups at https://gogoanime.lol/
Screenshots:
=> A: https://gogoanime.lol/

easylist/easylist_adservers.txt
Block popups/popunders at https://sextb.net/
Screenshot:
=> A: [NSFW]  https://sextb.net/

easylist/easylist_specific_hide.txt
Hide iframe at https://vw.ssoap2day.to/
Screenshot:
=> A: https://vw.ssoap2day.to/

easylist_adult/adult_specific_hide.txt
Hide inner banner at:
Screenshot:
=> A: [NSFW] https://pornmonde.com/

easylist/easylist_adservers.txt
Block adserver at https://fr.movizland.biz/
Screenshot:
=> A: https://fr.movizland.biz/

easylist/easylist_adservers.txt
Block adserver at https://manhwax.com/
Screenshot:
=> A: https://manhwax.com/

easylist/easylist_adservers.txt
Block adserver at https://bato.to/
Screenshots:
=> A: https://bato.to/

easylist/easylist_adservers.txt
Block adserver at https://pelispop.me/
Screenshot:
=> A: https://pelispop.me/

easylist/easylist_adservers.txt
Block adserver at https://tamilblasters.icu/
Screenshot:
=> A: https://tamilblasters.icu/

easylist/easylist_adservers.txt
Block adserver at https://dramacool.ps/
Screenshot:
=> A: https://dramacool.ps/

easylist/easylist_adservers.txt
Block adserver at https://myflixer.top/
Screenshot:
=> A: https://myflixer.top/

easylist/easylist_adservers.txt
Block adserver at https://jkanime.net/
Screenshot:
=> A: https://jkanime.net/

easylist/easylist_adservers.txt
Block adserver at https://watchtheofficetv.com/
Screenshot:
=> https://watchtheofficetv.com/

fanboy-addon/fanboy_notifications_specific_hide.txt
scr : 
- https://imgur.com/HbBLT47.png
=> A: https://ar.tdtube.net/article/115362 (mobile UA) 

easyprivacy/easyprivacy_specific_international.txt
Skroutz.gr Analytics update
Updated as per the following link
https://developer.skroutz.gr/analytics/#step-1-integrate-the-analytics-tracking-script
Screenshot of script in action
=> update skroutz analytics

easylist/easylist_specific_block.txt
- `https://<host>/Content/html5/47fb6792-5a4e-4ff8-9d2f-cba4aca4a182/INDX%20960.html`
=> A: https://wmtransfer.com/

easylist/easylist_adservers.txt
Block adserver at https://animesuge.to/
Screenshot:
=> A: https://animesuge.to/

easyprivacy/easyprivacy_allowlist_international.txt, fanboy-addon/fanboy_notifications_allowlist.txt
Comment broken, unfortunately whole these exception needed
=> P: https://www.zakzak.co.jp/article/20220315-UDHPWX4VGFJ3NLQKT6RKS3PE74/

easylist/easylist_adservers.txt
Block adserver at https://w1.onepiecemangafree.com/
Screenshot:
=> A: https://w1.onepiecemangafree.com/

easylist/easylist_adservers.txt
Block adservers at https://djpunjab.pro/
Screenshots:
=> A: https://djpunjab.pro/

easylist/easylist_adservers.txt
Block adserver at https://mikaraw.com/
Screenshot:
=> A: https://mikaraw.com/

easylist_adult/adult_specific_block.txt, easylist_adult/adult_specific_hide.txt
Block banners + hide placeholders at https://www.pervclips.com/
Screenshots:
=> A: [NSFW] https://www.pervclips.com/

easylist/easylist_adservers.txt, easylist_adult/adult_specific_hide.txt
Block adservers at https://www.porntry.com/ and hide placeholders
Screenshot:
=> A: [NSFW] https://www.porntry.com/

easylist/easylist_specific_hide.txt, easylist_adult/adult_specific_hide.txt
Hide placholders + popups at https://www.bravoporn.com/
Screenshots:
=> A: [NSFW] https://www.bravoporn.com/

easylist/easylist_adservers.txt
Block adserver at https://kinomax.to/
Screenshot:
=> A: https://kinomax.to/

easylist/easylist_adservers.txt
Block adserver at https://www.cpasfini.rip/
Screenshot:
=> A: https://www.cpasfini.rip/

easylist/easylist_adservers.txt
Block adservers at https://vizer.tv/ 
**Test at Mixdrop / Streamtape**
=> A: https://vizer.tv/

easylist/easylist_adservers.txt
Block adserver at https://www.otakustv.com/
Screenshot:
=> A: https://www.otakustv.com/

easylist/easylist_adservers.txt
Block adserver at https://www21.zippyshare.com/
Screenshot:
=> A: https://www21.zippyshare.com/

easylist/easylist_specific_hide.txt
Hide popups at https://gogoanime.be/
Screenshot:
=> A: https://gogoanime.be/

easylist/easylist_specific_block.txt
Block redirects at http://amp.mediatrias.com/dasf.xhtml
Screenshot:
=> A: http://amp.mediatrias.com/

easylist/easylist_adservers.txt
Block adserver at https://netfapx.com/
Screenshot:
=> A: [NSFW] https://netfapx.com/

easylist/easylist_adservers.txt
Block adservers at https://czechvideo.io/
Screenshot:
=> A: [NSFW] https://czechvideo.io/

easylist/easylist_adservers.txt
Block adservers at https://watchporn.to/
Screenshot:
=> A: [NSFW] https://watchporn.to/

easylist/easylist_adservers.txt
Block adserver at https://www.reddit.tube/
Screenshot:
=> A: [NSFW] https://www.reddit.tube/

easylist/easylist_adservers.txt
Block adserver at https://onlyfullporn.video/
Screenshot:
=> A: [NSFW] https://onlyfullporn.video/

easylist/easylist_adservers.txt
Block adserver at https://hentairead.com/
Screenshot:
=> A: [NSFW] https://hentairead.com/

easylist/easylist_adservers.txt
Block adserver at https://www.zone-telechargement.click/
Screenshot:
=> A: https://www.zone-telechargement.click/

easylist/easylist_adservers.txt
Block adserver at https://manhwalands.xyz/
Screenshot:
=> A: [NSFW] https://manhwalands.xyz/

easylist_adult/adult_specific_block.txt
Block popunders at https://www.pornky.com/
Screenshot:
=> A: [NSFW] https://www.pornky.com/

easylist_adult/adult_specific_block.txt
Block popunders at https://joysporn.sex/
Screenshot:
=> A: [NSFW] https://joysporn.sex/

easylist/easylist_adservers.txt
Block adserver at https://bollyflix.sbs/
Screenshots:
=> A: https://bollyflix.sbs/

easylist/easylist_adservers.txt
Block adserver at https://wiflix.city/
Screenshot:
=> A: https://wiflix.city/

easylist/easylist_thirdparty.txt
Block hosted adserver at https://7starhd.li/
Screenshots:
=> A: https://7starhd.li/

easylist/easylist_adservers.txt
Block adserver at https://divxfilmeonline.net/
screenshots:
=> A: https://divxfilmeonline.net/

easylist/easylist_adservers.txt
Block adserver at https://ww2.putlockernew.site/
Screenshots:
=> A: https://ww2.putlockernew.site/

easylist/easylist_adservers.txt
Block adserver at https://klmanga.net/
Screenshots:
=> A: https://klmanga.net/

easylist_adult/adult_specific_hide.txt
Hide banners at https://www.pornicom.com/
Screenshot:
=> A: [NSFW] https://www.pornicom.com/

easylist/easylist_adservers.txt
Block Side video at https://www.asurascans.com/
Screenshot:
=> A: https://www.asurascans.com/

easyprivacy/easyprivacy_allowlist_international.txt
=> P: https://www.cmoa.jp/title/175888/

easyprivacy/easyprivacy_allowlist_international.txt
=> P: https://nttxstore.jp/_II_TO16249141?pType=II&AT=none

easylist/easylist_adservers.txt
Block adserver at https://www2.pelisplus.so/
Screenshot:
=> A: https://www2.pelisplus.so/

easylist/easylist_adservers.txt
Block adserver at https://masteranime.es/
Screenshot:
=> A: https://masteranime.es/

easylist/easylist_adservers.txt
Block adservers at https://blogmflix.xyz/
Screenshot:
=> https://blogmflix.xyz/

easylist/easylist_adservers.txt
Block adserver at https://themoviesflix.com.se/ 
screenshot:
=> A: https://themoviesflix.com.se/

easylist/easylist_adservers.txt
Block adserver at https://manga-1001.com/
Screenshot:
=> A: https://manga-1001.com/

easylist/easylist_adservers.txt
Block adserver at https://animeheaven.ru/
screenshot:
=> A: https://animeheaven.ru/

easylist/easylist_specific_hide.txt
Hide VPN ads at https://simpasian.net/
Screenshots:
=> A: [NSFW] https://simpasian.net/

easylist/easylist_specific_hide.txt
Hide text placeholder at http://ksnews.me/
Screenshot:
=> A: http://ksnews.me/

easylist/easylist_adservers.txt
Block adserver at http://moviezwap.vip/
Screenshot:
=> A: http://moviezwap.vip/

easylist/easylist_adservers.txt
Block adserver at https://animehub.ac/
Screenshot:
=> A: https://animehub.ac/

easylist/easylist_adservers.txt
Block adserver at https://chrysanthemumgarden.com/
Screenshot:
=> A: https://chrysanthemumgarden.com/

easylist/easylist_adservers.txt
Block adserver at https://animepahe.com/
Screenshot:
=> A: https://animepahe.com/

easylist/easylist_adservers.txt
Block adserver at https://mobiletvshows.net/
Screenshot:
=> A: https://mobiletvshows.net/

easylist/easylist_adservers.txt
Block adserver at https://igg-games.com/
Screenshot:
=> A: https://igg-games.com/

easylist/easylist_adservers.txt
Block adserver at http://www.hesgoal.tv/
Screenshot:
=> A: http://www.hesgoal.tv/

easylist_cookie/easylist_cookie_international_specific_hide.txt
=> P: valotehdas.fi (remnant cookie banner overlay makes site unusable)

easylist_adult/adult_specific_block.txt
Block exoloader at https://pornvas.com/
Screenshot:
=> A: [NSFW] https://pornvas.com/

easylist/easylist_adservers.txt
Block adservers at https://www.movieswatch24.pk/
Screenshots:
=> A: https://www.movieswatch24.pk/

easylist/easylist_adservers.txt
Block adserver at http://vw1.ffmovies.sc/
Screenshots:
=> A: http://vw1.ffmovies.sc/

easylist/easylist_adservers.txt
Block adservers at https://vumoo.to/
Screenshot:
=> A: https://vumoo.to/

easylist/easylist_adservers.txt
Block adserver (Banners/popunders)
Screenshot:
=> A: [NSFW] https://iceflix.tv/

easylist/easylist_specific_hide.txt
Hide popups at https://yomovies.pm/
Screenshot:
=> A: https://yomovies.pm/

easylist/easylist_adservers.txt
Block adservers at https://9pm.to/
Screenshot:
=> A: https://9pm.to/

easylist/easylist_adservers.txt
Block adserver at http://lalastreams.me/
Screenshot:
=> A: http://lalastreams.me/

easylist/easylist_adservers.txt
Block adserver at https://wwv.duseries.net/
Screenshot:
=> A: https://wwv.duseries.net/

easyprivacy/easyprivacy_thirdparty_international.txt
JP locale but actually is Korean site.
=> A: https://jp.baddiary.com/

easyprivacy/easyprivacy_allowlist_international.txt
=> P: https://mieru-ca.com/blog/user_seminar/20220330/

easylist/easylist_adservers.txt
Block adserver at https://www.bombuj.si/
Screenshot:
=> A: https://www.bombuj.si/

easylist/easylist_adservers.txt
Block adserver at https://hdmoviesflix.cfd/
Screenshot:
=> A: https://hdmoviesflix.cfd/

easylist/easylist_adservers.txt
Block adserver at https://www.filmsrip.me/
Screenshot:
=> A: https://www.filmsrip.me/

easylist/easylist_adservers.txt
Block adserver at https://pinoymoviepedia.ru/
Screenshot:
=> A: https://pinoymoviepedia.ru/

easylist/easylist_adservers.txt
Block adserver at https://yaoitoon.com/
Screenshot:
=> A: https://yaoitoon.com/

easylist/easylist_adservers.txt
Block adserver at https://www.nisakadhatu.com/
Screenshot:
=> A: https://www.nisakadhatu.com/

easylist/easylist_adservers.txt
Block adservers at https://wwv.123-movies.club/
Screenshots:
=> A: https://wwv.123-movies.club/

easylist/easylist_adservers.txt
Block adservers at https://watchparksandrecreation.net/
Screenshots:
=> A: https://watchparksandrecreation.net/

easylist/easylist_adservers.txt
Block adserver at https://prmovies.bz/
Screenshots:
=> A: https://prmovies.bz/

easylist/easylist_adservers.txt
Block adserver at https://www1.moviesjoy.sc/
Screenshot:
=> A: https://www1.moviesjoy.sc/

easylist/easylist_adservers.txt
Block adservers at https://wvw.voirseries.pro/
Screenshots:
=> A: https://wvw.voirseries.pro/

easylist/easylist_adservers.txt
Block adserver at https://wuxiarealm.com/
Screenshot:
=> A: https://wuxiarealm.com/

easylist_adult/adult_specific_hide.txt
hide video. 
To reproduce: 
1 - open some random video
2 - if it won't appear, go to related videos bellow and click in another video
3 - if not, repeat the process. 
Screenshot:
=> A: [NSFW] https://xhamster.com/

easylist/easylist_adservers.txt
https://kissasians.org/
||torusesinact.com^
||steppesshirvan.com^
||ca65b1531c.com^
http://mangaraw.surf/
||youngestdisturbance.com
https://www.gnula.cc/
||thorpknubby.com^
||sledderjuggle.com^
||waggerbianco.com^
||eiryabba.com^
||grahma.com^
=> A: Adservers (bundle)

easylist/easylist_specific_hide.txt
Hide top banner ad on homepage: https://vigilantcitizen.com/
=> A: https://vigilantcitizen.com/

easylist/easylist_adservers.txt
=> A: http://kt.freestreams-live1.com/channel-3/

easyprivacy/easyprivacy_specific_international.txt
Need Japanese IP (and perhaps some interaction)
=> A: https://tver.jp/episodes/epzhwjq02t

easylist_cookie/easylist_cookie_specific_block.txt
=> A: playpilot.com (cookie banner block)

easylist/easylist_adservers.txt
https://gogoanime.mom/
||amygdalbrittle.com^
https://animeheaven.ru/
||achiersawman.com^
https://wwvv.filmstreaming-1.net/
||woohoobiolith.com^
||suissemicron.com^
||meabor.com^
https://hentai20.com/
||tennubifaces.com^
https://readgrandblue.com/
||enchantmenthopeless.com^
||stinternoctuae.com^
https://tamilblasters.buzz/
||lipinstott.com^
https://www.toongod.com/
||eremuribleak.com^
https://homecine.tv/
||comitechokier.com^
=> A: Adservers (Bundle) - 04.04.22

easylist/easylist_specific_hide.txt
Hide popups at https://filmyzilla.autos/
Screenshot:
=> A: https://filmyzilla.autos/

easylist/easylist_specific_hide.txt
Hide banner ads at https://www.thenetnaija.co/
Screenshot:
=> A: https://www.thenetnaija.co/

easylist/easylist_adservers.txt
Not much of them this time 😢 
https://dramacool.city/
||gyppedsquiss.com^
https://www.mov.onl/
||hockeyhavoc.com^
=> A: Adservers (bundle) - 05/04/22

easylist/easylist_adservers_popup.txt
Adserver popups at https://www.1tamilmv.run/
Screenshot:
=> A: https://www.1tamilmv.run/

easylist_adult/adult_specific_hide.txt
Hide banner at https://www.pornhat.com/
Screenshot:
=> A: [NSFW] https://www.pornhat.com/

easylist_adult/adult_specific_block.txt, easylist_adult/adult_specific_hide.txt
Block banners at https://www.rat.xxx/
Screenshot:
=> A: [NSFW] https://www.rat.xxx/

easylist/easylist_adservers.txt
https://pelispop.me/
||pewdomdiff.com^
||flabbyyolkinfection.com^
https://prmovies.cam/
||sumlessbelat.com^
||staithecrinion.com^
||geishascoset.com^
||semifiboolongs.com^
https://dramaid.xyz/
||strepenboweled.com^
||hurstplants.com^
||cholosfuhrer.com^
https://kisstvshow.to/
||mangoalmahs.com^
https://www.limetorrents.pro/
||kindjalvitalic.com^
[NSFW] https://vivud.com/
||hadsans.com^
https://www1.dramacoolc.com/
||rammishruinous.com^
||adjoincomprise.com^
=> A: Adservers (bundle) - 07/04/22

easylist/easylist_adservers.txt
https://www.netflix-izle.com/
||ynklendr.online
https://www.wiflix.pw/
||armpitstamnos.com
https://dvdplay.guru/
||calcoh.com
||bogginunstill.com
||shikarshexace.com
||cowyardstulm.com
||datismelysee.com
||widdiesbrawns.com 
[NSFW] https://tube.perverzija.com/
||5ef80ae889.com
=> A: Adservers(bundle) - 08/04/22

easyprivacy/easyprivacy_specific_international.txt, easyprivacy/easyprivacy_trackingservers.txt
=> A: (nsfw) https://www.dxlive.com/

easylist/easylist_allowlist.txt, easylist/easylist_allowlist_general_hide.txt
=> P: https://www.so-net.ne.jp/access/hikari/minico/ad/

easylist_adult/adult_specific_hide.txt
Hide placeholder at https://www.empflix.com/
Screenshot:
=> A: [NSFW] https://www.empflix.com/

easylist_adult/adult_specific_block.txt, easylist_adult/adult_specific_hide.txt
Hide placeholders (one is an Iframe after pause the video)
Screenshots:
=> A: [NSFW] https://www.3movs.com/

easylist/easylist_adservers.txt, easylist/easylist_adservers_popup.txt
||titral.com^
https://www1.7starmovies.net/
||reflectedcockbegan.com^
http://www.kmansin03.com/
||lythonefa.com^
https://www.goflix.io/
||celsiansnite.com^
http://shadowrangers.live/
||xthizbdwgebzqf.com^
||sduptpppm.com^
http://starlive.xyz/
||sysxezolnaxavw.com^
||lickingimprovementpropulsion.com^
||lickingimprovementpropulsion.com^$popup
||verbalconnoisseurstoppage.com^
https://w-123movies.com/
||operonsablate.com^
https://www.animeblix.org/
||rovettobirse.com^
https://ww1.filmlicious.co/
||cerebrifetors.com^
https://pelispop.me/
||udalmanresuit.com^
||unpredictableshell.com^
||ericaunct.com^
||repliesreearns.website^
||aquabibchawed.website^
http://kurakura21.com/
||moundgrandmotherel.com^ …
=> A: Adservers(bundle) - 11/04/22

easylist/easylist_adservers.txt
https://lightnovelpdf.com/
||godescargas.xyz^
||retreatregular.com^
https://mp3paw.u4m.cfd/
||jumboprodigious.com^
||fppzikurc.com^
||tfqhmnexjjni.com^
||myotictawse.com^
https://www5.javmost.com/
||eyebrowscrambledlater.com^
https://gogoanime.fan/
||aftrangale.com^
https://cuevana3.me/
||wirelessannexwren.com^
https://igg-games.com/
||buddiestophe.com^
||sullensregimes.com^
||cyanolcomply.com^
http://moviezwap.bar/
||goosedsmee.com^
||epheboiwreath.com^
https://masahub.net/
||d8fb9b701c.com^
=> A: Adservers(bundle) - 12/04/22

easylist/easylist_adservers.txt
https://ytmp3eu.com/
||ywxigvzbkqg.com
||owohvnpbno.com
[NSFW] https://porntn.com/
||dropkickmedia.com^$third-party
https://ww1.123movies.tc/
||neverthelessdepression.com
https://animeflv.ac/
||sicepegger.com
https://jkanime.net/
||revolutionarydrillprotective.com
https://atomixhq.club/
||exchad.com
https://clasico.tv/
||ljyaqiggcpkica.com
https://www.ver-television.online/
||propositiondisinterested.com
||bostopago.com
https://watchcharmedonline.com/
||flaxenvapour.com
||baffledzein.com
https://www.animeblix.org/
||geldantgrins.com
=> A: Adservers(bundle) - 13/04/22

easylist/easylist_thirdparty.txt
Hosted adserver at https://tioanime.com/
Screenshot:
=> A: https://tioanime.com/

easylist/easylist_adservers.txt, easylist/easylist_specific_hide.txt
Block widget at https://www.intouchweekly.com/posts/avril-lavignes-ex-brody-jenner-happy-for-her-engagement-2/
Widget: **Powered By Intentx**
=> A: https://www.intouchweekly.com

easylist/easylist_specific_hide.txt
User reported issue:
https://github.com/mediumkreation/IndianList/issues/5003
=> A:dkoding.in

easylist/easylist_specific_block.txt
Block Script responsible for popups at https://vidhdthe.online/
Screenshot:
=> A: https://vidhdthe.online/

easylist/easylist_specific_hide.txt
Hide modal at http://manganatos.com/
Screenshots:
=> A: http://manganatos.com/

easylist/easylist_specific_hide.txt
Hide popups inside videos at https://ww1.123movies.tc/movie/criminal-minds-season-3-msnvz0e/watching.html?ep=1&sv=8
Screenshot:
=> A: https://ww1.123movies.tc/

easylist/easylist_specific_block.txt
Block popups at https://9anime.id/
Screenshots:
=> A: https://9anime.id/

easylist/easylist_general_hide.txt, easylist/easylist_specific_hide.txt
User reported issue:
https://github.com/mediumkreation/IndianList/issues/5002
=> A:republicworld.com

easylist_adult/adult_specific_block.txt
Block script responsable for overlay at https://www.cambro.tv/
Screenshot:
=> A: [NSFW] https://www.cambro.tv/

easyprivacy/easyprivacy_general.txt
=> A: https://www.ironnet.com/

easylist/easylist_adservers_popup.txt
Block adserver popup at https://watchasians.cc/
Screenshot:
=> A: https://watchasians.cc/

easylist/easylist_specific_hide.txt
Hide banner ads at https://chicagoprowrestling.com/
1 - Top ad placeholder - `chicagoprowrestling.com###Chicagoprowrestling_com_Top`
2 - Banner **THE CHICAGO METAL FACTORY** - `chicagoprowrestling.com##a[href*="//thecmf.com/"] > img`
3 - Bottom banner **Alicia's House FOOD PANTRY** - `chicagoprowrestling.com##a[href*="//www.aliciashouse.org/"] > img`
_Banners: ChicagoProwrestling.com! and VISIT OUR RETAIL STORE are part of the content._
=> A: https://chicagoprowrestling.com/

easylist/easylist_specific_hide.txt
=> A: Hide placeholder on johnogroat-journal.co.uk

easylist/easylist_specific_hide.txt
hid left rail (id="affiliates"
)
=> A: hide affiliate ads https://purplepainforums.com

easylist/easylist_adservers.txt
||oorierenegue.com
https://entrepelis.org/
||spikscabrin.com
https://www.verboruto.online/
||beqmwvupsowvls.com
||ukhkcxmzesi.com
https://www.rojadirectatvenvivo.com/
||nlqznsleo.com
||factermer.com  
https://ww7.123movieshub.tc/
||pleagaietyparalysis.com
https://www.tarjetarojatvonline.sx/
||luxope.com
=> A: Adservers(bundle) - 20/04/22

easylist/easylist_adservers.txt
https://seriesly.org/
||moronghumaner.com
https://ver.cuevana3.cc/
||plumbummoca.com
https://seriepourvous.com/
||tendencyexcavatornook.com
https://dramaid.xyz/
||rokeewoozy.com
||indexesport.com 
https://lookmovie.la/
||rhagitegreeted.com
||knowhowlobe.com
=> A: Adservers(bundle2) - 20/04/22

easylist/easylist_adservers_popup.txt
Adserver popup at https://seriepourvous.com/
Screenshot:
=> A: https://seriepourvous.com/

easylist/easylist_specific_block.txt
Block script related to adservers at https://9anime.to/
Screenshot:
=> A: https://9anime.to/

easylist/easylist_specific_hide.txt
Fixes https://github.com/easylist/easylist/issues/10645
cc @Edivania
=> Remove bad filter for unsplash.com

easylist/easylist_adservers.txt
https://welovemanga.one/
||nasrolaugers.com
||bowpinfrow.com
||agletmagilp.com   
https://klmanga.net/
||helvesgraian.com
||20239be1ae.com
||quinuaknife.com
||scramsaaron.com
https://animepahe.ac/
||pillowspopes.com
https://komiklokal.xyz/
||grazajoba.com
https://leak.sx/
||boxofficeliterally.com
https://jpscan-vf.com/
||vawsmoocah.com
=> A: Adservers(bundle) - 21/04/22

easylist/easylist_specific_hide.txt
Hide popup messages at https://rawkuma.com/
Screenshots:
=> A: https://rawkuma.com/

easylist/easylist_specific_hide.txt
Hide ad labels at https://unsplash.com/t/history
See thread: https://github.com/easylist/easylist/pull/11744#issuecomment-1105407657
=> A: https://unsplash.com/t/history

easylist/easylist_adservers.txt
||demitstanged.com
https://kissanime.tube/
||epigaeatoasty.com
https://kissasian.es/
||catalpaaxillae.com
||enwingdondia.com
https://1337x.g3g.sbs/
||csykhjry.com
||bashfuladvancedeliberately.com
||aedqunriyswthc.com
https://emovies.si/
||odinistromneya.com 
https://otakufr.co/
||xyn1d4bjg4vr4m2qwypvuj.com 
https://123-movies.win/
||dragbarstints.com
=> A: Adservers(bundle) - 22/04/22

easylist_cookie/easylist_cookie_general_hide.txt
- https://i.ibb.co/LtnXCSF/image.jpg
=> A: https://iap-webpay-dre.cloud.huawei.eu/iapwebsite/

easyprivacy/easyprivacy_allowlist_international.txt
The black add-to-cart button is unresponsive:
<details>
</details>
=> P: https://francfranc.com/products/1104080005449

easylist_adult/adult_specific_block.txt
Block script related to Admanager at https://vjav.com/
Screenshot:
=> A: [NSFW] https://vjav.com/

easylist/easylist_specific_hide.txt
Hide popup messages at https://www8.putlockers.fm/
Screenshot:
=> A: https://www8.putlockers.fm/

easylist/easylist_specific_hide.txt
Hide popup messages at https://movierulz.cam/
screenshot:
=> A: https://movierulz.cam/

easylist/easylist_adservers.txt
https://www1.moviecrumbs.net/
||kotalxyloyl.com
https://www.wiflix.pw/
||hexaplatubmen.com
https://www.mov.onl/
||sodallay.com 
||sinatrakohens.com 
https://ww3.d123movies.to/
||scrymeddle.com 
https://weloma.art/
||zebraicrudista.com 
||cernamer.com
https://w-123movies.com/
||lousierphones.com
http://vw1.ffmovies.sc/
||furoidrewash.com 
https://moviestars.to/
||gamblingliquidate.com
||hijragain.com
https://movierulz.cam/
||thrinaxpublic.com
||coosersmidward.com
https://manhwa18.cc/
||reverysteno.com
https://mangagenki.me/
||exambalmy.com
||prbtqjujwzwepv.com
||wteicogfeyhjk.com
https://mangadna.com/
||beeferzak.com
https://manga18fx.com/
||behootpokeys.com
=> A: Adservers(Bundle-1) - 25/04/2022

easylist/easylist_adservers.txt
https://kisstvshow.to/
||dcmosques.com
||cystspalt.com
https://gogoanime.quest/
||auditioningouncesufficiently.com
[NSFW] https://daftsex.com/
||speedsupermarketdonut.com
https://brokensilenze.one/
||dulosislimmata.com
||clinkumebulus.com
https://www.blueseries.net/
||wielderchiefly.com
https://attaque-des-titans-streaming.net/
||oversowcholam.com
||pyxidiaimmerit.com 
https://animeyt.es/
||briskedmiskept.com
https://animeheaven.ru/
||toaprefool.com
https://anime-flix.net/
||islecolloquial.com
=> A: Adservers(Bundle-2) - 25/04/2022

easylist_adult/adult_specific_block.txt
Block script related to admanager at https://upornia.tu
Screenshots:
=> A: [NSFW] https://upornia.tu

easylist_cookie/easylist_cookie_international_specific_hide.txt
Cookie dialog overlay remnant.
https://evl.fi/etusivu
=> P: evl.fi (cookie dialog overlay)

easylist/easylist_specific_block.txt
Block top banners at https://tode837.com/
Screenshot:
=> A: https://tode837.com/

fanboy-addon/fanboy_newsletter_specific_hide.txt
=> A: https://www.alaraby.co.uk/

easylist/easylist_adservers.txt
||osseasougan.com
https://gogoanime.onl/
||globeshyso.com
http://gogoanime.unblockedstreaming.net/
||licencerings.com
||onpluslean.com
https://vipleague.im/
||volumeearthquakedozen.com
||tholected.com
https://animeseries.nocensor.sbs/
||featassuage.com
||vrqsvrnjrhdmek.com
||diqkldlh.com
=> A: Adservers(bundle) -26/04/2022

easylist/easylist_specific_block.txt
Block script responsible for redirects at https://zmovies.cc/
Screenshot:
=> A: https://zmovies.cc/

easylist/easylist_adservers.txt
https://multicanais.tv/
||uprightmidsummer.com
https://xlecx.one/
||bangabdicate.com
https://www.skidrowreloaded.com/
||clainence.com
https://reddit.mlbstream.me/
||nzihjybdeq.com
||nvmjdpbjgrh.com
https://www.myanimesonlinebiz.com/
||boroniasunback.com
||scurfrubicon.com
||mamboedclarine.com
https://bollyflix.space/
||mirishkeeps.com
https://cinecalidad.nocensor.sbs/
||vknalqcnfxu.com
||jarbirdkorait.com
||revereshaggeis.com
https://www1.pelisplushd.nu/
||oozyunmix.com
https://212.32.226.234/
||1219c3e1c9.com  
https://youtube4kdownloader.com/
||guardianamazedwireless.com
https://www.gogoanime.me/
||tripolihash.com
https://anime-free.biz/
||azskk.com
https://m.animeid.tv/
||balldevelopedhangnail.com
http://desivdo.com/ …
=> A:  Adservers(bundle) - 27/04/22

easylist/easylist_specific_hide_abp.txt
**VPN Location:** US
**Lists:** ABP + EL
Note: Didn't add with`:-abp-has(span:-abp-contains(Ad))` for example because Ad label change depending on location.
All sites have class: `uitk-badge-sponsored`
**cheaptickets.com** - https://www.cheaptickets.com/Hotel-Search?adults=2&d1=2022-05-24&d2=2022-05-28&destination=San%20Diego%2C%20California%2C%20United%20States%20of%20America&endDate=2022-05-28&latLong=32.71444%2C-117.16237&regionId=3073&rooms=1&semdtl=&sort=RECOMMENDED&startDate=2022-05-24&theme=&useRewards=false&userIntent=
**ebookers.com** - https://www.ebookers.com/Hotel-Search?adults=2&d1=2022-05-25&d2=2022-05-28&destination=Honolulu%2C%20Hawaii%2C%20United%20States%20of%20America&endDate=2022-05-28&latLong=21.306957%2C-157.858336&regionId=1488&rooms=1&semdtl=&sort=RECOMMENDED&startD …
=> A: Sponsored ads (several sites)

easylist_adult/adult_specific_hide.txt
hide side placeholders at http://risextube.com/
Screenshot:
=> A: [NSFW] http://risextube.com/

easylist_adult/adult_specific_block.txt
Block exoclick scripts at https://fapster.xxx/
Screenshot:
=> A: [NSFW] https://fapster.xxx/

easylist/easylist_specific_hide.txt
Hide message popups at https://mangas-raw.com/
Screenshot:
=> A: https://mangas-raw.com/

easylist/easylist_adservers_popup.txt
Block adserver popups at https://pelisplus.sh/
Screenshots:
=> A: https://pelisplus.sh/

easylist/easylist_thirdparty.txt
Block hosted adserver at https://www23.estrenosdoramas.net/
Screenshot:
=> A: https://www23.estrenosdoramas.net/

easylist/easylist_specific_hide.txt
Ads spotted on https://www.techadvisor.com/how-to/windows/record-pc-sound-3800679/ - 
Ad ID seems to have changed.
=> M: Ads on techadvisor.com

easylist_adult/adult_adservers.txt
Block third-party adserver at https://freeadultcomix.com/
Screenshot:
=> A: https://freeadultcomix.com/

easylist/easylist_adservers.txt
||rowenspopped.website
https://animeheaven.ru/
||sutlerstriller.com
||desticall.com
||prinosknick.com
https://www.wiflix.pw/
||sholombombic.com
https://www.mangatigre.com/
||rotchestche.com
https://manga18fx.com/
||flaunchmuzhiks.com
||unallowferae.com
https://prmovies.cam/
||wedgesdayment.com
https://hentai20.com/
||chinoismoras.com
https://moviecrumbs.net/
||airconditionblown.com
||spaleswairsh.com
https://emovies.si/
||emulousoaty.com
https://tmomanga.com/
||gyrivehmic.com
=> A: Adservers(bundle) - 29/04/22

easylist/easylist_specific_hide.txt
Hide primary-products  widget at https://www.talkbass.com/threads/are-there-any-songs-you-refuse-to-play-and-why.1560733/
=> A: https://www.talkbass.com

easylist/easylist_specific_hide.txt
Hide popup messages at:
https://watchomovies.cam/
https://hhdmovies.cam/
Screenshot:
=> A: [NSFW] https://watchomovies.cam/

easyprivacy/easyprivacy_allowlist_international.txt, fanboy-addon/fanboy_annoyance_allowlist.txt
=> P: mainichi.jp

easylist/easylist_adservers.txt
https://wwv.voirseries.rip/
||stertorblaver.com
https://turkish123.com/
||responsibleassociation.com
https://manhwa18.cc/
||logoestulles.com
https://altadefinizione01.in/
||wafflescrappyprosperous.com
||maritanewark.com
https://hindilinks4u.cam/
||affluentshinymulticultural.com
||dcbnameapneas.com
https://fuxnxx.com/
||e8a0cb51c6.com
||tierbignews.com
=> A: Adservers(bundle) - 01/05/22

easylist/easylist_adservers.txt
Block adserver responsible for ads before videos
Screenshots:
=> A: [NSFW] https://adult.mat6tube.com/

easylist/easylist_specific_block.txt
Block iframe at http://roof99dollars.com/
Screenshot:
=> A: http://roof99dollars.com/

easylist/easylist_general_hide.txt, easylist/easylist_specific_hide.txt
**Issue:** 
Ad spaces on home page and article pages (Desktop and Mobile)
**Sample URLs:**
https://www.onlymyhealth.com
https://www.onlymyhealth.com/tips-to-ease-migraine-pain-1651495958
=> A: https://www.onlymyhealth.com

easylist/easylist_adservers.txt
http://st.freestreams-live1.com/
||visesi.com
||betflippant.com
https://manga-mx.com/
||dmshlhnzvzu.com
https://www23.estrenosdoramas.net/
||tmmkjvphbawgul.com
||thuqqyggwc.com
||pikedhelloed.com
||scunderqueller.website
https://ko.strikeout.cc/
||tightenmonuments.com
https://www102.zippyshare.com/
||encloseddealing.com
https://www.filmoves.net/
||youngsterbusinessman.com
https://cuevana3.la/
||chosesleptcattish.com
https://hdfull.be/
||clickpromptlyfowl.com
=> A: Adservers(bundle) - 04/05/22

easylist/easylist_adservers.txt
https://www.universanimes.co/
||impertinentitaliangeological.com
https://ww3.gnula.cc/
||dronedgentile.com 
https://vipleague.im/
||tremendousfastened.com
||lirelt.com
||oaascbasgdffq.com
||ahwqsczvsi.com
https://veziseriale.org/
||advertisemisuseequipment.com
https://v3.cine-calidad.com/
||elkconsistbirch.com
https://tmomanga.com/
||semirawbatter.com
||ebonscornier.com
||vipersengoue.com
https://soap2day.gy/
||latvianswived.com
https://porncomics.to/
||instinctiveachievement.com
||angoisehohn.com
||sandalcamases.com
https://manhwa68.com/
||breakdownfragileindication.com
||galopelikeantelope.com
||ponentshebar.com
https://manga1st.com/
||cunyiesus.com
https://ilkpop.com/ …
=> A: Adservers(bundle) - 06/05/22

easylist/easylist_adservers.txt
||piluskbar.com
||tilingsfardels.com
https://www2.kickassanime.ro/
||arguesmoke.com
||hokespotheen.com
https://sextb.net/
||bankerconcludeshare.com
=> A: Adservers(bundle-2) - 06/05/22

easylist_adult/adult_specific_block.txt
Block Admanager at https://vxxx.com/
Screenshot:
=> A: [NSFW] https://vxxx.com/

easylist/easylist_specific_hide.txt
hide bannners all over the page. 
Screenshot:
=> A: https://kenyan-post.com/

easylist/easylist_allowlist_general_hide.txt
=> M:eenadu.net

easylist/easylist_specific_hide.txt
found in url: https://www.cinemaexpress.com/telugu/interviews/2022/apr/18/taking-a-big-leap-30962.html
=> A:cinemaexpress.com

easylist/easylist_specific_hide.txt
Fount in url: https://timesofindia.indiatimes.com/ , 
https://timesofindia.indiatimes.com/most-searched-products/electronics/air-conditioners/hot-and-cold-air-conditioners-for-all-seasons/articleshow/73273606.cms
=> A:indiatimes.com

fanboy-addon/fanboy_newsletter_general_hide.txt
https://www.seiska.fi/Kotimaa/Kansanedustaja-Sebastian-Tynkkynen-lapsuudestaan-Seurakunta-kerasi-perheellemme-rahaa
=> A: seiska.fi (newsletter widget, generic hide)

easylist/easylist_allowlist.txt, easylist/easylist_general_block.txt
=> P: animallabo.hange.jp, puretomo.hange.jp

easylist/easylist_specific_hide.txt
Hide banner ads on https://kollelbudget.com/
=> A: https://kollelbudget.com/

easylist/easylist_general_hide.txt
Hide iframe on https://realgearonline.com/
=> A: https://realgearonline.com/

fanboy-addon/fanboy_social_thirdparty.txt
Example of a website using getbutton
https://www.sesyalitimsungerleri.net/
https://www.thecasesolutions.com/
https://pedreirao.com.br/
https://pamperhamper.in/
https://i.imgur.com/0Qysdso.jpg
=> add getbutton.io

easylist_adult/adult_adservers_popup.txt
Block adserver popup at https://pinayflix.tv/
Screenshot:
=> A: [NSFW] https://pinayflix.tv/

easylist/easylist_adservers.txt
||mouseryearlike.com
||oensil.com 
https://animeheaven.ru/
||spirliesalse.com
||bluedcrwth.com
https://vostanimez.com/
||ravenousdrawers.com
https://mangagenki.me/
||aehjtauekqjtvc.com
||srfhtrjzvf.com
||sometimesfaith.com
https://kissasian.es/
||eyelidfallage.com
https://kisscartoon.nz/
||wheeshtdooring.com
=> A: Adservers(bundle) - 07/05/22

easylist/easylist_adservers.txt
||ceboidbusting.com
https://kr18plus.com/
||cuddlethehyena.com
http://www.filmeserialeonline.org/
||coherentescalatorjeweller.com
https://www.zonestreaming.rip/
||samariaalipeds.com
https://www.actvid.com/
||vidkidsgedrite.com
https://hitbdsm.com/
||plungebackyard.com
https://hentai20.com/
||egistonemes.com
https://www.y2meta.com/
||fewvincent.com
||junkieswudge.com
https://teenager365.com/
||vubihowhe.com
=> A: Adservers(bundle) - 08/05/22

easylist_adult/adult_specific_block.txt
Block admanager at https://thegay.com/
Screenshot:
=> A: [NSFW] https://thegay.com/

easylist/easylist_adservers_popup.txt
Block adserver popups at http://www.filmeserialeonline.org/
Screenshot:
=> A: http://www.filmeserialeonline.org/

easylist/easylist_adservers.txt, easylist/easylist_thirdparty.txt
http://scenesource.unblocked.club/
||practitionermonsieurstable.com
||outwhirlipedeer.com
||wwwowww.xyz
https://emovies.si/
||moriceprich.com 
https://mangadna.com/
||motfanner.com
||salsifyballone.com
https://fullmatchtv.com/
||splitcursednagging.com
https://cyberleaks.to/
||importancediscipline.com
||ad-serve.b-cdn.net
=> A: Adservers(bundle) - 09/05/22

easylist/easylist_general_hide.txt, easylist/easylist_specific_hide.txt
Go to https://airhostacademy.com/summer-pool-supplies-your-airbnb-guests-will-love/
=> Airhost_09052

easylist_adult/adult_specific_block.txt
Block exoloader at https://manga18fx.com/
Script name/folder changes
Screenshot:
=> M: [NSFW] https://manga18fx.com/

easylist/easylist_specific_hide_abp.txt
Banner ads on  https://tossinggames.com/
=> A: https://tossinggames.com/

easylist_adult/adult_specific_block.txt
Popunders at https://picshick.com/
Screenshot:
=> A: [NSFW] https://picshick.com/

easylist/easylist_specific_block_popup.txt
Block popups at http://scenesource.unblocked.club/
Screenshot:
=> A: http://scenesource.unblocked.club/

easyprivacy/easyprivacy_specific.txt
Script load `https://rum.condenastdigital.com/client/boomerang-1.0.e7f702e5362e8a8f56f0cf3040ee24077d13a9a8.min.js`
Ping `https://rum.condenastdigital.com/beacon`
=> Add rum.condenastdigital.com analytics filter

easylist_cookie/easylist_cookie_international_specific_hide.txt
=> A: esri.fi (cookie banner hide)

easylist_cookie/easylist_cookie_specific_uBO.txt
https://www.mehilainen.fi
Only for uBO, as the scrolling needs to be fixed (fixed already).
=> M: mehilainen.fi (cookie dialog filter update)

easylist/easylist_specific_hide.txt
Hide top banner ad
Reference PR: https://github.com/easylist/easylist/pull/10290
=> M: Fixes #10290

easylist_adult/adult_specific_block.txt
Block exoloader at http://hornyjourney.com/
Screenshot:
=> A: http://hornyjourney.com/

easylist/easylist_adservers.txt
https://hiperdex.com/
||gbvqblkpxmzji.com
||qxazefkhgayy.com
https://tinyurl.is/
||immenseflakespyramid.com
||waspsbiga.com
||laulup.com   
https://ww3.gnula.cc/
||befuglago.live
||gombmobil.store
https://leermanga.net/
||backetkidlike.com
||shyheglasy.com
https://mangamovil.net/
||sipibowartern.com
||escotsmaligns.com
https://www.pelispedia.de/
||understoodadjoiningarab.com
https://pelispop.me/
||oxynticarkab.com 
https://tarjetarojatv.live/
||indebtedatrocious.com
||janglemysticalpiggy.com
https://www.cinecalidad.live/
||munsterduke.com
=> A: Adservers(bundle-1) - 11/05/22

easylist/easylist_specific_hide.txt
Hide side banners at https://www.brandsoftheworld.com/
=> A: https://www.brandsoftheworld.com/

easylist/easylist_specific_block_popup.txt
@ryanbr As you've mentioned it would be fast till they change, maybe this format would be a better way
Screeenshot:
=> M: Fix for proxy popups

easylist_adult/adult_specific_block.txt
Block exoloader at https://www.bigtitslust.com/
PS: If we would block the whole folder (frd5) the videos would break
Screenshot:
=> A: [NSFW] https://www.bigtitslust.com/

easylist_adult/adult_specific_block.txt, easylist_adult/adult_specific_hide.txt
Hide/block banners at https://www.trannygem.com/
Screenshot:
=> A: [NSFW] https://www.trannygem.com/

easylist/easylist_adservers.txt, easylist/easylist_thirdparty.txt
https://www.porndish.com/
||greatestquaint.com
https://www.jperotica.com/
||awnexus.com
https://www.gamelivestory.com/
||uncertainimprovementsspelling.com
https://wwv.movizland.biz/
||d2qnx6y010m4rt.cloudfront.net
https://real.buffstreams.tv/
||supportivedistrustuldistrustulmaturity.com
||noeire.com
||xndcnnkygvd.com
||rftqvbgisqke.com
||kgpabtukhwrp.com
https://m.mangabat.com/
||ranselbetons.com
https://read.mangabat.com/
||pigpenchiba.com
https://mp3clan.net/
||waymarkgentiin.com
https://manhuascan.me/
||jandersburntly.com
||flabsbosons.com
||inunctsignate.com
||smegmasclarify.com
||lippieramman.com
||fuffyauth.com
||poesonk.com
||loajawun.com
https://123-movies.fun/
||saurelunbitt.com
||commitamulet.com
https://apk4free.org/ …
=> A: Adservers(bundle) - 12/05/22

easylist/easylist_adservers.txt
https://hitbdsm.com/
||deludereflexunderwater.com
https://mangamovil.net/
||wodycaha.com
https://xxxdessert.com/
||spidersprimary.com
=> A: Adservers(bundle) - 13/05/22

easyprivacy/easyprivacy_allowlist_international.txt
Cart (partially) broken - reproducing may be bit troublesome as you have to buy a product with two confirmation dialogues. You have to start from the URL (direct URL always returns error).
<details>
</details>
=> P: https://paypaymall.yahoo.co.jp/store/ploom/top/

easylist/easylist_specific_hide.txt
Hide banner ad on https://www.cricket.com/
=> A: https://www.cricket.com/

easylist_adult/adult_specific_hide.txt
Hide side banner at https://www.pornwhite.com/
Screenshot:
=> A: [NSFW] https://www.pornwhite.com/

easylist/easylist_general_hide.txt, easylist/easylist_specific_hide.txt
**1 - Hide top and bottom ad 
`##.cuFitaCon`**
**2 - Hide sticky ad 
`###wiDoCon`**
**3 - Hide sidebar banner ads
`##.sdbrUnitFlex100`
`##.sdbrUnitFlex250a`**
_Didn't suggest `##.sdbrUnitFixCol ` as it hides the entire sidebar div._ 
**4 - Hide ad spaces throughout the page
`##.cuPopuCon`**
=> A: https://www.apotelyt.com/

easylist/easylist_specific_hide.txt
Hide side gif ad at https://hentaihaven.xxx/
Screenshot:
=> A: https://hentaihaven.xxx/

easylist/easylist_specific_hide.txt
Left ad space, including close button on https://www.wcostream.com/cartoon-list
=> A: https://www.wcostream.com/cartoon-list

fanboy-addon/fanboy_newsletter_specific_uBO.txt
https://www.rakentaja.fi/keskustelut/156981/rj45_rasioiden_asennus
The newsletter modal should appear after a while (need to scroll the page also).
=> A: rakentaja.fi (newsletter dialog)

easylist_adult/adult_specific_block.txt
Block popups/unders at https://xxxdessert.com/
Screenshot:
=> A: [NSFW] https://xxxdessert.com/

easylist_adult/adult_specific_hide.txt
hide banner and overlay at https://setdartwatches.com/
Screenshot:
=> A: [NSFW] https://setdartwatches.com/

easylist_adult/adult_specific_block.txt
Block banner ads all over the page at https://www.erofus.com/
Screenshot:
=> A: [NSFW] https://www.erofus.com/

easylist/easylist_specific_hide.txt
Hide ads at https://tinyurl.is/ZHqa?sport=soccer
Redirected after click in any game at https://redi1.soccerstreams.net/
Adservers added in the daily bundle.
Screenshots:
=> A: https://tinyurl.is/

easylist/easylist_adservers.txt
https://kissasian.li/
||graduationstoryladen.com
||amuletsld.com
https://www.japscan.ws/
||jundiedsesamin.com
https://klmanga.net/
||3a1be44ca9.com
=> A: Adserver(bundle) - 17/05/22

easylist/easylist_adservers.txt
https://www.pastemytxt.com/
||phialedamende.com
||tvefrico.com
https://www.aiohotzgirl.com/
||breathtricklealleviate.com
https://www.animefenix.com/
||everywheresavourblouse.com
https://miraculous.to/
||forgottedvere.xyz 
https://www.cuevanahd.net/
||qpslgfcsbvgm.com
https://ww3.series24.cc/
||guabmobil.site
https://www.zonarutoppuden.com/
||midlandvenisondollars.com
https://www.cuevanahd.net/
||hbunmokcwopj.com
||wfveippeyhtegob.com
https://latinblog.tv/
||b0oie4xjeb4ite.com
||b546c8dcd2.com
=> A: Adservers(bundle) - 18/05/22

easylist/easylist_adservers.txt
https://www.mangaworld.in/
||dehornuplock.com
https://www.animeworld.tv/
||gibbousbalaic.com
https://voe-unblock.net/
||futiledrugstore.com 
||kilocythera.com
https://jpscan-vf.com/
||9f3f61c6a1.com
||maidishcubbing.com
https://www.kimoitv.com/
||jacquesskinned.com
=> A: Adservers(bundle-1) - 19/05/22

easylist/easylist_adservers.txt, easylist/easylist_general_hide.txt
https://www.mangatigre.com/
||gleitmappy.com
https://bobmovies.cc/
||subseaprinker.com
https://moviesjoy.to/
||jainafashing.com 
https://www.filkhabr.com/
||ficinvesses.com
||egglikelt.com 
https://spyxmanga.com/
||safelywestselfish.com
https://www.annuaire-telechargement.club/
||extillcasula.com
https://masahub.net/
||0dc77eb60d.com
||backstagefreakish.com
||chrif8kdstie.com
##a[href^="//chrif8kdstie.com/"]
https://monoschinos2.com/
||accordinglyvenisonelse.com
||awafthealer.com
||odonatainbowed.com
=> A: Adservers(bundle) - 20/05/22

easylist/easylist_adservers.txt
https://www5.himovies.to/
||labellaunkamed.com
https://a.gateanime.cam/
||petasusawber.com
https://cineb.net/
||inutilepiously.com
https://www9.0123movies.com/
||waymentriddel.com
||sigilsspeiss.com
https://extramovies.tel/
||brioletredeyes.com
||unbuttondeferinstalment.com
=> A: Adservers(bundle-3) - 19/05/22

easylist/easylist_specific_block.txt
Block image banner at https://extramovies.tel/
Screenshot:
=> A: https://extramovies.tel/

easylist/easylist_adservers.txt
https://ngomik.net/
||hardishserries.com
https://hentaiworld.tv/
||fb9c1069a6
https://kisstvshow.to/
||taffiaveiner.com
||tallcy.com
https://noxx.is/
||nutrientassumptionclaims.com
||carguedquannet.com
http://www.mavanimes.co/
||bhlcimjcpvkxn.com
https://animeclipsraw.fr/
||kronervisile.com
https://arabsex1.com/
||mathneedle.com 
https://pinoyflix.to/
||formationmisjudgebegun.com
https://watchofree.com/
||pandlewombier.com
||melagratoftmen.com
=> A: Adservers(bundle-2) - 19/05/22

easyprivacy/easyprivacy_allowlist_international.txt
=> P: https://d-card.jp/st/campaigns/index.html

easylist/easylist_specific_block.txt
Block banners at https://mfilecloud.com/cGFjd2lqZG1xcGNxX2loSnEz
Screenshot:
=> A: https://mfilecloud.com/

easylist_adult/adult_specific_block.txt
Block exoloader at https://javguru.top/
Screenshot:
=> A: [NSFW] https://javguru.top/

easylist/easylist_general_hide.txt
Generic hide (Redirect to adservers) : 
http://misslinkvocation.com/wdi2p953d9?jyl=37&refer=https%3A%2F%2Fww1.idope.cyou%2Ffullsearch%3Fq%3Dcategory%3A201&kw=%5B%22full%22%2C%22search%22%2C%22page%22%2C%22-%22%2C%22idope%22%5D&key=06444360220cd3121ea71b73847bab58&scrWidth=2560&scrHeight=1440&tz=2&v=22.3.v.34&ship=&res=12.31&dev=r&adb=y
http://residenceseeingstanding.com/wdi2p953d9?vnwc=100&refer=https%3A%2F%2Fww1.idope.cyou%2Ftor%3Fid%3D58995746&kw=%5B%22torrent%22%2C%22page%22%2C%22-%22%2C%22idope%22%5D&key=06444360220cd3121ea71b73847bab58&scrWidth=2560&scrHeight=1440&tz=2&v=22.3.v.34&ship=&res=12.31&dev=r&adb=y
=> A: https://ww1.idope.cyou/

easylist/easylist_adservers.txt
https://ww2.limetorrents.cyou/
||pasquinzippy.com
||sunglasseslollipopoperating.com
https://wwv.cpasmal.biz/
||enserfshoofish.com
https://keopitranslations.com/
||collationstrend.com
https://masahub.net/
||0e24f9441d.com
https://mycima.cloud/
||awelessawelessmilliondisorganized.com
https://www.vipleague.st/
||rainbending.com
||mipism.com
http://www.curvaweb.com/
||visitsviolatedifficult.com
||facesrenaissanceconfirmed.com
||wzcdn264.net
https://m.downloadlagu321.site/
||witlingdandie.com
https://kissasian.li/
||coenuriauge.com
=> A: Adservers(bundle) - 23/05/22

easylist/easylist_specific_hide_abp.txt
Hide **Sponsored** ads on https://unsplash.com/
=> A: https://unsplash.com/

easylist/easylist_specific_hide_abp.txt
Hide banner ads on https://www.1001tracklists.com/tracklist/2m7qxg9k/ed-lev-gui-de-gas-edm-evolution-211-2022-04-01.html
Reference: https://github.com/easylist/easylist/pull/12048
=> A: https://www.1001tracklists.com

easylist/easylist_adservers.txt, easylist/easylist_specific_hide.txt
https://apkmody.io/
||hsxmxmsootyl.com
||casleygkqvkx.com
https://javhat.tv/
||morrowfreezer.com
https://readcomiconline.li/
||outsoarpg.com
https://animexin.xyz/
||cephidelixed.com
###overplay (Close button – videos)
https://cpasmieux.lol/
||ingramony.com
https://mangakita.net/
||bastingestival.com
=> A: Adsrvers(bundle) - 24/05/22

easylist/easylist_adservers.txt
http://www.incestflix.com/
||tklaxrrzzo.com
https://lalamanga.com/
||azoniumsinamin.com
||aspiredcapitol.com
||escapeeelapid.com
https://www.pelisplus2.io/
||sortyrails.com
https://wwvv.cpasfini.rip/
||debitswiping.com
https://apkmody.io/
||thinnerconcha.com
||agenduret.com
https://voiranime.com/
||slaydesperatelyimmensely.com
||erenowcommie.com
https://animebalkan.org/
||suinglygaggler.com
https://wwv.cocostream.rip/
||lagginleapful.com
||atevaccination.com
https://www.1tamilmv.cloud/
||xjzcbddnj.com
http://gratflix.org/
||2e8dgn8n0e0l.com
https://www.limetorrents.lol/
||irchincsp.com
=> A: Adservers(bundle) - 26/05/22

easylist/easylist_specific_hide.txt
Hide ad banner at https://kotaku.com/
Screenshot:
=> A: https://kotaku.com/

easylist/easylist_specific_hide.txt
Hide ad space labeled as `Advertisement` on https://www.distractify.com/p/will-the-mandalorian-be-in-obi-wan-kenobi
=> A: https://www.distractify.com/p/will-the-mandalorian-be-in-obi-wan-kenobi

easylist/easylist_specific_hide.txt
Hide  animated ad on the right side
URL: https://www.tractorbynet.com/
=> A: https://www.tractorbynet.com/

easylist/easylist_adservers.txt
https://seebussy.com/
||milfunsource.com
||larverewish.com
https://animotvslashz.blogspot.com/
||absorbedexistence.com
https://readcomiconline.li/
||flapnaperer.com
||pickaxewafters.com
https://www.pagalmovies.lol/
||newburgtourism.com
https://masahub.net/
||2629ff5ff5.com
https://porndish.com/
||vacationambulancekin.com
=> A: Adservers(bundle) - 27/05/22

easylist/easylist_adservers.txt
https://yomovies.ws/
||vinalsmuffish.com
https://www3.moviecrumbs.net/
||limitlessexterminator.com
https://www2.kickassanime.ro/
||retiringvarieties.com
https://www.wiflix.pw/
||dosawhatkin.com
https://www.freeuseporn.com/
||objectdressed.com
https://www.blablastream.rip/
||musedalisma.com
https://ww3.d123movies.to/
||curredreflex.com
https://wvv1.123movieshub.tc/
||permittedswift.com
||mhvllvgrefplg.com
||ucxfdvhuqwpig.com
https://pornmz.com/
||hauntcontribution.com
https://readcomiconline.li/
||bahuthue.com
https://soap2day.gy/
||dandiesvicua.com
||ceileangsts.com
https://starlive.xyz/
||separatecolonist.com
||latcoy.com
https://voiranime.com/
||forecastsinglegait.com
https://watchseries.ma/
||kanoonhymens.com
https://mangahere.onl/
||kudrunoptime.com
=> A: Adservers(bundle) - 30/05/22

easylist/easylist_adservers.txt
https://cyberleaks.to/
||defyblackmailrecommended.com
||impiabaxile.com
https://moviesjoy.to/
||wrivedipnoi.com
https://wwvv.french-stream.pl/
||laplamed.com
https://gledalica.online/
||onsetknives.com
=> A: Adservers(bundle) - 01/06/22

easylist/easylist_specific_hide_abp.txt
[Changed file location](https://github.com/easylist/easylist/pull/12094/files)
=> A: Hide Sponsored ads on Instacart.com

easylist/easylist_general_hide.txt
Hide in-content ad spaces on https://metabattle.com/wiki/Guardian
Reference https://github.com/easylist/easylist/commit/9ac7782
=> A: https://metabattle.com/wiki/Guardian

easylist/easylist_specific_hide.txt
Hide ads at https://wikikeep.com/
Screenshot:
=> A: https://wikikeep.com/

easylist/easylist_specific_hide.txt
Hide side banners at https://www.essentialenglish.review/
Screenshot:
=> A: https://www.essentialenglish.review/

easylist/easylist_adservers.txt, easylist/easylist_thirdparty.txt
https://vizer.tv/
||dragonspontaneous.com
https://topflix.app/
||harmonycanyon.com
https://pelismart.com/
||bromismcrouton.com
||guineapilotage.com
https://atomohd.org/
||chinlesufer.com
https://ww2.series24.cc/
||phontomsasa.cfd
https://monoschinos2.com/
||cribbolts.com 
||12805b86d6.com
https://www4.doramasvip.com/
||disrootaffa.com
https://hentaila.com/
||joedisarmament.com
https://ww3.gnula.cc/
||delwargal.click
https://kimcartoon.li/
||curatcullion.com
https://jkanime.top/
||clayierglaiks.com
||cunzashope.com
https://gnula.se/
||reflushneuma.com
https://www.torrentdownloads.pro/
||jogglyisohel.com
https://www3.animeflv.net/
||d2rx475ezvxy0h.cloudfront.net
https://linksly.co/
||foreverhealthsculptor.com
=> A: Adservers(bundle) - 03/06/22

easylist/easylist_general_hide.txt, easylist/easylist_specific_hide.txt
Banner ads on https://www.92kqrs.com and https://www.93x.com
=> A: https://www.92kqrs.com

easylist/easylist_specific_hide.txt
Hide banner ad on 
https://1013thebear.com
https://929wxdc.com/
https://941qzk.com/
https://947welk.com/
=> A: https://1013thebear.com

easylist/easylist_specific_hide.txt
Hide banner ads on 
https://www.101thefox.net
https://www.949kcmo.com/
**PARISI** and **DIGITAL MEDIA EASY**
=> A: https://www.101thefox.net

easylist/easylist_specific_hide.txt
=> A: fortune.com

easylist/easylist_adservers.txt
||tramemedea.com
https://www.sksmileanimation.xyz/
||dotsenhanced.com
https://www.toongod.com/
||grideawkwarddepth.com
https://www3.bestjavporn.com/
||berchsoda.com
https://www.muitohentai.com/
||jazzharder.com
https://www.shemale6.com/
||dcwkgvoeufhnm.com
||nnlczheczlq.com
https://www.dramacool9.co/
||rhombicsomeday.com
https://www.blablastream.rip/
||jumbalsmouser.com
https://www.animeunity.tv/
||becrustleom.com
https://ww.kiss-anime.ws/
||tarrilyathenee.com
||overrateddimension.com
https://wvv1.123movieshub.tc/
||membersfifteenthintent.com
https://tmomanga.com/
||psychaltuxes.com
||fortssturt.com
=> A: Adservers(bundle - 1) - 06/06/22

easylist/easylist_adservers.txt, easylist/easylist_thirdparty.txt
https://spyxmanga.com/
||straticjustice.com
https://pelispop.me/
||sculledoxygens.com
https://mrworldpremiere.tv/
||painfulpropaganda.com
||hyloistmithan.com
https://m.animeflv.net/
||d1e9rtdi67kart.cloudfront.net
https://www5.himovies.to/
||emploresmith.com
https://illimite-streaming.com/
||reflexalright.com
https://kinox.top/
||selfconfidencecap.com
https://komikav.com/
||fattiersereins.com
http://letitnews.com/
||tetrylscullion.com
||fustinrepure.com
https://manhuascan.io/
||boatlyseljuk.com
||whistedsynapte.com
||yabacackler.com
=> A: Adservers(bundle-2) - 06/06/22

easylist/easylist_adservers.txt
https://hentai20.com/
||biniprobit.com
https://gogoanime.mom/
||topdisplayformat.com
https://ww.gogoanime.me/
||primevalrespectful.com
https://123films.ch/
||steinrelists.com
https://194.233.66.232/
||begrimdos.com
http://1stream.top/
||dysses.com
https://anime-flix.net/
||luracancamus.com
https://animepahe.org/
||garaupedata.com
=> A: Adservers(bundle) - 07/06/22

easylist/easylist_specific_hide.txt
=> A: Ads on apotelyt.com

easylist/easylist_adservers.txt, easylist/easylist_thirdparty.txt
http://www.tvsubtitles.net/
||ethicel.com
https://wvvw.cpasfini.rip/
||cuberssnur.com
https://bustyanimalsex.com/
||easyads29.mobi
https://erotom.com/
||dibjaahejdaeejhhaacd.ru
http://watchasian.ac/
||scythesandwiches.com
https://wiflix.bet/
||ongaromusket.com
||icelessbogles.com
||bargedoctarch.com
https://cloudy.cfd/
||d2vwl2vhlatm2f.cloudfront.net
http://www.xxxgirls88.com/
||cawber.com
=> A: Adservers(bundle) - 08/06/22

easylist/easylist_adservers.txt, easylist/easylist_thirdparty.txt
https://x2manga.com/
||surnamesubqueryaloft.com
https://www6.f2movies.to/
||snarlsevres.com
https://www3.zoechip.com/
||sunburnquasars.com
https://www.unionmangas.xyz/
||enthusiasticsabotage.com
||narior.com
http://hd.worldcupfootball.me/
||aerialmistaken.com
||qqaskpbofrji.com
https://manga21plus.com/
||c5b8d9d52f.com
https://javplayer.org/
||jojome.xyz
https://moviesjoy.to/
||briefsupbuoy.com
https://pahe.li/
||precessfetidly.com
https://torrentgalaxy.to/
||profitablecpmgate.com
https://jujmanga.com/
||takychasing.com
||d3rjndf2qggsna.cloudfront.net
https://www.blablastream.rip/
||acustomfaeries.com
=> A: Adservers(bundle-2) - 10/06/22

easylist/easylist_adservers.txt
https://futbollatam.com/
||kindleloving.com
||barneysunsharp.com
 
https://atomohd.xyz/
||dienesasides.com
||sacdon.com
||d2vwl2vhlatm2f.cloudfront.net
https://ww5.cinecalidad.link/
||shrinkmesh.com
https://pelisplus.ac/
||inheritedfinnishdysfunctional.com
https://pelismart.com/
||elicitsfoozle.com
https://ww1.pelishouse.me/
||brocardcored.com
https://cuevana3.epizy.com/
||resemblanceilluminatedcigarettes.com
https://mangamovil.net/
||linaloabatches.com
=> A: Adservers(bundle-1) - 10/06/22

easylist/easylist_specific_hide.txt
Banner ads on https://www.thescore1260.com
=> A: https://www.thescore1260.com

easylist/easylist_specific_hide.txt
https://www.tenforums.com/tutorials/25843-turn-off-spell-checking-windows-10-a-2.html
Empty ad container remnants between posts.
=> A: tenforums.com (specific ad hide)

easylist/easylist_specific_hide.txt
Hide sponsored content on https://hbr.org/
=> A: https://hbr.org/

easylist/easylist_specific_hide.txt
Hide banner ads from lottery.ok.gov on the following sites:
https://www.katt.com
https://www.kyis.com
https://www.thesportsanimal.com
https://www.wild1049hd.com
http://www.wky930am.com/
=> A: lottery ads

easylist/easylist_specific_hide.txt
Related commits:
https://github.com/easylist/easylist/pull/12178
https://github.com/easylist/easylist/pull/12234
Classes has changed 
`apotelyt.com##.cuFita-Con` to hide top and bottom ads
`apotelyt.com##.sdbrUnit-Flex100` to hide left placeholder
=> M: Fixes https://www.apotelyt.com/

easylist/easylist_specific_hide.txt
Banner ads on https://www.985kissfm.net
=> A: https://www.985kissfm.net

easylist/easylist_adservers.txt
https://yout.pw/
||neglectedwhip.com
https://yomovies1.live/
||daribahactaea.com
https://www.vipleague.st/
||gleameddelightprosperity.com
||mtttvrit.com
||brftedjb.com
http://www.papystreamings.com/
||blackcurrantspent.com
https://ww.kiss-anime.ws/
||rungglasses.com
https://movies2watch.tv/
||mxabetogiycjdp.com
||sloughybucayo.com
https://tophdgayporn.com/
||wokentractorfurnished.com
https://vww.papadustream.co/
||rapillireddles.com
https://w2.readone-piece.com/
||fridgestretched.com
https://fuxporn.com/
||dd09af1279.com
https://dokisuru.com/
||hecticpassenger.com
||whootkhankah.com
https://gogoanime.gg/
||anicli.click
https://gogoanime.re/
||bustlemiszone.com
https://hurawatch.live/
||tagoutlookignoring.com
https://mangaboat.com/
||arenalitteraccommodation.com …
=> A: Adservers(bundle) - 13/06/22

easylist/easylist_specific_hide.txt
Hide side video at https://hentaistream.tv/
Screenshot:
=> A: https://hentaistream.tv/

easylist_adult/adult_specific_block.txt
Block adservers to initiate at https://dailyporn.club/
Screenshot:
=> A: [NSFW] https://dailyporn.club/

easylist/easylist_general_hide.txt, easylist/easylist_specific_hide.txt
=> A: www.europeanpharmaceuticalreview.com, www.pharmacytimes.com

easylist/easylist_specific_hide.txt
Banner ads on https://www.indysmix.com and https://www.wzpl.com/
=> A: sweetjack ads

easylist_adult/adult_specific_block.txt
block gifs at https://www.camwhores.porn/
=> A: [NSFW] https://www.camwhores.porn/

easylist/easylist_adservers.txt, easylist/easylist_specific_block.txt, easylist/easylist_thirdparty.txt, easylist_adult/adult_specific_block.txt
https://animesgratis.net/
||singerrespectfuljerk.com
https://sbfull.com/
||omervagant.com
||sbfull.com/js/mainpc.js
https://lookmoviess.com/
||ftmsovmmsoi.com
https://hpjav.tv/
||stunninglover.com
|| hpjav.tv/asset/js/mainzk.js
https://tioanime.com/
||d1hnmxbg6rp2o6.cloudfront.net
https://ww3.animeflv.cc/
||clipelis.lol
https://entrepelis.org/
||caruagedlr.com
https://yts-subs.com/
||vnyhxpplppmooe.com
||soluth.com
https://leermanga.net/
||astaticglib.com
||ptistyvymi.com 
https://pelismart.com/
||dowellippen.com
https://www.pelispedia2.me/
||gombaltowa.cfd  
https://lectortmo.org/
||cubeslichees.com
=> A: Adservers(bundle) - 15/06/2022

easylist/easylist_specific_hide.txt
Hide fake download buttons on ww3.d123movies.to
[Sample URL](https://ww3.d123movies.to/watch-movie-2/jackass-4-5-2022_cwobl9wa8/o7oaby4-full-movie-free-online)
=> A: https://ww3.d123movies.to/

easylist/easylist_specific_hide.txt
**found in url:** https://www.careerindia.com/general-knowledge/world-day-to-combat-desertification-drought-theme-significance-impacts-and-facts-on-drought-031985.html
=> A:careerindia.com

easylist/easylist_specific_hide.txt
found in url: https://news24online.com/
=> A:news24online.com

easylist/easylist_adservers.txt
||whootascots.com
https://mydesi.net/
||ubbfpm.com
https://kisscartoon.nz/
||redouthicks.com
https://kazefuri.net/
||prudencebeyondfalter.com
https://hdmovie2.tv/
||ghostedridotto.com
||unjointbobbed.com
https://gnula.se/
||squidgyhawsed.com
https://fmoviesf.co/
||fumarinpest.com
https://episodes.mflixblog.xyz/
||balonamble.com
https://dragontranslation.com/
||uphelyacurrier.com
http://doujinmitai.com/
||configurationluxuriantinclination.com
https://bollyflix.ink/
||puggedproses.com
=> A: Adserver(bundle-2) - 20/06/22

easylist/easylist_specific_hide.txt
Banner ads on 
https://www.bxr.com
https://www.catcountry951.com/
https://www.nashfm1065.com/
https://www.power923.com/
https://www.wbnq.com/
https://www.wncv.com/
https://www.wskz.com/
=> A: https://www.bxr.com

easylist/easylist_adservers.txt
||nicewistful.com
||blinnowther.com
https://animefrenzy.net/
||formfulerses.com
https://vostfree.tv/
||dummieseardrum.com
https://x2download.com/
||truantsambaree.com
https://wv5.123movieshub.tc/
||seedattentiontestify.com
https://yt5s.com/
||pardongaskins.com 
https://fmovies.to/
||qbccpgljgxc.com
https://www.sokrostream.rip/
||carextenuous.com
 
https://watchomovies.net/
||hulksskyed.com
https://pobreflix.top/
||b3kyo0de1fr0.com
http://ww1.putlocker-website.com/
||bainingsardana.com
https://putlockers9.live/
||cuttooscete.com
https://manhuascan.io/
||setoutcazique.com
https://cineb.net/
||jiffspogonia.com
=> A: Adservers(bundle) - 21/06/2022

easylist/easylist_adservers.txt
https://gnula.nu/
||vichycobourg.com
https://fc-lc.com/
||mucinshasht.com
https://pelismart.com/
||pilaryhurrah.com
||freudunsneck.com
https://www.pelispedia2.me/
||camilo4free.cfd
||258c7c3d75.com
https://atomohd.art/
||shrewdoscular.com
=> A: Adservers(bundle) - 22/06/22

easylist/easylist_adservers.txt, easylist/easylist_thirdparty.txt
https://hdtoday.tv/
||atokefissure.com
https://vww.voirseries.rip/
||loggerbunty.com
https://tv.cima4u.cloud/
||ongoingfitfullacerate.com
https://www.roketdizi.pw/
||filese.me
https://ilovemanhwa.com/
||orchidreducedbleak.com
https://123-movies.site/
||frapsguardo.com
https://www2.kickassanime.ro/
||surediscourageconcerning.com
https://www1.animeonline.ninja/
||socketlidoperative.com
https://manga-mx.com/
||laagershosed.com
https://m.animeflv.net/
||d1voskqidohxxs.cloudfront.net
=> A: Adservers(bundle) - 23/06/22

easylist/easylist_general_hide.txt
=> A: (nsfw) https://hdsex.org/video/427687821

easylist/easylist_adservers.txt
https://0gomovie.tv/
||zigansherpa.com
https://watchasian.ac/
||hexodesmacker.com
https://weloma.art/
||foughtdicecup.com
http://globeofnews.com/
||sutiletoroid.com
https://watchthebigbangtheory.com/
||evitingawabi.com
https://m.vegamovies.lol/
||bravoedkilan.com
||duranigaulic.com
https://www5.himovies.to/
||cobnutsvalure.com
https://daftsex.com/
||fosterchildwarehouse.com
https://manhuascan.io/
||clarkiainde.com
||stheneencave.com
||retailgobioid.com
=> A: adservers(bundle) - 24/06/2022

easylist/easylist_specific_hide.txt
Ad in navigation and on the right side. 
There are also ads in the slider, which I am still trying to figure out.
=> A: Ads on wlevradio.com

easylist_adult/adult_specific_block.txt
=> A: (nsfw) txxx.com

easylist/easylist_specific_hide.txt
Hide side video banner at https://hentaihaven.icu/
Screenshot:
=> A: https://hentaihaven.icu/

easylist/easylist_specific_hide_abp.txt
Sponsored ads throughout the page
Other filter suggestion: 
`digg.com#?#.story-flex:-abp-has(div:-abp-contains(DIGG PICKS | SPONSORED))`
=> A: https://digg.com

easylist/easylist_adservers.txt, easylist/easylist_thirdparty.txt
https://yomovies.cam/
||tearoomruchbah.com
||pumiceprutah.com
||bhabgrqjjhn.com
https://xmovies8.fun/
||aripplebeluga.com
https://www4.musichq.net/
||flocktanjib.com
https://www.tvseriesnmovies.com/
||faminedealergirl.com 
https://www.frstream.rip/
||quiapobood.com
https://www.1377x.to/
||colorfullank.com
https://ww6.putlocker.vip/
||photographingmake.com
https://wv5.123movieshub.tc/
||renderscreech.com
https://tokder.org/
||scalpaccomplishedliving.com
https://vizjer.com/
||preferenceforfeit.com
https://themoviesflix.ac/
||staggerconstructionface.com
http://socceron.name/
||gangstermoleanywhere.com
||vswlxqhvjiz.com
||ddnmzrpp.com
https://ngomik.net/
||hernialbriefer.com
https://nhentai.com/
||cebygijy.pro
https://pelismartv.com/
||hymenalwiring.com
https://gogoanime.mom/ …
=> A: Adservers(bundle) - 27.06.22

easylist/easylist_specific_hide_abp.txt
Hide sponsored labels on mobile.
Reference commit: https://github.com/easylist/easylist/commit/c1cdf76
=> A: https://digg.com/ (Mobile)

easylist/easylist_specific_hide.txt
Leftover **Advertisement** labels.
Reference commit: https://github.com/easylist/easylist/commit/72d37bc
=> A: https://gamertweak.com/gallium-warframe/

easylist/easylist_adservers.txt
https://myfreemp3juices.cc/
||jeeryzest.com
https://seriesperu.com/
||mdxidbcodehpy.com
https://pelismartv.com/
||catclawvines.com
https://cinecalidad.fan/
||proclaimincurable.com
https://manhuascan.io/
||catnipsdaymen.com
||expressfouty.com
||fordgitter.com
||drailsaculeus.com
||hoazinangles.com
||hinchantickt.com
||coxalscyth.com
||thackgooder.com
=> A: Adservers(bundle-1) - 29.06.2022

easylist/easylist_adservers.txt, easylist/easylist_thirdparty.txt
https://wwv.streamdeouf.org/
||manivalyrid.com
https://mdisk.me/
||promotebred.com
https://readerzoneclub.xyz/
||dcai7bdiz5toz.cloudfront.net
https://illimite-streaming.com/
||sulkydozeperceive.com
https://readmangabat.com/
||peltingcatwood.com
https://watchdoctorwhoonline.com/
||submitgills.com
||suomicgeyser.com
https://fuxnxx.com/
||3711c45955.com
https://klmanga.net/
||educedsteeped.com
https://lookmovie.la/
||hurlockserail.com
http://moviekhhd.biz/
||bonuscontract.com
=> A: Adservers(bundle - 1) - 30.06.2022

easylist/easylist_general_hide.txt
issue:  https://github.com/mediumkreation/IndianList/issues/5409
=> A:dhakatribune.com

easylist/easylist_adservers.txt, easylist/easylist_specific_block.txt
https://vostanimez.tv/
||strowedatellan.com
||suspectedsinewnotary.com
https://tv.cima4u.cloud/
||sunsetjuxtapositioninvoke.com
https://ww1.putlockers.li/
||irenicaserrano.com
https://gogoanime.day/
||immixteddo.com
||flagmantensity.com
https://movieminions.to/
||supplerneedled.com
||snailteasesimulator.com
http://lk-21.cc/
||go6shde9nj2itle.com
||alas4kanmfa6a4mubte.com
https://kisstvshow.to/
||ageistlutists.com
https://lookmovie.la/
||seraialumins.com
https://mangaforfree.net/
||e55cdcbcd2.com
https://wvvw.cpasfini.rip/
||varechphugoid.com
https://ww.kiss-anime.ws/
||pestgermagriculture.com
https://animeheaven.pro/
||vizcloud.store/E/ 
https://vostfree.tv/
||tootseloin.com
https://animeflv.ac/
||funkerpep.com
=> A: Adserver(bundle-2) - 30.06.22

easylist_adult/adult_specific_block.txt
Block popups at https://watchfreexxx.net/
screenshot:
=> A: [NSFW] https://watchfreexxx.net/

easyprivacy/easyprivacy_allowlist_international.txt
I don't know where to add but `||type.jp/common/js/script_probo.js` can be added to Annoyance list for popup/ai widget.
=> P: https://type.jp/job-1/1259275_detail/?pathway=32

easylist/easylist_adservers.txt, easylist/easylist_adservers_popup.txt
https://readcomiconline.li/
||amitaephapse.com
https://divxfilmeonline.net/
||pitchedfurs.com$popup
https://themoviesflix.ac/
||wilfridscandalconceived.com
||katukaunamiss.com
https://kissasians.org/
||computebailiff.com
https://pelismartv.com/
||unsternrelease.com
=> A: Adservers(bundle) - 01.07.22

easylist/easylist_specific_hide.txt
`https://gameinfinitus.com/`
`https://gameinfinitus.com/news/nintendo-to-release-a-metroid-prime-remaster-this-holiday/`
Hide ad placeholders:
=> A: gameinfinitus.com

easyprivacy/easyprivacy_allowlist_international.txt
=> P: https://onlineshop.ocn.ne.jp/category/ANDROID_MNP/

easylist/easylist_general_hide.txt
Found on `https://avatars.alphacoders.com/by_category/3`.
=> [EasyList] Add ##.ad-side-wrapper

easylist/easylist_specific_hide_abp.txt
=> A: sponsored content on Albertsons

easyprivacy/easyprivacy_trackingservers.txt
Admiral homepage: https://www.getadmiral.com/.
=> Add Admiral hosts

easylist/easylist_adservers.txt
https://www.xmegadrive.com/
||rehearsemeltdownrust.com
||41fcd2b939.com
https://www.watchmyheroacademia4freeonline.xyz/
||concoursestrickenpuppy.com
https://www.mangatigre.net/
||bourranuncurbs.com
https://rawkuma.com/
||lengthcalk.com
https://pmh.li/
||saviourketonic.com
||alfpair.com
https://www.masaporn.xyz/
||gettraffnews.com
||d27genukseznht.cloudfront.net
https://punch.ldkmanga.com/
||closvisarga.com
||attemptgyrose.com
=> A: Adservers(bundle) - 05.07.22

easylist_cookie/easylist_cookie_allowlist_general_hide.txt, easylist_cookie/easylist_cookie_specific_uBO.txt
It seems that those filter would no longer be needed.
=> M: No longer needed

easylist/easylist_specific_hide.txt
Hide placeholders at https://www.lightnovelpub.com/
Screenshot:
=> A: https://www.lightnovelpub.com/

easylist/easylist_adservers.txt
https://nusaslots.one/
||gondangwicopy.com
https://tv.cima4u.cloud/
||serenityspokenrust.com
https://azm.to/
||headstonefoamcleaver.com
https://edoujin.net/
||60e19222e9.com
https://nhentai.website/
||cricketunbutton.com
https://manga-mx.com/
||shotstopers.com
=> A: Adservers(bundle) 07.07.22

easyprivacy/easyprivacy_general.txt
=> P: quiz.mkpo.li

easylist_cookie/easylist_cookie_international_specific_hide.txt
=> A: napsu.fi (specific cookie hide)

easyprivacy/easyprivacy_specific_international.txt
`https://theporn.cc/`
Tracking iframe:
<details>
</details>
=> A: (nsfw) https://theporn.cc/

easylist_cookie/easylist_cookie_international_specific_block.txt
Not relevant anymore.
https://www.sanoma.fi/
https://www.hsy.fi/
=> M: redundancies

easylist_cookie/easylist_cookie_specific_block.txt
=> A: nylon.com (cookie script)

easylist/easylist_adservers.txt
||sautreesned.com
https://www.watchseries.cyou/
||sesameasterisk.com
https://www.animeblix.org/
||barreraxyloid.com
https://watchomovies.online/
||bluntedhalvah.com
http://waptrick.one/
||condoledownright.com
https://w1.123movies-org.site/
||pendulumkeg.com
||galileirice.com
||binmenkollast.com
https://torrentgalaxy.to/
||apartslimlettuce.com
https://moviesjoy.to/
||plebiancairn.com
https://manhwaclub.net/
||01d0c91c0d.com
=> A: Adservers(bundle) - 12.07.22

easylist/easylist_specific_hide.txt
Hide ads carousel at https://www.1tamilmv.click/
Screenshot:
=> A: https://www.1tamilmv.click/

easylist/easylist_specific_hide.txt
Best Reviews widget that links to Amazon
=> A: https://www.dcnewsnow.com/

easylist_cookie/easylist_cookie_specific_block.txt
=> A: irc-galleria.net (cookie script)

easylist/easylist_specific_hide_abp.txt
Leftover ad label on [winaero](https://winaero.com) and also on [article pages](https://winaero.com/how-to-change-start-page-in-windows-11-task-manager/)
=> A: https://winaero.com

easylist_cookie/easylist_cookie_international_specific_hide.txt
https://www.kilpisjarvenretkeilykeskus.fi/
=> A: kilpisjarvenretkeilykeskus.fi (cookie banner hide)

easylist_cookie/easylist_cookie_specific_uBO.txt
=> P: alueviesti.fi (fix scrolling)

fanboy-addon/fanboy_newsletter_specific_hide.txt
- https://imgur.com/pGiHL6c.png
=> A: https://www.windowscentral.com/

easylist/easylist_adservers.txt
http://otakudesu.to/
||deepermagnes.com
https://mangabuddy.com/
||antrumsregrind.com
https://m.animeflv.net/
||distinctlynobleprosecute.com
||d31y1abh02y2oj.cloudfront.net
https://www3.gnula24.xyz/
||don403deblakda.store
||poltbassa.com
https://pelisplus.uproxy.page/
||owlcongratulate.com
http://www.holedk.com/
||abnegationbanquet.com
https://monoschinos2.com/
||resourceswhistlingmore.com
https://www.y2meta.com/
||lunoidgulsach.com
https://www4.pelisplushd.to/
||fakeerupriser.com
https://x2download.com/
||dotlessnorelin.com
https://yt5s.io/
||strivenramplor.com
https://yts-subs.com/
||bladic.com
=> A: Adservers(bundle) - 18.07.22

easylist_cookie/easylist_cookie_specific_block.txt
=> A: timeanddate.com (cookie script)

easylist/easylist_specific_hide.txt
Hide video banner at https://wtechnews.com/
Screenshot:
=> A: https://wtechnews.com/

easylist/easylist_adservers.txt, easylist/easylist_adservers_popup.txt, easylist/easylist_thirdparty.txt
https://www.fullstream.rip/
||dollopsshutout.com
https://www.1-2-3movies.com/
||roesdwaibly.com
https://www.watchseries.cyou/
||foiblesretried.com
https://themoviesflix.cx/
||trashyfindconfront.com
https://tube.perverzija.com/
||bf9c1dc8ca.com
https://verhentai.top/
||d28u86vqawvw52.cloudfront.net
https://vostanimez.tv/
||taggyhearse.com
||sumpki.com
https://onlyfansleaks.tv/
||cupbiologicaljourney.com
https://ponselharian.com/
||kanasmeedful.com
https://series.waploaded.com/
||refugedcuber.com
||requotehocker.com
https://sextb.net/
||stbvip.co
https://soap2day.show/
||upendsspicily.com
||gcouncer.buzz$popup
https://megadeportes.online/
||captiveimpossibleimport.com
https://nkiri.com/
||santosseorita.com
||sabreurnevome.com
=> A: Adservers(bundle) - 19.07.22

easylist/easylist_adservers.txt, easylist/easylist_thirdparty.txt
||hakeemzeugma.com
||flogspci.com
||djinscavalla.com
||chargerbeakers.com
https://mangaforfree.net/
||79cedd0043.com
https://kissjav.li/
||hgub2polye.com
https://keephealth.info/
||captivatepestilentstormy.com
https://kimcartoon.li/
||canangalaities.com
https://incestgod.com/
||contemplatereunitededgy.com
http://imovie.uno/
||leisurelypizzascarlet.com
https://hotindiansexstories.com/
||addresshisselephant.com
https://hentairead.com/
||indirecttagordered.com
https://cineb.net/
||acesbashlyk.com
https://cinecalidad.fan/
||familyliar.com
https://comics24hi.com/
||cepterunlogic.com
https://dramacool.cm/
||gizzenaceric.com
https://dramacool.sr/
||ppikhedas.com
https://duckmanga.com/
||cullflitted.com
||smokesplical.com 
https://earlym.org/ …
=> A: Adservers(bundle) - 20.07.22

easylist/easylist_specific_block.txt
Block script at https://apkmody.io/
Screenshot:
=> A: https://apkmody.io/

easylist/easylist_specific_hide.txt
hide video banner ad at https://nhentai.io/
Screenshot:
=> A: [NSFW] https://nhentai.io/

easylist/easylist_adservers.txt, easylist/easylist_thirdparty.txt
https://v2.cine-calidad.is/
||presidentrestoration.com
https://peliculaspornonline.com/
||jfecfzzuwevyqc.com
https://www.pornotorrent.es/
||d1twn22x8kvw17.cloudfront.net
||orahmaggi.xyz
=> A: Adservers(bundle) - 21.07.22

easylist_cookie/easylist_cookie_general_hide.txt
https://www.liquidblox.com/
https://www.ihanalehti.fi/
=> A: liquidblox.com (generic cookie hide)

easylist_cookie/easylist_cookie_specific_block.txt
=> A: tilannehuone.fi (cookie script)

easylist/easylist_adservers.txt
https://vww.papadustream.co/
||effectdeuce.com
||indold.com
https://wawanimes.tv/
||simoolkankrej.com
||serbianstonish.com
https://ww2.putlocker.fan/
||vetcheslegumen.com
https://www.couchtuner.show/
||arablucidlygrease.com
https://www1.moviesjoy.sc/
||selvaexposit.com
||ruelliaforgift.com
https://ytanime.tv/
||doffingiceboat.com
https://www.seriezloaded.com.ng/
||pavilionslendercudgel.com
||scrumsrokey.com
https://overflix.com/
||ksdlzcmvmj.com
https://prmovies.one/
||jinssimon.com
https://sflix.to/
||vethojoa.net
||toroidscentry.com
https://starplusserial.net/
||argondenial.com
https://streamm4u.ws/
||wagersinging.com
https://kantotin.com/
||protectorincorporatehush.com
https://milfnut.com/
||deliverytraffnews.com …
=> A: Adservers(bundle) - 22.07.22

easyprivacy/easyprivacy_specific_international.txt
or
```
/ext/analytics
/ext/figanalytics
```
=> A: https://codespromo.lefigaro.fr/

easyprivacy/easyprivacy_allowlist_international.txt
Made  the filter more specific. Reference: https://github.com/easylist/easylist/commit/4e90ee517fcd13c3fcf412a8798202bf78c485b5
=> M: foreca.fi scrolling blocked

easyprivacy/easyprivacy_allowlist.txt
These sites needs fixing too.
References:
https://github.com/easylist/easylist/issues/12685
https://github.com/easylist/easylist/commit/4e90ee517fcd13c3fcf412a8798202bf78c485b5
=> P: foreca.com / forecaweather.com (scrolling blocked)

easylist/easylist_adservers.txt
||drinkergenys.com
https://www2.kickassanime.ro/
||lustresneakvisitation.com
https://www1.otakustv.com/
||eggnogsagrapha.com
https://www1.dramacool.ac/
||bathyalmalkin.com
https://turkish123.com/
||sneakyinfected.com
https://mangalek.com/
||yajlpetccbodq.com
https://www.japscan.me/
||atwounlit.com
https://hothit.me/
||bunchypueblo.com
https://www.hispasexy.org/
||columnisterror.com
||lgtdkpfnor.com
https://www.frenchstream.rip/
||fanjetrecoil.com
https://vegamovies.tech/
||estuantunsnow.com
http://webtoontop.xyz/
||pizasoji.com
https://weloma.art/
||unswingfluvial.com
https://welovemanga.one/
||camarondo.com
https://world4ufree1.pics/
||kikugrotzen.com
https://wwvv.streamway.rip/
||curdlesgazump.com
https://www.animefenix.com/
||reariikosin.com
https://www.apkheist.com/ …
=> A: Adservers(bundle-1) - 26.07.22

easylist/easylist_adservers.txt
https://allmovieshub.guru/
||fetiseovisac.com
https://altadefinizione.pe
||dvgigmhdhwtvb.com
||rzqqpamj.com
https://aniworld.to/
||launchreliantcleaver.com
https://bkworldtube.com/
||ocqueroques.com
https://animexinax.com/
||raphidewakener.com
||repairedbringstale.com
||cozesplacebo.com
https://9anime.gg/
||irradiatestartle.com
https://123moviesgo.club/
||okraenrolls.com
https://123gomovies.to/
||pervialinagile.com
https://123-movies.st/
||clozetempts.com
https://www.japscan.me/
||sayingcoxy.com
https://www1.dramacool.ac/
||creedalguilery.com
https://welovemanga.one/
||leerilypimelea.com
https://www.limetorrents.lol/
||olpfeere.com
https://ww4.onlinewatchmoviespk.me/
||gyvesmutic.com
https://vizer.info/
||immisurns.com
https://french-stream.ac/ …
=> A: Adservers(bundle) - 27.07.22

easylist/easylist_adservers.txt
https://pelismartv.com/
||besullyatte.com
https://repack-games.com/
||liegelygosport.com
https://secretstash.in/
||nawyhinu.pro
https://sflix.to/
||naisoops.net
https://soap2day.ai/
||cleanedglistenwhite.com
http://streaming-french.net/
||bendingalliance.com
https://streamm4u.ws/
||chooppolygar.com
https://lectormanga.com/
||ceilidhgrazier.com
https://lookmovie.la/
||revarynookier.com
http://looptorrent.net/
||pilaffskoniga.com
https://monoschinos2.com/
||sprinterchance.com
https://emovies.si/
||sorrilytoon.com
https://french-stream.ac/
||widespreadgabblewear.com
https://hentai-img.com/
||devotedvarnish.com
=> A: Adservers(bundle-2) - 26.07.22

fanboy-addon/fanboy_annoyance_specific_hide.txt
- https://imgur.com/DoXwZBL.png
=> A: https://www.ncrypted.net/

easyprivacy/easyprivacy_allowlist_international.txt
=> P: https://science-net.kahaku.go.jp/app/page/activity.html

easylist_cookie/easylist_cookie_specific_uBO.txt
=> A: flixable.com (cookie hide for uBO)

easylist_cookie/easylist_cookie_specific_block.txt
https://gekkonen.net/
https://www.kilokalori.net/
https://www.riemurasia.net/
=> A: gekkonen.net + others (cookie script)

easylist_cookie/easylist_cookie_specific_hide.txt
=> A: pelit.fi (cookie banner hide)

easylist_cookie/easylist_cookie_specific_block.txt
=> A: findit.fi (cookie banner block)

fanboy-addon/fanboy_newsletter_specific_hide.txt
https://www.suomenmaa.fi/uutiset/paatosta-vanhemmuudesta-pohditaan-useimmiten-lapsen-edun-kautta-on-huolta-periytyvista-mielenterveysongelmista-pahoista-kokemuksista-tai-taloudellisesta-turvattomuudesta/
=> A: suomenmaa.fi (newsletter hide)

fanboy-addon/fanboy_social_specific_hide.txt
https://rakennusmaailma.fi/tassa-ovat-asuntomessujen-parhaat-talot-arvioinnissa-loytyi-helmia/
=> A: rakennusmaailma.fi (social media hide)

fanboy-addon/fanboy_newsletter_international_hide.txt
https://www.netrauta.fi/
Dimmed screen still left.
=> A: netrauta.fi (partial newsletter hide)

easylist_cookie/easylist_cookie_specific_block.txt
=> A: cdon.fi (specific cookie block)

easylist_cookie/easylist_cookie_specific_block.txt
https://www.quora.com/What-are-your-thoughts-on-political-correctness
=> A: quora.com (cookie banner block)

easylist_cookie/easylist_cookie_specific_hide.txt
=> A: e-ville.com (cookie banner hide)

easylist_cookie/easylist_cookie_specific_hide.txt
=> A: flashscore.fi (specific cookie hide)

easylist_cookie/easylist_cookie_international_specific_hide.txt
=> A: liiga.fi (specific cookie hide)

easyprivacy/easyprivacy_allowlist_international.txt
https://www.is.fi/taloussanomat/art-2000008982700.html
=> P: is.fi (video doesn't work)

easyprivacy/easyprivacy_general.txt
Had been caught by now-removed `/i?e=*&page=*&cookie=`
=> A: www.30tidennivyzva.cz

easylist_cookie/easylist_cookie_general_block.txt
=> A: autodoc.fi (generic cookie banner block)

easylist/easylist_general_hide.txt
https://www.is.fi/ulkomaat/art-2000008985364.html
When pausing a video, there's a text at the upper corner saying "Sulje mainos". It translates to "Close the ad". It's a pause ad container remnant. I think this filter would do as a generic.
=> A: is.fi (generic ad hide)

fanboy-addon/fanboy_social_general_hide.txt
https://www.jurvansanomat.fi/uutiset/uusi-nuoriso-ohjaaja-kannustaa-nuoria-ehdottamaan-ohjelmaa-kun-aloite-tulee-nuorilta-min%C3%A4-voin-organisoida
=> A: jurvansanomat.fi (generic social icon hide)

easylist_cookie/easylist_cookie_specific_ABP.txt, easylist_cookie/easylist_cookie_specific_uBO.txt
The scrolling is locked unless cookies are accepted. Only fixable for uBO.
https://lempaala.ideapark.fi/liikkeet/?sc=erikoisliikkeet
https://olutposti.fi/
=> P: lempaala.ideapark.fi / olutposti.fi (locked scrolling)

easylist_cookie/easylist_cookie_international_specific_hide.txt
There was too many `#` in the filter and moved it to the correct location.
=> M: rowery-indiana.pl

easyprivacy/easyprivacy_general.txt
- `https://ak.jacquielawson.com/js/ga_helper.js`
- `https://ak.imgag.com/imgag/js/ga_helper.js`
=> A: https://www.jacquielawson.com/

easyprivacy/easyprivacy_specific_international.txt
https://alypaa.com/pelit/kesavisa
=> A: ruutu.fi (tracking pixel)

easylist/easylist_adservers.txt
Adserver at https://www.extreme-down.io/
Screenshot:
=> A: https://www.extreme-down.io/

easylist_cookie/easylist_cookie_specific_block.txt
GDPR request blocking already covered in this rule:
https://github.com/easylist/easylist/blob/ee23e100c14a7dd419f02f12d4802fcaae46fd07/easylist_cookie/easylist_cookie_specific_block.txt#L79
=> M: duplicate rule

easylist_cookie/easylist_cookie_international_specific_block.txt
=> A: vpd.fi (specific gdpr block)

easylist/easylist_general_hide.txt
https://www.chess.com/article/view/chess-olympiad-deja-vu
=> A: chess.com (ad placeholder)

fanboy-addon/fanboy_newsletter_general_hide.txt
https://www.suomela.fi/
Newsletter remnant.
=> A: suomela.fi (newsletter, generic)

fanboy-addon/fanboy_social_international.txt
https://www.suomela.fi/asuntomessut-herattavat-vanhan-kasarmialueen-henkiin-kouvolassa-esilla-uusinta-asumista-historiallisessa-ymparistossa/
"Jaa sosiaalisessa mediassa" means "Share on social media".
Concerning the filter suggestion:
`suomela.fi##.some-icons`
Word "some" is a colloquial for "social media" in the Finnish language.
=> A: suomela.fi (social media share container)

fanboy-addon/fanboy_annoyance_international.txt
- https://imgur.com/shhDgmE.png
=> A: https://www.manga-sanctuary.com/

easylist_cookie/easylist_cookie_specific_block.txt
https://www.mtvyritys.fi/
Safe to block, info page that doesn't have any embedded content.
=> A: mtvyritys.fi (GDPR script)

easylist/easylist_adservers_popup.txt
1 - Go to https://voiranime.com/anime/kumicho-musume-to-sewagakari/kumicho-musume-to-sewagakari-04-vostfr/ 
2 - select "LECTEUR VOE" server
3 - Click on the play button and you'll get a redirect popup.
Initiator: `fittingcentermondaysunday.com`
**Suggested filter with `$popup` option otherwise video frame gets blocked.**
=> A: https://voiranime.com/anime/kumicho-musume-to-sewagakari/kumicho-musume-to-sewagakari-04-vostfr/

easylist_cookie/easylist_cookie_specific_block.txt
https://www.finder.fi/
No issues caused.
=> A: finder.fi (GDPR block)

easylist_cookie/easylist_cookie_specific_block.txt
https://github.com/AdguardTeam/AdguardFilters/issues/123027
https://elisa.fi/kauppa/puhelinliittymat
=> P: elisa.fi (content not loading)

easylist/easylist_specific_hide.txt
Hide sticky and sidebar ad spaces.
=> A: https://tvtv.us/ma/longmeadow/01116/luUSA-DITV543-DEFAULT

easylist/easylist_general_hide.txt
`https://www.noktabursa.com.tr/2022/03/04/is-kadinina-korkunc-tehdit-sikayetinizi-geri-cekmezseniz-seni-ve-kocani-oldurecegiz/`
<details>
<summary>Image</summary>
</details>
---
The right column is already hidden by the `##.fixedRightAd` rule
=> fixedLeftAd-generic

easyprivacy/easyprivacy_specific_international.txt
i verified it does not raise https://github.com/uBlockOrigin/uAssets/issues/12089 issue
=> A: https://cdiscount.com tracking

easyprivacy/easyprivacy_thirdparty.txt
seen in https://hookupsofficial.myshopify.com/, https://boutique.louvre.fr/?lang=en
=> A: monorail-edge.shopifysvc.com shopify tracking

easylist/easylist_adservers.txt
=> clickoutnetwork.care

easylist_cookie/easylist_cookie_general_hide.txt
`https://www.arcadiafinans.se/`
`https://www.arkadiarahoitus.fi/`
`https://www.netkredit24.de/`
`https://www.komparate.com/`
`https://www.top5credits.com/`
etc..
=> A: Multiple sites (generic cookie hide)

easylist_cookie/easylist_cookie_allowlist.txt, easylist_cookie/easylist_cookie_specific_uBO.txt
https://www.nordiskfilm.com/news-0
=> A: nordiskfilm.com (cookie hide for uBO)

easylist_cookie/easylist_cookie_international_specific_hide.txt
https://www.suomentivoli.fi/
Hides dark overlay leftover
=> A: suomentivoli.fi (specific cookie hide)

fanboy-addon/fanboy_newsletter_specific_uBO.txt
https://www.taloon.com/
Scroll the page a while.
=> P: taloon.com (newsletter overlay breaks scrolling)

easylist_cookie/easylist_cookie_international_specific_hide.txt
=> A: ilvesfoorumi.com (specific cookie hide)

easylist_cookie/easylist_cookie_international_specific_block.txt
=> A: krookmedia.fi (cookie script)

easylist/easylist_specific_hide_abp.txt
Related issue: https://github.com/easylist/easylist/issues/9612
This increases performance, as now only specific divs are checked whether they contain that text. Not all the divs on the page.
=> M: performance improvement

easylist_cookie/easylist_cookie_specific_uBO.txt
See my comment here: https://github.com/easylist/easylist/pull/13055#issuecomment-1227212174
=> M: filter adjusting, performance reasons

easylist_cookie/easylist_cookie_specific_block.txt
Samples pages:
https://asmand.wordpress.com/
https://timoeskola.wordpress.com/
=> M: filter update for wordpress (GDPR script)

easylist_cookie/easylist_cookie_specific_hide.txt, easylist_cookie/easylist_cookie_specific_uBO.txt
=> P: www.dailymotion.com

easylist_cookie/easylist_cookie_specific_uBO.txt
=> A: whatsapp.com (GDPR dialog, uBO)

easylist/easylist_allowlist.txt
=> P: http://musictrack.jp/

easylist/easylist_specific_hide.txt
Hide top ad space.
Reference: https://github.com/easylist/easylist/pull/13143
=> A: https://www.soundguys.com/

easylist/easylist_general_hide.txt
Hide ads at https://kurashinista.jp/ (japanese, but filter can be generic)
Screenshot:
=> A: https://kurashinista.jp/

easylist/easylist_specific_hide.txt
Hide top left side and leftovers ads on https://www.yugatech.com/guides/big-data-promos-smart-globe-gomo-dito-sun-tm/
=> A: https://www.yugatech.com/guides/big-data-promos-smart-globe-gomo-dito-sun-tm/

easylist/easylist_adservers.txt
||drillpatiotrash.com
||tallyhoquires.com
||tunuhap.com
https://www.dramacool9.co/
||quealcoodle.com
https://www.japscan.me/
||rusticswollenbelonged.com
||immixedpistrix.com
=> A: Adservers(bundle)

easylist/easylist_specific_hide.txt, easylist/easylist_specific_hide_abp.txt
https://1337x.to/torrent/4740499/Linux-Mint-20-1-Ulyssa-Cinnamon-64-bit/
=> M: 1337x.to (filter updates)

easylist_cookie/easylist_cookie_international_specific_hide.txt
=> A: lahella.fi (specific cookie hide)

fanboy-addon/fanboy_annoyance_thirdparty.txt
Embed on wordpress blogs/sites.
=> A: https://libroediting.com/

.gitattributes
- I tried it, you can add the template files without any problems, the highlighter simply ignores `%include ...%` lines
- this PR also enables statistics:
@monzta
=> Update Linguist config

easylist/easylist_allowlist.txt
user posted in [forum](https://forum.adblockplus.org/viewtopic.php?f=1&t=93123&sid=c7256b4a3026e954ac98fe9d74fda05d):
With Adblock Plus ON, you cannot scroll dates on [www.titantv.com](http://www.titantv.com/). You have a "loading please wait" message that never ends.
=> F: load error on titantv.com

easylist/easylist_adservers_popup.txt
Block adserver popup at https://www.monstream.org/
Screenshot:
=> A: https://www.monstream.org/

easylist/easylist_specific_hide.txt
Hide top banner at https://lightnovelreader.org/
Screenshot:
=> A: https://lightnovelreader.org/

easylist_cookie/easylist_cookie_allowlist_general_hide.txt
otherwise block registration form, where a "i accept gdpr policy" mandatory box is hidden and block the submission
=> P: https://www.sans.org/registration/register.php?event=74170 

easylist_cookie/easylist_cookie_international_specific_block.txt
https://www.karttakauppa.fi/
also:
https://www.metsakauppa.fi/
=> A: karttakauppa.fi (cookie script)

easylist/easylist_allowlist_general_hide.txt
https://www.tubefilter.com/2022/09/08/youtube-education-distraction-player-courses-quizzes-coder/
Article header goes slightly under navbar
=> P: tubefilter.com

easylist/easylist_specific_hide.txt
Hide banners at https://www.sonyalpharumors.com/fuji-gets-bold-and-announced-the-highest-resolution-aps-c-camera-the-40mp-x-h2/
Screenshot:
=> A: https://www.sonyalpharumors.com/

easylist_cookie/easylist_cookie_specific_hide.txt
=> M: lindex.com (update cookie hide)

easylist/easylist_specific_hide.txt
https://github.com/Ultimate-Hosts-Blacklist/blacklist/issues/11
=> A: https://abbaspc.net/idm-crack/

easylist/easylist_adservers.txt
Block adserver at https://animixplay.to/
Screenshot:
=> A: https://animixplay.to/

easylist/easylist_allowlist_general_hide.txt, easylist/easylist_general_hide.txt
Scroll blocked due to popup overlay.
EL filter causing the issue: `###bww-advertising-popup-overlay`
**With filter enabled:**
**With filter disabled:**
=> P: https://petri.com/how-to-add-domain-controller-to-existing-domain/

easylist/easylist_adservers.txt
Popup banners.
Sample URL: https://kissanime.com.ru/Anime/Kuusen-Madoushi-Kouhosei-no-Kyoukan/
=> A: https://kissanime.com.ru/Anime/Kuusen-Madoushi-Kouhosei-no-Kyoukan/

easylist/easylist_general_hide.txt
Hide footer stick banner at https://latestupdatespk.com/
Screenshot:
=> A: https://latestupdatespk.com/

easylist_adult/adult_specific_block.txt
Block Exoloader at https://thisvid.com/
Screenshot:
=> A: [NSFW] https://thisvid.com/

easylist/easylist_adservers.txt, easylist/easylist_specific_hide.txt, easylist/easylist_thirdparty.txt
CNAME: `web.prebidwrapper.com` ⇒ `dn0qt3r0xannq.cloudfront.net`
`prebidwrapper.com` has HP: `http://www.prebidwrapper.com/`
=> A: thepostmillennial.com

easylist_cookie/easylist_cookie_specific_hide.txt
=> A: reddit.com (mobile cookie hide)

easylist/easylist_specific_hide.txt
Featured content labeled as Advertisement (slider and bottom of the page)
=> A: https://www.kroger.com/

easylist/easylist_specific_hide_abp.txt
Hide sponsored content at Zalando domains
Screenshot:
=> A: https://www.zalando.de/

easylist/easylist_specific_hide.txt
Hide ads in the right side after supporters.
=> A: https://theshoesnobblog.com/

easylist_cookie/easylist_cookie_general_hide.txt
=> A: https://www.videogameschronicle.com/

easylist_cookie/easylist_cookie_specific_hide.txt
https://flixable.com/
Can't click anything.
If you don't see it, try clearing cookies. Only shows on first page load.
=> A: flixable.com (cookie modal background overlay)

easylist/easylist_specific_hide.txt
```
xda-developers.com###xda_alert_bar
```
- `https://www.xda-developers.com/`
```
xda-developers.com##.notices--thnoticesplus_topbar
```
- `https://forum.xda-developers.com/`
=> A: https://www.xda-developers.com/

easylist_cookie/easylist_cookie_specific_hide.txt
=> A: snapchat.com (specific cookie hide)

fanboy-addon/fanboy_social_general_hide.txt
- https://imgur.com/q0U7BH0.png
=> A: https://miniwebtool.com/sort-text-by-length/

easylist/easylist_general_hide.txt
`#anchor-ad`  <details>
<summary>view</summary>
</details>
________
`.bonnier-ad`
<details>
<summary>view</summary>
</details>
_________
`.bonnier-ads-middle`
<details>
<summary>view</summary>
</details>
=> A: https://www.islands.com/

easyprivacy/easyprivacy_specific_international.txt
- https://pastebin.com/raw/ZGRhaCxL
=> A: Email Tracking (nautiljon.com)

easyprivacy/easyprivacy_specific_international.txt
to reproduce, enter a search like "paris lille demain" in the search form in the middle of the main page. you'll have APM script doing a bunch of call, then Events one when you click on a search result square on the right of the list.
=> A: https://www.sncf-connect.com trackers

fanboy-addon/fanboy_annoyance_specific_hide.txt
website down, it was renamed as sncf-connect.com
=> M: remove https://voyages-sncf.com

easylist/easylist_general_block.txt
nsfw
`https://imagetwist.com/m4jv4i8xzt3z/www.0xxx.ws_LittleCaprice-Dreams.22.09.16.Missy.Luv.Streetfuck.XXX.1080p.MP4-WRB.mp4-1.jpg`
=> A: (nsfw) imagetwist.com

easylist/easylist_allowlist.txt
=> P: https://ascii.jp/elem/000/004/095/4095442/

easyprivacy/easyprivacy_thirdparty.txt
seen sending a bunch of fingerprint stuff at https://send.tresorit.com
=> A: applicationinsights.azure.com Azure tracking

fanboy-addon/fanboy_annoyance_international.txt
=> A: https://chektools.com/

fanboy-addon/fanboy_annoyance_international.txt
=> A: https://www.sanctuary.fr/

easylist/easylist_specific_hide.txt
Hide gif banners at https://www.greatandhra.com/
=> A: https://www.greatandhra.com/

easylist/easylist_specific_hide.txt
=> A: https://image.online-convert.com/convert-to-png

easylist/easylist_specific_hide_abp.txt
Hide Sponsored content at https://www.pyszne.pl/ and other regions domains
=> A: https://just-eat.co.uk/ | https://www.pyszne.pl/ | https://takeaway.com/

easylist/easylist_allowlist.txt
=> P: point.rakuten.co.jp (account required)

fanboy-addon/fanboy_newsletter_international_hide.txt, fanboy-addon/fanboy_notifications_specific_hide.txt
https://www.hyvinvoinnin.fi/blogs/ravitsemus/k2-vitamiinilla-on-hatkahdyttavat-terveysvaikutukset
Wait around 20 sec, scroll the page and the left one (newsletter) will appear. After a short while (maybe 20 secs again), the right one (self promo-notification) will appear.
=> A: hyvinvoinnin.fi (newsletter + notification)

easylist_cookie/easylist_cookie_specific_block.txt
=> A: aiheenasyopa.fi (GDPR script)

easylist/easylist_specific_hide.txt
Hide side banners at https://coinweek.com/
https://coinweek.com/category/coins/medals-and-tokens/
=> A: https://coinweek.com/

easyprivacy/easyprivacy_specific.txt
https://clivethompson.medium.com/weird-19th-century-punctuation-marks-you-should-try-using-49d2e2516e5e
=> A: medium tracking

easylist/easylist_specific_hide.txt
Hide banners at:
https://www.sgcarmart.com/used_cars/info.php?ID=1130061&DL=1213 
https://www.sgcarmart.com/used_cars/listing.php?VEH=11
=> A: https://www.sgcarmart.com/

easyprivacy/easyprivacy_trackingservers.txt
behind cname https://act.acotedemoi.com/
=> A: https://www.stokomani.fr

easylist/easylist_specific_hide_abp.txt
According to the website: "These are ads for products on BestBuy.com. These brands paid for an extra chance to get your attention."
=> A: Sponsored Ad carousel on bestbuy.com

fanboy-addon/fanboy_social_allowlist.txt
- `https://www.pngrepo.com/svg/183608/twitter`
- `https://www.svgrepo.com/svg/183608/twitter`
=> A: https://www.pngrepo.com/ & https://www.svgrepo.com/

easyprivacy/easyprivacy_specific_international.txt
https://ici.radio-canada.ca/nouvelle/1920200/elections-quebec-erreurs-francois-legault-politique i don't see it immediately, try to click on some items or just wait seconds
```
logstashUrl: {
production: 'https://logstash-3.radio-canada.ca/c2c7330cbb884818a5b9130b9d46f76d5f83360c9953676739ff196ecab8bfb7',
preproduction: 'https://logstash-1.radio-canada.ca/d73d8efa72c89a4fa2a6cfad49ce012be68bbee7d4887929e2dffe198c8ebe1d',
development: 'https://logstash-1.radio-canada.ca/d73d8efa72c89a4fa2a6cfad49ce012be68bbee7d4887929e2dffe198c8ebe1d',
local: 'https://logstash-1.radio-canada.ca/d73d8efa72c89a4fa2a6cfad49ce012be68bbee7d4887929e2dffe198c8ebe1d'
},
```
=> A: https://ici.radio-canada.ca

easylist_adult/adult_thirdparty.txt
Avoided blocking `http://byxxxporn.com/rta.gif`.
=> A: (nsfw) teensnow.biz, young-tube.me

fanboy-addon/fanboy_social_international.txt
- https://i.imgur.com/Ogzu3a4.png
=> A: https://dontorrent.uno/

fanboy-addon/fanboy_social_international.txt
- https://i.imgur.com/nVHIApx.png
=> A: https://www.gamestorrents.fm/home/

easylist/easylist_general_hide.txt
Hide top banner at https://investmentguruindia.com/
=> A: https://investmentguruindia.com/

easylist_adult/adult_adservers.txt
(NSFW) `clipxn.com` and `in3x.net` are websites so needing third-party
=> A: (nsfw) https://hayjav.com/271459289/91-av-91cm-101

easylist_adult/adult_specific_hide.txt
ex. (NSFW) `https://xanimu.com/es/tag/4611-eipril/`
=> M: update #13665

easylist/easylist_general_hide.txt, easylist/easylist_specific_hide.txt
Hide leftover sticky ad on https://www.writerscafe.org/
=> A: https://www.writerscafe.org/

easyprivacy/easyprivacy_specific.txt
the metrics endpoints only appear after some minutes with tab in the background
fix #13604
=> A: https://app.box.com/s/gzj65oaik4cic1852g5zqyaqw8f2v55w

easyprivacy/easyprivacy_thirdparty_international.txt
The changes resolves https://github.com/AdguardTeam/AdguardFilters/issues/114908.
The filter that will be deleted is added at https://github.com/easylist/easylist/commit/d4149bfbee51bb8ec9deae0e227212b635a82bb2.
=> D: jp.naver.line.android

easyprivacy/easyprivacy_specific_international.txt
=> A: https://charliehebdo.fr

easylist_cookie/easylist_cookie_allowlist.txt
Add `telekom.hu` exception, which fixes #13753
=> A: telekom.hu (Fixes #13753)

easyprivacy/easyprivacy_allowlist_international.txt
Fix hided section at https://www.focus.de/panorama/welt/acht-jahre-nach-der-tat-38-jaehriger-zieht-in-das-haus-in-dem-er-seine-freundin-erstach_id_166156737.html
=> P: https://www.focus.de/

easyprivacy/easyprivacy_specific.txt
- `https://td.airdroid.com/webstat`
=> A: https://web.airdroid.com/?

fanboy-addon/fanboy_social_general_hide.txt
- https://i.imgur.com/IEyunz3.png
=> A: https://thorium.rocks/media/Material/material-design

easyprivacy/easyprivacy_specific.txt
=> A: https://www.kaggle.com/

fanboy-addon/fanboy_social_specific_hide.txt
Related to https://github.com/easylist/easylist/pull/13793
=> A: https://fontawesome.com/search?q=linux

easyprivacy/easyprivacy_trackingservers.txt
They have a site `www.ptztvpremium.com`
=> A: www.portevergladeswebcam.com (www.portevergladeswebcam.com player)

easylist_cookie/easylist_cookie_specific_uBO.txt
tested to login and buy ticket
=> A: https://www.sncf-connect.com

fanboy-addon/fanboy_annoyance_specific_hide.txt
registration modal that pops on top right of the screen doesn't block JS or login
=> A: https://fr.indeed.com/cmp/Starbucks

easylist/easylist_adservers.txt
https://github.com/easylist/easylist/issues/13670
=> A: Update revolving adservers

easyprivacy/easyprivacy_trackingservers.txt
tested that it doesn't break photo album editor
=> A: https://www.vistaprint.com

easylist/easylist_specific_hide.txt
- https://i.imgur.com/mKx7CrA.png
=> A: https://phish.report/

easyprivacy/easyprivacy_general.txt
Added whitelist for the Openskies.sh domain
=> A: utm.openskies.sh

fanboy-addon/fanboy_social_general_hide.txt
Similar case https://github.com/easylist/easylist/issues/13643
=> A: https://www.digital-eliteboard.com/

easyprivacy/easyprivacy_specific.txt
=> A: https://www.welcometothejungle.com/en

easylist/easylist_specific_block_popup.txt
`https://ytsyifys.com/go.php?q=Prey`
=> A: https://ytsyifys.com/

easylist/easylist_adservers.txt, easylist/easylist_specific_block.txt, easylist_adult/adult_specific_block.txt
Just another adspyglass adserver happened to be 1p. So I think better adservers.txt than specific.txt.
=> A: (nsfw) manga9.co​

easylist/easylist_allowlist_general_hide.txt
=> P: [Breakage] https://www.kombi.de/

easylist/easylist_general_hide.txt
e.g. at
```
https://thepiratebay10.org/
https://thepirate-bay.org/
```
=> A: https://thepiratebay10.org/torrent/59191690

easyprivacy/easyprivacy_thirdparty_international.txt
=> A: https://vietnamnet.vn/

easyprivacy/easyprivacy_specific_international.txt
=> A: (nsfw) https://games.dmm.co.jp/detail/MistTrainGirlsX/

easyprivacy/easyprivacy_thirdparty_international.txt
`https://www.hs.fi/`
`https://www.is.fi/`
=> A: sanoma tracking

easyprivacy/easyprivacy_specific_international.txt
`https://www.io-tech.fi/`
`https://bbs.io-tech.fi/`
Tracking pixel.
=> A: io-tech.fi

easyprivacy/easyprivacy_general.txt
```
https://immobilier.nc/a_immo.php?g=getStats_immo&_=1489666412661
```
=> A: https://immobilier.nc/

easylist/easylist_general_hide.txt, easylist/easylist_specific_hide_abp.txt
Hide sponsored content at: 
https://www.priceline.com/relax/in/3000021763/from/20221110/to/20221112/rooms/1/adults/2?vrid=df0b5b9023634d36b7922de7e39399b5
https://www.agoda.com/search?city=12772&checkIn=2022-11-17&los=3&rooms=1&adults=1&children=0&cid=1844104&locale=en-us&ckuid=236579a0-621b-4ba8-a183-c549d59ec1e2&prid=0&currency=USD&correlationId=5dd3a8b3-21ef-4bd4-b094-34a8e9a997ab&pageTypeId=1&realLanguageId=1&languageId=1&origin=BG&userId=236579a0-621b-4ba8-a183-c549d59ec1e2&whitelabelid=1&loginLvl=0&storefrontId=3&currencyId=7&currencyCode=USD&htmlLanguage=en-us&cultureInfoName=en-us&machineName=am-pc-4f-acm-web-user-864649bcf7-rxh46&trafficGroupId=1&sessionId=lzkindkleewt3pf1ma12xhg2&trafficSubGroupId=84&aid=130589&useFullPageLogin=true&cttp=4&isRealUser=true&mode=production&checkOut …
=> A: Sponsored Content

fanboy-addon/fanboy_social_international.txt
https://www.huuto.net/kohteet/vhs-kasetti-kamaa--lahto-0-/571584936
"Jaa" Translates to "Share".
=> A: huuto.net (social share remnant)

easylist/easylist_specific_hide.txt
remove deprecated filters for `returnyoutubedislike` and add new filter
#13904
=> M: returnyoutubedislike.com

easylist_cookie/easylist_cookie_international_specific_block.txt
Filter needs re-adjusting to properly match pages. Sample page https://www.synlab.fi/
=> M: filter re-adjust

easylist_cookie/easylist_cookie_specific_block.txt
https://www.mtv.fi/
https://www.skanska.fi/
https://sponda.fi/
=> A: mtv.fi + others (GDPR script block)

easylist/easylist_allowlist.txt
=> P: https://nosh.jp/influencer-promotion?key=shinycolors20221101

easyprivacy/easyprivacy_specific_international.txt
=> A: kaitori.carview.co.jp (mobile UA, Chromium)

fanboy-addon/fanboy_annoyance_general_block.txt
https://ps.w.org/q2w3-fixed-widget/assets/screenshot-1.gif
=> A: https://phoenixnap.com/kb/linux-tr

easylist/easylist_specific_hide.txt
Top and bottom banners at https://www.sportscardforum.com/
=> A: https://www.sportscardforum.com/

easylist/easylist_thirdparty.txt
e.g.
```
https://static.ifruplink.net/static_src/mc-banner/728%2A90-3-en.gif
https://static.ifruplink.net/static_src/mc-banner/728%2A90-4-en.gif
```
```
https://static.ifruplink.net/static_src/mc-banner/728%2A90-3-ar.gif
https://static.ifruplink.net/static_src/mc-banner/728%2A90-4-ar.gif
```
=> A: https://telemetr.io/en/channels/1640277540-jointojoin11/posts

easylist_cookie/easylist_cookie_specific_uBO.txt
https://www.seurakuntavaalit.fi/
=> A: seurakuntavaalit.fi (GDPR dialog, uBO)

easylist/easylist_adservers.txt
Hilltopads server, may change.
=> A: leermanga.net

easyprivacy/easyprivacy_allowlist_international.txt
=> P: https://zozo.jp/sp/zozoweek/ (account required)

easylist/easylist_adservers.txt
||souvoana.xyz
||dwrdjfdxtoel.com
||wyjaxvuejinse.com
=> A: https://www.couchtuner.show/

easylist/easylist_specific_hide.txt
Hide reels ads between contents at:
https://www.usmagazine.com/celebrity-news/news/hilarie-burton-slams-candace-cameron-bure-for-marriage-comments/?utm_source=UsWeekly&utm_medium=GlobalNews&utm_campaign=GlobalNews
Refer to: https://firework.com/
=> A: https://www.usmagazine.com

easylist/easylist_specific_hide.txt
Hide ad banners between reels at https://imgur.io/ [class="Ad AssemblySlot"]
=> A: https://imgur.io/

easylist/easylist_specific_hide.txt
Hide side banners at https://everydayrussianlanguage.com/es/palabras/piel-de-gallina/
=> A: https://everydayrussianlanguage.com/

easylist/easylist_specific_hide.txt
=> A: https://zoro.to/

easylist/easylist_general_hide.txt
Sponsored items at the bottom of the page foe example on https://www.homedepot.com/s/blower?NCNI-5&Nao=24
=> A: https://www.homedepot.com/

easyprivacy/easyprivacy_general.txt
=> A: https://www.courir.com/fr/p/nike-hoodie-have-a-nike-day-1497631.html

easylist/easylist_specific_hide.txt
=> A: https://dexdotexe.com/ (ad placeholders)

easylist_cookie/easylist_cookie_specific_uBO.txt
If you're wondering why I removed the html from the style filter:
<details>
<summary>view</summary>
sometimes issues when scrolling
</details>
=> M: https://www.healthline.com/ (Fixes #14180)

easyprivacy/easyprivacy_thirdparty.txt
=> A: https://chewingthefat.us.com/

easylist/easylist_adservers.txt
=> A: https://wheregoes.com/

fanboy-addon/fanboy_social_international.txt
- https://i.imgur.com/9SXJP5v.png
=> A: https://stad.yalla-shoot.io/live/1.php

easylist/easylist_allowlist.txt
=> P: https://atcoder.jp/posts/780

fanboy-addon/fanboy_social_general_hide.txt
=> A: https://www.kooora.com/

easylist/easylist_general_hide.txt, easylist_cookie/easylist_cookie_general_hide.txt
Front page:
Article page:
Cookie banner with same name also here:
`https://info.connatix.com/`
=> A: https://www.devex.com/

easylist/easylist_specific_hide.txt
Hide right side banners at https://www.liverpoolway.co.uk/
=> A: https://www.liverpoolway.co.uk/

easylist/easylist_adservers.txt
Some may already be changed.
`worldcupstream.pm`: `||hafnes.com^` 
`www.hentaizm.fun`: `||ppcnt.pro^`
`apkmody.io`: `||ovxdhhgklmrwcqo.com^`
`gmanga.me`: `||ootchaig.xyz^` (needs some interaction, see SS)
=> M: adservers

easylist/easylist_general_hide.txt
=> A: https://www.fastcompany.com/

fanboy-addon/fanboy_notifications_allowlist_general_hide.txt
=> P: https://app.joinhandshake.com/stu/notifications

easylist_cookie/easylist_cookie_specific_hide.txt
=> A: amazon.com.be (GDPR dialog)

easyprivacy/easyprivacy_specific.txt
post request with tons of performance stuff and all the requests loaded
does not appear to be sent all the time
=> A: https://stackoverflow.com/questions/tagged/angular-cdk

easylist_cookie/easylist_cookie_specific_hide.txt
=> A: https://factory.pixiv.net/

easylist/easylist_specific_hide.txt
Animated advertisement on the side of the page.
thank you
=> A: https://greyhound-data.com/

easylist/easylist_specific_hide.txt
=> A: www.millennial-grind.com

easylist/easylist_general_hide.txt
Go to https://cointiply.com/home
Set up an account and log in
You will see a page with bars at the top of the page, below the nav bar
If you hover over these three bars, you will see an ad covering the content
=> A: https://cointiply.com/

easylist_cookie/easylist_cookie_allowlist.txt, easyprivacy/easyprivacy_allowlist.txt
`||transcend.io^` is blocked by easylist cookie. not in easyprivacy
=> M: #14159 (move to correct list)

easyprivacy/easyprivacy_allowlist_international.txt
Please allowlist this domain as its blocking video content owned by the website 
Thank you
=> M: video content blocked on autobild.de

easylist/easylist_allowlist_general_hide.txt
(account required)
Fixed point count not displayed. (See screenshot.)
=> P: https://nicoad.nicovideo.jp/video/publish/sm41501707?frontend_id=6&frontend_version=0&video_watch

easyprivacy/easyprivacy_allowlist_international.txt
Reported in `https://twitter.com/sarukiti_se/status/1604736978133880834`
So far the error message only, but I don't use/login the site. Yet this is Japanese national ID site and any possilble breakge will not be acceptable.
=> P: https://myna.go.jp/alpha/discover (mobile UA)

easylist/easylist_general_hide.txt, easyprivacy/easyprivacy_general.txt
=> A: (nsfw) elog.tokyo

easylist_cookie/easylist_cookie_specific_hide.txt
=> https://adressa.no

easylist_adult/adult_specific_block.txt
Please add this domain to the existing filter, it redirects on another page then pressing on the page.
=> A: [NSFW] `http://desiporn.tube/`

easylist_cookie/easylist_cookie_international_specific_hide.txt
=> A: valostore.fi

easylist_cookie/easylist_cookie_international_specific_hide.txt, easylist_cookie/easylist_cookie_specific_hide.txt
=> A: valomania.fi (GDPR dialog)

easylist_adult/adult_specific_hide.txt
Please add this domain to the existing filter has a lot of overlaying ads on mobile  https://imgur.com/a/jjlS6ZM
=> A: [NSFW] `manga18fx.com`

easyprivacy/easyprivacy_allowlist_international.txt
=> P: https://townwork.net/tokyo/areaSelect/ (mobile UA)

easylist_adult/adult_specific_hide.txt
Please add this domain to the existing filter, has popping ads on mobile. 
Thank you
=> A: `[NSFW] https://manhwa18.cc/`

easyprivacy/easyprivacy_thirdparty.txt
=> A: https://m.alibaba.com

easyprivacy/easyprivacy_specific_international.txt
=> A: https://hoctap.coccoc.com/

easyprivacy/easyprivacy_specific_international.txt
=> A: hepsiburada.com

easyprivacy/easyprivacy_specific_international.txt
=> A: https://www.cesu.urssaf.fr/

easylist_cookie/easylist_cookie_international_specific_hide.txt
=> A: https://assure.ameli.fr/PortailAS/appmanager/PortailAS/assure

easyprivacy/easyprivacy_allowlist_international.txt
Please allowlist this filters for `https://www.computerbild.de/` its blocking their video content.  Thank you
=> A: `https://www.computerbild.de/`

easyprivacy/easyprivacy_allowlist_international.txt
Please add this filters and domain to the existing filter its blocking the video content on page
=> F: (blocks video content) `rollingstone.de`

easyprivacy/easyprivacy_thirdparty.txt
i've successfully made a donation payment with the tracker blocked
=> A: https://don.secourspopulaire.fr/defaut/~mon-don

easylist/easylist_adservers.txt
https://github.com/easylist/easylist/issues/14573
=> A: (nsfw) sextb.net (fixes #14573)

easylist_adult/adult_specific_block.txt
https://github.com/easylist/easylist/issues/14475
=> A: (nsfw) www.naughtyblog.org (fixes #14475)

easylist_cookie/easylist_cookie_specific_hide.txt
Site to test: https://meteoschweiz.roundshot.com/zuerich-fluntern/
=> A: https://www.roundshot.com/

easylist/easylist_specific_hide.txt
- https://i.imgur.com/ZtnDCLJ.png
=> A: https://www.romsgames.net/download/nintendo-64-rom-donkey-kong-64/

easyprivacy/easyprivacy_general.txt
- `https://cdn.wwads.cn/js/fp-3.3.6.min.js`
=> A: (wwads.cn > ventoy.net) #14604

easyprivacy/easyprivacy_thirdparty.txt
international, also on https://www.decathlon.it/
=> A: https://www.decathlon.fr

fanboy-addon/fanboy_newsletter_allowlist_general_hide.txt
https://halvinsähkösopimus.fi/hintavahti/
Technically, this is a newsletter but it's a price watch tool. It's on a separate, dedicated page, thus it should not be blocked. You must willingly click yourself to that page.
=> P: halvinsähkösopimus.fi (price watch broken)

easylist/easylist_specific_hide.txt
Please add this filter to hide the ads banner on the top of the page
Thank you
=> A: `torbay.gov.uk`

easylist_cookie/easylist_cookie_international_specific_hide.txt
https://www.luvn.fi/en
The site uses similar solution to https://www.espoo.fi/en. They have 3 different language and the aria label changes depending on the language being selected so 3 filters are needed.
Also cleaned some old espoo.fi entries that are not needed.
=> A: luvn.fi (GDPR dialog hide)

easylist_cookie/easylist_cookie_specific_hide.txt
and also https://tv.marianne.net
this time #didomi-host without blocked scrolling
=> A: https://www.marianne.net

easylist/easylist_specific_hide.txt
Hi, please add this filter to hide this banner with ads.
Thank you in advance
=> A: `healthnfitness.net`

easylist/easylist_specific_hide.txt
=> picnob.com
