- easylist/easylist_general_hide.txt
- easylist/easylist_specific_hide.txt
Please add this filter to hide the ads displayed on the page
Thank you
> A: `itmedia.co.jp`

- easylist/easylist_allowlist.txt
https://github.com/easylist/easylist/pull/10137
> M: remove obsolete rule (by #10137)

- easylist/easylist_specific_hide.txt
Fixes https://github.com/easylist/easylist/issues/14686
> A: https://www.irishtimes.com/ (Fixes #14686)

- easylist/easylist_allowlist.txt
> P: ads-i.org

- easylist/easylist_allowlist.txt
> P: https://adfurikun.jp/adfurikun/

- easylist_adult/adult_adservers_popup.txt
Please add this adservers popups filters to the list as they open ads in another tab. thank you
> A: (nsfw) `https://nhentai.to/`

- easylist_adult/adult_specific_block_popup.txt
Please add the domain to the existing filter to stop popping ads and redirection of the content in another tab.
> [NSFW] A: `https://forums.socialmediagirls.com/`

- easyprivacy/easyprivacy_allowlist_international.txt
Related issue: https://github.com/AdguardTeam/AdguardFilters/issues/140678
> P: https://sportiva.shueisha.co.jp/smart/?category=baseball (mobile UA)

- easylist_cookie/easylist_cookie_international_specific_hide.txt
> A: vts.fi (GDPR dialog)

- easylist/easylist_specific_hide.txt
Please add the filters to hide the ads on `dailydooh.com` 
Thank you in advance
> A: `dailydooh.com`

- easylist/easylist_specific_hide.txt
"Partner Banners" are ads.
Site to test: https://manual.limesurvey.org/Question_object_types
> A: https://manual.limesurvey.org/

- easyprivacy/easyprivacy_specific.txt
does not block adding to cart and go to payment form
> A: https://www.lego.com

- easylist_cookie/easylist_cookie_international_specific_hide.txt
Example: `https://www.mod.gov.lv/lv/selijas-militarais-poligons`
> `mod.gov.lv` (cookies)

- easylist/easylist_specific_hide.txt
Site to test: https://forums.limesurvey.org/forum/installation-a-update-issues/133917-is-php-8-1-or-8-2-supported-by-ls-5-x
> M: https://forums.limesurvey.org/

- easylist/easylist_general_block.txt
`$script` for `/code/native.js?h=` is to avoid xhr bait. Moved `/yzfdmoan.js` as is not Clickadu.
<details>
<summary>Screenshots (include NSFW sites)</summary>
`https://btcheat.com/`
`http://k-streaming.com/`
[NSFW] `https://www.daftporn.com/`
[NSFW] `https://japanhub.net/`
[NSFW] `http://pornreactor.cc/`
[NSFW] `https://gaysex69.net/`
[NSFW] `https://www.zzcartoon.com/`
[NSFW] `https://freemomsonporn.com/`
[NSFW] `https://www.bravotube.net/`
[NSFW] `http://xxxaporn.com/`
`https://unimasgo.com/`
`https://adspromoters.com/`
`https://changthairestaurants.com/`
</details>
> M: add generic rules for revolving adservers

- fanboy-addon/fanboy_social_allowlist_general_hide.txt
- fanboy-addon/fanboy_social_international.txt
> P:  https://www.voice.fi/

- easyprivacy/easyprivacy_allowlist_international.txt
Images below articles are blocked
> P: https://www.findance.com/

- easylist/easylist_allowlist.txt
> P: https://pro-foto.jp/ads/

- easylist_cookie/easylist_cookie_international_specific_hide.txt
https://hackthenetworks.fi/en
https://havaro.fi/
https://www.kyberturvallisuuskeskus.fi/
https://tietoturvamerkki.fi/
https://turvalistit.fi/
> A: Multiple sites (cookie hide)

- fanboy-addon/fanboy_newsletter_international_hide.txt
Appears on mobile and smaller window sizes.
> A: https://www.iltalehti.fi/

- fanboy-addon/fanboy_social_international.txt
> A:  https://www.ku.fi/

- easyprivacy/easyprivacy_specific_international.txt
> A: https://www.telerama.fr/

- easylist/easylist_specific_hide.txt
https://github.com/mediumkreation/IndianList/issues/6692
> A:news18.com

- easyprivacy/easyprivacy_allowlist_international.txt
- easyprivacy/easyprivacy_specific_international.txt
- fanboy-addon/fanboy_annoyance_specific_hide.txt
The pandora.tv service will be ended in February 1st, 2023 (KST).
http://www.pandora.tv/company/notice/view/1/1178
- https://github.com/List-KR/List-KR/issues/572
- https://github.com/AdguardTeam/AdguardFilters/pull/140855
> M: pandora.tv

- easylist/easylist_general_hide.txt
Hi, sorry I know this is EL. english but this greek domain is full with ads and this generic filter would help hide min. 3 banners. (see image with 3 ads around the page) 
Would really appreciate if it can be added, thank you
> A: `https://psaxna.gr/`

- easylist/easylist_specific_hide.txt
Hi, this website has a banner add on top of the page.  
Thank you
> A: `morningagclips.com`

- easylist_cookie/easylist_cookie_international_specific_hide.txt
https://www.suojakalvotukku.fi/
> A: suojakalvotukku.fi (GDPR dialog)

- easylist_cookie/easylist_cookie_international_specific_hide.txt
> A: phonelife.fi (GPRR dialog)

- easylist/easylist_allowlist.txt
- easyprivacy/easyprivacy_allowlist_international.txt
Unfortunately these are the minimal exception to play the game.
> P: https://www.fukuishimbun.co.jp/feature/games/?top_game=&amGameId=158

- easylist/easylist_adservers.txt
- easylist_adult/adult_adservers.txt
Please remove from the list. 
User complained the page is broken when blocking ads
> M: (nsfw)`tubesweet.com`

- easylist/easylist_specific_hide.txt
https://github.com/mediumkreation/IndianList/issues/6692
> A:hindustantimes.com

- easylist_cookie/easylist_cookie_specific_ABP.txt
- easylist_cookie/easylist_cookie_specific_uBO.txt
https://lvs.fi/
https://orivedensanomat.fi/
https://pirkkalainen.fi/
https://pirmediat.fi/
https://radiosun.fi/
https://ylojarvenuutiset.fi/
> P: Multiple (fix scrolling)

- easylist/easylist_adservers.txt
> M: https://adhunt.net/

- easylist/easylist_specific_hide.txt
Hi please add this domain to the existing filter to hide this ads on the page: 
Thank you
> A: `androidpctv.com`

- easyprivacy/easyprivacy_allowlist_international.txt
https://www.verkkokauppa.com/fi/product/778669/Samsung-UE65BU8072-65-4K-LED-televisio/questions/write
Sending a product question is blocked, due to "privacy settings".
```
Kysymystä ei voida lähettää!
Selaimellesi asetetut yksityisasetukset estävät kysymyksen lähettämisen. Muuta asetuksia, jotta pääset jakamaan mielipiteesi!
```
Translation:
```
Question could not be send!
Your browser's privacy settings prevent sending the question. Change settings, so that you can share your opinion!
```
(You'll need an account for this.)
When it's fixed, you'll see this button (it's a button to send a question):
> P: verkkokauppa.com

- fanboy-addon/fanboy_newsletter_specific_hide.txt
Hides too much. 
See: https://github.com/easylist/easylist/issues/13243#issuecomment-1242788462
> P: https://www.dexerto.com/

- easylist_cookie/easylist_cookie_general_hide.txt
> CRM XenForo 2.x

- easylist/easylist_specific_block.txt
Hi, please add the third-party section to the filter, it's breaking one of the functionalities of the page to open links in another tab. and this filter is crucial to stop all the redirecting ads on the pages.
Thank you in advance.
> F: `soap2day.ac`

- easylist/easylist_specific_hide.txt
Hi, please add the following filter to the list to hide this add
Thank you
> A: `hidefninja.com`

- easylist/easylist_allowlist.txt
Have to go through questionnaire on `https://yuru-mbti.com/quiz.php`.
> P: https://yuru-mbti.com/adsense.html (direct access impossible)

- easylist/easylist_adservers.txt
Only at the very first visit. Will disappear on reload.
<details>
</details>
> A: (nsfw) https://nextlawyer.it/video-uzelnea/_18_..._

- easyprivacy/easyprivacy_specific.txt
seen on https://www.ted.com/talks/t_morgan_dixon_and_vanessa_garrison_the_most_powerful_woman_you_ve_never_heard_of
> A: ted.com

- easylist/easylist_specific_hide.txt
Side banner at https://superdeluxeedition.com/news/last-chance-to-order-the-bob-dylan-blu-ray-audio/
> A: https://superdeluxeedition.com/

- easylist/easylist_specific_hide_abp.txt
Related:
https://github.com/AdguardTeam/AdguardFilters/issues/115751
https://github.com/AdguardTeam/AdguardFilters/issues/74505
> A: https://www.standard.co.uk/tech/fbi-recommends-ad-blocker-online-scams-b1048998.html

- easylist/easylist_specific_hide.txt
Hide Banners at https://swimswam.com/
> A: https://swimswam.com/

- easylist_adult/adult_specific_hide.txt
Ads on the page top header, bottom footer and at the bottom of page.  Thank you
> A:[NSFW] `zbporn.com`

- easylist/easylist_general_hide.txt
https://black-flag.net/release/20210818-6958.html
> A: https://black-flag.net/

- easylist_adult/adult_specific_hide.txt
Hi please add the domain to the existing filter, thanks
> A: [NSFW] `javhat.tv`

- easylist/easylist_specific_hide.txt
Banners at https://golfworkoutprogram.com/foresight-gc3-review/
> A: https://golfworkoutprogram.com/

- easylist_cookie/easylist_cookie_specific_ABP.txt
- easylist_cookie/easylist_cookie_specific_uBO.txt
https://akaanseutu.fi/
https://shl.fi/
> A: akaanseutu.fi + shl.fi

- easylist/easylist_specific_hide.txt
placeholder above navbar on mobile
> A: https://www.atlasobscura.com/

- easylist/easylist_general_block.txt
> M: https://adrefresh.io/

- easylist_adult/adult_specific_hide.txt
Blocks analytics and third party content
> [NSFW] sexhd.pics

- easylist/easylist_specific_hide.txt
- easylist/easylist_specific_hide_abp.txt
thefreshgrocer.com 
shoprite.com
coles.com.au
petco.com
> A: Banners

- fanboy-addon/fanboy_notifications_specific_hide.txt
- https://i.imgur.com/Ku1F84t.png
- https://i.imgur.com/IMqb7AX.png
> A: masrawy.com & yallakora.com

- easylist/easylist_specific_block.txt
Hi, could you please review and add this filter to the list, the user complained about still seeing ads displayed across the platform: 
Kind regards,
> A: `hltv.org`

- easylist_adult/adult_specific_hide.txt
- easylist_adult/adult_thirdparty.txt
Unsure if `##.content` is safe or `##.ads` is worth adding.
> A: (nsfw) https://javbraze.com/search/pornstar/?s=

- easyprivacy/easyprivacy_allowlist_international.txt
> P: https://www.eeva.fi/luetuimmat

- easylist/easylist_adservers.txt
> Fixes desusffsdfsf

- fanboy-addon/fanboy_social_specific_hide.txt
> A: https://www.suomi24.fi/viihde/

- easyprivacy/easyprivacy_allowlist_international.txt
Blocking this request causes this error:
Sample link: https://www.supla.fi/episode/149090c5-fac5-49a2-8b22-35127d2e928c
> P: supla.fi podcasts not working (EP issue)

- easylist/easylist_allowlist.txt
https://www.telsu.fi/
When I hover mouse over a program, it says:
`Ohjelmatietojen haku epäonnistui. Kytke mainosten esto pois päältä`
Translation:
`Retrieval of program information failed. Turn off the adblocker.`
> P: telsu.fi (TV-Program information can't be retrieved)

- easylist/easylist_general_hide.txt
- easylist_adult/adult_specific_hide.txt
Three languages so I assume is an international site.
> A: (nsfw) ggjav.com

- fanboy-addon/fanboy_newsletter_specific_uBO.txt
> M: merge + add https://www.bygonely.com/

- easyprivacy/easyprivacy_specific_international.txt
> A: spoox.skyperfectv.co.jp (account required)

- easyprivacy/easyprivacy_trackingservers.txt
> A: jp.mercari.com

- easylist/easylist_specific_block.txt
- https://i.imgur.com/neW1C94.png
> A: https://www.iconfinder.com/icons/99019/translate_google_icon

- fanboy-addon/fanboy_annoyance_specific_hide.txt
- https://i.imgur.com/E2v2YFy.png
> A: https://forums.opera.com/

- easylist/easylist_specific_hide.txt
> A: https://www.wargamer.com/

- easylist_cookie/easylist_cookie_international_specific_hide.txt
> A: https://varasija.com/

- easylist/easylist_general_hide.txt
- https://i.imgur.com/7jLqQUG.png
> A: https://www.freepik.com/free-vector/sand-desert-landscape-template_9581115.htm

- easyprivacy/easyprivacy_specific.txt
> A: https://wise.com/

- easylist/easylist_specific_hide_abp.txt
Hi please add the following filter to the list to hide this sponsored ads on the main page: 
Thank you
> A: `sainsburys.co.uk`

- easyprivacy/easyprivacy_thirdparty.txt
- easyprivacy/easyprivacy_trackingservers.txt
Elevar is a tracking company for shop websites
blocking it does not seams to block delsey.com order process
> A: https://fr.delsey.com

- easyprivacy/easyprivacy_trackingservers.txt
> A: https://www.mediapart.fr/

- easylist/easylist_specific_hide.txt
https://www.newegg.com/houdeos-cost-effective-series-ls878-black/p/380-00EE-00001?Description=drone&cm_re=drone-_-9SIB7GGGUZ6837-_-Product
> A: https://www.newegg.com/

- easyprivacy/easyprivacy_specific.txt
> A: https://medal.tv/

- easyprivacy/easyprivacy_thirdparty.txt
> A: fillage.jp

- easylist/easylist_thirdparty.txt
- easyprivacy/easyprivacy_thirdparty.txt
International: https://publicwww.com/websites/%22%2Fsca_affiliate_new.js%22/
> A: aoiro.co

- easylist/easylist_specific_hide.txt
- easylist/easylist_specific_hide_abp.txt
👋  Hi, please add this filter to hide the sponsored items on the page. Thank you
> A:`countdown.co.nz`

- easylist_cookie/easylist_cookie_international_specific_hide.txt
https://www.matkapuhelinfoorumi.fi/
> A: matkapuhelinfoorumi.fi (GDPR dialog hide)

- easylist_cookie/easylist_cookie_general_block.txt
> A: nuorisoala.fi (Generic GDPR block)

- easylist/easylist_specific_hide_abp.txt
> easylist_specific_hide: trends.gab.com

- easylist/easylist_specific_hide_abp.txt
Hi please review this filter to hide the ads on the page: 
Thank you
> A: `priceline.com`

- easylist/easylist_allowlist.txt
> P: https://www.bsfuji.tv/ondemand/library/hak2022.html

- easylist/easylist_specific_hide.txt
> coindesk div.high-impact-ad

- easylist/easylist_specific_hide_abp.txt
Hi please review this website with ads: 
Please bear in mind that this is reproducible in some regions only like with VPN -USA(New Jersey)  in this particular case.  Thank you
> A: `macys.com`

- easyprivacy/easyprivacy_thirdparty.txt
https://github.com/easylist/easylist/blob/36fcc48d7c2f5cc1ddd2048c0dce666e7974bf2c/easyprivacy/easyprivacy_trackingservers.txt#L1636
https://github.com/easylist/easylist/blob/36fcc48d7c2f5cc1ddd2048c0dce666e7974bf2c/easyprivacy/easyprivacy_thirdparty.txt#L1202
> lr-ingest.io - duplicate rule 

- easylist/easylist_general_hide.txt
https://gizmodo.com/sonos-era-300-smart-speaker-dolby-atmos-apple-airplay-1850267456
> A: https://gizmodo.com

- easylist_cookie/easylist_cookie_international_specific_hide.txt
> A: https://www.tapahtumienkeskipohjanmaa.fi/

- easylist_cookie/easylist_cookie_specific_hide.txt
https://www.jackjones.com/
https://www.jjxx.com/
https://www.mamalicious.com/
https://www.veromoda.com/
> A: Multiple (background overlay)

- easyprivacy/easyprivacy_thirdparty.txt
related to search function, does not break it
> A: https://www.onepiece.com/fr

- fanboy-addon/fanboy_newsletter_international_hide.txt
https://i.imgur.com/bo9qUKw.png
> A: https://www.marmiton.org/recettes/recette_17656.aspx

- easylist_adult/adult_specific_hide.txt
Hi 👋 please review this filter there are ads on top of the page:
Thank you
> A:[NSFW] `hentai2read.com`

- easylist/easylist_specific_hide.txt
The ad and class name is currently hard coded into the site.
> A: https://modrinth.com

- easyprivacy/easyprivacy_trackingservers.txt
> A: aptrinsic.com

- easylist_adult/adult_specific_block.txt
- easylist_adult/adult_specific_hide.txt
- easylist_adult/adult_thirdparty.txt
`||c3s.bionestraff.pro^` is on `bbporntube.pro` and `||jo.hqbang.com^` on `www.4wank.com`, both are AdSpyglass.
> M: update NSFW sites

- easyprivacy/easyprivacy_specific.txt
error reporting while i'm connected. Does not appear when browsing non-logged-in.
> A: https://www.vinted.fr/

- fanboy-addon/fanboy_newsletter_general_hide.txt
> A: https://www.digitaltrends.com/

- easylist_cookie/easylist_cookie_specific_uBO.txt
https://www.fruugo.fi/voiruoka-posliinivoiastia-jossa-on-puinen-kansi-ja-pieni-veitsi-juustolaatikko-sailytettavaksi-cusine-jaakaapissa-250g-vari-valkoinen/p-154244679-326525279
> A: fruugo.fi (GDPR dialog, uBO)

- easylist_adult/adult_specific_hide.txt
- easyprivacy/easyprivacy_specific.txt
See https://github.com/easylist/easylist/pull/15678 too
> A: (nsfw) https://jav4tv.com/video147256/caribbeancom-041823-001

- easyprivacy/easyprivacy_thirdparty_international.txt
> A: https://tver.jp/episodes/epnaiaub44

- easylist/easylist_specific_hide.txt
https://github.com/easylist/easylist/pull/15610
> A: https://dryicons.com/icon/flat-blossom-icon-8076

- easylist_adult/adult_specific_block.txt
- easylist_adult/adult_specific_hide.txt
https://tuheroesincapahub.com/
https://thefap.net/
https://xgroovy.com/
> [NSFW] M: Update

- fanboy-addon/fanboy_newsletter_international_hide.txt
- https://i.imgur.com/OM8nDWP.png
> A: https://www.mariefrance.fr/

- easyprivacy/easyprivacy_general.txt
Its internal domain, adding this will make devs live easier.
> M: Added dynatracelabs.com domain to existing dynatrace rules.

- easylist/easylist_specific_hide.txt
> A: https://www.liverpoolecho.co.uk/

- easyprivacy/easyprivacy_thirdparty.txt
https://www.terveystalo.com/
Even if this is officially a GDPR dialog, I think this should go here as it seems to be analytics related completely.
> A: terveystalo.com (GDPR dialog, analytics)

- easyprivacy/easyprivacy_allowlist_international.txt
> P: www.bookoffonline.co.jp

- fanboy-addon/fanboy_notifications_general_block.txt
Generic script to create app banner.
https://publicwww.com/websites/%22smart-app-banner.js%22/
> A: suomenkuvalehti.fi (generic block smart app banner)

- easyprivacy/easyprivacy_specific_international.txt
lemonde.fr/28daa137ca05404c23e8c5eef47f54b8d4a63912
> A: https://www.lemonde.fr/

- fanboy-addon/fanboy_newsletter_international_hide.txt
https://www.valitutpalat.fi/terveys-ja-hyvinvointi/syopa-15-naisten-useasti-sivuuttamaa-syopaoiretta/
> A: valitutpalat.fi (newsletter)

- easylist_cookie/easylist_cookie_specific_uBO.txt
https://www.veikkaus.fi/fi/yritys#!/article/tiedotteet/pelit/2017/06-kesakuu/15-nain-rationaalinen-ihminen-pelaa-lottoa
> M: veikkaus.fi filters update (GDPR hide)

- easylist/easylist_general_hide.txt
- easyprivacy/easyprivacy_general.txt
```
www.juststarz.com
www.kueez.com
www.thefunpost.com
www.shrinkplus.com
```
> A: www.buzzerilla.com, www.historictalk.com, www.parentmood.com, etc.

- easyprivacy/easyprivacy_allowlist.txt
Added `in.bookmyshow.com` in easyprivacy_allowlist.txt to fix issue #15825
> Added in.bookmyshow.com to fix issue #15825

- easylist/easylist_specific_hide.txt
https://food.allwomenstalk.com/magnificent-ways-to-flavor-sweet-potatoes/
> A: https://allwomenstalk.com/

- easyprivacy/easyprivacy_general.txt
Exclude the site utm.lol which is an UTM builder site.
> M: ://utm.

- easylist/easylist_adservers_popup.txt
- easylist/easylist_specific_hide.txt
Banner ads at the top of the website:
Also there are popups from any clicks on the page
> A:`komikcast.site`

- easylist_cookie/easylist_cookie_international_specific_hide.txt
> A: https://www.luurinetti.fi/

- easylist_cookie/easylist_cookie_international_specific_hide.txt
> M: https://www.valostore.fi/

- easylist_cookie/easylist_cookie_specific_uBO.txt
fix https://github.com/ghostery/broken-page-reports/issues/300
> Fix theprotocol.it

- easylist_cookie/easylist_cookie_international_specific_hide.txt
> A: https://viddla.fi/

- easyprivacy/easyprivacy_allowlist_international.txt
Fixes `https://twitter.com/UnisonSkySme/status/1657894973709381632` See the video below:
https://github.com/easylist/easylist/assets/58900598/d5344b21-4489-41e3-8976-e8925d88c851
> P: https://hakurei.ga/bin2img/?

- easylist/easylist_specific_hide.txt
Fixes https://github.com/easylist/easylist/issues/15931.
Existing rules already cover the intended content which should be hidden:
https://github.com/easylist/easylist/blob/b106f81373f58234d32b2f8f057cf14a3668235e/easylist/easylist_specific_hide.txt#L3548
https://github.com/easylist/easylist/blob/b106f81373f58234d32b2f8f057cf14a3668235e/easylist/easylist_specific_hide.txt#L3922
> M: builtbybit.com

- easylist/easylist_specific_hide.txt
sponsor widget at the bottom of the page
> A: https://www.freebmd.org.uk/

- easylist_cookie/easylist_cookie_specific_hide.txt
> A: https://www.nationalworldplc.com/

- easylist/easylist_thirdparty.txt
See issue https://github.com/easylist/easylist/issues/16044
> Remove CDN address from 3rd party list

- easylist/easylist_specific_hide.txt
> A: https://eprinkside.com/

- fanboy-addon/fanboy_social_international.txt
> A: https://www.rakentaja.fi/

- fanboy-addon/fanboy_newsletter_international_hide.txt
https://i.imgur.com/p4WFIEV.png
https://i.imgur.com/nst8z3Q.png
> A: https://www.francetvinfo.fr/

- fanboy-addon/fanboy_social_international.txt
- https://i.imgur.com/07TFUyF.png
> A: https://www.20minutes.fr/

- fanboy-addon/fanboy_newsletter_international_hide.txt
https://i.imgur.com/gcSV1kj.png
> A: https://www.fourchette-et-bikini.fr/

- easylist_cookie/easylist_cookie_specific_uBO.txt
> M: fruugo.*

- fanboy-addon/fanboy_newsletter_specific_hide.txt
> A: https://decode39.com/

- fanboy-addon/fanboy_newsletter_international_hide.txt
Blocked newsletter leaves huge empty space below footer
> A: https://tyyliniekka.fi/

- fanboy-addon/fanboy_newsletter_shopping_specific_hide.txt
Fixes https://github.com/easylist/easylist/issues/16002
> M: hallensteins.com (Fix typo)

- easylist/easylist_specific_hide.txt
> A: cattime.com, liveoutdoors.com

- easylist_cookie/easylist_cookie_specific_hide.txt
> A: https://www.thinkwithgoogle.com/

- easyprivacy/easyprivacy_specific.txt
Click on top right Register button on https://www.behance.net/ I was able to create an account while using this rule
> A: https://auth.services.adobe.com/fr_FR/deeplink.html

- easylist/easylist_specific_hide.txt
Filter to hide this ad space leftovers:
https://github.com/easylist/easylist/issues/16321
> M: Fix for #16321

- easylist_cookie/easylist_cookie_specific_uBO.txt
`tiede.fi` redirects you now to `hs.fi/tiede/`
> M: Remove outdated

- easylist/easylist_specific_hide_abp.txt
Fix for this issue: https://github.com/easylist/easylist/issues/14991
> A:`templateshub.net`

- easylist_cookie/easylist_cookie_general_hide.txt
https://hammastieto.fi/
It takes a while for the dialog to appear.
> A: hammastieto.fi (GDPR generic hide)

- easylist_cookie/easylist_cookie_international_specific_hide.txt
- easylist_cookie/easylist_cookie_specific_hide.txt
cookie banner
https://www.gomibo.gr/en/samsung-galaxy-a54/128gb-white
https://www.gomibo.cy/en/samsung-galaxy-s23-eu/128gb-black
https://www.gomibo.se/samsung-galaxy-a54/128gb-vit
https://www.gomibo.co.uk/samsung-galaxy-s23-eu/128gb-black
https://www.gomibo.fr/samsung-galaxy-s23-plus-eu/256gb-noir
etc.
> A: gomibo.*

- easylist_cookie/easylist_cookie_specific_uBO.txt
https://proficient.fi/
https://eco-toimistotarvikkeet.fi/
Accept mandatory cookies.
> eco-toimistotarvikkeet.fi / proficient.fi GDPR (uBO)

- fanboy-addon/fanboy_annoyance_specific_hide.txt
- fanboy-addon/fanboy_annoyance_thirdparty.txt
Annoying "Did you know" dialog:
Thank you
> A:`dictionary.com`

- easylist_cookie/easylist_cookie_specific_hide.txt
> A: https://www.songsterr.com/

- fanboy-addon/fanboy_newsletter_international_hide.txt
> M: https://www.iltalehti.fi/

- easylist_cookie/easylist_cookie_specific_uBO.txt
https://developer.ing.com/openbanking/home
Menus are broken without setting a cookie.
> A: developer.ing.com (GDPR, uBO)

- easylist/easylist_specific_hide.txt
> A: https://www.androidtrends.com/

- fanboy-addon/fanboy_annoyance_international.txt
Scroll down to see https://i.imgur.com/tTBa4QM.png
> A: https://sigma-4pc.com/742/office-2007-english-full

- easylist_cookie/easylist_cookie_specific_uBO.txt
I think it might be better after all to also allow functional cookies. They are not used for tracking / personalized ads at least on these pages and not allowing them might cause breakages.
> M: adjust GDPR rules

- fanboy-addon/fanboy_chatapps_third-party.txt
Fixes uBlockOrigin/uAssets#18609
> M: allow Zoho cdn firstparty

- easylist_cookie/easylist_cookie_specific_hide.txt
cookie banner
soldfy.com
soldfy.dk
soldfy.fi
soldfy.no
> A: soldfy.*

- easylist_cookie/easylist_cookie_international_specific_hide.txt
> A: https://www.virtasenkauppa.fi/

- easylist_cookie/easylist_cookie_specific_uBO.txt
> A: gedik.com (GDPR dialog)

- easylist/easylist_specific_hide.txt
- easyprivacy/easyprivacy_specific.txt
Addresses https://github.com/easylist/easylist/issues/15268 and https://github.com/easylist/easylist/issues/16418.
> Update EasyPrivacy Specific, EasyList Specific Hide

- easylist_cookie/easylist_cookie_specific_hide.txt
- easyprivacy/easyprivacy_specific.txt
To address https://github.com/easylist/easylist/issues/15315.
> Update EasyPrivacy Specific, EasyList Cookie Specific Hide

- easylist_cookie/easylist_cookie_international_specific_block.txt
https://www.kotitesti.fi/
Didn't see any issues, adding items to cart works and checkout as well (though didn't actually buy anything).
> A: kotitesti.fi (GDPR block)

- easylist/easylist_specific_hide.txt
Found in : https://github.com/mediumkreation/IndianList/issues/7651
> A:pricehistoryapp.com

- easylist/easylist_specific_hide.txt
> A: https://wallpapers.com/ (Fix #16365)

- easylist_cookie/easylist_cookie_specific_hide.txt
> A: https://www.spotlistr.com/ (Fix #16556)

- easylist/easylist_specific_hide.txt
- easylist_cookie/easylist_cookie_specific_hide.txt
Fix #16188 — ad placeholders & cookie banner
> A: https://www.agegeek.com/ (Fix #16188)

- easylist_cookie/easylist_cookie_specific_hide.txt
> A: https://www.equalweb.com/ (Fix #16651)

- easylist_cookie/easylist_cookie_allowlist_general_hide.txt
- easylist_cookie/easylist_cookie_specific_uBO.txt
> P: https://webtrack.dhlecs.com (Fix #14794)

- easylist_cookie/easylist_cookie_specific_hide.txt
> A: https://support.arcgames.com/ (Fix  #15581)

- easylist/easylist_specific_hide.txt
> A: https://maxblizz.com/

- fanboy-addon/fanboy_newsletter_shopping_specific_hide.txt
<details>
<summary>Hides newsletter signup form</summary>
</details>
> A: `penguin.co.uk`

- easylist_cookie/easylist_cookie_international_specific_hide.txt
> A: https://visitnaantali.com/

- easylist/easylist_specific_hide.txt
> A: https://www.filmbooster.com/

- easylist_cookie/easylist_cookie_allowlist_general_hide.txt
- easyprivacy/easyprivacy_thirdparty.txt
To address https://github.com/easylist/easylist/issues/16048.
> Update EasyList Cookie Allowlist General Hide, EasyPrivacy Third Party

- easylist_cookie/easylist_cookie_general_hide.txt
> A: https://www.identity.digital/

- easylist/easylist_specific_hide.txt
> P: cgdirector.com (Fix #16798)

- easylist_cookie/easylist_cookie_specific_hide.txt
> A: https://medizzy.com/ (Fixes #15300)

- easylist_cookie/easylist_cookie_specific_hide.txt
> A: https://spline.design/

- fanboy-addon/fanboy_newsletter_international_hide.txt
Hides newsletter popup.
This pull request fixes #15220.
> A: `mayottehebdo.com`

- easylist/easylist_specific_hide.txt
Hides ad banner and ad leftovers.
This pull request fixes #15251.
> A: `seeklogo.com`

- easylist/easylist_specific_hide.txt
This pull request fixes #15294.
> A: `tvarticles.me`

- easylist/easylist_allowlist_general_hide.txt
> P: gumtree.com.au

- easylist/easylist_general_block.txt
https://www.telsu.fi/
Adjust not to block this request, as otherwise opening tv program info doesn't work.
Just click any tv program to reproduce.
> P: telsu.fi

- easylist_cookie/easylist_cookie_specific_hide.txt
> A: https://dashboard.stripe.com/

- easylist_adult/adult_specific_hide.txt
filter to hide the banner on the page
> [NSFW] fix for https://github.com/easylist/easylist/issues/16835

- easylist_cookie/easylist_cookie_allowlist_general_hide.txt
- easyprivacy/easyprivacy_thirdparty.txt
To address https://github.com/easylist/easylist/issues/14841 and what seems to be a tracker.
> Update EasyPrivacy Third Party, EasyList Cookie Allow General Hide

- easylist_cookie/easylist_cookie_international_specific_hide.txt
cookie banner,
it takes some time before it appears
> A: https://www.imt.fi/

- easylist/easylist_specific_hide.txt
> A: https://agar.io/ (Fixes #15671)

- easylist/easylist_specific_hide.txt
Ad placeholder below article on mobile
> A: https://m.koreatimes.co.kr/

- easylist/easylist_specific_hide.txt
Ad leftovers, old filter not working anymore
> M: https://www.indiewire.com/

- easylist_cookie/easylist_cookie_specific_hide.txt
> A: https://www.perplexity.ai/

- easylist_cookie/easylist_cookie_general_hide.txt
Hope this general rule is fine :)
> A: https://go.dev/

- easylist_cookie/easylist_cookie_specific_uBO.txt
> P: https://www.autohero.com/fr/search/ (Fix #16854)

- fanboy-addon/fanboy_annoyance_specific_hide.txt
Hi could you please add the domain to the existing filter there is a radio pop up display on the page:
Thank you
> A:`reaperscans.com`

- easylist_cookie/easylist_cookie_specific_uBO.txt
Product review section won't appear, unless statistic cookies allowed.
Samples:
https://www.elgiganten.dk/product/mobil-tablet-smartwatch/mobiltelefon/iphone-14-5g-smartphone-128gb-midnight/522692
https://www.gigantti.fi/product/kodinkoneet/pyykinpesu-ja-kuivaus/pyykinpesukoneet/samsung-ww95ta047ae-pyykinpesukone-ww5000t/185561
> A: elgiganten.dk,elgiganten.se,elkjop.no,gigantti.fi (GDPR)

- easyprivacy/easyprivacy_general.txt
Different versions of `/flying-analytics/*` script
```
http://astucesdegrandmere.net/comment-conserver-peches-et-nectarines/
/wp-content/plugins/flying-analytics/js/analytics.js
```
```
https://www.bewaremag.com/yaaster-interview/
/wp-content/plugins/flying-analytics/js/gtagv4.js?
```
```
https://economipedia.com/definiciones/bono.html
/wp-content/plugins/flying-analytics/js/minimal-analytics.js
```
> `/flying-analytics/*`

- easylist/easylist_specific_hide.txt
Class name is hardcoded into the backend
> U: modrinth.com

- easylist_cookie/easylist_cookie_international_specific_block.txt
- easylist_cookie/easylist_cookie_specific_uBO.txt
cookie script, old filters not working anymore
> M: https://pirkkalainen.fi/

- easylist_cookie/easylist_cookie_specific_hide.txt
> A: https://orbitaltoday.com/

- easylist_cookie/easylist_cookie_specific_uBO.txt
> A: ilonpolku.fi (GDPR, uBO)

- easylist/easylist_allowlist.txt
- easylist/easylist_general_block.txt
> Fix for https://thetvdb.com/ #16917

- easylist/easylist_specific_block.txt
- easyprivacy/easyprivacy_specific.txt
To address https://github.com/easylist/easylist/issues/16287.
> Sonic5435325 patch 12

- easylist/easylist_specific_hide_abp.txt
removing this as with latest update this is blocking the complete site.
> M:indiatimes.com

- easylist/easylist_allowlist_general_hide.txt
- fanboy-addon/fanboy_annoyance_specific_hide.txt
Hide annoyance reported at https://github.com/easylist/easylist/issues/16834, partially fix https://github.com/easylist/easylist/issues/15520.
> Update Fanboy's Annoyance Specific Hide, EasyList Allowlist General Hide

- easylist_adult/adult_specific_hide.txt
> A:[NSFW] `xhtab2.com`

- fanboy-addon/fanboy_social_international.txt
> A: https://www.adressit.com/

- easylist/easylist_specific_hide_abp.txt
Hides ad placeholders.
This pull request fixes #15293.
> A: `radio.net`

- easylist/easylist_specific_hide.txt
- fanboy-addon/fanboy_social_specific_hide.txt
A copy of https://github.com/easylist/easylist/pull/17004, without changes from Fanboy's Social Specific Block.
> Update EasyList/Fanboy's Social Specific Hide

- easylist/easylist_specific_hide.txt
Ads at the top of the [page](https://www1.watchcartoononline.bz/episode/spongebob-squarepants-season-8-episode-28/) 
Thank you
> A:`watchcartoononline.bz`

- easylist/easylist_specific_hide.txt
Hi there is a left over banner at the bottom of the page even if the ads are removed: 
Thank you
> A:`comiko.net`

- easylist/easylist_specific_hide.txt
Hi could you please review and add this filter to hide the advertisement banner on top of the page for example [here](https://www.teachit.co.uk/history/allyear-planners) : 
Thank you
> A:`teachit.co.uk`

- easylist/easylist_specific_hide.txt
Banner at the bottom of the page
> A:`nacm.xyz`

- easylist/easylist_specific_hide.txt
- easylist_adult/adult_specific_hide.txt
popping up advertisements banner:
> A:[NSFW]`komikindo.info`

- easylist/easylist_specific_hide.txt
This pull request fixes https://github.com/easylist/easylist/issues/15908.
> A: `numuki.com`

- easylist/easylist_specific_hide.txt
Hides left-hand ad banner placeholder.
> A: `garticphone.com`

- easyprivacy/easyprivacy_thirdparty.txt
- fanboy-addon/fanboy_annoyance_specific_hide.txt
This pull request
- blocks pixel tracker, and
- hides scroll to top button.
This pull request fixes https://github.com/easylist/easylist/issues/15861.
> A: `indiamike.com`

- easylist/easylist_specific_hide.txt
- fanboy-addon/fanboy_newsletter_specific_hide.txt
To address https://github.com/easylist/easylist/issues/16419.
> Update EasyList/Fanboy's Newsletter Specific Hide

- easylist_cookie/easylist_cookie_specific_uBO.txt
> Correction of easylist_cookie_specific_uBO.txt for dafy-moto.com

- easyprivacy/easyprivacy_thirdparty.txt
```
https://www.hitprace.cz/
https://ketamineclinics.com/
```
</details>
> ketamineclinics.com

- easylist/easylist_specific_block.txt
- easylist_cookie/easylist_cookie_specific_block.txt
To address https://github.com/easylist/easylist/issues/15997.
> Update EasyList/EasyList Cookie Specific Block

- easylist/easylist_specific_hide.txt
- easylist_cookie/easylist_cookie_specific_hide.txt
- fanboy-addon/fanboy_newsletter_specific_block.txt
Fixes https://github.com/easylist/easylist/issues/16632, as well as a new cookie warning showing up.
> Update EasyList/Cookie Specific Hide, Fanboy's Newsletter Specific Block

- easylist_cookie/easylist_cookie_international_specific_hide.txt
> A: https://bussitkartalla.matkahuolto.fi/

- easylist/easylist_specific_hide.txt
- fanboy-addon/fanboy_annoyance_specific_hide.txt
Fixes https://github.com/easylist/easylist/issues/16228 as well as a "Back to top" annoyance.
> Update EasyList/Fanboy's Annoyance Specific Hide

- easylist/easylist_specific_hide.txt
`https://me.mashable.com/`
`##.zad` covers all advertising spaces including `##.topadv`
</details>
> mashable.com

- fanboy-addon/fanboy_annoyance_specific_ABP.txt
- fanboy-addon/fanboy_newsletter_specific_ABP.txt
Hides newsletter form.
This pull request fixes https://github.com/easylist/easylist/issues/15968.
> A: `headphonesty.com`

- easylist/easylist_specific_hide.txt
> A: https://quipmag.com/

- easylist/easylist_adservers_popup.txt
Redirects on the domain if press on the video play button or also on streaming platform/download buttons.
> A:`lookmovie.la`

- easylist_cookie/easylist_cookie_specific_uBO.txt
https://www.kiertokanki.com/verkkokauppa/
> A: kiertokanki.com (GDPR, uBO)

- easyprivacy/easyprivacy_trackingservers.txt
Admiral homepage: https://www.getadmiral.com/.
Validated the same way as `199d674`.
See: https://github.com/easylist/easylist/pull/9770.
> Add more Admiral hosts

- fanboy-addon/fanboy_social_international.txt
Text leftover from share buttons
Other button is for feedback or sending suggestions for articles
> A: https://seura.fi/

- easylist_cookie/easylist_cookie_specific_hide.txt
Pages requires an account. (Blurred text just in case).
The main domain uses different GDPR dialog than its subdomain.
> A: elisa.rekrytointi.com (GDPR)

- easylist_cookie/easylist_cookie_specific_hide.txt
Site to test: https://www.registry.google/
> A: https://www.registry.google/

- easylist/easylist_specific_block.txt
added: 
- uptobox.eu 
- uptobox.fr
- uptobox.link
> A: Update domain for uptobox.com

- easylist/easylist_specific_hide.txt
Sticky ads banner at the bottom and also ads embedded in the content:
thank you
> A:`easypet.com`

- easylist/easylist_specific_hide.txt
Hi please check out this domain there are a couple of unblocked ads for now on[ the page](https://www.conversanttraveller.com/saruni-samburu-luxury-lodge-kenya-review/):
Thank you
> A:`conversanttraveller.com`

- easylist/easylist_specific_hide.txt
Hi could you please add this filter for the domain lots of banners around the page on the top and also right side:
Thank you
> A:`lakeconews.com`

- easylist/easylist_specific_hide.txt
ad text leftovers in footer and sidebar
> A: https://www.gamescensor.com/

- easylist_cookie/easylist_cookie_specific_hide.txt
> A: https://trakt.tv/

- easylist/easylist_specific_hide.txt
Right side ads on this page: `https://www.treesofblue.com/queen-victoria-family-tree-1819-1901/?expand_article=1`
Thank you
> A:`treesofblue.com`

- easylist_cookie/easylist_cookie_specific_hide.txt
> A: https://www.norwegianholidays.com/eu

- easylist/easylist_specific_hide.txt
Affiliate widget at: https://czechtheworld.com/cheap-flights-tickets/
> A: https://czechtheworld.com/

- easylist_cookie/easylist_cookie_international_specific_hide.txt
update sfanytime and add blocbuster.dk (sfanytime owns it)
> M: sfanytime.com + blockbuster.dk

- easylist_cookie/easylist_cookie_specific_hide.txt
- easylist_cookie/easylist_cookie_specific_uBO.txt
https://finna.fi/?lng=en-gb
Feedback here: https://www.reddit.com/r/uBlockOrigin/comments/16ooc5g/finnafi_page_navigation_breaks_to_some_degree/
> P: finna.fi (tab function blocked, GDPR)

- easylist_cookie/easylist_cookie_specific_hide.txt
> A: https://www.breakingthenews.net/

- fanboy-addon/fanboy_notifications_specific_hide.txt
> A: 9animetv.to (download our app notification)

- easyprivacy/easyprivacy_specific.txt
Adding Snowplow analytics data collector
> A: c.vogue.com & qc.vogue.com

- easylist_cookie/easylist_cookie_general_hide.txt
> A: saarioinen.fi (GDPR, generic)

- easylist/easylist_specific_hide.txt
Hi could you please check this article page: `https://insidemydream.com/sacred-spaces-creating-a-secure-haven-for-spiritual-practices/` there are some unblocked amazon widgets:
Thank you
> A:`insidemydream.com`

- easylist/easylist_specific_block.txt
Hi could you please check this page `https://www.forabodiesonly.com/mopar/`  there are a lot of side banners on the right side of the screen:
Thank you
> A:`forabodiesonly.com`

- fanboy-addon/fanboy_newsletter_international_hide.txt
- mobile user agent
- newsletter
- https://i.imgur.com/Epq7EVg.png
> A: https://www.lesmobiles.com/telephones/samsung-galaxy-a23.html

- easylist/easylist_specific_hide.txt
> A: https://waqi.info/

- easylist_cookie/easylist_cookie_specific_hide.txt
> A: https://safety.google/ (Fix #17454)

- fanboy-addon/fanboy_notifications_specific_hide.txt
> A: muziker push notifications popup

- easylist/easylist_allowlist.txt
> P: startrek.website (Fix #17443)

- easyprivacy/easyprivacy_specific.txt
Snowplow analytics data collector
> A: c.newyorker.com & qc.newyorker.com

- easylist/easylist_specific_hide.txt
Banners at https://www.thegradcafe.com/survey/index.php?q=stanford
> A: https://www.thegradcafe.com/

- fanboy-addon/fanboy_notifications_specific_hide.txt
"New: DeepL for Windows"
"The easiest and fastest way to translate"
"Translations in any desktop app"
"Free download" "No, thanks"
> A: https://www.deepl.com/

- fanboy-addon/fanboy_notifications_specific_hide.txt
Please let me know if this is incorrect (or just fix it), I haven't contributed here before.
(Would you maybe want a `CONTRIBUTING.md` that has some of the conventions for this project? I can try and write a draft of what I see done (`A: ` vs `M: ` commits, alphabetical ordering by block fragment rather than domain, what each of the annoyance files seems to mean) if that would be helpful.)
Fixes #17482
> A: https://www.patreon.com/posts/how-to-resize-sd-90211333 (Mobile Popup, Fixes #17482)

- fanboy-addon/fanboy_notifications_specific_hide.txt
When pausing a video, recommendations appear at the top.
Sample video https://areena.yle.fi/1-3353076
> M: filter update

- fanboy-addon/fanboy_notifications_specific_uBO.txt
> A: https://www.patreon.com/posts/how-to-resize-sd-90211333 (Mobile, fixes #17536)

- easylist_cookie/easylist_cookie_specific_hide.txt
Site to test: https://insightsengineering.github.io/teal/main/index.html
I refrained from adding `##.cookie-consent` to [easylist_cookie_general_hide.txt](https://github.com/easylist/easylist/blob/master/easylist_cookie/easylist_cookie_general_hide.txt) since I assume it hasn't already been included for a good reason like breaking scrolling on too many pages or the like. If my assumption is true, `##.cookie-consent` should be added to the [*Removed filters* table in the README](https://github.com/easylist/easylist/tree/master/easylist_cookie#removed-filters), I guess.
> A: github.io

- easylist/easylist_specific_hide.txt
Right side ads on all 3 domains: 
Thank you
> A:Multiple car dealers forums

- easylist/easylist_specific_hide.txt
Hi please add the domain to the existing filter to hide the top banner on the page:
Thanks
> A:`houstonherald.com`

- easylist/easylist_specific_hide.txt
- fanboy-addon/fanboy_newsletter_specific_hide.txt
- fanboy-addon/fanboy_social_specific_hide.txt
Hides ad banners, subscribe form, and social banner.
The following can be accessed for testing the proposed filters.
`https://theanalyst.com`
`https://theanalyst.com/eu/2023/10/manchester-city-vs-brighton-prediction-preview`
> A: `theanalyst.com`

- easylist/easylist_specific_block.txt
Blocks ad banners and tracking pixels.
This pull request fixes https://github.com/easylist/easylist/issues/16161.
> M: `steamanalyst.com`

- easylist_cookie/easylist_cookie_specific_uBO.txt
https://github.com/uBlockOrigin/uAssets/commit/7aa2c7ec06255ebd6d4873f52b9e6a475104261b
> M: added to uAssets

- easylist/easylist_specific_hide.txt
Hi please add these filters to the list there are a lot of empty placeholders on this [page ](https://www.gamingbible.com/news/platform/playstation/playstation-4-games-playable-at-120fps-on-ps5-935819-20230912) 👍 
Thank you
> A:`gamingbible.com`

- fanboy-addon/fanboy_annoyance_international.txt
search survey
- https://i.imgur.com/LglFCcX.png
> A: https://www.leroymerlin.fr/search?q=iphone

- easylist_cookie/easylist_cookie_specific_uBO.txt
https://bittimittari.fi/fi/mittaus
> A: bittimittari.fi (GDPR, uBO)

- easylist_cookie/easylist_cookie_allowlist.txt
https://www.fandom.com/articles/hgt-wow-wrath-of-the-lich-king
Needs to be whitelisted, otherwise the video won't work.
> P: fandom.com (blank videos, GDPR script)

- easylist/easylist_adservers.txt
- easylist/easylist_specific_hide.txt
- fanboy-addon/fanboy_social_specific_hide.txt
Content related to the author info being hidden at https://amgreatness.com/2023/10/26/the-current-republican-party-no-longer-represents-me/
> M: https://amgreatness.com/

- easylist/easylist_specific_hide.txt
**Found in url:** 
https://food.ndtv.com/ 
https://food.ndtv.com/food-drinks/the-fine-dining-guide-10-basic-restaurant-etiquettes-you-need-to-know-4534380
**Screenshots:**
> A:food.ndtv.com

- easylist/easylist_specific_hide.txt
Main page bottom of the page: 
On article page `https://patriotnewsfeed.com/ukraines-struggle-with-corruption-damages-reputation/` on the right side: 
Thank you
> A:`patriotnewsfeed.com`

- easylist_cookie/easylist_cookie_general_block.txt
> A: chillamo.com (GDPR block, generic)

- easylist_cookie/easylist_cookie_allowlist_general_hide.txt
> M: obsolete

- easyprivacy/easyprivacy_specific.txt
Snowplow analytics data collector
> A: c.wired.com & qc.wired.com

- easylist/easylist_specific_hide.txt
Hi please add the filter to hide the bottom banner on this page `https://www.codapedia.com/article_2979_The_2024_ICD-10-CM_Updates_Include_New_Codes_for_Reporting_Metabolic_Disorders_and_Insulin_Resistance.cfm` 
Thank you
> A:`codapedia.com`

- easylist/easylist_specific_hide.txt
Hi please add this filter to the list there is a banner on the right side of this page for example `https://jayisgames.com/review/the-best-gaming-apps-that-people-can-use-this-winter.php` 
Thank you
> A:`jayisgames.com`

- fanboy-addon/fanboy_social_general_hide.txt
- fanboy-addon/fanboy_social_international.txt
https://www.kuorsauskauppa.fi/Putkilonenaeklipsi
> A: kuorsauskauppa.fi (social media generic hide)

- easylist/easylist_specific_hide.txt
- easylist/easylist_thirdparty.txt
Hi could you please add this filter to the list there are Dianomi widget ads on the page (might take a bit of time to load) 
Best regards,
> A:`marketwatch.com`

- fanboy-addon/fanboy_newsletter_specific_hide.txt
> A: `culture.org`

- easylist_cookie/easylist_cookie_specific_hide.txt
> A: `jackbox.tv`

- fanboy-addon/fanboy_annoyance_specific_uBO.txt
- fanboy-addon/fanboy_notifications_specific_hide.txt
The id changed, now it's `#headlessui-dialog-46`
To reproduce add this `local-storage-item`:
`onboardingData` 
`{"g":"16/11/2023","g__%expires":1702748578,"h":119,"h__%expires":1702748877,"a2":189613,"a2__%expires":1702748652,"b":{"RUEN":33533,"ENRU":2066},"b__%expires":1702748652,"d":33,"d__%expires":1702748604,"c":5251,"c__%expires":1702748662}`
> M: deepl.com

- easylist/easylist_specific_hide.txt
> A: https://matrixcalc.org/#%7B%7B1,1,-1%7D,%7B2,2,-2%7D,%7B4,4,-4%7D%7D%5E11

- easylist/easylist_specific_hide.txt
- easylist/easylist_specific_hide_abp.txt
Hides ad banners.
This pull request fixes https://github.com/easylist/easylist/issues/12718.
> A: `coolors.co`

- easylist_cookie/easylist_cookie_specific_hide.txt
Site to test: https://doi.datacite.org/
> A: https://datacite.org/

- easylist/easylist_adservers.txt
Ad appears on the top right of this page: `gamovideo.com/frvqlftrlu7v`
> A: `adstean.com`

- easylist/easylist_specific_hide.txt
Hides ads with random class name at the top of the site.
> M: `paste.fo`

- easylist/easylist_specific_block.txt
> A: ads.audio.thisisdax.com

- easylist_cookie/easylist_cookie_specific_uBO.txt
> M: remove Bloomberg GDPR rule

- easylist_cookie/easylist_cookie_general_block.txt
To match cases like:
/cookieconsent.min.f2bc08049209.js
Sample page: https://www.aitoapteekki.fi/
> M: adjust generic GDPR block rule

- fanboy-addon/fanboy_newsletter_specific_ABP.txt
- fanboy-addon/fanboy_social_specific_ABP.txt
- fanboy-addon/fanboy_social_specific_hide.txt
Hides newsletter form and social icons.
This pull request fixes https://github.com/easylist/easylist/issues/16423.
> A: `relationshiphero.com`

- fanboy-addon/fanboy_newsletter_allowlist_general_hide.txt
Chat button at the bottom right corner is being hid.
> P: varma.fi

- fanboy-addon/fanboy_newsletter_allowlist_general_hide.txt
Unhides newsletter article.
This pull request fixes https://github.com/easylist/easylist/issues/14975.
> P: `uol.com.br`

- fanboy-addon/fanboy_newsletter_general_hide.txt
Unhides login form.
This pull request fixes https://github.com/easylist/easylist/issues/14455.
> P: `adventuregamehotspot.com`

- easyprivacy/easyprivacy_specific.txt
- fanboy-addon/fanboy_newsletter_specific_hide.txt
- fanboy-addon/fanboy_notifications_specific_hide.txt
This pull request
- blocks tracking script loader, 
- hides freelance advertisement notification, and
- hides newsletter form.
This pull request fixes https://github.com/easylist/easylist/issues/14146.
> A: `codeur.com`

- easylist/easylist_specific_hide.txt
> A: `nft.news`

- fanboy-addon/fanboy_newsletter_specific_hide.txt
https://talotekniikka-lehti.fi/
> A: talotekniikka-lehti.fi

- easylist_cookie/easylist_cookie_international_specific_hide.txt
https://asiakaspalvelu.verkkokauppa.com/hc/fi
(The main domain has a different dialog and handled via a different filter.)
> A: asiakaspalvelu.verkkokauppa.com (GDPR)

- easylist/easylist_specific_hide.txt
> A: `pd3.gg`

- easylist/easylist_specific_hide.txt
Hide banners at https://lowcarbtips.org/keto-diet-plan-for-beginners-step-by-step-guide-7-ahad/
> A: https://lowcarbtips.org/

- easyprivacy/easyprivacy_specific.txt
Updated previously in #17969 and #17946
Admin keeps changing url ):
> [NSFW] kemono.su and coomer.su first-party analytics fix

- easylist_cookie/easylist_cookie_specific_uBO.txt
Old solution that stopped working on mobile. Added a better trusted-filter solution to uAssets.
https://github.com/uBlockOrigin/uAssets/commit/b315110326ad5a9761b097c345784a313850baa5
> M: removed

- fanboy-addon/fanboy_newsletter_specific_uBO.txt
> A: launer.com

- easylist/easylist_allowlist_general_hide.txt
Accessing a sponsored article is prevented.
https://toimitilat.kauppalehti.fi/Artikkeli/nailla-vinkeilla-loydat-passelin-toimitilan?uuid=40279f87-963c-4d27-a744-705b92ca01db&mode=Latest
> A: toimitilat.kauppalehti.fi

- easylist/easylist_specific_hide.txt
found in url: https://www.financialexpress.com/
> A:financialexpress.com

- easylist/easylist_specific_hide.txt
found in url: https://www.timesnownews.com/
> A:timesnownews.com

- easylist/easylist_specific_hide.txt
**found in url:** https://cmr24.net/
> A:cmr24.net

- easylist/easylist_specific_hide.txt
**found in url:** https://lankanewsweb.net/
> A:lankanewsweb.net

- easylist/easylist_specific_hide.txt
**found in url**: https://www.greatandhra.com/
> A:greatandhra.com

- easylist/easylist_specific_hide.txt
- easylist/easylist_specific_hide_abp.txt
found in url: http://www.telugupeople.com/NewsGallery/
> A:telugupeople.com

- easylist_cookie/easylist_cookie_allowlist.txt
Cannot click personalization option in the GDPR dialog.
> P: m2o.it,deejay.it,capital.it

- easyprivacy/easyprivacy_specific.txt
- easyprivacy/easyprivacy_thirdparty.txt
`https://en.estsecurity.com/support/report` loads `https://d-collect.jennifersoft.com/demian-b2.js`
[That script](https://gist.github.com/iam-py-test/a33fae47eaf0df2af495b4fccecae596) contacts `https://d-collector.jennifersoft.com/json` (sends CPU cores, visitor ID, page, scripts on current page, page load time) and `https://d-collector.jennifersoft.com/[application ID]/resource` (page ID, css/js/images).
I have added a block on `jennifersoft.com` as it appear to be a tracking/error reporting service.
Thanks
> A: https://en.estsecurity.com/support/report

- fanboy-addon/fanboy_newsletter_specific_hide.txt
Newsletter sign up in articles
> A: https://www.newsweek.com/

- fanboy-addon/fanboy_annoyance_international.txt
dinamalar is not a Turkish website.
> M: dinamalar.com

- fanboy-addon/fanboy_annoyance_thirdparty.txt
`https://goodwillwine.com.au/products/sauvignon-blanc-2020-bendigo-vic`
</details>
`https://hellocharlie.com.au/collections/natural-body-lotion/products/koala-eco-natural-hand-body-lotion-lemon-scented-eucalyptus-rosemary`
</details>
> A: https://goodwillwine.com.au/

- easylist/easylist_general_hide.txt
> A: https://tyopaikat.oikotie.fi/

- easylist_cookie/easylist_cookie_specific_uBO.txt
https://www.tampereenratikka.fi/
Set necessary cookies accepted, and disable marketing and statistical ones.
> A: tampereenratikka.fi

- easylist_cookie/easylist_cookie_specific_hide.txt
https://odeoncinemasgroup.smg.com/
> A: odeoncinemasgroup.smg.com

- easylist_cookie/easylist_cookie_international_specific_hide.txt
> M: https://www.yaani.com.tr/

- easylist/easylist_specific_hide.txt
Found in url: https://udaipurkiran.com/
> A:udaipurkiran.com

- easylist/easylist_specific_block.txt
Top banner ad at https://forum.miata.net/vb/showthread.php?threadid=777327
> A: https://forum.miata.net/

- easylist/easylist_specific_block.txt
- easylist/easylist_specific_hide.txt
**Found in url:** https://www.newkerala.com/
> A:newkerala.com

- easyprivacy/easyprivacy_thirdparty.txt
- fanboy-addon/fanboy_newsletter_specific_hide.txt
`https://lacolon.com/article/how-fast-does-colon-cancer-grow`
Unblocked tracking domains
`||beamanalytics.b-cdn.net^`
`||calltrack.co^`
> Update privacy/newsletter lists

- fanboy-addon/fanboy_annoyance_specific_hide.txt
- fanboy-addon/fanboy_newsletter_specific_hide.txt
> Update newsletter/annoyance filter

- fanboy-addon/fanboy_annoyance_specific_hide.txt
> Update fanboy_annoyance_specific_hide.txt (NSFW)

- easylist/easylist_specific_hide.txt
Fix https://github.com/easylist/easylist/issues/18063
> M: paste.fo

- easylist_cookie/easylist_cookie_international_specific_hide.txt
- fanboy-addon/fanboy_annoyance_international.txt
Cookie notice and scroll to top button.
> A: taosect.com

- easylist/easylist_allowlist.txt
https://www.sportbible.com/football/football-news/newcastle-united/newcastle-united-eddie-howe-christmas-party-517732-20231218
> P: sportbible.com (broken videos)

- fanboy-addon/fanboy_annoyance_general_block.txt
```
https://www.erevollution.com/en/article/2626
https://www.aksesuarix.com/
https://www.kandypens.com/
```
> A: https://www.erevollution.com/en/article/2626

- fanboy-addon/fanboy_social_specific_ABP.txt
https://viranomaisuutiset.fi/raumalla-on-murtauduttu-ainakin-viiteen-omakotitaloon/
> A: viranomaisuutiset.fi

- easylist/easylist_specific_hide.txt
- fanboy-addon/fanboy_newsletter_specific_hide.txt
> Update ad and newsletter list

- easylist_cookie/easylist_cookie_specific_uBO.txt
Necessary and functional cookies for the chat to work.
> A: kymppikatsastus.fi

- easylist_cookie/easylist_cookie_international_specific_hide.txt
This PR fixes https://github.com/easylist/easylist/issues/18143 by hiding all elements with the class `govgr-cookie-banner`.
Thank you.
> A: https://dilosi.services.gov.gr/login

- easylist/easylist_allowlist.txt
`https://loudwire.com/musicians-truth-being-parent/`
Fix video breakage
> M: https://loudwire.com/

- easylist/easylist_allowlist.txt
`https://klaq.com/ixp/366/p/musicians-play-favorite-90s-songs/`
Fix video breakage
> P: https://klaq.com/

- easylist/easylist_allowlist_general_hide.txt
`https://epawaweather.com/weather-alerts/`
Unhides the weather alerts
> P: https://epawaweather.com/weather-alerts/

- fanboy-addon/fanboy_newsletter_international_hide.txt
- https://i.imgur.com/aWRQl4g.png
> A: https://www.maison-travaux.fr/

- easylist_cookie/easylist_cookie_specific_hide.txt
> A: https://copilot.microsoft.com/

- easylist/easylist_allowlist.txt
`https://screencrush.com/doctor-doom-secret-marvel-villain/`
Fix video breakage
> P: https://screencrush.com/doctor-doom-secret-marvel-villain/

- easylist_cookie/easylist_cookie_allowlist.txt
Fix https://github.com/AdguardTeam/AdguardFilters/issues/171492
> P: https://otto.fi/missa-otto/

- fanboy-addon/fanboy_notifications_specific_uBO.txt
> eksisozluk

- easylist_cookie/easylist_cookie_international_specific_hide.txt
`https://quatrorodas.abril.com.br`
> A: abril.com.br

- fanboy-addon/fanboy_annoyance_specific_hide.txt
- https://i.imgur.com/3sgVZZQ.png
> A: https://blogs.opera.com/desktop/2024/01/opera-108-developer/

- easylist/easylist_adservers.txt
`https://ceptenmuzikindir.me/`
`https://www.mp3indirdur.biz/`
</details>
> A: https://ceptenmuzikindir.me/

- easyprivacy/easyprivacy_thirdparty_international.txt
```
https://www.noteshop.com.tr/
https://www.exporgin.com/
```
Closes #17621
> A: https://www.noteshop.com.tr/

- easylist/easylist_specific_block.txt
- easylist/easylist_specific_hide.txt
found in url: https://www.dailynews.lk/
> M:dailynews.lk

- easylist/easylist_specific_hide.txt
found in url: https://srilankamirror.com/
> A:srilankamirror.com

- easylist/easylist_specific_hide.txt
found in url: 
https://tennews.in/
https://tennews.in/pm-modi-to-inaugurate-nit-goa-campus-on-feb-6/
> A:tennews.in

- easylist/easylist_specific_hide.txt
found in url: https://surattimes.com/
> A:surattimes.com

- easylist/easylist_specific_hide.txt
found in url: https://savefree.in
> A:savefree.in

- fanboy-addon/fanboy_annoyance_international.txt
**Annoyance**
https://github.com/uBlockOrigin/uAssets/issues/22145
> A: https://sadisflix.biz/

- easylist/easylist_specific_hide.txt
Banner at https://dustinabbott.net/
> A: https://dustinabbott.net/

- easylist/easylist_specific_block.txt
- easylist/easylist_specific_hide.txt
Hide banner at https://happywayfarer.com/
> A: https://happywayfarer.com/

- easylist/easylist_specific_hide.txt
Ads on the right trail of the domain (similar on all 5 domains )
Best regards
> A:`resohangout.com`

- fanboy-addon/fanboy_newsletter_general_hide.txt
https://i.imgur.com/covWXqF.png
https://i.imgur.com/vsMGkse.png
https://i.imgur.com/QQ5hu0T.png
https://i.imgur.com/S1qDlt1.png
> A: https://www.ouest-france.fr/

- easylist/easylist_specific_hide.txt
`wordplays.com`
Ad at bottom of site
> A: wordplays.com

- easylist/easylist_specific_hide.txt
Hide banners all over https://www.snowmagazine.com/
> A: https://www.snowmagazine.com/

- easylist/easylist_specific_hide.txt
Hide sticky placeholder at at the bottom of the page - https://yr.favouriteus.uk/1890/
> A: https://yr.favouriteus.uk/

- easylist_cookie/easylist_cookie_specific_uBO.txt
https://github.com/easylist/easylist/issues/17935
> aida64 cookies

- easylist/easylist_specific_hide.txt
> M: `pixwox.com`

- fanboy-addon/fanboy_annoyance_allowlist.txt
- fanboy-addon/fanboy_annoyance_specific_hide.txt
Unhides program information.
This pull request fixes https://github.com/easylist/easylist/issues/15564.
> P: `tv-asahi.co.jp`

- easylist_cookie/easylist_cookie_international_specific_hide.txt
> M: Dead domain

- easylist_cookie/easylist_cookie_specific_hide.txt
> A: https://ccmhockey.com

- easylist/easylist_specific_block.txt
Banners ads on the top of the page and on the side:
Thanks
> A:`myeongbeauty.com`

- easyprivacy/easyprivacy_general_emailtrackers.txt
`<p><img style="display:none;" width="1px" height="1px" src="https://cloud.tradewhy.cn//openemail/12345/123456789/0BnbWwMZAdoTGMFpbNcFa20=/CDF7JGD51S.jpg"></p>`
`https://ci3.googleusercontent.com/meips/ADK...6kSQ=s0-d-e1-ft#https://cloud.tradewhy.cn//openemail/12345/123456789/0BnbWwMZAdoTGMFpbNcFa20=/CDF7JGD51S.jpg`
> A: (email tracker) tradewhy.cn

- easylist/easylist_specific_hide.txt
Hide placeholder at https://go.hypergames.top/ginrummy/#/
> A: hypergames.top

- easyprivacy/easyprivacy_general.txt
- easyprivacy/easyprivacy_specific_international.txt
> A: `sayurbox.com`

- easyprivacy/easyprivacy_thirdparty.txt
> A: `fossbytes.com`

- easylist_cookie/easylist_cookie_specific_uBO.txt
Hides cookie modal.
This pull request fixes https://github.com/easylist/easylist/issues/15223.
> A: `clipix.com`

- fanboy-addon/fanboy_annoyance_specific_hide.txt
- https://i.imgur.com/0zCIkqd.png
> A: https://www.codeur.com/projects/413452-application-web

- custom-lists/bing-with-no-copilt.txt
- custom-lists/youtube-shorts.txt
Initial addition to Custom lists for Easylist.
> Add custom lists

- easylist_adult/adult_specific_block.txt
- easylist_adult/adult_specific_hide.txt
Banners and popunders at
https://x-hd.video/video/fabulous-lay-shae-gets-smashed.html
> A: [NSFW] https://x-hd.video/

- easylist_adult/adult_specific_block.txt
Popunders at https://www.hdtube.porn/
> A: [NSFW] https://www.hdtube.porn/

- easylist/easylist_specific_hide.txt
> A: https://www.newspointapp.com/

- easylist_adult/adult_specific_hide.txt
https://xnxxporn.video/video/innocent-sex-addict-stretches-narrowed-puss-and-loses.html
<details>
<summary>[NSFW] Screenshot</summary>
<br>
</details>
> A: [NSFW] https://xnxxporn.video/

- easyprivacy/easyprivacy_specific_cname_adobe.txt
Self promo Popup being blocked at https://www.manager-magazin.de/
> R: [breakage] https://www.manager-magazin.de/

- easylist_adult/adult_specific_block.txt
Banners and popunders at https://www.sexvid.pro/curvy-starlet-is-shown-as-she-is-making-a-hot-and-sexy-porn-video.html
> A: [NSFW] https://www.sexvid.pro/

- easylist/easylist_specific_hide.txt
Ads banners in the header of the article page `https://marionmugshots.com/crime-news/` 
Thanks a lot in advance
> A:`marionmugshots.com`

- easylist/easylist_specific_hide.txt
Hide placeholder at https://7274.read.astrozop.com/?session-start-screen=tarot-pick-cards-page&int-nav=1
> A: astrozop.com

- easylist_adult/adult_specific_hide.txt
https://www.negozioxporn.com/to/pUK/himachal_girlfriend_knows_how_to_give_a_proper_blowjob.html
> A: [NSFW] https://www.negozioxporn.com/

- easylist/easylist_specific_hide.txt
> A: https://www.1tamilmv.tax/

- easylist/easylist_specific_hide.txt
> A: https://www.5movierulz.band/

- easyprivacy/easyprivacy_specific.txt
- easyprivacy/easyprivacy_trackingservers_general.txt
Blocks fingerprinting script.
This pull request fixes https://github.com/easylist/easylist/issues/15279.
> A: `cdiscount.com`

- easylist_cookie/easylist_cookie_general_hide.txt
- easylist_cookie/easylist_cookie_international_specific_hide.txt
https://www.huoltopalvelu.com/
Usage on other pages as well: https://publicwww.com/websites/GBaseGDPRConsentDialog/
> A: huoltopalvelu.com (GDPR generic hide)

- easylist/easylist_specific_hide.txt
Hi please add the domain to the existing filter there is a banner at the top of the page: 
Best regards,
> A:`addictivetips.com`

- easyprivacy/easyprivacy_trackingservers_thirdparty.txt
`https://shareasale-analytics.com/r.cfm?b=5761627&u=435077&m=307106&urllink=&afftrack=&shrsl_analytics_sscid=21k8%5Ftsk2l&shrsl_analytics_sstid=21k8%5Ftsk2l`
> A: https://www.memoryc.com/

- easylist_cookie/easylist_cookie_thirdparty.txt
```
c.sd1.fr/cn/cn.js
c.sd1.fr/cn/cn.min.js
```
> A: http://en.pickture.com/blogs/nounoubricabrac/

- easylist/easylist_specific_hide.txt
Hi, there are top banners with ads on the top of the page:
Best Regards,
> A:`arboristsite.com`

- easylist/easylist_specific_hide.txt
Hi please add the domain to the existing filter, there is a banner at the bottom of the page:
Best Regards,
> A:`dcfcfans.uk`

- easylist/easylist_specific_hide.txt
Hi please add the domain to the existing filter there is a banner in the header of the page:  
Best regards,
> A:`droidgamers.com`

- easyprivacy/easyprivacy_specific_international.txt
Blocks fingerprinting and analytics requests.
This pull request fixes https://github.com/easylist/easylist/issues/15502.
> A: `music.163.com`

- easylist/easylist_specific_hide.txt
- easylist/easylist_specific_hide_abp.txt
- fanboy-addon/fanboy_annoyance_specific_hide.txt
This pull request
- hides sponsored articles,
- hides self-promotion banner, and
- hides related articles.
This pull request fixes https://github.com/easylist/easylist/issues/15418.
> A: `nation.africa`

- easylist_adult/adult_specific_block.txt
> A: [NSFW] http://boyfriendtv.com/

- easylist_cookie/easylist_cookie_international_specific_hide.txt
This is a website based in Thailand.
> M: moved to correct section

- easyprivacy/easyprivacy_specific.txt
Snowplow analytics data collector
> A: c.arstechnica.com & qc.arstechnica.com

- fanboy-addon/fanboy_newsletter_international_hide.txt
- fanboy-addon/fanboy_social_international.txt
Hides newsletter popup and social buttons.
This pull request fixes https://github.com/easylist/easylist/issues/15526.
> A: `nabd.com`

- easyprivacy/easyprivacy_specific.txt
- fanboy-addon/fanboy_annoyance_specific_block.txt
- fanboy-addon/fanboy_annoyance_specific_hide.txt
> A: `khanacademy.org`

- easyprivacy/easyprivacy_specific_perimeterx.txt
Blocks PerimeterX script initialiser.
> A: `foodpanda.my`

- easylist/easylist_specific_hide.txt
Fixed: https://github.com/mediumkreation/IndianList/issues/9287
> A:jagranjosh.com

- easylist/easylist_specific_hide.txt
Banners at https://weather.us/radar-us/lackawanna/reflectivity/KBGM.html#play-0-12-5
> A: https://weather.us/

- easylist_cookie/easylist_cookie_specific_hide.txt
Added a rule that prevented from using those websites.
> A: easyjet.com

- easyprivacy/easyprivacy_specific.txt
Snowplow analytics data collector
> A: c.vanityfair.com & qc.vanityfair.com

- fanboy-addon/fanboy_newsletter_shopping_specific_hide.txt
- fanboy-addon/fanboy_newsletter_specific_hide.txt
`https://www.lizzomusic.com/`
`https://store.lizzomusic.com/collections/all-products`
> Update Fanboy's Newsletter, Fanboy's Newsletter Shopping specific hide

- easylist/easylist_specific_hide.txt
found in url: 
https://vedantbhoomi.com/
https://vedantbhoomi.com/english/eus-new-sanctions-aim-to-cut-russia-off-from-world-bank-imf/
> A:vedantbhoomi.com

- easylist/easylist_specific_hide.txt
Found in url: https://crickhabari.com/
> A:crickhabari.com

- easylist/easylist_specific_hide.txt
found in url: https://watnopaarpunjabinews.com/
> A:watnopaarpunjabinews.com

- easyprivacy/easyprivacy_specific.txt
Per discussion in https://github.com/easylist/easylist/issues/19033, removing `khanacademy.org/api/internal/_bb`
> M: Update khanacademy

- easylist/easylist_specific_hide.txt
Fixed: https://github.com/mediumkreation/IndianList/issues/9345
> A:thewire.com

- easyprivacy/easyprivacy_specific_international.txt
`https://www.cimri.com/market/cay/en-ucuz-lipton-100-lu-200-gr-yellow-label-suzen-bardak-poset-siyah-cay-fiyatlari,1244264`
https://github.com/easylist/easylist/assets/103899764/4109842f-4594-4e0d-ac3d-03a4ab0ffc94
> A: https://www.cimri.com/

- easylist_cookie/easylist_cookie_international_specific_hide.txt
- easyprivacy/easyprivacy_specific_international.txt
- easyprivacy/easyprivacy_thirdparty.txt
Blocks listing impression and hides cookie banner notice.
> A: `propertyguru.com.my`

- easylist/easylist_adservers_popup.txt
- easyprivacy/easyprivacy_trackingservers_thirdparty.txt
Hi there,
intended href click should open up and prompt to continue if tracking list is enabled and not automatically close. 
Thanks you in advance
> M: https://www.bandsintown.com/e/1029906793-iron-maiden-at-spark-arena

- fanboy-addon/fanboy_social_international.txt
- fanboy-addon/fanboy_social_specific_hide.txt
(login required)
https://i.ibb.co/qjHrLSz/20240505-132913.png
> A: https://cloud.disroot.org/

- easylist/easylist_general_hide.txt
- `https://www.edclub.com/sportal/program-1/4600.play`
- `https://www.typingclub.com/sportal/program-3/117.play`
> A: edclub.com & typingclub.com

- easylist/easylist_general_hide.txt
```
##.in-thumb-ad
##.in-thumb-video-ad
```
> A: https://alphacoders.com/

- easylist_cookie/easylist_cookie_allowlist.txt
fix javascript while clicking on "+" right buttons of the lists
> M: https://www.syntec.fr/convention-collective/

- easylist_cookie/easylist_cookie_specific_hide.txt
> A: https://nordpass.com/

- fanboy-addon/fanboy_social_international.txt
> A: https://dawn.fi/

- fanboy-addon/fanboy_notifications_specific_hide.txt
https://github.com/easylist/easylist/commit/a57528cd0440b9f125e1a5a526af2b2e7a2071e4
> fix typo and add subdomain

- easylist/easylist_specific_hide.txt
Placeholder at the bottom and a "Advertisement" Placeholder on the right side.
> A: https://emojipedia.org/top-hat

- .aglintrc.yaml
- .github/workflows/lint.yml
- .gitignore
- package.json
> [!IMPORTANT]
> Please check https://github.com/easylist/easylist/settings/actions before approve it.
Installing a `AGLint` or `lint-staged` package on your local development environment is not required.
It checks filters ordering issue as mentioned in `FOP.py` and [`if-closed` error](https://github.com/AdguardTeam/AGLint?tab=readme-ov-file#if-closed) on a GitHub-hosted actions runner after you push a commit to GitHub.
> M: Init AGLint and FOP.py

- easylist/easylist_specific_hide.txt
Hide ad container.
Site to test: https://www.pexels.com/photo/mixed-drinks-18580850/
> A: https://www.pexels.com

- easyprivacy/easyprivacy_trackingservers_international.txt
```
https://www.karakosehaber.com/
```
<details><summary>Script:</summary>
```
document.addEventListener('DOMContentLoaded', function() {
var intervalId;
var userId = localStorage.getItem('userId') || 'user-' + Date.now();
localStorage.setItem('userId', userId);
var refUrl = document.referrer || "Direct Entry";
var newsTitle = document.querySelector('h1.content-title') ? document.querySelector('h1.content-title').textContent.trim() : "Haber Başlığı Yok";
var newsCategoryElements = document.querySelectorAll('section.breadcrumbs ol li a');
var newsCategory = newsCategoryElements.length > 1 ? newsCategoryElements[1].textContent.trim() : "Kategori Yok"; // İkinci <li> içerisindeki <a> elementi
var newsShareTime = document.querySelector('time') ? …
```
> A: https://diyarbakiryenigun.com/

- easylist/easylist_specific_block.txt
> fix tempr.email ads

- easylist/easylist_specific_block.txt
https://github.com/uBlockOrigin/uAssets/issues/24109
> fix https://github.com/uBlockOrigin/uAssets/issues/24109

- easylist/easylist_specific_block.txt
https://github.com/uBlockOrigin/uAssets/issues/24128
> fix https://github.com/uBlockOrigin/uAssets/issues/24128

- easylist/easylist_specific_hide.txt
Found in url: 
https://collegedunia.com/university/25455-iit-delhi-indian-institute-of-technology-iitd-new-delhi
https://collegedunia.com/exams/iit-jam/counselling
https://collegedunia.com/news/e-60-gate-ccmt-cutoff-for-mnnit-allahabad
https://collegedunia.com/university/25777-chandigarh-university-cu-chandigarh/bachelor-of-science-bsc-full-time
https://collegedunia.com/indiatoday-ranked-colleges
https://collegedunia.com/bdes/user-experience-design-colleges
https://collegedunia.com/neet-score-accepting-colleges
> A:collegedunia.com

- easylist/easylist_specific_hide.txt
**found in url**: https://girgitnews.com/health-insurance-what-are-the-key-differences/
> A:girgitnews.com

- easylist_cookie/easylist_cookie_specific_uBO.txt
Hides cookie modal.
This pull request fixes https://github.com/easylist/easylist/issues/16072.
> A: `artifica.fr`

- easylist/easylist_specific_hide.txt
- easyprivacy/easyprivacy_thirdparty.txt
- easyprivacy/easyprivacy_trackingservers_thirdparty.txt
https://github.com/uBlockOrigin/uAssets/issues/24149
> fix https://github.com/uBlockOrigin/uAssets/issues/24149

- fanboy-addon/fanboy_annoyance_international.txt
They have been using these annoying pop-up windows for [5 years](https://github.com/AdguardTeam/AdguardFilters/commit/d89b50c589361d2542145516dc6d4ef13048491b).
```
https://gardrops.com/kadin/aksesuar/woody-ve-lessie-anahtarlik-cift-6658fa7bc05ea
```
<details><summary>Screenshots</summary>
</details>
> A: https://gardrops.com/

- easyprivacy/easyprivacy_specific_international.txt
A login is required
```
https://kuponlarim.hepsiburada.com/
```
</details>
Initiator
`https://images.hepsiburada.net/hbus/hbus.min.v3.8.58.js`
but blocking the initiator breaks the page.
> A: https://www.hepsiburada.com/

- easyprivacy/easyprivacy_specific.txt
https://github.com/uBlockOrigin/uAssets/issues/24250
> address https://github.com/uBlockOrigin/uAssets/issues/24250 tracking

- easylist_cookie/easylist_cookie_specific_hide.txt
Site to test: https://www.itmagazine.ch/
> A: https://www.itmagazine.ch

- easylist/easylist_specific_hide.txt
Banners at https://www.skitalk.com/home/
> A: skitalk.com

- easylist/easylist_specific_hide.txt
found in url: https://paryatanbazar.com/en
> A:paryatanbazar.com

- easylist/easylist_specific_hide.txt
found in url: https://www.rediff.com/getahead/report/food-photographer-of-the-year/20240618.htm
> A:rediff.com

- fanboy-addon/fanboy_newsletter_international_hide.txt
- fanboy-addon/fanboy_notifications_specific_hide.txt
Hides newsletter popup and newsletter form.
This pull request fixes https://github.com/easylist/easylist/issues/16094.
> A: `croq-kilos.com`

- easyprivacy/easyprivacy_specific_international.txt
Blocks analytics initiator and endpoint.
This pull request fixes https://github.com/easylist/easylist/issues/16103.
> M: `decathlon.fr`

- easylist/easylist_specific_hide.txt
found in url: 
http://www.manabadi.co.in/institute/Universities-Boards-Entrance-exams-recruitment-exams-of-AP-and-TS.htm
http://www.manabadi.co.in/Institute-menu.aspx
http://www.manabadi.co.in/cbse/ncert-solutions.aspx
> A:manabadi.co.in

- easylist/easylist_specific_hide.txt
found in url: 
https://www.thehansindia.com/
https://www.thehansindia.com/my-voice/myvoice-views-of-our-readers-4th-july-2024-889173?infinitescroll=1
> A:thehansindia.com

- easylist/easylist_specific_hide.txt
found in url: 
https://www.boldsky.com/insync/44-000-year-old-siberian-wolf-discovery-raises-concerns-about-ancient-viruses-future-medicines-156355.html
> A:boldsky.com

- easylist/easylist_general_hide.txt
found in url: https://www.firstpost.com/opinion/world-tibet-day-special-tibetan-struggle-has-its-ups-and-downs-but-far-from-dying-amb-dilip-sinha-13790109.html
> A:firstpost.com

- easylist/easylist_specific_hide.txt
found in url: https://www.filmibeat.com/bollywood/ott/2024/what-could-happen-in-mirzapur-season-4-power-struggle-to-unfold-between-guddu-bhaiya-chhote-tyagi-405323.html
https://www.filmibeat.com/movies.html
> M:filmibeat.com

- easylist/easylist_specific_hide.txt
found in url: 
https://www.ndtv.com/
https://www.ndtv.com/photos/entertainment/couple-spotting-kiara-advani-and-sidharth-malhotra-are-holiday-ready-107939#photo-472429
> A:ndtv.com

- easyprivacy/easyprivacy_specific.txt
Blocks Plausible analytics endpoint.
> A: `doubledouble.top`

- easylist/easylist_specific_hide.txt
- easyprivacy/easyprivacy_thirdparty.txt
Blocks performance/impression logging and hides ad banner placeholder.
> A: `fotmob.com`

- easylist/easylist_specific_hide.txt
found in url: 
https://timesofindia.indiatimes.com/city/agra/victims-kin-blame-police-administration-for-hathras-stampede-remain-faithful-to-bhole-baba/articleshow/111546793.cms
https://telecom.economictimes.indiatimes.com/news/telecom-equipment/nokia-aims-to-kickstart-jio-airtels-5g-monetisation-investing-in-6g-in-india-harri-holma/111228740
> A:timesofindia.indiatimes.com

- easylist/easylist_specific_hide.txt
Fixed: https://github.com/mediumkreation/IndianList/issues/9773
> A:topperlearning.com

- easylist/easylist_adservers_popup.txt
- easylist/easylist_general_hide.txt
popup ads when trying to play a video (e.g. https://tv3.lk21official.mom/boy-in-the-walls-2023/)
> A: https://tv3.lk21official.mom/

- easylist_cookie/easylist_cookie_specific_hide.txt
This pull request fixes https://github.com/easylist/easylist/issues/17516.
> A: `kaleido.ai`

- easylist/easylist_specific_hide.txt
> A: `piokok.com`

- easylist_cookie/easylist_cookie_international_specific_hide.txt
Hides consent banner.
This pull request fixes https://github.com/easylist/easylist/issues/17562.
> A: `neurocenter.gr`

- easylist_cookie/easylist_cookie_thirdparty.txt
```
https://www.mondihome.com.tr/
https://www.bellona.com.tr/
https://www.istikbal.com.tr/
https://www.doquhome.com.tr
```
</details>
> A: https://www.mondihome.com.tr/

- fanboy-addon/fanboy_annoyance_thirdparty.txt
This is not an annoyance, it's blocks desired functionality for people who use last.fm
Fixes https://github.com/easylist/easylist/issues/19533
> Remove audioscrobbler from fanboy annoyances

- easyprivacy/easyprivacy_allowlist.txt
Restore page load.
This pull request fixes https://github.com/easylist/easylist/issues/17617.
> P: `globalatlanticannuity.com`

- easylist/easylist_general_hide.txt
- easylist_cookie/easylist_cookie_general_hide.txt
- easylist_cookie/easylist_cookie_specific_ABP.txt
- fanboy-addon/fanboy_newsletter_international_block.txt
While creating a Debian package that contains EasyList, the automated build tools noticed the following spelling errors.
> Correct minor spelling errors.

- easyprivacy/easyprivacy_trackingservers_admiral.txt
```
configchain.com
```
```
mindfulgem.com
```
refs ghostery/broken-page-reports#669
refs ghostery/broken-page-reports#743
> Update admiral tracking servers

- easylist/easylist_specific_hide.txt
> A: clubsearay.com

- easyprivacy/easyprivacy_allowlist.txt
https://www.usplastic.com/search/?q=bottle&filter=category~eq~620
search results section displays blank instead of showing product images
> A: usplastic.com

- easyprivacy/easyprivacy_specific_international.txt
https://github.com/easylist/easylist/pull/19550
> A: https://iptvgratuit.net/

- easyprivacy/easyprivacy_specific.txt
Blocks Plausible analytics endpoint.
A test link can be accessed via `https://embedme.top/embed/sky-sports-saturday-social/1`
> A: `embedme.top`

- easylist/easylist_specific_block.txt
- easylist/easylist_specific_hide.txt
found in url: https://wishesh.com/
> A:wishesh.com

- easylist/easylist_specific_hide.txt
https://english.newsfirst.lk/
https://tamil.newsfirst.lk/
https://sinhala.newsfirst.lk/
> A:newsfirst.lk

- easylist/easylist_specific_hide.txt
Hides mobile ad banner placeholder.
> A: `setlist.fm` (mobile UA)

- fanboy-addon/fanboy_chatapps_third-party.txt
Blocks third-party chatbot.
This pull request fixes https://github.com/easylist/easylist/issues/17684.
> A: `ito.org.tr`

- easylist/easylist_specific_hide.txt
found in url: https://www.harpersbazaar.in/
> A:harpersbazaar.in

- easyprivacy/easyprivacy_trackingservers_thirdparty.txt
> A: `outlier.ai`

- easyprivacy/easyprivacy_specific.txt
> A: `farfetch.com`

- easyprivacy/easyprivacy_specific.txt
> A: `worldremit.com`

- easylist/easylist_adservers.txt
- easylist/easylist_thirdparty.txt
https://owebsearch.com/
Blank page, move to third-party filters.
> M: [Breakage] https://owebsearch.com/

- easyprivacy/easyprivacy_thirdparty_international.txt
```
https://digitalage.com.tr
https://mediacatmagazine.co.uk/
```
> A: https://mediacat.com/

- easyprivacy/easyprivacy_trackingservers_thirdparty.txt
> A: `scmagazine.com`

- easylist/easylist_specific_hide.txt
> A: `bulinews.com`

- easylist/easylist_thirdparty.txt
Top banner at https://www.wsj.com/tech/ai/openai-search-engine-searchgpt-97771f86?mod=tech_lead_pos5
> A: https://www.wsj.com/

- easylist/easylist_specific_hide.txt
Sponsored items at: https://search.yahoo.com/search;_ylt=AwrEtTZV56lmYAQAClJXNyoA;_ylc=X1MDMjc2NjY3OQRfcgMyBGZyA3NmcARmcjIDc2ItdG9wBGdwcmlkA3hQUXlQc19LUTNlV3NreVBfenhDZ0EEbl9yc2x0AzAEbl9zdWdnAzEwBG9yaWdpbgNzZWFyY2gueWFob28uY29tBHBvcwMwBHBxc3RyAwRwcXN0cmwDMARxc3RybAM2BHF1ZXJ5A2xhcHRvcAR0X3N0bXADMTcyMjQxMDg3Mw--?p=laptop&fr=sfp&fr2=sb-top&iscqry=
Try different VPN locations.
> A: https://search.yahoo.com/

- fanboy-addon/fanboy_annoyance_allowlist_general_hide.txt
Restore page settings.
This pull request fixes https://github.com/easylist/easylist/issues/17732.
> P: `journals.sagepub.com`

- easylist/easylist_specific_hide.txt
> address diep.io placeholder

- easylist_cookie/easylist_cookie_specific_hide.txt
This pull request fixes https://github.com/easylist/easylist/issues/17767.
> A: `cardmates.org`

- easylist/easylist_adservers.txt
Ad request saw on `freemcserver.net` `https://prebid-stag.setupad.net/`
> add adserver

- easylist/easylist_general_hide.txt
```
https://www.textfixer.com/tools/alphabetical-order.php
```
</details>
```
https://www.alleydog.com/glossary/definition.php?term=Cognition
```
</details>
> A: https://www.textfixer.com/tools/alphabetical-order.php

- easyprivacy/easyprivacy_thirdparty.txt
> A: `numero.ai`

- easyprivacy/easyprivacy_specific.txt
> A: `th.gl`

- easyprivacy/easyprivacy_thirdparty.txt
Third-party analytics on the page `https://www.diffeyewear.com/collections/all-glasses`
> A: `diffeyewear.com`

- easyprivacy/easyprivacy_thirdparty.txt
> A: `brooklynclothing.com`

- easyprivacy/easyprivacy_thirdparty_international.txt
> A: https://www.maymoda.com/cepli-kurklu-suet-kaban-siyah-19105/

- easyprivacy/easyprivacy_specific.txt
> A: `stablediffusionweb.com`

- easylist/easylist_thirdparty.txt
Remove false positive for bubble.io's image loading CDN
Fixes: #19871
> R: bubble.io false positive

- easyprivacy/easyprivacy_specific.txt
> A: `tremendous.com`

- easyprivacy/easyprivacy_specific.txt
> A: `pcoptimum.ca`

- easyprivacy/easyprivacy_thirdparty.txt
> A: `scale.com`

- easyprivacy/easyprivacy_specific.txt
> A: `zumper.com`

- easyprivacy/easyprivacy_specific.txt
This website may not available from external. Please, request HAR via email: seia@outlook.kr — if you require it.
```
https://connect.airfrance.com/#/wifi/options
```
```
curl 'https://connect.airfrance.com/ach/api/event?client=ach-client&label=SUCCESS_SDK_INITIALIZED&fcid=<redacted>&cb=1' \
-H 'sec-ch-ua: "Not/A)Brand";v="8", "Chromium";v="<redacted>"' \
-H 'Accept-Language: <redacted>' \
-H 'sec-ch-ua-mobile: ?0' \
-H 'User-Agent: <redacted>' \
-H 'Content-Type: application/json' \
-H 'Accept: application/json' \
-H 'Referer: https://connect.airfrance.com/' \
-H 'sec-ch-ua-platform: "<redacted>"' \
--data-raw '{"name":"SUCCESS_SDK_INITIALIZED","details":{"achStatus":{"components":{"ach":[{"id":"aircon-server","version":"7.5.3","healthy":true,"details":{"buildName":"IST-1","company":"af"} …
```
> Add airfrance in-flight wifi

- easyprivacy/easyprivacy_specific.txt
> A: `clutter.com`

- easyprivacy/easyprivacy_specific.txt
Analytics
Visit `https://ai.invideo.io/signup` to see post requests to `a-da.invideo.io`
> A: `invideo.io`

- easylist/easylist_specific_hide.txt
https://github.com/uBlockOrigin/uAssets/discussions/17361#discussioncomment-10508832
> Address https://github.com/uBlockOrigin/uAssets/discussions/17361#discussioncomment-10508832

- easylist_cookie/easylist_cookie_thirdparty.txt
```
https://www.finansopia.com/
```
</details>
```
https://havabus.com/
```
</details>
> A: https://www.finansopia.com/

- easylist/easylist_specific_hide.txt
hiding banner ad on krdo.com homepage
> A: krdo.com

- easylist/easylist_specific_hide.txt
Hides ad banners.
This pull request fixes https://github.com/easylist/easylist/issues/17907.
> A: `phpbb.com`

- easyprivacy/easyprivacy_specific.txt
- fanboy-addon/fanboy_notifications_specific_hide.txt
Blocks page-view logging and hides promotion notification.
This pull request fixes https://github.com/easylist/easylist/issues/17855.
> A: `clickindia.com` (IN IP)

- easylist_cookie/easylist_cookie_general_hide.txt
Fixes https://github.com/easylist/easylist/issues/19898
> Remove ant-notification false positive

- easylist_cookie/easylist_cookie_international_specific_hide.txt
Hello 👋
I fixed some cookie notices that I found during the last days or in some issues.
If I should contribute this in another way, please just comment and tell me what I should do.
> Hide some cookie banners

- easyprivacy/easyprivacy_specific.txt
> A: `pi.ai`

- easylist_cookie/easylist_cookie_allowlist_general_hide.txt
fixes https://github.com/ghostery/broken-page-reports/issues/843
> fix appleid.apple.com

- easylist_cookie/easylist_cookie_international_specific_hide.txt
https://tapahtumat.tampere.fi/
https://www.eventz.today/
The latter is Finnish based site as well.
> A: tapahtumat.tampere.fi / eventz.today (GDPR hide)

- easylist_cookie/easylist_cookie_allowlist_general_hide.txt
Site is not interactive/usable unless the cookie modal has beed filled.
Site to test: https://www.oeko.de/news/pressemeldungen/alternative-reaktorkonzepte-loesen-das-endlagerproblem-nicht/
> M: https://www.oeko.de

- easyprivacy/easyprivacy_specific.txt
> A: `canva.com`

- easylist_cookie/easylist_cookie_specific_hide.txt
> P: elfadistrelec.fi (GDPR dimming leftover)

- easylist_cookie/easylist_cookie_international_specific_block.txt
- easylist_cookie/easylist_cookie_specific_uBO.txt
> P: finnair.com (blocked scrolling, GDPR)

- easylist_cookie/easylist_cookie_thirdparty.txt
</details>
```
https://www.lassa.com.tr/
https://www.anadolubank.com.tr/
https://www.kinesislastik.com.tr/
https://8bitiz.com/
https://anadoluyatirim.com.tr/
```
> A: https://webborsam.com/

- easylist/easylist_allowlist.txt
> Fix wsj.com

- easylist_cookie/easylist_cookie_allowlist_general_hide.txt
```
https://toptantr.com/tr/register
```
Membership agreement button. You cannot become a member of the site without accepting the agreement.
before:
</details>
after:
</details>
> P: https://toptantr.com/tr/register

- easyprivacy/easyprivacy_trackingservers_thirdparty.txt
> A: `atatus.com`

- easyprivacy/easyprivacy_trackingservers_thirdparty.txt
Third-party tracking and analytics
> A: `perplexity.ai`

- easylist_cookie/easylist_cookie_allowlist.txt
https://www.finnishdesignshop.fi/fi-fi/tuote/biennale-jakkara
> P: finnishdesignshop.fi (content won't load)

- easylist/easylist_specific_hide.txt
multiple unblocked banner ads on `https://www.bayequest.com/`
> A: bayequest.com

- easylist_cookie/easylist_cookie_specific_hide.txt
> A: https://discoland.fi/

- README.md
Just fixing a variety of spelling and grammar errors I noticed in the README.
> README.md grammar and spelling corrections

- easyprivacy/easyprivacy_specific.txt
> A: asuracomic.net

- easyprivacy/easyprivacy_specific.txt
Event tracking and tracking pixel
> A: `wealthfront.com`

- easylist/easylist_specific_hide.txt
Side banner at https://earth911.com/
> A: https://earth911.com/

- easyprivacy/easyprivacy_thirdparty.txt
click `See it in my room`
`https://quickstyle.com/product/exotica-bali/`
</details>
---
click `view in your room`
`https://shawpropertysolutions.com/pdp/resilient/purview-20/serengeti/5036v-00700`
</details>
---
click `view in a room`
`https://www.marazziusa.com/products/Cotto-Look/Cotto-Revival/Baltic`
</details>
> A: https://quickstyle.com/product/exotica-bali/

- easyprivacy/easyprivacy_thirdparty_international.txt
```
https://sozbursa.web.tv/embed/f2zz7ziegxc?autoplay=0&mute=0
https://webursa.web.tv/video/navigasyon-olum-getirdi-ucurumdan-yuvarlanip-yanarak-can-verdiler__tpyhqxppq7y
https://bursahakimiyet.web.tv/embed/xv9dhky7zlw
```
</details>
> A: https://sozbursa.web.tv/embed/f2zz7ziegxc?autoplay=0&mute=0

- easylist/easylist_specific_hide.txt
Fixed: https://github.com/mediumkreation/IndianList/issues/10051
> A:nagpurtoday.in

- easylist/easylist_specific_hide.txt
found in url: 
https://colombotimes.lk/
https://colombotimes.lk/Biden-Praises-Harris-Democratic-Rally-Trump-Launches-2024-09-16-.html
> A:colombotimes.lk

- fanboy-addon/fanboy_newsletter_international_hide.txt
> A: tempodent.fi (newsletter)

- easyprivacy/easyprivacy_thirdparty.txt
> A: `incogni.com`

- easyprivacy/easyprivacy_specific.txt
- easyprivacy/easyprivacy_trackingservers_thirdparty.txt
Event logging and third-party tracking server
> A: `joggo.run`

- easylist_adult/adult_specific_hide.txt
Ad placeholder on a video link
> A: (NSFW) `thotcity.su`

- easyprivacy/easyprivacy_thirdparty.txt
This product analytics service: https://www.june.so/
> Added api.june.so to easyprivacy_thirdparty.txt

- fanboy-addon/fanboy_newsletter_thirdparty.txt
A rule for popups like newsletters, coupon, donations, etc.
`https://yuzefi.com/`
</details>
---
`https://www.theanswerbank.co.uk/`
</details>
---
`http://weapons-universe.com/`
</details>
---
`https://onual.com/forum/`
</details>
---
`https://perifericas.es/`
</details>
---
`http://www.girlzgoneriding.com/`
</details>
---
`https://www.freegeek.org/`
</details>
---
`https://www.arkansasgop.org/`
</details>
---
The websites below use powr.io's web form tool, so blocking powr.io …
> A: https://yuzefi.com/

- fanboy-addon/fanboy_social_specific_hide.txt
corrected filter syntax to use "-abp-contains()"
> M: correct typo

- easyprivacy/easyprivacy_trackingservers_international.txt
session recorder. takes a visual record of user behavior
</details>
> A: https://www.modanisa.com/ayakkabi-canta-1111-firsatlari-mena.list

- easyprivacy/easyprivacy_trackingservers_international.txt
```
https://www.galships.com/
https://www.plaatvis.nl/
```
</details>
> A: https://www.jeremiassiehr.com/

- easyprivacy/easyprivacy_thirdparty_international.txt
conversion tracking
</details>
---
```
https://senelyapimarket.com/
https://sockstunnel.com/
https://migma.com.tr/
https://tiffle.com.tr/
```
References for `eticaret.pro/pixel`
https://eticaret.pro/referanslarimiz/
> A: https://madam10.com/ariel-dag-esintisi-camasir-deterjani-1-5-kg

- easyprivacy/easyprivacy_trackingservers_thirdparty.txt
> A: https://rainbowly.com/

- fanboy-addon/fanboy_notifications_specific_block.txt
https://www.iltalehti.fi/
Doesn't appear everytime.
> A: iltalehti.fi (survey notification)

- easyprivacy/easyprivacy_general.txt
```
arabxporn . net/wp-content/plugins/wp-rocket/assets/js/wpr-beacon.js
arabxporn . net/wp-content/plugins/wp-rocket/assets/js/wpr-beacon.min.js
```
> A: (NSFW) net.arabxporn

- fanboy-addon/fanboy_newsletter_specific_block.txt
- fanboy-addon/fanboy_newsletter_specific_hide.txt
- fanboy-addon/fanboy_social_specific_hide.txt
Blocks newsletter popup and hides social icon.
This pull request fixes https://github.com/easylist/easylist/issues/18182.
> A: `electricfencing.co.uk`

- easyprivacy/easyprivacy_general.txt
https://github.com/easylist/listear/issues/37
> A: (NSFW) com.alarbda

- easyprivacy/easyprivacy_specific.txt
Blocks Plausible analytics endpoint.
> A: `lucida.to`

- easylist_cookie/easylist_cookie_specific_uBO.txt
https://github.com/uBlockOrigin/uAssets/commit/105c2f60b517725a979fce76465243cad8a7a439
> M: removed, handled in uAssets

- easyprivacy/easyprivacy_specific.txt
> A: `zed.dev`

- easylist_cookie/easylist_cookie_international_specific_hide.txt
https://www.komediateatteri.fi/
> A: komediateatteri.fi (GDPR)

- easylist_adult/adult_specific_block.txt
> A: (NSFW) `xfree.com`

- easylist/easylist_specific_hide.txt
**Found in url:** https://www.cricketnmore.com/ ,
> A:cricketnmore.com

- easylist/easylist_specific_hide.txt
found in url: https://ihrc24x7.com/
> A:ihrc24x7.com

- easylist/easylist_specific_block.txt
**found in url:** http://teluguwebsite.com/ ,
http://teluguwebsite.com/Telugu_Saamethalu.html
> A:teluguwebsite.com

- easylist/easylist_specific_hide.txt
found in url: https://www.newsindiatimes.com/
> A:newsindiatimes.com

- easylist/easylist_specific_block.txt
- easylist/easylist_specific_hide.txt
found in url: https://impressivetimes.com/
> A:impressivetimes.com

- easyprivacy/easyprivacy_general_emailtrackers.txt
> A: (email tracker) lassuranceretraite.fr

- easylist/easylist_specific_hide.txt
Example: https://dict.leo.org/german-english/relentlessly
> M: dict.leo.org sitebar ads

- easylist_cookie/easylist_cookie_allowlist_general_hide.txt
- easylist_cookie/easylist_cookie_specific_uBO.txt
https://www.multitronic.fi/
Try to search something, such as "Windows". You won't see any results without accepting functional cookies (toiminalliset in Finnish)
Dealth with trusted filters in uAssets.
> P: multitronic.fi (broken search)

- easylist/easylist_specific_block_popup.txt
**dzapk.com**
```
// Function to show the popup
function showPopup(){const url = 'https://s.click.aliexpress.com/e/_xxxxxx'; // Replace with your desired URL
window.open(url, '_blank'); // Open the link in a new tab
```
**up-4ever.com**
```
<a id="downLoadLinkButton" class="btn my-2 btn-sm btn-secondary" 
onclick="window.open('https://s.click.aliexpress.com/e/_abcdef?af=azerty');" href="[javascript:void(0)](about:blank)"
data-target="https://s8.up4ever.download:8443/d/xxxyyyzzz...">
<span class="firstOne"><i class="ph ph-spinner-gap"></i> Preparing Download Link, Please wait...</span>
<span class="notFirstOne" style="display: none;"><i class="ph ph-download"></i> Click here to download</span>
</a>
```
> A: https://dzapk.com/

- easylist/easylist_specific_hide.txt
> A: openguessr.com

- easyprivacy/easyprivacy_allowlist_international.txt
Overblocking self-promo (soft slide up)
> A: faz.net

- easylist/easylist_specific_block.txt
Do a reverse image search to see Shutterstock ads https://i.imgur.com/LBs81Pp.png
> A: https://tineye.com/

- easylist/easylist_allowlist_general_hide.txt
Whole page blocked - https://www.bibliaon.com/jeremias_9/
> P: [Breakage] https://www.bibliaon.com/

- easylist/easylist_specific_hide.txt
[Example](https://www.nationalrail.co.uk/tickets-railcards-offers/promotions/freedom-of-north-east-7-days/)
Before:
After:
[Example](https://www.nationalrail.co.uk/tickets-railcards-and-offers/ticket-types/pay-as-you-go/)
Before:
After:
> A: nationalrail.co.uk

- easylist/easylist_specific_hide.txt
Site to test: https://politicalcompass.org/germany2025
> A: https://politicalcompass.org/

- fanboy-addon/fanboy_social_general_block.txt
the following generic blocking filters already exist in this file, making the pruned ones redundant
`/addtoany.min.js`
`/sme-facebook-likebox-sidebar/*`
> removed redundant filters

- fanboy-addon/fanboy_notifications_specific_hide.txt
`bing.com##.b_bnp_bopc` already exists
> remove duplicate filter

- easylist/easylist_specific_block.txt
found in url: https://www.uitvconnect.com/
> A:uitvconnect.com

- easyprivacy/easyprivacy_specific.txt
https://freenote.biz/raw/mw41s1iast
> A: https://app.box.com/folder/0

- easylist_adult/adult_specific_hide.txt
https://fetish-games.com/him-kabuki/
> A: (nsfw) https://fetish-games.com/him-kabuki/

- easylist_adult/adult_specific_hide.txt
> M: (nsfw) https://androidadult.com/

- easylist_adult/adult_specific_hide.txt
> M: (nsfw) https://porngames.games/

- easylist_adult/adult_specific_hide.txt
https://new.lewd.ninja/game/129163-couples-v030-neverlucky
> A: (nsfw) https://new.lewd.ninja/

- easylist/easylist_specific_hide.txt
embedded legitimate video content is hidden on https://www.washingtonexaminer.com/opinion/editorials/3317408/trump-right-on-birthright-citizenship/
> P: washingtonexaminer.com

- easylist_adult/adult_specific_hide.txt
> A: (nsfw) https://www.visitmama.com/

- easylist/easylist_specific_hide.txt
> M: https://time.is/

- easylist_adult/adult_specific_hide.txt
> M: (nsfw) https://h-flash.com/

- easylist/easylist_allowlist.txt
- easylist/easylist_allowlist_general_hide.txt
- easylist/easylist_specific_block.txt
on `https://laurelberninteriors.com/the-new-george-smith-jules-sofa-is-finally-in-my-living-room/#part-2-begins-here` the video content under the title "and now, the video" does not appear
> A: laurelberninteriors.com

- easylist/easylist_specific_hide.txt
- https://www.wsj.com/
- https://www.wsj.com/politics/policy/trump-plans-another-10-tariff-on-products-from-china-f7c0d4d9
> M: https://www.wsj.com/

- easylist/easylist_specific_hide.txt
> A: https://decrypt.day/

- easylist_cookie/easylist_cookie_specific_hide.txt
this rule doesn't seem to solve for ios.
any help with that is appreciated.
> fix tedbaker.com

- easyprivacy/easyprivacy_thirdparty.txt
```
www.kaspersky.com
www.kaspersky.co.kr
www.kaspersky.it
www.kaspersky.com.tr
www.kaspersky.co.jp
www.kaspersky.nl
www.kaspersky.com.tw
www.kaspersky.fr
www.kaspersky.com.br
www.kaspersky.co.uk
www.kaspersky.com.vn
www.kaspersky.es
www.kaspersky.com.cn
```
> A: https://www.kaspersky.com/

- easylist/easylist_specific_block.txt
banner ads at `https://filepv.com/cye2lh867d24/sample-5s.mp4.html`
> A: https://filepv.com/cye2lh867d24/sample-5s.mp4.html banner ads

- easylist_adult/adult_specific_hide.txt
> A: (nsfw) https://porngameshub.com/

- fanboy-addon/fanboy_annoyance_thirdparty.txt
https://github.com/easylist/easylist/commit/25a8e89d1a497213c342f1cb38216a7e0ab0c4b3
> A: (#21383) affilizz.com

- fanboy-addon/fanboy_annoyance_thirdparty.txt
```
<script src="https://timez.ai/widgets/widget.js"></script>
```
> A: https://wwvv.blablastream.com/

- fanboy-addon/fanboy_annoyance_specific_hide.txt
https://k2s.cc/file/b593f1d90d5c0
> A: https://k2s.cc/file/b593f1d90d5c0

- FOP.py
added
```
"csp=frame-src"
"csp=img-src"
"csp=media-src"
"csp=script-src"
"csp=worker-src"
```
\+ sort
> M: Update (KNOWNOPTIONS) FOP.py

- easylist/easylist_specific_hide.txt
Sponsored content
https://i.ibb.co/60HhYDWk/234124.png
> A: https://www.g2.com/products/gedit/reviews

- easyprivacy/easyprivacy_trackingservers_international.txt
```
https://bilmeyenkalmasin.com/
https://www.tutku.net/
https://futbolsayfasi.net/
```
</details>
> A: https://www.haberindogrusu.com/

- easylist/easylist_thirdparty.txt
domain name registrar ads injected in parked domains
e.g.
```
choobmesvak.com
dapodikcenter.com
legbk.com
```
> A: http://yagumania.com/ (parked domain ads)

- easyprivacy/easyprivacy_thirdparty_international.txt
Umami script
</details>
```
https://www.damsmood.com/
https://www.sasa.com.tr/urunler-filament-poy
https://www.giovanegentile.com/
```
> A: https://www.yenikoza.com.tr/

- easylist_cookie/easylist_cookie_thirdparty.txt
> A: https://www.inveon.com/

- easylist/easylist_thirdparty.txt
- https://i.ibb.co/S7P4VMC4/181101.png
- https://i.ibb.co/8nVR2B8M/181125.png
> A: https://fossforce.com/2025/04/cve-foundation-emerges-from-stealth-to-rescue-cve-program/

- fanboy-addon/fanboy_annoyance_specific_hide.txt
https://i.ibb.co/fVHNgYDd/180503.png
> A: https://fossforce.com/

- easylist/easylist_specific_hide.txt
- https://i.ibb.co/jvcVs9rZ/image.png
#21678
> A: https://www.immoweb.be/en/search/house/for-sale/

- easylist/easylist_specific_block.txt
- easylist/easylist_specific_hide.txt
Site to test: https://coinmarketcap.com/currencies/bitcoin/
> A: https://coinmarketcap.com

- easylist_adult/adult_specific_hide.txt
> A: (nsfw) https://f95zone.to/

- easyprivacy/easyprivacy_allowlist.txt
broken product images e.g. `https://www.barenecessities.com/collections/sale?filter_department=Sleepwear&sort=MostPopularFirst`
> A: barenecessities.com

- easylist/easylist_specific_hide.txt
Side ad banners at https://hometheaterreview.com/
> A: https://hometheaterreview.com/

- easylist_adult/adult_specific_block.txt
Domains: 
https://www.xvideos.com/
https://www.txnhh.com/
https://www.xvv1deos.com/
> A: In-video ads [NSFW]

- easylist/easylist_specific_hide.txt
- `href="https://metricool.com/linkedin-trends-study/"`
- `class="tracklink"`
> hide `metricool` promo banner

- fanboy-addon/fanboy_notifications_specific_hide.txt
`wowhead.com##.notifications-dialog` already exists in this file (line 52)
> Pruned duplicate filter

- easylist/easylist_specific_hide.txt
same filter already exists in this file (line 5464)
> removed duplicate filter

- easylist/easylist_specific_hide.txt
Flickering page while scrolling down. 
https://fulltime.thefa.com/index.html?league=418624324
> A: [Breakage] thefa.com

- easyprivacy/easyprivacy_trackingservers_general.txt
A domain from Device Fingerprinting service https://www.incognia.com/device-fingerprint
> A: icg-in.com

- easyprivacy/easyprivacy_thirdparty_international.txt
https://www.farmahanem.com
https://latanwood.com.tr/
https://utkushome.com/
</details>
> A: https://www.leecooper.com.tr/

- fanboy-addon/fanboy_newsletter_specific_hide.txt
Hide newsletter subscription popup.
Site to test: https://www.crisisgroup.org/middle-east-north-africa/gulf-and-arabian-peninsula/iran/195-thin-ice-iran-nuclear-deal-three
> A: https://www.crisisgroup.org

- easylist/easylist_specific_hide.txt
Hide inline ad
Site to test: https://www.itpro.com/security/cyber-attacks/all-us-forces-must-now-assume-their-networks-are-compromised-after-salt-typhoon-breach
> A: https://www.itpro.com

- easylist_cookie/easylist_cookie_general_block.txt
`https://www.markonshop.com/`
</details>
---
`https://www.celebiogullari.com.tr/`
</details>
> A: https://www.markonshop.com/

- easyprivacy/easyprivacy_thirdparty_international.txt
Add tracking server for HKTVMall
> A: ts-analysis.shoalter.com

- fanboy-addon/fanboy_newsletter_specific_hide.txt
Site to test: https://bitwarden.com/help/managing-items/
> A: https://bitwarden.com

- easylist/easylist_adservers.txt
- easyprivacy/easyprivacy_thirdparty.txt
Hello, as highlighted in [that topic](https://forums.lanik.us/viewtopic.php?t=48804-collectiveaudience-co), I tried to suggest some edition to let our servers still fulfill its role for editorial contents. Let me know if I mis-understood the repo. 
Best
> Proposition of change from collectiveaudience.co

- easylist_cookie/easylist_cookie_specific_hide.txt
- `https://libre-media.com/`
- https://github.com/easylist/easylist/pull/22273
> A: https://libre-media.com/

- easylist_cookie/easylist_cookie_international_specific_hide.txt
> M: https://github.com/easylist/easylist/pull/22272

- easyprivacy/easyprivacy_thirdparty.txt
Yandex Metrica server
</details>
> A: https://www.porland.com/

- easylist_cookie/easylist_cookie_allowlist_general_hide.txt
- easylist_cookie/easylist_cookie_specific_uBO.txt
> P: gpiaaf.gov.pt

- easylist/easylist_allowlist_general_hide.txt
fixes https://github.com/ghostery/broken-page-reports/issues/1702
> fix lagruyere.ch

- easylist/easylist_specific_hide.txt
found in url: https://english.navyamedia.com/
> A:navyamedia.com

- easylist/easylist_specific_hide.txt
found in url: https://www.deccanchronicle.com/
> A:deccanchronicle.com

- easylist/easylist_specific_hide.txt
found in url: https://www.herzindagi.com/
> A:herzindagi.com

- easylist/easylist_specific_block.txt
- easylist/easylist_specific_hide.txt
found in url: https://moviegalleri.net/
> A:moviegalleri.net

- easyprivacy/easyprivacy_trackingservers_general.txt
Related to #21778
Spotted on [their own site](https://www.incognia.com/device-fingerprint) and in the wild at https://www.just-eat.co.uk
Also, was there a contributions guidelines document anywhere I missed?
> A: icg-in.info
