easylist/easylist_general_block.txt

Added to allow our ajax requests through in order for our interactive tables to work.

Add linkpizza.com/advertiser/* to exceptions

---

easylist/easylist_specific_block.txt

site broken for easylist users until rule is corrected

rule34.xxx exception rule URL was incorrect

---

easylist/easylist_whitelist.txt

old domains redirects to new addresses.

update to current domains for KissAnime and KissCartoon

---

easylist/easylist_general_hide.txt

###advertising-right -> Found in comunio.es

Addition to easylist_general_hide.txt

---

easylist/easylist_general_hide.txt

Found in mercadolibre.com.ar:
##.publicity-box ->Main page, bottom-right
##.section-publicity -> You can only see it on individual publications, for example: http://articulo.mercadolibre.com.ar/MLA-604531925-maza-de-baqueano-500-jeep-ika-estanciera-_JM - Bottom-right of the page

Additions to easylist_general_hide.txt

---

easylist/easylist_whitelist.txt

fixes #320 for *.wetransfer.com

Added WeTransfer's Advertisement pages

---

easyprivacy/easyprivacy_whitelist_international.txt

Create exception to load googletagmanager script in www.saraiva.com.br

Addition to easylist_whitelist_international.txt

---

fanboy-addon/fanboy_social_whitelist_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=64&p=119626

P: http://zik.ua/

---

fanboy-addon/fanboy_social_whitelist_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=64&p=119696

P: http://kinogo-720.net/463-moya-uzhasnaya-nyanya-3.html

---

easylist/easylist_adservers.txt

[b6f2fcfc1b016d42e30d6cdb5d750dc8bf8ae2e3](https://github.com/uBlockOrigin/uAssets/commit/b6f2fcfc1b016d42e30d6cdb5d750dc8bf8ae2e3)

A: http://www.spaste.com/p/?c=eSmGUA4587

---

easylist/easylist_specific_hide.txt

https://forums.lanik.us/viewtopic.php?p=124126#p124126

A: http://beta.speedtest.net/

---

fanboy-addon/fanboy_social_whitelist.txt

http://i.imgur.com/PS6bfMW.png

P: https://www.almasdarnews.com/login/

---

easyprivacy/easyprivacy_general.txt

https://forums.lanik.us/viewtopic.php?f=62&t=38514

A: https://upromise.com/

---

easylist/easylist_general_block.txt

`http://asiancomics.net/reader/ads/box300.html`

A: http://asiancomics.net/reader/comics/Tokyo%20Ghoulre/Tokyo%20Ghoulre%20chapter%20149

---

easyprivacy/easyprivacy_trackingservers.txt

https://forums.lanik.us/viewtopic.php?f=62&t=38777

A: http://www.wpsuperstars.net/

---

fanboy-addon/fanboy_annoyance_general_hide.txt

https://forums.lanik.us/viewtopic.php?p=125580#p125580

A: http://kotburger.pl/

---

easyprivacy/easyprivacy_general.txt

https://forums.lanik.us/viewtopic.php?f=108&t=34212

A: http://www.zive.cz/

---

easylist/easylist_general_hide.txt

https://forums.lanik.us/viewtopic.php?p=128331#p128331

A: http://www.gocomics.com/news/laugh-tracks/4351/

---

fanboy-addon/fanboy_annoyance_general_block.txt

https://forums.lanik.us/viewtopic.php?f=62&t=39145

A: http://bitcoingarden.org/

---

easyprivacy/easyprivacy_general.txt

https://github.com/easylist/easylist/commit/089ad74d4f12#commitcomment-24839312

A: https://www.insuranceage.co.uk/

---

easylist/easylist_adservers.txt

https://forums.lanik.us/viewtopic.php?f=62&t=38947

A: https://coincodex.com/crypto/monero/

---

easyprivacy/easyprivacy_specific.txt

https://pastebin.com/raw/N5Fb6A5b

A: https://www.topachat.com/

---

easyprivacy/easyprivacy_trackingservers.txt

https://forums.lanik.us/viewtopic.php?f=62&t=37242

http://www.travaux.com/

---

easyprivacy/easyprivacy_general.txt

https://forums.lanik.us/viewtopic.php?f=62&t=38749

A: http://www.3a2ilati.com/

---

fanboy-addon/fanboy_annoyance_general_hide.txt

https://forums.lanik.us/viewtopic.php?p=126572#p126572

A: https://files.fm/

---

easylist/easylist_specific_hide.txt

https://forums.lanik.us/viewtopic.php?f=62&t=36915

A: https://www.wikihow.com/Create-Printed-Circuit-Boards

---

easyprivacy/easyprivacy_trackingservers.txt

It's the restaurant of a burger chain

Remove thecounter.com

---

fanboy-addon/fanboy_social_general_block.txt

`http://axicom.de/assets/app/images/social/soc-ln.png`

A: http://axicom.de/

---

easylist/easylist_adservers.txt

https://github.com/easylist/easylist/pull/634

A: https://gamecopyworld.eu/

---

easylist/easylist_general_block.txt

`http://www.letslive.tv/static/scripts/generateAds.js`
(https://forums.lanik.us/viewtopic.php?f=62&t=35996)

A: http://www.crichd.sc/eurosport-1-live-stream-uk

---

easylist_adult/adult_adservers.txt

**NSFW**
```
http://chatgyi.net/
http://xxnxx2017.org/
http://videopornoitalia.com/
https://www.pornokk.com/
http://filmeleporno.xxx/
```
https://pastebin.com/raw/z11CjZ3d

A: (NSFW) http://chatgyi.net/

---

easylist/easylist_thirdparty.txt

M: Added noadblock.org

---

easylist/easylist_adservers.txt

- http://i.imgur.com/ioXitdh.png

A: https://dailyuploads.net/dtdp8rgl07qi

---

easylist/easylist_specific_hide.txt

Fix mail.yahoo.com selector.

---

easylist/easylist_adservers_popup.txt

* https://forums.lanik.us/viewtopic.php?p=131051#p131051

M: Fix typo

---

easylist/easylist_general_block.txt

https://forums.lanik.us/viewtopic.php?f=64&t=39895
@Khrin

P: https://adpage.io/

---

easylist/easylist_general_block.txt

https://forums.lanik.us/viewtopic.php?f=64&t=39896
@Khrin

P: http://adbuddy.beeldstudio.be/

---

easylist/easylist_adservers.txt

`http://adzmaza.in/adtools/banner.php`

A: http://massmovies.pw/

---

easylist/easylist_adservers.txt

https://forums.lanik.us/viewtopic.php?f=62&t=37282

A: http://watchseriesmovie.net/

---

easylist/easylist_adservers.txt

`http://traffic2bitcoin.com/ptp.php?ref=tiago`

A: http://querodindin.com/

---

easyprivacy/easyprivacy_specific.txt

Hidden location tracking and ads without ability to disable in the popular GPS navigation application maps.me (https://play.google.com/store/apps/details?id=com.mapswithme.maps.pro)

A: https://maps.me/ (mobile app tracking)

---

easyprivacy/easyprivacy_thirdparty_international.txt

`http://179.43.173.134/elementscount`

A: http://sokrostream.tv/

---

fanboy-addon/fanboy_social_general_block.txt

`http://www.laredoute.fr/images/footer/social-networks-icon.png`

A: http://www.laredoute.fr/

---

fanboy-addon/fanboy_annoyance_general_hide.txt

* http://i.imgur.com/r5h8zxO.png

A: https://ksiegarnia.pwn.pl/

---

easylist/easylist_whitelist.txt

M: Change for adf.ly

---

easyprivacy/easyprivacy_specific_international.txt

```
http://www.easyvols.fr/
http://www.easyvoyage.com/
http://www.get-the-look.fr/
http://www.jeuxactu.com/
http://www.lestream.fr/
http://www.millenium.org/
http://www.cap-cine.fr/
http://www.cotecine.fr/
```

A: http://www.easyvols.fr/ (webediads.com)

---

fanboy-addon/fanboy_annoyance_thirdparty.txt

```
https://www.jobangola.com/
https://www.totaltrivia.com/
https://prinhouse.ru/
https://pastebin.com/raw/Q4fv6A8y (nsfw)
```

A: https://www.jobangola.com/

---

easylist/easylist_adservers.txt

https://forums.lanik.us/viewtopic.php?f=62&t=38135

A: https://coinmarketcap.com/

---

fanboy-addon/fanboy_social_whitelist_general_hide.txt

https://github.com/easylist/easylist/issues/576

A: https://ezhikezhik.ru/reviews/pocemu-francuzenkam-tak-legko-vospityvat-detej-4-priciny

---

easyprivacy/easyprivacy_trackingservers.txt

```
http://www.life.hu/
http://www.bama.hu/
http://www.nemzetisport.hu/
```

A: https://www.grazia.fr/

---

easyprivacy/easyprivacy_general.txt

```
http://chorouk.net/
http://librodot.com/
http://jam-hot.com/
http://waptvseries.net/
```

A: http://chorouk.net/

---

easylist/easylist_whitelist.txt

https://github.com/easylist/easylist/commit/e01764d554888746f539b747f1afa7b8f4a63803

M: Removed redundant filter for news-leader.com

---

fanboy-addon/fanboy_annoyance_specific_hide.txt

https://forums.lanik.us/viewtopic.php?f=64&t=40204

A: https://www.derwaldhof.com/

---

fanboy-addon/fanboy_annoyance_general_hide.txt

https://github.com/ryanbr/fanboy-adblock/issues/311

A: https://www.deepl.com/translator

---

fanboy-addon/fanboy_annoyance_specific_hide.txt

https://forums.lanik.us/viewtopic.php?f=62&t=32845 (14 Sep 2016)

A: https://www.e-day.ro/

---

easyprivacy/easyprivacy_trackingservers.txt

https://forums.lanik.us/viewtopic.php?f=62&t=40328

A: https://www.downloadpirate.com/

---

easyprivacy/easyprivacy_trackingservers.txt

https://forums.lanik.us/viewtopic.php?p=134464&hilit=datacoral#p134464
```
https://events.instartlogic.datacoral.io/tp2
https://datacoral.com/instrumentation/js/1.0.0/dc.js
```

A: http://www.wowhead.com/

---

easylist/easylist_adservers.txt

https://forums.lanik.us/viewtopic.php?f=62&t=40361

A: http://btcleets.xyz/Px0XG8WZ

---

easylist/easylist_adservers.txt

e.g.
```
https://www.adzchoice.com/b160.php/?Admin
https://www.adzhits.com/b728.php/?Admin
https://www.adzposter.com/b125.php/?Admin
```

A: http://intelhits.com/

---

easylist/easylist_general_block.txt

https://forums.lanik.us/viewtopic.php?f=64&t=40376

P: https://adnet.agency/

---

easyprivacy/easyprivacy_specific.txt

See https://github.com/uBlockOrigin/uAssets/issues/1889

block https://github.com/hydro_browser_events

---

fanboy-addon/fanboy_social_general_hide.txt

http://i.imgur.com/UpnZlb9.png

A: https://dreambox-info.net/iptv-vu/

---

fanboy-addon/fanboy_social_general_hide.txt

http://i.imgur.com/iZREkor.png

A: http://www.i3arby.com/

---

fanboy-addon/fanboy_social_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=62&t=34016

A: https://www.echoroukonline.com/washington-closes-investigation/

---

easylist/easylist_adservers.txt

```
https://alxzes.com/tag/BulTNz0ZjKYM.js?id=223614
https://flixlnk.top/a/99b2b919292f7692455b0cec7569f935.js?id=885726
```

A: https://www.t7meel.xyz/file/d6baa303ebeac109ea11c873108b74ad

---

fanboy-addon/fanboy_annoyance_thirdparty.txt

e.g.
`cheaphumidors.com` http://i.imgur.com/6ryy16c.png
`growerssupply.com` http://i.imgur.com/W0Q5jul.png
`farmtek.com` http://i.imgur.com/OsoHbZl.png

A: https://www.cheaphumidors.com/

---

easyprivacy/easyprivacy_trackingservers.txt

`callrail.com` mirrors
```
http://cdn.calltrk.com/companies/148383582/d277abfe7c2db9264453/12/swap.js
http://cdn.callreports.com/companies/148383582/d277abfe7c2db9264453/12/swap.js
```

A: http://www.infopluscommerce.com/

---

easylist/easylist_general_hide.txt

http://i.imgur.com/wscuGEQ.png

A: https://www.slant.co/options/1507/alternatives/~git-cola-alternatives

---

fanboy-addon/fanboy_annoyance_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=62&t=40541

A: http://www.52rd.com/Blog/Detail_RD.Blog_jiyongqing_98135.html

---

easylist/easylist_general_block.txt

https://forums.lanik.us/viewtopic.php?f=64&t=40560

P: http://intellitext.us/

---

easylist/easylist_adservers.txt

https://forums.lanik.us/viewtopic.php?f=62&t=40619

M: Update Tagnwin adservers

---

easylist/easylist_adservers.txt

[#commitcomment-28873673](https://github.com/uBlockOrigin/uAssets/commit/fe82cada62f59ce7cadf15ecd41cf37c37e64da8#commitcomment-28873673)

A: https://www.cinedoblego.com/

---

easyprivacy/easyprivacy_thirdparty.txt

e.g
```
http://88.150.172.219:81/n/i?r=&u=http%3A//epornoflv.tv/&s=1920*1080*24&t=0.1774655451204528
```

A: (NSFW) http://epornoflv.tv/

---

easylist/easylist_general_block.txt

```
https://www.manga.ae/cdn-cgi/pe/bag2?r[]=https%3A%2F%2Fcode.zwaar.org%2Fpcode%2Fcode-4540.js%3Fday%3D6
```

A: https://www.manga.ae/death-note/52/1/

---

easyprivacy/easyprivacy_trackingservers.txt

https://forums.lanik.us/viewtopic.php?f=62&t=36403

A: (NSFW) http://savebt.org/

---

easylist/easylist_adservers_popup.txt

- http://i.imgur.com/Qp5Te6g.png
- https://forums.lanik.us/viewtopic.php?p=136569#p136569

A: https://www.ddlvalley.me/

---

easylist/easylist_general_block.txt

e.g.
https://forums.lanik.us/viewtopic.php?p=125463#p125463
https://forums.lanik.us/viewtopic.php?p=120104#p120104
https://forums.lanik.us/viewtopic.php?p=122544#p122544
https://forums.lanik.us/viewtopic.php?p=136864#p136864

M: Update exads filters

---

easylist/easylist_general_block.txt

* `http://xijgedjgg5f55.com/1526682/?`
* https://forums.lanik.us/viewtopic.php?p=136783#p136783

M: Update Propellerads filter

---

easylist/easylist_specific_block.txt

```
https://www.nzbstars.com/images/blb_ani.gif
https://www.nzbstars.com/images/blb_ani_2.gif
```

A: https://www.nzbstars.com/

---

easylist/easylist_specific_block.txt

https://github.com/easylist/easylist/pull/1187
https://github.com/uBlockOrigin/uAssets/issues/2349

https://search.stream.cr/y/video.php?mid=el

---

easylist/easylist_adservers.txt

https://github.com/easylist/easylist/pull/1188
https://forums.lanik.us/viewtopic.php?f=62&t=38132

A: https://stream.cr/

---

easylist/easylist_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=62&t=40823

A: https://www.themidweeksun.co.bw/

---

easyprivacy/easyprivacy_specific.txt

```
Received: by poc-bom3.splio.com id aaaaaaaa for <abcdef@xyz.com>; Thu, 21 May 2018 06:51:12 +0300 (envelope-from <bestofmedia_fr@s3s-bofm.net>)
X-Abuse-Reports-To: abuse@splio.com
X-CSA-complaints: whitelist-complaints@eco.de
Message-ID: <abcdef-123@s3s-bofm.net>
X-Auto-Response-Suppress: OOF,AutoReply
X-CampaignID: abcdef
List-Unsubscribe: <https://s3s.fr/l-uns/000000/000000/000000.html>, <mailto:un-000000-000000-000000@s3s-bofm.net>
List-Unsubscribe-Post: List-Unsubscribe=One-Click
List-ID: v3bestofmedia_fr
Feedback-ID: abcdef:v3bestofmedia_fr:splio
X-SignalSpam-CID: abcdef:v3bestofmedia_fr:splio
MIME-Version: 1.0
From: "Communauté Tom's" <notices@purch.fr>
To: <abcdef@xyz.com>
Subject: Information importante à propos de votre compte
Precedence: bulk
Reply-To: <privacy@purch.com> …
```

A: (opened email tracker) http://www.bestofmedia.com/

---

fanboy-addon/fanboy_social_whitelist.txt

P: https://icons8.com/iconizer/en/search/No-license-filtering/0-128/1/google

---

easylist/easylist_general_block.txt

```
http://cdn.studentmossaonline.com/js/gomage/adspromo.js
http://cdn.studentmossaonline.com/js/gomage/adspromo-window.js
http://cdn.studentmossaonline.com/js/gomage/adspromo-effects.js
```

A: http://studentmossaonline.com/

---

fanboy-addon/fanboy_annoyance_general_hide.txt

* http://i.imgur.com/r8bWkNL.png
`https://www.alibaba.com/`
* http://i.imgur.com/CXg2Mrv.png
`https://activity.alibaba.com/promotion/weeklyfinds/regional-selections.html`
----
@ryanbr @Khrin >> https://forums.lanik.us/viewtopic.php?f=64&t=40845

A: https://www.alibaba.com/

---

easylist/easylist_general_hide.txt

https://github.com/uBlockOrigin/uAssets/issues/2376#issuecomment-392217259

A: (NSFW) hxxps://www.videoszoofiliahd.com/

---

easyprivacy/easyprivacy_trackingservers_international.txt

https://forums.lanik.us/viewtopic.php?f=62&t=40287

A: https://www.femmesplus.fr/

---

fanboy-addon/fanboy_annoyance_specific_hide.txt

http://i.imgur.com/PV6aj0j.png

A: http://www.planet.fr/

---

easylist/easylist_specific_block.txt

https://forums.lanik.us/viewtopic.php?f=62&t=40812

A: http://turbobit.net/rps96t1rs030.html

---

easylist/easylist_adservers.txt

https://forums.lanik.us/viewtopic.php?p=136739#p136739

A: https://freenem.com/

---

fanboy-addon/fanboy_annoyance_specific_hide.txt

http://i.imgur.com/Hx65dub.png
https://forums.lanik.us/viewtopic.php?f=62&t=40852
https://github.com/easylist/easylist/pull/1196

A: https://seatguru.com/

---

easylist/easylist_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=62&t=40843

A: https://www.geeksaresexy.net/

---

fanboy-addon/fanboy_annoyance_specific_hide.txt

**Annoying signup prompt** 
* http://i.imgur.com/cNOowuG.png

A: https://github.com/easylist/easylist

---

easylist/easylist_adservers_popup.txt

* https://forums.lanik.us/viewtopic.php?f=62&t=40799
* https://github.com/easylist/easylist/pull/1167

A: http://www.yify-torrent.xyz/

---

easylist/easylist_adservers_popup.txt

* https://forums.lanik.us/viewtopic.php?f=62&t=40798
* https://github.com/easylist/easylist/pull/1168

A: http://ytsyify.com/

---

easylist/easylist_specific_block.txt

https://forums.lanik.us/viewtopic.php?f=62&t=40795

A: https://javascriptobfuscator.com/Javascript-Obfuscator.aspx

---

easylist/easylist_specific_block.txt

https://forums.lanik.us/viewtopic.php?f=62&t=40794

A: http://abdokarbil.blogspot.com/2017/11/core-areas-where-virtual-reality-app.html

---

fanboy-addon/fanboy_social_general_hide.txt

http://i.imgur.com/9iURqv6.png

A: http://elfariq.com/

---

fanboy-addon/fanboy_annoyance_thirdparty.txt

http://i.imgur.com/764lnCV.png

A: https://www.gamekult.com

---

easylist/easylist_specific_hide.txt

https://github.com/uBlockOrigin/uAssets/issues/2302

A: https://www.hit2k.com/2018/05/connectify-pro-crack-2018-lifetime.html

---

easyprivacy/easyprivacy_specific_international.txt

```
https://mootanroo.com/
https://bimebazar.com/
http://pcquest.ir/
https://www.gt724.com/
```
```
https://footprint.anetwork.ir/a?0000000.v1.00000
https://footprint.anetwork.ir/v1/handle?d=*&p=*&wi=*&h=*&w=
```

A: https://mootanroo.com/

---

easylist/easylist_adservers.txt

https://forums.lanik.us/viewtopic.php?f=62&t=40740

A: http://gogoanime.bz/anime/hd-detective-conan-episode-one/

---

fanboy-addon/fanboy_annoyance_general_hide.txt

`yukari git` mean `back to top`, `go to top` or `scroll to top`

A: http://www.decomaniacos.es/

---

easylist/easylist_whitelist.txt

https://github.com/easylist/easylist/commit/f3a9b41cf0839398199df3848aa4d6579848d5f1
https://github.com/easylist/easylist/commit/ee0e74651bb1696b4f1ce4bb6d67d6e690831c5a

M: (Removed obsolete filters) http://www.eclypsia.com/

---

fanboy-addon/fanboy_annoyance_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=62&t=40632

A: https://www.parcelmonitor.com/blog/

---

easylist/easylist_general_hide.txt

https://forums.lanik.us/search.php?keywords=inclk.com&fid%5B0%5D=62

A: https://desiupload.info/f/agcnuu-fa2k1hbniw3f8

---

easylist/easylist_adservers.txt

https://forums.lanik.us/viewtopic.php?f=62&t=39607

A: http://2conv.com/

---

fanboy-addon/fanboy_annoyance_thirdparty.txt

http://i.imgur.com/Tz6We6d.png

A: http://onehoste.com/

---

fanboy-addon/fanboy_annoyance_general_hide.txt

```
bdc.ae
free-cloud-storage.com
NSFW onlineporn24.com
```

A: http://www.bdc.ae/

---

easyprivacy/easyprivacy_whitelist.txt

M: swisscom.ch

---

easylist/easylist_specific_block.txt

https://forums.lanik.us/viewtopic.php?f=62&t=40585

A: https://text-compare.com/

---

easylist/easylist_specific_block.txt

```
https://www.phpbb.com/assets/images/images/bg_forumatic_front_page.png
https://www.phpbb.com/assets/images/images/hosting/hostmonster-downloads.gif
```

A: https://www.phpbb.com/downloads/

---

easylist/easylist_adservers_popup.txt

- http://i.imgur.com/kglwSUY.png
- https://forums.lanik.us/viewtopic.php?p=137336#p137336

A: https://www4.zippyshare.com/v/87202567/file.html

---

easylist/easylist_general_block_popup.txt

propellerads popup
- http://i.imgur.com/pmQlnVg.png

A: https://streamzentier.com/

---

easylist/easylist_general_block.txt

- https://github.com/easylist/easylist/commit/45ee599b
- https://forums.lanik.us/viewtopic.php?f=62&t=40911

A: http://www.americanlisted.com/

---

easylist/easylist_adservers_popup.txt

- http://i.imgur.com/vnTqa9a.png
- https://github.com/Ultimate-Hosts-Blacklist/smed79_parkingcrew.com/blob/master/domains.list
```
http://douate.com/popup.js
http://douate.com/popup.js
http://skompiec.pl/popup.js
http://siterank.me/popup.js
http://egcash.com/popup.js
http://egcash.com/popup.js
http://consorsfnanz.de/popup.js
http://solda.io/popup.js
http://ichwerdereich.de/popup.js
```

M: added parkingcrew.net popup adserver

---

easyprivacy/easyprivacy_general.txt

https://forums.lanik.us/viewtopic.php?f=64&t=40883

P: https://bugs.chromium.org/p/chromium/issues/detail?id=108055

---

easylist/easylist_general_block.txt

https://forums.lanik.us/viewtopic.php?f=62&t=40638

A: http://streamylo.com/channel/5

---

fanboy-addon/fanboy_cookie_general_hide.txt

http://i.imgur.com/FZXbINH.png

A: https://www.accuweather.com/

---

fanboy-addon/fanboy_annoyance_general_block.txt

- http://i.imgur.com/iQ8Xdrh.png
- https://forums.lanik.us/viewtopic.php?f=62&t=40907

A: https://www.healthline.com/

---

fanboy-addon/fanboy_social_general_hide.txt

http://i.imgur.com/L65exZi.png

A: https://www.t-online.de/

---

fanboy-addon/fanboy_social_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=62&t=40877

A: https://www.manageo.fr/entreprises/381286251.html

---

easylist/easylist_specific_block.txt

https://forums.lanik.us/viewtopic.php?f=62&t=40876

A: https://chinapost-track.com/china-post-tracking

---

fanboy-addon/fanboy_annoyance_specific_hide.txt

http://i.imgur.com/evww1bt.png

A: https://yaoota.com/

---

fanboy-addon/fanboy_cookie_general_block.txt

```
https://api.all.biz/lazyblocks/we_use_cookies?jsoncallback=jQuery1183710023574753926693_1503402810725&_=1703528104026
```

A: https://expofr.all.biz/1618-paris-org8414024

---

easyprivacy/easyprivacy_general.txt

https:\//all.biz/
https:\//5306-fr.all.biz/
```
https://count.all.biz/site_counter?page_id=5&resource=US&lng=en&lng_id=2&isa=0&ise=0&ts=0.44462000+5478106865
https://count.all.biz/ent_counter?page_id=8&tld=1111&tsid=123&resource=fr&lng=en&lng_id=14&size=200&reff=&rand=0.3111363771216236
```

A: https://5306-fr.all.biz/

---

easylist/easylist_general_block.txt

https://forums.lanik.us/viewtopic.php?f=64&t=40941

P: http://adsquare.ma/

---

fanboy-addon/fanboy_annoyance_general_hide.txt

http://i.imgur.com/IK6r0hR.png

A: https://www.diplomatie.gouv.fr/

---

fanboy-addon/fanboy_annoyance_general_block.txt

```
https://thepiratebay.org/static/img/rss_small.gif
https://thepiratebay.cr/static/img/rss_small.gif
https://thepiratebay.red/static/img/rss_small.gif
https://thepiratebay.rocks/static/img/rss_small.gif
```

A: https://thepiratebay.org/

---

fanboy-addon/fanboy_annoyance_general_block.txt

https://forums.lanik.us/viewtopic.php?p=137544&hilit=taboola#p137544

A: https://www.rd.com/

---

fanboy-addon/fanboy_social_whitelist.txt

https://forums.lanik.us/viewtopic.php?f=64&t=40945

P: http://megaserial.me/762-anatomiya-strasti.html

---

fanboy-addon/fanboy_cookie_general_block.txt

@ryanbr Layout issue with the filter `##.gdpr-notification`
https://forums.lanik.us/viewtopic.php?f=91&t=41026

A: https://www.nieuwsblad.be/

---

easylist/easylist_adservers_popup.txt

https://forums.lanik.us/viewtopic.php?p=137811#p137811

A: http://mp3clan.com/

---

easylist/easylist_thirdparty.txt

https://forums.lanik.us/viewtopic.php?f=62&t=41021

A: http://www.citethisforme.com/

---

easylist/easylist_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=62&t=41024

A: https://licensekey.net/

---

fanboy-addon/fanboy_cookie_general_block.txt

`https://s3.amazonaws.com/booster-eu-cookie/rudby.myshopify.com/booster_eu_cookie.js`

A: https://www.rudby.fr/

---

easyprivacy/easyprivacy_general.txt

https://github.com/easylist/easylist/pull/1339

A: https://www.hbrfrance.fr/

---

easylist/easylist_adservers_popup.txt

https://forums.lanik.us/viewtopic.php?p=137798#p137798

A: https://adsrt.com/3s0X

---

easyprivacy/easyprivacy_specific.txt

```
http://tortoise.proboards.com/tortoise.pl?field=amount_guest&mobile=0&rand=0.00668019020800159&forum_id=6138434
```

A: http://gdforum.freeforums.net/

---

easyprivacy/easyprivacy_general.txt

```
https://static.autoplus.fr/js/stats/xtcore.js
https://static.sportauto.fr/js/stats/xtcore.js
https://static.autojournal.fr/js/stats/xtcore.js
```

A: https://www.autoplus.fr/

---

easylist/easylist_general_hide.txt

```
https://www.msn.com/en-in/entertainment/bollywood/celebrity-deaths-that-shocked-india/ss-BBzXKsA?li=AA5a2m
```
https://github.com/uBlockOrigin/uAssets/issues/506#issuecomment-397560166

A: https://www.msn.com/

---

easylist/easylist_thirdparty.txt

hdtorrent.in, third-party block filter added

---

easylist/easylist_thirdparty_popup.txt

domovies.co.in

---

easylist/easylist_general_block.txt

https://forums.lanik.us/viewtopic.php?f=62&t=39694

A: (NSFW) http://xrares.com/

---

easylist/easylist_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=62&t=41122

A: http://www.ign.com/

---

fanboy-addon/fanboy_cookie_general_hide.txt

http://i.imgur.com/jQIE7mI.png

A: https://www.scribd.com/

---

easylist/easylist_specific_block.txt

A: https://www.oureducation.in/Course-List/Medical/5

---

easylist/easylist_thirdparty.txt

https://forums.lanik.us/viewtopic.php?f=62&t=33062
https://forums.lanik.us/viewtopic.php?f=62&t=40707

A: https://tusfiles.net/q4za8cgkvghg

---

easylist/easylist_adservers.txt

https://forums.lanik.us/viewtopic.php?f=62&t=34071

A: https://dottech.org/

---

easylist/easylist_general_hide.txt

- https://forums.lanik.us/viewtopic.php?f=62&t=41153
- https://github.com/ryanbr/fanboy-adblock/issues/468 (social)

A: https://www.startupranking.com/adblock-plus

---

easyprivacy/easyprivacy_general.txt

https://forums.lanik.us/viewtopic.php?f=103&t=41142

A: https://vmf.edge-apps.net/embed/live.php?streamname=americahls-100056

---

fanboy-addon/fanboy_annoyance_whitelist_general_hide.txt

@ryanbr https://forums.lanik.us/viewtopic.php?f=64&t=41137

P: https://www.humblebundle.com/monthly

---

fanboy-addon/fanboy_cookie_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=62&t=41133

A: https://osb-alliance.de/news

---

fanboy-addon/fanboy_annoyance_specific_hide.txt

http://i.imgur.com/VcNIqdx.png
http://i.imgur.com/B5lKmTQ.png

A: http://www.letribunaldunet.fr/

---

fanboy-addon/fanboy_cookie_general_hide.txt

https://github.com/ryanbr/fanboy-adblock/issues/473

A: https://hinta.fi/ (ryanbr/fanboy-adblock#473)

---

easyprivacy/easyprivacy_general.txt

https://forums.lanik.us/viewtopic.php?f=64&t=41167

P: https://writelog.com/

---

easylist/easylist_general_block.txt

https://forums.lanik.us/viewtopic.php?f=103&t=41170

P: https://technomedia.co/

---

fanboy-addon/fanboy_annoyance_thirdparty.txt

```
https://www.zspotmedia.ro/
https://www.shoppingcidadesp.com.br/
https://www.tieteplazashopping.com.br/
```

A: https://www.zspotmedia.ro/

---

easylist/easylist_adservers.txt

```
http://www.vidcpm.com/watch.xml?&key=c3d0b1a112694afdda3d7c78a14a5f12
http://www.vid7delivery.com/watch.xml?&key=c3d0b1a112694afdda3d7c78a14a5f12
http://www.vidsdelivery.com/watch.xml?&key=c3d0b1a112694afdda3d7c78a14a5f12
```
NSFW
```
https://cdnb.acloudvideos.com/v/whad/whnonnude_640.mp4
https://cdnb.acloudvideos.com/v/pwngames/RealAdultSex/rasg-en-5mb_1280x720_30.mp4
```

Update #1505 (video ad server)

---

easylist/easylist_specific_block.txt

https://forums.lanik.us/viewtopic.php?p=138534#p138534

A: https://vidzi.online/dofuw7s2ujlg.html

---

easylist/easylist_specific_block.txt

@ryanbr https://forums.lanik.us/viewtopic.php?f=62&t=41141

A: http://shon.xyz/S1uen

---

easyprivacy/easyprivacy_general.txt

`https://wordpress.org/plugins/host-analyticsjs-local/`

A: https://bestgadgetry.com/

---

easylist/easylist_general_hide.txt

- #1442
- https://forums.lanik.us/viewtopic.php?f=62&t=26024

A: http://www.themelock.com/

---

fanboy-addon/fanboy_social_whitelist_general_hide.txt

https://github.com/ryanbr/fanboy-adblock/issues/479

P: https://solojuve.com/ (ryanbr/fanboy-adblock#479)

---

easylist/easylist_specific_block.txt

@ryanbr https://github.com/uBlockOrigin/uAssets/issues/2886

A: https://discordbots.org/bot/388823187246546948

---

easylist/easylist_specific_hide.txt

**Found in URL:** https://www.englishgrammar.org/lessons/
**Found in URL:** grammarcheck.net

Englishgrammar.org, grammarcheck.net

---

easylist/easylist_specific_hide.txt

**Found in URL:** https://medicaldialogues.in/
**Found in URL:** https://education.medicaldialogues.in/panel-to-be-set-up-to-fix-medical-course-fee-madras-hc/
**Found in URL:** https://education.medicaldialogues.in/panel-to-be-set-up-to-fix-medical-course-fee-madras-hc/

medicaldialogues.in

---

easylist/easylist_specific_hide.txt

**Found in URL:** https://freshdesignweb.com

freshdesignweb.com

---

easylist/easylist_specific_hide.txt

**Found in URL:** https://startbootstrap.com

startbootstrap.com

---

easylist/easylist_specific_hide.txt

snaptest.org

---

easyprivacy/easyprivacy_trackingservers.txt

smartlook.com mirror >> https://forums.lanik.us/viewtopic.php?f=62&t=41209

A: https://www.e-liquide-fr.com/

---

easylist/easylist_specific_hide.txt

- https://forums.lanik.us/viewtopic.php?f=62&t=41236
- https://github.com/uBlockOrigin/uAssets/issues/2949

A: http://www.techweez.com/2018/07/20/not-used-third-party-antivirus/

---

fanboy-addon/fanboy_annoyance_general_hide.txt

https://i.imgur.com/Ze6CGN3.png

A: https://www.aufeminin.com/

---

easylist/easylist_adservers.txt

https://forums.lanik.us/viewtopic.php?f=62&t=37273
https://forums.lanik.us/viewtopic.php?f=62&t=23318
https://forums.lanik.us/viewtopic.php?f=62&t=37272

A: http://www.check-domains.com/

---

easyprivacy/easyprivacy_general.txt

https://forums.lanik.us/viewtopic.php?p=139137#p139137

P: https://stats.wikimedia.org/v2/#/all-projects

---

easylist/easylist_general_block.txt

[uAssets#2426 (comment)](https://git.io/fNaPe)

A: (NSFW) http://efukt.com/

---

easylist/easylist_general_hide.txt

```
https://www.fifa.com/worldcup/
https://www.fifa.com/worldcup/destination/index.html
```
https://forums.lanik.us/viewtopic.php?f=62&t=41028

A: https://www.fifa.com/

---

fanboy-addon/fanboy_annoyance_general_hide.txt

https://github.com/smed79/easylist/commit/f00a24daaf0a0dd78b4d05404fdf9fcc638e6e9c

A: https://www.drweb.com/

---

fanboy-addon/fanboy_cookie_general_block.txt

`https://www.deco.fr/api/js/cookieu.js`

A: https://www.deco.fr/

---

easyprivacy/easyprivacy_thirdparty.txt

A: (opened email tracker) https://madmimi.com/

---

easyprivacy/easyprivacy_whitelist.txt

uBlockOrigin/uAssets/issues/2518

A: https://archive.softwareheritage.org/

---

easylist/easylist_specific_hide.txt

https://i.imgur.com/22ZkkF1.png

A: http://www.newagebd.net/article/47105/

---

fanboy-addon/fanboy_cookie_general_hide.txt

https://i.imgur.com/srcmPym.png

A: https://www.priceminister.com/

---

fanboy-addon/fanboy_annoyance_general_block.txt

`https://www.lequipe.fr/wonderpush.min.html`

A: https://www.lequipe.fr/

---

fanboy-addon/fanboy_annoyance_whitelist_general_hide.txt

- https://forums.lanik.us/viewtopic.php?f=64&t=41338
- https://i.imgur.com/HLZ0EkR.png
- https://i.imgur.com/jD2jmzq.png

P: https://forum.qscservice.com/viewtopic.php?f=34&t=5204

---

fanboy-addon/fanboy_annoyance_general_hide.txt

https://i.imgur.com/iu3XGHn.png

A: https://nur.gratis/

---

fanboy-addon/fanboy_cookie_whitelist_general_hide.txt

P: http://www.ramics-conference.org/?page_id=173 (ryanbr/fanboy-adblock#506)

---

easylist/easylist_specific_hide.txt

**Found in URL:** https://www.lawctopus.com/

lawctopus.com

---

easylist/easylist_adservers.txt

Found in URL: https://whatismyipaddress.com

whatismyipaddress.com

---

easylist/easylist_specific_block.txt

**Found in URL:** https://www.getmyuni.com/engineering-colleges

getmyuni.com

---

easylist/easylist_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=62&t=41372

A: https://reddit.com/

---

easylist/easylist_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=62&t=41565

A: (NSFW) https://www.pornhat.com/video/1082/hot-lesbian-pin/

---

easyprivacy/easyprivacy_specific.txt

- `https://e.infogram.com/2dbf879e-8591-4b12-88c5-d4ad2dbeeda4?`
- `https://www.ksl.com/article/46386064/`
- https://forums.lanik.us/viewtopic.php?f=62&t=41594

A: https://e.infogram.com/2dbf879e-8591-4b12-88c5-d4ad2dbeeda4?

---

easylist/easylist_specific_hide.txt

https://i.imgur.com/dPc56OZ.png

A: https://www.ksl.com/ (Update #1785)

---

easylist/easylist_general_hide.txt

https://forums.lanik.us/viewtopic.php?p=140211#p140211

A: (NSFW) https://xhamster.com/

---

easylist/easylist_general_block.txt

adcore.ch has nothing in common with adcore.com
#495

P: https://www.adcore.ch

---

easyprivacy/easyprivacy_whitelist.txt

https://forums.lanik.us/viewtopic.php?f=64&t=11557

M: Removed allrecipes.com (not longer necessary)

---

fanboy-addon/fanboy_annoyance_general_block.txt

https://i.imgur.com/Q3cGojn.png

A: https://www.allrecipes.com/

---

easylist/easylist_specific_block.txt

https://forums.lanik.us/viewtopic.php?f=64&t=41636

P: https://suprafiles.me/register.html

---

easylist/easylist_adservers.txt

https://i.imgur.com/uq4WXH6.png

A: https://apkmb.com/

---

easylist/easylist_adservers_popup.txt

https://i.imgur.com/elTzgvq.png

A: https://apk4free.net/

---

easylist/easylist_general_block.txt

https://forums.lanik.us/viewtopic.php?f=64&t=41660

P: https://advertise-solution.nl/

---

easylist/easylist_adservers_popup.txt

https://i.imgur.com/KeFa5mT.png

A: https://onhax.me/

---

easyprivacy/easyprivacy_general.txt

```
http://riotpixels.com/rpc.gif?ac=RP-1-1&j=1&c=_trackPageview&a=&l=&v=&r=256x128&p=%2Fgames%2F&h=riotpixels.com&po=&pr=http%3A&r=0.27901480282483954
```

A: http://en.riotpixels.com/

---

easylist_adult/adult_specific_block.txt

- https://i.imgur.com/WkPJ6HC.png
- https://i.imgur.com/gNRQe2l.png

A: (NSFW) https://anyporn.com/

---

easylist/easylist_specific_block.txt

https://forums.lanik.us/viewtopic.php?f=62&t=41669

A: https://cutpaid.com/7UC6pyKk

---

fanboy-addon/fanboy_annoyance_general_hide.txt

@ryanbr You can merge other good generic hiding filters from [viewtopic.php?f=91&t=41658](https://forums.lanik.us/viewtopic.php?f=91&t=41658)

A: https://www.tsa-algerie.com/

---

easylist/easylist_specific_block.txt

https://forums.lanik.us/viewtopic.php?p=140047#p140047

A: http://itdmusic.com/?s=interpol

---

easylist/easylist_specific_block.txt

https://forums.lanik.us/viewtopic.php?p=140834#p140834

M: Update bebi script

---

easylist_adult/adult_adservers.txt

https://forums.lanik.us/viewtopic.php?f=62&t=41665

A: (NSFW) https://zoomgirls.net/

---

easylist/easylist_general_block.txt

https://forums.lanik.us/viewtopic.php?p=141292&hilit=lazyad+lazy-ads#p141292

A: https://www.vipbox.live/ospreys-vs-treviso-1-live

---

easylist/easylist_specific_block.txt

https://github.com/uBlockOrigin/uAssets/issues/911#issuecomment-423770511

M: Update adsrt.com

---

fanboy-addon/fanboy_annoyance_general_hide.txt

https://i.imgur.com/M6VV5UO.png

A: https://www.journaldunet.com/

---

easylist/easylist_adservers.txt

https://forums.lanik.us/viewtopic.php?p=141362#p141362

A: https://xmovies8.pl/

---

easylist/easylist_general_hide.txt

https://forums.lanik.us/viewtopic.php?p=141376#p141376

A: https://www.ivoox.com/

---

easylist/easylist_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=62&t=41774

A: http://oms.matchat.online/player/dg7d18uAnl

---

easyprivacy/easyprivacy_general.txt

```
http://public.ebc.com.br/templates/ebc2/js/google_analytics3_v2.js
```

A: http://agenciabrasil.ebc.com.br/en

---

easylist/easylist_general_block.txt

```
http://static.terratraf.com/engine/adsbyadsn.js
```

M: Update #1908

---

easylist/easylist_specific_hide.txt

https://i.imgur.com/kZqwkhn.png

A: https://www.tinkercad.com/

---

fanboy-addon/fanboy_social_general_hide.txt

https://i.imgur.com/JRUehdW.png

A: https://www.tinkercad.com/#/dashboard

---

easylist/easylist_adservers_popup.txt

https://i.imgur.com/st4rlUK.png

A: https://clipwatching.com/embed-4hfva8e6z7e4.html

---

easylist/easylist_specific_block.txt

Update https://github.com/easylist/easylist/commit/9b455912

A: https://vidcloud.co/v/5b85a572c4db9

---

easylist/easylist_specific_block.txt

```
http://1app.blob.core.windows.net/script/p.js
```

A: http://xsportshd.com/

---

easylist/easylist_general_hide.txt

anti adblock, see https://forums.lanik.us/viewtopic.php?f=62&t=41827

A: https://sp-today.com/

---

fanboy-addon/fanboy_social_specific_block.txt

https://forums.lanik.us/viewtopic.php?f=62&t=41829

A: https://5movies.to/movie/white-boy-rick-87668/

---

fanboy-addon/fanboy_social_whitelist_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=64&t=41834

P: http://darudar.org/users/Borz/wishes/personal/

---

fanboy-addon/fanboy_annoyance_whitelist_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=64&t=41790

P: https://us.audionetwork.com/track/searchkeyword

---

easylist/easylist_whitelist_general_hide.txt

redundancy with `$generichide`

M: Removed receive-a-sms.com (https://github.com/easylist/easylist/commit/9e1669e)

---

fanboy-addon/fanboy_annoyance_specific_hide.txt

hide the push notification pop-in 
- https://vgy.me/G9721l.png
- https://vgy.me/WEmm95.png

A: https://myegy.cc/

---

easyprivacy/easyprivacy_trackingservers.txt

https://forums.lanik.us/viewtopic.php?f=64&t=41914

P: https://fortnitetracker.com/lfg

---

fanboy-addon/fanboy_social_whitelist_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=64&t=41925

P: https://reefbuilders.com/friday-smorgasbord-76/

---

fanboy-addon/fanboy_annoyance_general_block.txt

https://i.imgur.com/O0eLxnn.png

A: https://aajtak.intoday.in/

---

easylist_adult/adult_specific_block.txt

A: (NSFW) https://m.spankbang.com/

---

easyprivacy/easyprivacy_trackingservers.txt

https://forums.lanik.us/viewtopic.php?f=62&t=41912

A: https://www.alutronic.de/

---

fanboy-addon/fanboy_annoyance_specific_hide.txt

https://i.imgur.com/ga1Ytwr.png

A: https://www.howtogeek.com/341972/

---

easyprivacy/easyprivacy_whitelist_international.txt

https://forums.lanik.us/viewtopic.php?f=91&t=41892

P: https://mon.compteczam.fr/

---

fanboy-addon/fanboy_cookie_whitelist_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=91&t=41896

P: https://www.free.fr/freebox/index.html

---

fanboy-addon/fanboy_cookie_whitelist_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=91&t=41895

P: https://www.ikks.com/

---

easyprivacy/easyprivacy_specific_international.txt

https://forums.lanik.us/viewtopic.php?f=62&t=41931

A: https://meblem4.pl/

---

easylist_adult/adult_specific_block.txt

https://forums.lanik.us/viewtopic.php?p=142277#p142277

M: (NSFW - Removed exploited whitelist filters) http://pussyspace.com/

---

easylist/easylist_specific_hide.txt

https://forums.lanik.us/viewtopic.php?f=62&t=41118

A: https://www.ettv.tv/torrent/244489/

---

fanboy-addon/fanboy_annoyance_specific_block.txt

```
https://navbharattimes.indiatimes.com/subscriptionhomepage.cms
```

A: https://navbharattimes.indiatimes.com/

---

easylist/easylist_general_block.txt

https://github.com/easylist/easylist/commit/d4fde05090
https://forums.lanik.us/viewtopic.php?f=64&t=42008

P: https://adw.olsztyn.pl/

---

fanboy-addon/fanboy_social_whitelist_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=64&p=142499

P: https://workroom-myata.ru/buketi-roz/25-ekvadorskih-roz-40-sm/

---

fanboy-addon/fanboy_cookie_whitelist.txt

https://i.imgur.com/Mv7NuoC.png

M: Update ryanbr/fanboy-adblock#591 (pole-emploi.fr)

---

easylist/easylist_adservers.txt

`http://quickads.net/pub/_jpopunder/b822c8fd27_vrc7j2vjf3_1540602722.js`

A: http://aa2133.blogspot.com/

---

easylist/easylist_general_hide.txt

https://i.imgur.com/RpAuc7t.png

A: http://allmusicsite.com/

---

fanboy-addon/fanboy_cookie_general_hide.txt

https://github.com/ryanbr/fanboy-adblock/issues/605

A: https://www.eurodk.com/

---

fanboy-addon/fanboy_social_whitelist_general_hide.txt

https://github.com/ryanbr/fanboy-adblock/issues/607

P: https://disqus.com/profile/login/

---

fanboy-addon/fanboy_cookie_whitelist.txt

https://github.com/ryanbr/fanboy-adblock/issues/608

P: https://www.kjellmann.no/

---

fanboy-addon/fanboy_cookie_general_hide.txt

https://github.com/ryanbr/fanboy-adblock/issues/612

A: https://www.oph.fi/

---

easylist_adult/adult_adservers.txt

https://forums.lanik.us/viewtopic.php?f=62&t=36025
https://github.com/uBlockOrigin/uAssets/issues/869#issuecomment-435216929

A: (NSFW) http://www.daporn.com/

---

easyprivacy/easyprivacy_general.txt

https://forums.lanik.us/viewtopic.php?f=62&t=42104

A: https://japantoday.com/

---

fanboy-addon/fanboy_cookie_general_hide.txt

https://github.com/ryanbr/fanboy-adblock/issues/630

A: https://www.teliacarrier.com/

---

fanboy-addon/fanboy_annoyance_general_hide.txt

https://github.com/ryanbr/fanboy-adblock/issues/628

A: https://www.learningsolutionsmag.com/

---

easylist/easylist_thirdparty.txt

https://forums.lanik.us/viewtopic.php?f=62&t=38259

A: https://gamecopyworld.eu/games/pc_nba_2019.shtml

---

fanboy-addon/fanboy_social_general_hide.txt

https://github.com/ryanbr/fanboy-adblock/issues/659

A: https://lushka.al/osd-summit-2018/

---

easylist/easylist_general_hide.txt

https://github.com/easylist/easylist/commit/557641a3b8a21c46724848555f7f439cfcb2e45f

M: Fix typo 557641a

---

fanboy-addon/fanboy_annoyance_specific_hide.txt

https://github.com/ryanbr/fanboy-adblock/issues/631#issuecomment-443030639

M: translate.google.com

---

easyprivacy/easyprivacy_trackingservers.txt

A: Update #2388 (opened email tracker)

---

easylist/easylist_adservers_popup.txt

A: https://www.mediafire.com/file/6bkcr491y8yomx6/

---

easylist/easylist_general_block.txt

https://forums.lanik.us/viewtopic.php?f=64&t=42356

P: https://adx.world/ & https://adx.cx/

---

easylist/easylist_general_block.txt

https://forums.lanik.us/viewtopic.php?f=64&p=144237

P: https://ads.bigbom.com/

---

fanboy-addon/fanboy_cookie_international_specific_hide.txt

`modrykonik.sk##.nc_a`
cookie warning hide

A: modrykonik.sk

---

easyprivacy/easyprivacy_trackingservers.txt

https://forums.lanik.us/viewtopic.php?f=62&t=34598

A: (nsfw - fullasiantube.com) https://forums.lanik.us/viewtopic.php?f=62&t=34598

---

easylist/easylist_general_hide.txt

`https://torrentz2.eu/dd894392602bd584966240c8ddf66f7c000f1e5b`

M: Update #2427

---

fanboy-addon/fanboy_annoyance_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=62&t=42325

A: https://uk.jooble.org/jobs-administrator/London

---

fanboy-addon/fanboy_social_whitelist.txt

https://forums.lanik.us/viewtopic.php?f=64&t=42313

P: https://jut.su/naruto/season-2/episode-308.html

---

easylist/easylist_general_block.txt

https://forums.lanik.us/viewtopic.php?f=64&t=42311

P: https://adboost.sellerboost.de/

---

easylist/easylist_specific_block.txt

https://forums.lanik.us/viewtopic.php?p=111920#p111920
https://github.com/uBlockOrigin/uAssets/issues/4288

A: (ally.sh) http://al.ly/f9Q6I

---

easylist/easylist_general_hide.txt

```
https://www.txxx.com/embed/1773400
https://www.hclips.com/embed/965425
```

A: (NSFW) https://www.txxx.com/embed/1773400

---

easylist_adult/adult_specific_hide.txt

```
https://www.hclips.com/videos/video586/
https://www.hclips.com/videos/daredorm-episode-closet-jerker/
```

A: (nsfw) https://www.hclips.com/videos/video586/

---

easylist/easylist_general_block.txt

https://github.com/uBlockOrigin/uAssets/issues/2938#issuecomment-445134813

A: https://uptostream.com/jhv1ll2ac71k

---

easylist/easylist_general_block.txt

https://github.com/uBlockOrigin/uAssets/issues/4263

A: http://short.es/XxKIe

---

easyprivacy/easyprivacy_general.txt

```
igns/pqs57650d315/track-opening/82btfpf58y3t5d" alt=3D"" />
```

A: (opened email tracker) http://track-server-100.com/

---

easyprivacy/easyprivacy_trackingservers.txt

* https://i.imgur.com/a8Pc5LI.png
```
https://hfagfcbadgjhdchaaej.ru./0801144000271313.js
https://hcadfghcafccdaejaeh.ru./0801144000183272.js
https://hfbcbhbahdbgiaeiaej.ru./0001838011440272.js
```

M: Added "ru" TLD

---

fanboy-addon/fanboy_social_general_hide.txt

https://imgur.com/ttgcQvCl.png

A: https://www.hotukdeals.com/deals/m-3151225

---

easylist/easylist_general_block.txt

```
https://gdriveplayer.us/embed.php?hash=M9py4pEiYovoLppgZU4Lhwa+JY1tA6VWLoEBs2sjDKrKzdLxgRWCyntKjlQk7Ashs2Wr9nQ7EdgvK4qttnC3hjOaUkmJI98Xu0qZIXHS0R0fageq80RcTKPw6b8nSBBHPmAUx92oVt6hyHtQDu1RRkQxiUPsXn+ZLZCMdrJvPqEQcrr9TKMo50KVtNpCQ6eWcY5VZYEvChqrktgb1ApoQBZMtI7/OOXcE+/YhgXoYeVDgA3lZTttTjaEWvE/Qf/KjqbHXvazKHM2vfZUiK82nxNw+5iWEOGkbg+E8BTyGFXkNfRRfbTW6kjaoYCrQ6TdXTfuz1p5Rdg6pThiNiASbCW9KXRLBc0VPdHJlIyNgxNzun2boiNF1Qvr8q7BFmWQhrX6JfeJmVGeAEeVZY9/I5TQDPru9f31WNxM8VGiIuhbllh6aXOffMrVm5D0yo6YI=
```
```
https://gdriveplayer.us/ads.xml?v=newadsdas
```
https://pastebin.com/raw/N6fEhKu3

A: https://gdriveplayer.us/embed.php?hash=*

---

easylist/easylist_specific_block.txt
easylist/easylist_specific_hide.txt

Found in URL: https://www.iimjobs.com/c/it--systems-jobs-15.html

A:iimjobs.com

---

easylist/easylist_specific_block.txt
easylist/easylist_specific_hide.txt

Found in URL: http://www.amulyam.in/shop-and-earn

A:amulyam.in

---

easylist/easylist_specific_block.txt
easylist/easylist_specific_hide.txt

Found in URL: https://musicpleer.la/
Found in URL: https://musicpleer.la/#!2162c9d64d7a5dc78128463482a32e16

A:musicpleer.la

---

easylist/easylist_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=62&t=37883
https://github.com/uBlockOrigin/uAssets/issues/4452

A: https://www.torrentfunk.com/

---

easylist_adult/adult_specific_block.txt

https://github.com/uBlockOrigin/uAssets/issues/4433

A: (NSFW) mrskin.com

---

easylist/easylist_thirdparty.txt

A: https://www.dailymotion.com/embed/video/x58kk9x

---

fanboy-addon/fanboy_cookie_specific_hide.txt

https://i.imgur.com/GvVenzw.png

A: http://www.fixedbyvonnie.com/

---

easylist/easylist_specific_block.txt

https://forums.lanik.us/viewtopic.php?f=62&t=38211

A: http://adbull.cc/3pg4

---

easylist_adult/adult_specific_block_popup.txt

https://github.com/uBlockOrigin/uAssets/issues/4354

A: (NSFW) fashionyip.info

---

easyprivacy/easyprivacy_thirdparty.txt

```
https://id.verticalhealth.net/script.js?partnerid=endo
```

A: https://www.endocrineweb.com/

---

easylist/easylist_specific_block.txt

```
https://www.gamezhero.com/promo
```

A: https://www.gamezhero.com/games/seaboom

---

easylist/easylist_specific_block.txt

```
https://multiup.eu/en/mirror/f4bec00400edc4e4711b4254fdeb94b1/Black_Panther__2018__Hindi_Dubbed_HDTS_720p_900MB_MovieMAD.mkv
```

M: Update domain (multiup.eu)

---

easylist_adult/adult_thirdparty.txt

https://forums.lanik.us/viewtopic.php?f=62&t=42220

A: (NSFW) https://www.spankwire.com/

---

fanboy-addon/fanboy_social_whitelist_general_hide.txt

https://i.imgur.com/JKeLMLt.png
https://forums.lanik.us/viewtopic.php?f=64&t=42218

P: https://www.iherb.com/pr/A/73050

---

easylist/easylist_specific_block.txt

https://forums.lanik.us/viewtopic.php?f=62&t=42150

A: https://prostylex.com/

---

easylist/easylist_specific_block.txt

https://forums.lanik.us/viewtopic.php?f=96&t=42132

A: http://serietvsubita.me/

---

easylist/easylist_whitelist_popup.txt

https://i.imgur.com/1wdg2Gb.png

A: https://sendvid.com/

---

easylist/easylist_whitelist.txt

https://forums.lanik.us/viewtopic.php?f=64&t=42422

P: https://www.investopedia.com/terms/r/returnoninvestment.asp

---

fanboy-addon/fanboy_cookie_general_block.txt

```
https://fr.trustpilot.com/cookiebar
```

A: https://fr.trustpilot.com/

---

easyprivacy/easyprivacy_whitelist.txt

https://forums.lanik.us/viewtopic.php?f=64&t=42421

P: https://www.mundodeportivo.com/mundoplay

---

fanboy-addon/fanboy_social_general_block.txt

```
https://www.definitions-marketing.com/wp-content/themes/yoo_nano3_wp/warp/js/social.js
http://www.christchurchvets.com/templates/yoo_avion/warp/js/social.js
https://flejando.com/templates/yoo_aurora/warp/js/social.js
http://3con14.biz/js/templates/yoo_aurora/warp/js/social.js
https://www.neulandpartner.de/templates/yoo_everest/warp/js/social.js
https://www.jacktrout.com/templates/yoo_frequency/warp/js/social.js
http://www.hotelatlantic.com/templates/yoo_vida/warp/js/social.js
```

A: https://www.definitions-marketing.com/

---

easyprivacy/easyprivacy_general.txt

```
<FONT SIZE=3D"1" COLOR=3D"#EEEEEE" ><BR/>{~AO953633912091060414344308863223=
19~}</FONT><IMG SRC=3D"http://response.pure360.com/_act/tracking.php?type=
=3Demail&id=3DA6488632O9536854736543033912092319&subjId=3D320648"  BORDER=
=3D"0" HEIGHT=3D"1" WIDTH=3D"1"  />
```

A: (opened email tracker) https://www.pure360.com/

---

fanboy-addon/fanboy_social_general_hide.txt

https://i.imgur.com/DnUHnSU.png
https://i.imgur.com/WwsvE4A.png
https://pastebin.com/raw/p7e9rAhV

A: https://www.hellosign.com/

---

easylist/easylist_adservers.txt

M: Update Tag adservers

---

easyprivacy/easyprivacy_specific.txt

https://forums.lanik.us/viewtopic.php?f=62&t=42399

A: http://www.topix.com/

---

easyprivacy/easyprivacy_trackingservers.txt

https://github.com/easylist/easylist/pull/2559

A: http://url4btc.com/VRhOCY

---

fanboy-addon/fanboy_annoyance_general_block.txt

`http://cdn.pushnews.eu/push/ilabspush.js`

A: http://www.wemystic.fr/

---

fanboy-addon/fanboy_annoyance_whitelist.txt

https://imgur.com/96DrV4Al.png
https://forums.lanik.us/viewtopic.php?f=64&t=42475

P: https://novyny.org/

---

easylist/easylist_general_block.txt

https://forums.lanik.us/viewtopic.php?f=64&t=42464

P: https://admedia.net.au/

---

fanboy-addon/fanboy_annoyance_whitelist_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=64&t=42506

P: https://spb.tele2.ru/

---

easylist/easylist_general_block.txt

https://forums.lanik.us/viewtopic.php?f=64&t=42518
https://forums.lanik.us/viewtopic.php?f=64&t=38072

P: https://adpop.io/

---

easylist/easylist_specific_block.txt

https://forums.lanik.us/viewtopic.php?p=145167#p145167

P: (tamilrockerss.ch) 6d56845

---

fanboy-addon/fanboy_annoyance_whitelist_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=64&t=42533

P: https://letyshops.com/

---

fanboy-addon/fanboy_social_whitelist.txt

https://forums.lanik.us/viewtopic.php?f=64&t=42531

P: https://angvremya.ru/

---

easylist/easylist_adservers_popup.txt

https://imgur.com/YbL5ryvl.png

A: https://torrentz2eu.icu/

---

easylist/easylist_thirdparty.txt

https://forums.lanik.us/viewtopic.php?f=62&t=40573

A: https://www.2giga.link/

---

fanboy-addon/fanboy_cookie_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=103&t=42528

A: https://www.minube.com/

---

easylist/easylist_adservers_popup.txt

https://forums.lanik.us/viewtopic.php?f=62&t=42522

A: https://mysembed.net/0kdne6qincr0

---

easylist_adult/adult_thirdparty.txt

A: (NSFW) imgcloud.pw/image/G30kW9

---

fanboy-addon/fanboy_annoyance_specific_hide.txt

https://imgur.com/f90yGvxl.png

A: https://duckduckgo.com/

---

fanboy-addon/fanboy_annoyance_specific_hide.txt

https://i.imgur.com/jkWbe3U.png

A: https://www.startpage.com/

---

easylist/easylist_specific_block.txt

https://forums.lanik.us/viewtopic.php?f=62&t=42499

A: https://www.talkmagic.co.uk/forum1.php

---

easylist/easylist_specific_block.txt

https://forums.lanik.us/viewtopic.php?f=62&t=42499

A: https://www.themagiccafe.com/forums/

---

easylist_adult/adult_thirdparty.txt

https://forums.lanik.us/viewtopic.php?p=144996#p144996

A: (NSFW) gamcore.com

---

easylist/easylist_specific_hide.txt

https://forums.lanik.us/viewtopic.php?p=144873#p144873
https://i.imgur.com/kUAT9zg.png

A: https://www.yelp.com/search?find_desc=pizza&find_loc=New+York%2C+NY&ns=1

---

easyprivacy/easyprivacy_general.txt

```
https://www.welt.de/assets/resources/webtrekk/webtrekk-welt-v1.0.2-with-media-kameleoon.min.js
```

A: https://www.welt.de/

---

easyprivacy/easyprivacy_general.txt

https://imgur.com/ydvgq1Jl.png

A: https://www.animeyt.tv/

---

easylist_adult/adult_specific_block.txt

A: (NSFW) sexgalaxy.net

---

easylist/easylist_specific_hide.txt

fake video player and streaming links

A: https://www.sofascore.com/neman-grodno-belarus-u20/vHzsrcG

---

easyprivacy/easyprivacy_trackingservers.txt

https://github.com/uBlockOrigin/uAssets/issues/4649

A: https://amplitude.com/blog

---

fanboy-addon/fanboy_annoyance_general_block.txt

```
https://mwpaste.com/ir#zrtnjnerm!anFHUDd2OWJOZzRJeWpoRzhiNGMvQlhsa0g1NDVGOFdaS3duNGN4Z2tIK3lGdVZxcEpmS0w1Z0VRa1QrR0NzVg==
```

A: https://mwpaste.com/

---

easylist/easylist_adservers.txt

https://forums.lanik.us/viewtopic.php?f=62&t=42459

A: https://linkfay.com/ChJZ

---

easylist/easylist_adservers.txt

https://forums.lanik.us/viewtopic.php?f=62&t=41109

A: http://www.uploadbank.com/919unn0ryzpb

---

easylist/easylist_general_block.txt

https://forums.lanik.us/viewtopic.php?f=64&t=42031

P: https://advision.cl/

---

easylist/easylist_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=62&t=41958

A: https://sentry.mba/

---

easylist/easylist_specific_hide.txt

https://forums.lanik.us/viewtopic.php?f=62&t=41532
[uAssets#3717](https://git.io/fxz1q)

A: https://upload4earn.org/tdkzcz1liyhi

---

easylist/easylist_adservers.txt

M: Fix typo in 51f5a47

---

easylist/easylist_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=62&t=42554

A: https://weightweenies.starbike.com/forum/

---

easylist/easylist_whitelist.txt

https://forums.lanik.us/viewtopic.php?f=64&t=42552

P: https://www.insideedition.com/videos

---

easyprivacy/easyprivacy_general.txt

https://vgy.me/DiTdaZ.png
https://vgy.me/F0csvI.png

A: http://c.orange.fr/Errors/erreur404.html

---

easyprivacy/easyprivacy_general.txt

A: https://mail02.orange.fr/appsuite/

---

easylist_adult/adult_specific_block.txt

https://forums.lanik.us/viewtopic.php?f=64&t=42474

P: (NSFW - spankwire.com) Update 355e88ab6

---

fanboy-addon/fanboy_annoyance_specific_hide.txt

A: https://convertio.co/video-converter/

---

easylist/easylist_general_block.txt

https://vgy.me/JEpEOP.png
`http://nowdownload.to/glp?r=&u=http%3A%2F%2Fnowdownload.to%2F&rw=1440&rh=900&ww=1440&wh=336`
https://vgy.me/0UbtxH.png
`http://nowvideo.ag/glp?r=&u=http%3A%2F%2Fnowvideo.ag%2F&rw=800&rh=600&ww=800&wh=256`

M: Update 36b2e71d949

---

easylist/easylist_general_block_popup.txt

Export image popup blocked https://vgy.me/sr5EjN.png

P: http://www.clker.com/inc/svgedit/svg-editor.html

---

fanboy-addon/fanboy_annoyance_international.txt

A: https://www.voelkner.de/

---

fanboy-addon/fanboy_annoyance_specific_hide.txt

hide newsletter signup on first visit

A: https://matomo.org/

---

fanboy-addon/fanboy_cookie_general_hide.txt

Hides cookie banner on multiple websites, examples:
https://shop.mea-bausysteme.com/de/
https://thomkit.de/startseite
mycookietip info
https://contao.org/de/erweiterungsliste/view/mycookietip.30000029.de.html

A: (hide mycookietip) https://shop.mea-bausysteme.com/de/

---

fanboy-addon/fanboy_social_whitelist.txt

```
It seems that something is broken or temporarily unavailable.
```
https://vgy.me/MMV3NK.png
https://forums.lanik.us/viewtopic.php?f=64&t=42650

P: https://vpobede.ru/

---

easylist/easylist_general_block.txt

https://forums.lanik.us/viewtopic.php?f=64&t=42690

P: http://adboost.se/

---

easylist/easylist_specific_block.txt

```
https://hqq.tv/js/betterj/license.hqq.tv.js?
https://c.hqq.tv/js/betterj/license.hqq.tv.js?
```

A: https://hqq.tv/player/embed_player.php?vid=WVlUN3hFaGM0SGpmUWcreDJ2T2l2QT09

---

easylist/easylist_specific_block.txt

https://forums.lanik.us/viewtopic.php?f=62&t=42732

A: https://streamvid.co/player/5ZR36ZKI3AvgI5I/

---

easyprivacy/easyprivacy_general.txt

`https://torrentrapid.com/tr/library/content/template/js/_Crstatistics.js?`

A: https://torrentrapid.com/

---

easyprivacy/easyprivacy_trackingservers.txt

M: Removed ppoi.org & projectpoi.com (parked)

---

easylist/easylist_specific_block.txt

https://github.com/abp-filters/abp-filters-anti-cv/issues/86
https://github.com/abp-filters/abp-filters-anti-cv/issues/106

M: Removed obsolete unnecessary openload filters

---

easylist/easylist_general_block.txt

https://forums.lanik.us/viewtopic.php?f=64&t=42743

P: https://housead.ru/

---

easylist/easylist_general_block.txt

examples
https://vgy.me/TM0lQZ.png
https://vgy.me/u7RVhJ.png

M: Update generic filter

---

easylist/easylist_adservers.txt

https://github.com/easylist/easylist/pull/3032

A: (ffmovies.ru) Update adservers

---

easylist/easylist_thirdparty_popup.txt

How to reproduce ==> https://github.com/easylist/easylist/pull/3047#issuecomment-472720392

A: https://cloudvideo.tv/t0pjubv9pl91

---

fanboy-addon/fanboy_annoyance_whitelist.txt

https://forums.lanik.us/viewtopic.php?p=145861#p145861

P: https://ok.ru/

---

easylist/easylist_specific_hide.txt

https://forums.lanik.us/viewtopic.php?f=62&t=38238

A: https://www.allkeyshop.com/blog/

---

easylist/easylist_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=64&t=42714
https://forums.lanik.us/viewtopic.php?p=146135#p146135

P: https://fainaidea.com/

---

easyprivacy/easyprivacy_general.txt

`https://www.gazeta.ru/nm2015/js/noindex/add_utm_links.js`

A: https://www.gazeta.ru/

---

fanboy-addon/fanboy_annoyance_whitelist_general_hide.txt

https://forums.lanik.us/viewtopic.php?p=143626#p143626

P: https://www.nasa.gov/mission_pages/LRO/multimedia/lroimages/lroc-20110906-skimming.html

---

easylist/easylist_general_block.txt

https://forums.lanik.us/viewtopic.php?f=64&t=42753

P: https://ads.safi-gmbh.ch/

---

easylist/easylist_general_block.txt

https://forums.lanik.us/viewtopic.php?p=145934#p145934

P: (Update fcaa85fe) advertising.amazon.ae & advertising.amazon.sa

---

easylist/easylist_whitelist_popup.txt

fix typo in https://github.com/easylist/easylist/commit/31b6329e71b343a70c4596d5c3
@monzta

M: Fix typo in ca92675

---

easyprivacy/easyprivacy_general.txt

https://github.com/uBlockOrigin/uAssets/issues/4039#issuecomment-475429431

A: https://www.ncaa.com/

---

easyprivacy/easyprivacy_thirdparty.txt

```
=09<img src=3D"https://news.banggood.com/mo/G33OdyILVa_147625543_4715475_12=
85746_1825418.gif" height=3D"2" width=3D"2" border=3D"0"></body>
</html><img src=3D"http://news.banggood.com/mo/G33OdyILVa_147625543_4715475_12=
_85746_1825418.gif" height=3D"2" width=3D"2" border=3D"0"></body></html>
----=_---NextPart--=_-ZFspRsjKY--
```

A: (opened email tracker) https://www.banggood.com/

---

easylist/easylist_general_block.txt

https://forums.lanik.us/viewtopic.php?f=64&t=42773

P: https://advertiser.vungle.com/

---

fanboy-addon/fanboy_social_whitelist.txt

https://forums.lanik.us/viewtopic.php?f=64&t=42781

P: https://tgstat.ru/channel/@dvachannel

---

easylist/easylist_specific_block.txt

https://forums.lanik.us/viewtopic.php?f=62&t=42666

A: (convert2mp3.net) #3136

---

easylist/easylist_specific_block.txt

add a link when copy/past texte

A: https://chine.in/guide/top-des-noms-familles_4242.html

---

easylist/easylist_adservers.txt

https://github.com/abp-filters/abp-filters-anti-cv/issues/72

A: http://convert2mp3.net/

---

easyprivacy/easyprivacy_general.txt

https://forums.lanik.us/viewtopic.php?f=62&t=42802
https://forums.lanik.us/viewtopic.php?f=62&t=36550#p117329

A: https://www.preciosclaros.gob.ar/

---

easylist/easylist_general_hide.txt

A: http://sendvid.com/embed/9j3kuwn7

---

easylist/easylist_whitelist.txt

Removed
```
hqq.tv
go4up.com
sizedrive.com
```

M: Removed unnecessary obsolete rules

---

fanboy-addon/fanboy_annoyance_specific_hide.txt

https://i.imgur.com/ZA0YPEK.png

A: https://addons.opera.com/en/extensions/details/adblock-plus/

---

easyprivacy/easyprivacy_trackingservers.txt

* [i.vgy.me/azWjuA.png](https://i.vgy.me/azWjuA.png)
* `docs.aws.amazon.com/ses/latest/DeveloperGuide/configure-custom-open-click-domains.html`

A: (aws.amazon.com) opened email tracker

---

fanboy-addon/fanboy_social_general_hide.txt

A: https://www.aliexpress.com/

---

easylist/easylist_general_block.txt

https://forums.lanik.us/viewtopic.php?f=64&t=42860

P: https://adv.bet/

---

easyprivacy/easyprivacy_specific.txt

Add analytics.zg-api.com

---

easylist/easylist_specific_block.txt

revolving adservers
```
||arana.pw^
||beiren.xyz^
||daecan.xyz^
||daethana.pw^
||elabalar.pw^
||elmenor.xyz^
||farpeiros.pw^
||galiowen.com^
||galumbor.com^
||gilzana.pw^
||glynzumin.pw^
||grebanise.pw^
||ianhice.pw^
||ianxalim.pw^
||iarvyre.pw^
||ilinan.xyz^
||inaharice.pw^
||inastina.pw^
||keaven.pw^
||kelris.pw^
||liacyne.pw^
||miakalyn.pw^
||miastina.pw^
||miracan.pw^
||naetoris.pw^
||nornelis.pw^
||ololen.pw^
||omaceran.pw^
||omafaren.pw^
||omaris.pw^
||perkas.pw^
||ralozorwyn.pw^
||sarjor.pw^
||thefaren.pw^
||thenelis.pw^
||urifiel.pw^
||valkrana.xyz^
||wysara.pw^
||yinmyar.xyz^
||yllanala.pw^
||yllasatra.xyz^
||zinlar.pw^
||zumhice.pw^
```

A: https://uploadfiles.pw/0eda361024c19dec

---

easyprivacy/easyprivacy_trackingservers_international.txt

https://forums.lanik.us/viewtopic.php?f=90&t=42841

A: https://www.luzernerzeitung.ch/

---

easylist/easylist_specific_hide.txt

https://i.imgur.com/5h4ZHJ6.png

A: https://www.youtube.com/watch?v=XBXfL2AlOtg

---

easylist_adult/adult_adservers.txt

Update https://github.com/easylist/easylist/commit/0fcc61b125bda059e4909413483e3cc44df306ff

A: (nsfw) boundhub.com

---

easyprivacy/easyprivacy_general.txt

https://forums.lanik.us/viewtopic.php?p=146979#p146979

A: https://weather.com/

---

easylist/easylist_specific_block.txt

https://forums.lanik.us/viewtopic.php?p=147029#p147029

A: https://www.naturalnews.com/

---

fanboy-addon/fanboy_annoyance_whitelist.txt

P: http://url.hulblog.com/ZHyuY

---

easylist/easylist_general_block.txt

https://forums.lanik.us/viewtopic.php?f=64&t=42930

P: https://www.openad.lv/

---

fanboy-addon/fanboy_annoyance_whitelist_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=64&t=42929

P: https://ap.www.namecheap.com/

---

easylist/easylist_adservers.txt

https://forums.lanik.us/viewtopic.php?f=62&t=42932

A: https://megaurl.in/InMJaE3

---

easylist/easylist_specific_block.txt

https://forums.lanik.us/viewtopic.php?p=147177#p147177

A: kat2.biz & kickass2.biz

---

easyprivacy/easyprivacy_specific.txt

https://forums.lanik.us/viewtopic.php?p=147121#p147121

A: https://www.arte.tv/en/videos/074567-005-A/i-have-a-dream/

---

easylist/easylist_specific_block.txt

https://forums.lanik.us/viewtopic.php?f=64&t=42876

A: https://ibit.to/

---

fanboy-addon/fanboy_annoyance_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=64&t=42927

P: https://www.askona.ru/landing/kiber-lending/

---

easylist/easylist_specific_block.txt

https://forums.lanik.us/viewtopic.php?f=64&t=42890

P: https://9anime.to/schedule & https://9anime.vip/schedule

---

fanboy-addon/fanboy_annoyance_whitelist.txt

https://forums.lanik.us/viewtopic.php?f=64&t=42870

P: https://www.x-plane.com/

---

easylist/easylist_adservers.txt

https://pastebin.com/raw/AdSxcYvA
https://forums.lanik.us/viewtopic.php?f=62&t=42990

A: https://unlockapk.com/

---

easylist/easylist_adservers.txt

https://github.com/easylist/easylist/commit/b3281fdd18ac7bd611be60173d82f642328868c2

M: Removed exception for debrideurstream.fr

---

fanboy-addon/fanboy_social_whitelist.txt

https://forums.lanik.us/viewtopic.php?f=64&t=42987

P: https://geocaching.su/map/

---

easylist/easylist_specific_hide.txt

https://forums.lanik.us/viewtopic.php?p=147383#p147383

A: (yelp.com) Update 46c04adcf

---

easyprivacy/easyprivacy_general.txt

https://imgur.com/QMIpd5D.png
https://github.com/easylist/easylist/pull/3381

A: http://alsayeda.net/

---

easylist/easylist_general_hide.txt

A: https://www.tele5.de/

---

easylist/easylist_general_block.txt

https://forums.lanik.us/viewtopic.php?f=64&t=42986

P: https://adworks.jobijoba.io/

---

fanboy-addon/fanboy_annoyance_whitelist.txt

https://forums.lanik.us/viewtopic.php?f=64&t=42999

P: https://moto-store.com.ua/ua/moto/

---

easylist/easylist_specific_block.txt

https://forums.lanik.us/viewtopic.php?p=147492#p147492

P: https://www.cheezburger.com/

---

easylist/easylist_adservers.txt

https://github.com/easylist/easylist/pull/2940

M: Added "runative.com" adservers

---

easyprivacy/easyprivacy_specific_international.txt

https://forums.lanik.us/viewtopic.php?f=62&t=42943

A: https://ok.ru/video/1086122953387

---

easyprivacy/easyprivacy_thirdparty_international.txt

```
lesnumeriques.com
gamekult.com
zdnet.fr
beaute-test.com
cnetfrance.fr
...
```

A: https://www.lesnumeriques.com/

---

easylist/easylist_specific_hide.txt

https://forums.lanik.us/viewtopic.php?p=147254#p147254

A: https://torrentz2.eu/ & torrentz2.is

---

easylist/easylist_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=62&t=42950

A: https://worldfiile.biz/4723-2/

---

easylist/easylist_specific_block.txt

https://forums.lanik.us/viewtopic.php?p=147549#p147549

P: https://ffmovies.ru/search?keyword=300

---

easyprivacy/easyprivacy_general.txt

Google Analytics script
```
https://gledajonline.net/assets2/js/gootics.js
https://loadsubs.net/layout/gootics.js
```
https://github.com/easylist/easylist/pull/3254

A: https://gledajonline.net/

---

easylist_adult/adult_thirdparty.txt

```
http://static.twincdn.com/special/script.packed.js
http://static.twincdn.com/special/license.packed.js
https://static.twincdn.com/special/script.packed_new.js
https://static.twincdn.com/special/license.packed_new.js
```

A: (nsfw) nurlesben.com

---

easylist/easylist_specific_block.txt

https://github.com/abp-filters/abp-filters-anti-cv/issues/167

A: https://upload4earn.org/o5f376e4l5h9 & https://uploadbyte.com/o5f376e4l5h9

---

easylist/easylist_thirdparty_popup.txt

examples popup scripts
```
http://000webhodtapp.com/test.js
http://00237.com/easylist.js
http://001micro.com/easyprivacy.js
```
example of parked domains
* https://raw.githubusercontent.com/Ultimate-Hosts-Blacklist/smed79_parkingcrew.com/master/domains.list

M: Update for "parkingcrew.net" parked domains

---

easylist/easylist_general_block.txt

https://forums.lanik.us/viewtopic.php?f=64&t=43045

P: https://ads.yahoosmallbusiness.com/

---

easyprivacy/easyprivacy_whitelist.txt

Whitelist already fixes the admin panel, but network panel is blocked

Fix network panel for GADWP plugin

---

easylist/easylist_specific_block.txt

```
http://elixx.me/amilan.html
http://wenger.stream/ws/milan.php
```

A: http://wenger.stream/ws/milan.php

---

easyprivacy/easyprivacy_trackingservers.txt

https://forums.lanik.us/viewtopic.php?f=62&t=42849

A: https://nationalfamily.com/

---

easyprivacy/easyprivacy_specific.txt

https://forums.lanik.us/viewtopic.php?f=62&t=43061

A: https://socialblade.com/

---

easylist/easylist_adservers_popup.txt

A: http://arembed.com/live.php?ch=Bein_Sports1

---

easylist_adult/adult_thirdparty.txt

A: (nsfw) mrpornx.com

---

easylist/easylist_general_block.txt

https://forums.lanik.us/viewtopic.php?f=64&t=43056

P: https://adboost.fr/

---

fanboy-addon/fanboy_social_whitelist_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=64&t=43051

P: https://hotline.ua/login/

---

easylist/easylist_thirdparty.txt

https://imgur.com/gB95QE0.png
```
https://logo.tmearn.com/img1.png
https://logo.tmearn.com/img2.png
```

A: https://windowssof.weebly.com/blog

---

easyprivacy/easyprivacy_whitelist.txt

https://forums.lanik.us/viewtopic.php?f=103&t=43064

P: https://www.fcbarcelona.com/en/videos/1224969/

---

easyprivacy/easyprivacy_whitelist.txt

https://forums.lanik.us/viewtopic.php?p=145969#p145969

P: https://boxberry.ru/tracking/

---

fanboy-addon/fanboy_social_whitelist.txt

`https://s.trackingmore.com/??bootstrap/bootstrap.css,bootstrap/carriers.css,list/single.css,list/style.css,list/track-box.css,list/results.min.css,assets/css/notify.css,list/basepage_new.css,list/needsharebutton.min.css,list/relate.css,font-awesome-4.4.0/css/font-awesome.min.css?time=*`
`https://s.trackingmore.com/??bootstrap/jquery-2.1.1.min.js,bootstrap/bootstrap.min.js,list/jquery.js,list/lang_fr.js,list/express-rulers.js,list/trackRuler.js,list/commontool_changecountry.js,list/needsharebutton.js,list/clipboard.js,admin/js/langCookie.js,public.js?time=*`

P: https://www.trackingmore.com/

---

fanboy-addon/fanboy_annoyance_general_hide.txt

A: https://www.clubic.com/navigateur-internet-mobile/actualite-857616-tor-browser.html

---

fanboy-addon/fanboy_cookie_general_hide.txt

https://forums.lanik.us/viewtopic.php?p=147830#p147830

P: https://gateway.x-plane.com/register

---

easyprivacy/easyprivacy_specific_international.txt

https://forums.lanik.us/viewtopic.php?f=64&t=43072

P: (removed problematic filter) https://ok.ru/

---

easyprivacy/easyprivacy_general.txt

`<img src="https://mailtrack.io/trace/link/e75e97c84abc6f56eec6a2b?signature=40ac882f256a">`
`<img src="https://ci4.googleusercontent.com/proxy/nYHus9QdVGymuqsjBs9A_EHD2Gr8g5loeOtftgPyobnDfg89y62mSHN3NT9eGwO_nYOjAM3UC0Y6wjpp36uTI5djEElPsQVjLaZ_1sQOqn9PXuni4fzFP9WZdFwX92dkhl87NR9_YJyBQJPt=s0-d-e1-ft#https://mailtrack.io/trace/mail/c2573bfa8bb73e742debc407fd1839066611ea38.png?u=1003006">`

A: (mailtrack.io) opened email tracker

---

fanboy-addon/fanboy_social_whitelist_general_hide.txt

https://i.imgur.com/QZiZfuc.png
https://i.imgur.com/tsU84r0.png
https://forums.lanik.us/viewtopic.php?p=148052#p148052

P: https://www.gamepedia.com/

---

easylist/easylist_specific_block.txt

https://forums.lanik.us/viewtopic.php?f=62&t=43109

A: https://masternodes.online/

---

fanboy-addon/fanboy_cookie_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=62&t=43103

A: https://app.bitrise.io/users/sign_in

---

easylist/easylist_adservers.txt

https://forums.lanik.us/viewtopic.php?f=62&t=43117

A: https://www.goodnewsnetwork.org/

---

fanboy-addon/fanboy_social_whitelist.txt

https://forums.lanik.us/viewtopic.php?f=64&t=43125

P: https://oko-planet.su/politik/politikarm/500774-naz.html

---

easylist/easylist_general_hide.txt

https://forums.lanik.us/viewtopic.php?p=147826#p147826

A: https://topeuropix.net/tvs/friends-online/friends-season-4-hd-with-subtitles-europix-s2

---

easyprivacy/easyprivacy_whitelist.txt

- fix typo `,domain=|` https://github.com/easylist/easylist/commit/84575ced38dd719b682b8fb4054cfa7c651bb385#diff-57814f66f7ce561ca9320be995443b1fR38
- fix https://forums.lanik.us/viewtopic.php?f=64&t=43137

P: https://www.malaysiaairlines.com/uk/en.html

---

easyprivacy/easyprivacy_general.txt

`https://usa-m.banggood.com/statistics.html?url=https%3A%2F%2Fusa-m.banggood.com%2F%3FakmClientCountry%3DFR%26`

A: https://usa-m.banggood.com/

---

fanboy-addon/fanboy_annoyance_general_hide.txt

- `https://www.northlineexpress.com/`
- `https://www.united-states-flag.com/`

A: https://www.northlineexpress.com/

---

easylist/easylist_whitelist.txt

https://forums.lanik.us/viewtopic.php?f=64&t=43148

P: (autotrader.co.uk) Update 97d4265

---

fanboy-addon/fanboy_annoyance_whitelist_general_hide.txt

see https://github.com/AdguardTeam/AdguardFilters/issues/33740

P: wiemy.to

---

fanboy-addon/fanboy_annoyance_specific_hide.txt

for details, see https://forums.lanik.us/viewtopic.php?f=62&t=43252

A: https://www.xrel.to/tv/149973/Mr-Robot.html

---

fanboy-addon/fanboy_cookie_whitelist.txt

https://forums.lanik.us/viewtopic.php?f=64&t=43297

P: https://meine.postbank.de/

---

fanboy-addon/fanboy_cookie_specific_hide.txt

https://forums.lanik.us/viewtopic.php?f=62&t=43287

A: https://zh.chregister.ch/

---

fanboy-addon/fanboy_social_whitelist_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=64&t=43257

A: https://www.unian.ua/pogoda/news/10610298-u-210.html

---

easyprivacy/easyprivacy_trackingservers.txt

https://forums.lanik.us/viewtopic.php?f=62&t=43270

A: http://ineuropa.pl/en/

---

easyprivacy/easyprivacy_specific.txt

- `https://hqq.tv/cdn-cgi/trace`
- https://imgur.com/vZ1OrXF.png

A: https://hqq.tv/player/embed_player.php?vid=X5AFsbyA7ChN

---

easyprivacy/easyprivacy_specific.txt

https://forums.lanik.us/viewtopic.php?f=62&t=43266

A: https://oui.sncf/

---

fanboy-addon/fanboy_social_thirdparty.txt

https://forums.lanik.us/viewtopic.php?f=64&t=43261

A: (ugo.ru) https://vk.com/app2729395_54028067

---

fanboy-addon/fanboy_social_whitelist.txt

https://forums.lanik.us/viewtopic.php?f=64&t=43262

P: https://nardgammon.com/

---

easyprivacy/easyprivacy_general.txt

https://forums.lanik.us/viewtopic.php?f=64&t=43259

P: http://smartpixel.com/

---

fanboy-addon/fanboy_social_whitelist_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=64&t=43253

P: https://moikrug.ru/users/sign_in

---

easylist/easylist_general_block.txt

```
https://www.wakanim.tv/fr/v2/video/adsunauth?idepisode=8952
```

A: https://www.wakanim.tv/fr/v2/catalogue/embedded/8952

---

easylist/easylist_adservers.txt

https://github.com/abp-filters/abp-filters-anti-cv/issues/206

A: https://onlystream.tv/trdm4n19m2c0

---

easylist/easylist_adservers.txt

https://forums.lanik.us/viewtopic.php?f=62&t=43171

A: https://www.wowhead.com/

---

easylist_adult/adult_specific_block_popup.txt

https://github.com/abp-filters/abp-filters-anti-cv/issues/208

A: (NSFW) adultvideoz.net

---

easylist/easylist_adservers_popup.txt

webrtc popup `35.194.16.41`
https://forums.lanik.us/viewtopic.php?f=62&t=43237

A: https://www.mkvcage.com/

---

easylist/easylist_whitelist.txt

https://github.com/easylist/easylist/pull/3718

M: (gamecopyworld.com & gamecopyworld.eu) Removed whitelisted ad scripts #3718

---

easyprivacy/easyprivacy_specific_international.txt

A: https://www.coches.net/ & https://www.vibbo.com/

---

fanboy-addon/fanboy_cookie_international_specific_block.txt

A: https://www.capital.fr/

---

easylist/easylist_specific_block.txt
easylist/easylist_specific_hide.txt

A: https://www.spongepowered.org/downloads/spongevanilla/stable/1.12.2

---

easylist/easylist_specific_hide.txt

https://forums.lanik.us/viewtopic.php?p=149136#p149136

A: https://www.bing.com/news

---

easyprivacy/easyprivacy_specific.txt

https://forums.lanik.us/viewtopic.php?f=62&t=43371

A: https://www.gmx.net/

---

easylist/easylist_thirdparty.txt

P: nutaku.net #3918

---

fanboy-addon/fanboy_social_whitelist_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=64&t=43361

P: https://galaxydata.ru/community/convert-qcow2-to-raw-1195

---

fanboy-addon/fanboy_social_whitelist_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=64&t=43363

P: https://velodaily.ru/summary-for-russia/

---

easylist/easylist_specific_block.txt

[uAssets#452 (comment)](https://github.com/uBlockOrigin/uAssets/issues/452#issuecomment-519665780)

A: https://www.zdnet.com/

---

fanboy-addon/fanboy_annoyance_specific_hide.txt

A: (vibbo.com) #3903

---

easyprivacy/easyprivacy_general.txt

`https://www.france.tv/kameleoon/kameleoon-iframe.html`

A: https://www.france.tv/

---

fanboy-addon/fanboy_cookie_general_block.txt

https://forums.lanik.us/viewtopic.php?f=62&t=43343

A: https://www.migros.ch/

---

easylist/easylist_adservers.txt

NSFW `https://gfycat.com/frailsorekissingbug-snsd-yuri-nsfw`

A: (gfycat.com) https://forums.lanik.us/viewtopic.php?f=62&t=43473

---

easyprivacy/easyprivacy_specific.txt

https://forums.lanik.us/viewtopic.php?f=62&t=43477

A: https://www.onthemarket.com/details/7531341/

---

easylist/easylist_adservers_popup.txt

https://forums.lanik.us/viewtopic.php?f=62&t=43483

A: http://backin.net/mep9m6goo14c

---

fanboy-addon/fanboy_social_whitelist.txt

https://forums.lanik.us/viewtopic.php?f=64&t=43490

P: (id.logi.com) https://support.logi.com/hc/en-us/ => SIGN IN

---

easylist/easylist_specific_block_popup.txt

`http://of.downpit.com/code.php`

A: http://downpit.com/

---

easylist_adult/adult_specific_hide.txt

https://github.com/abp-filters/abp-filters-anti-cv/pull/257

A: (NSFW) xhamster.com

---

easyprivacy/easyprivacy_general.txt

```
https://s.ssl.qhimg.com/static/f5407c785655e6a1/monitor_analytic.js
https://s.ssl.qhimg.com/static/f5407c785655e6a1/monitor_analytic.min.js
```

A: https://www.360.cn/

---

fanboy-addon/fanboy_annoyance_whitelist.txt

https://forums.lanik.us/viewtopic.php?f=64&t=43192

A: https://www.windy.com/

---

easyprivacy/easyprivacy_trackingservers.txt

`https://get.geojs.io/v1/ip/geo.js`

A: https://www.pirateproxy.space/

---

easyprivacy/easyprivacy_specific.txt

Snapchat pixel loads this for shopify stores - https://intg.snapchat.com/shopify/shopify-scevent.js

Add intg.snapchat.com

---

fanboy-addon/fanboy_social_whitelist.txt

https://forums.lanik.us/viewtopic.php?p=149064#p149064

P: https://jut.su/jojo-bizarre-adventure/season-2/episode-7.html

---

easylist/easylist_adservers.txt

https://forums.lanik.us/viewtopic.php?f=62&p=149036

A: https://www.my5.tv/traffic-cops/season-7/episode-2

---

easylist/easylist_specific_hide.txt

https://forums.lanik.us/viewtopic.php?f=103&t=43334

A: https://en.yaencontre.com/sale/houses/cartagena

---

easylist/easylist_specific_block.txt

https://forums.lanik.us/viewtopic.php?f=62&t=43339

A: http://gamovideo.com/ivzm554ny92e

---

easylist/easylist_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=103&t=43335

https://wallapop.com/search?kws=pes

---

fanboy-addon/fanboy_annoyance_whitelist_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=64&t=43609

P: https://passeport-numerique.wecollect.ch/#subscribe

---

fanboy-addon/fanboy_cookie_specific_hide.txt

A: https://myanimelist.net/

---

fanboy-addon/fanboy_social_specific_hide.txt

https://forums.lanik.us/viewtopic.php?f=64&t=43433

A: https://www.schufa.de/en/

---

easylist/easylist_whitelist.txt

https://github.com/easylist/easylist/pull/2775

M: Edit dailymotion.com whitelist filter

---

easylist/easylist_specific_block.txt

https://forums.lanik.us/viewtopic.php?p=149759#p149759

A: https://ore.spongepowered.org/ & https://ore.stage.spongemc.org/

---

easyprivacy/easyprivacy_thirdparty_international.txt

https://forums.lanik.us/viewtopic.php?f=90&t=43530

A: https://www.abendzeitung-muenchen.de/

---

easylist/easylist_general_block.txt

https://forums.lanik.us/viewtopic.php?f=64&t=43620

P: http://advert.media/

---

easylist/easylist_specific_block.txt

https://forums.lanik.us/viewtopic.php?f=62&t=43504

A: https://high-minded.net/

---

easylist/easylist_specific_block.txt

https://github.com/abp-filters/abp-filters-anti-cv/issues/231

A: https://thevideobee.to/embed-ujrqoejsmatb.html

---

easylist/easylist_whitelist_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=64&t=43317

P: https://www.marca.com/en/stats/football/laliga/fixture.html

---

fanboy-addon/fanboy_annoyance_specific_hide.txt

https://forums.lanik.us/viewtopic.php?f=62&t=43312

A: https://www.poolsupplies.com/shop/toys-games

---

easyprivacy/easyprivacy_thirdparty_international.txt

https://forums.lanik.us/viewtopic.php?f=91&t=43309

P: https://www.newebregie.fr/

---

fanboy-addon/fanboy_cookie_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=64&t=43307

A: https://www.mouser.co.uk/

---

easylist/easylist_specific_block.txt

https://forums.lanik.us/viewtopic.php?f=64&t=43180

P: https://readcomiconline.to/

---

easylist/easylist_whitelist.txt

https://forums.lanik.us/viewtopic.php?p=149943#p149943

P: https://kissmanga.com/Manga/Blame/Vol-010-Ch-060-Read-Online?id=97381

---

easylist/easylist_specific_block.txt

https://forums.lanik.us/viewtopic.php?f=64&t=43179

M: https://kimcartoon.to/

---

easyprivacy/easyprivacy_trackingservers.txt

https://forums.lanik.us/viewtopic.php?p=148466#p148466

A: (rightmove.co.uk) #3627

---

easyprivacy/easyprivacy_general.txt

https://forums.lanik.us/viewtopic.php?f=62&t=43161

A: https://www.rightmove.co.uk/property-for-sale/property-73050497.html

---

easylist/easylist_general_block.txt

https://forums.lanik.us/viewtopic.php?p=148293#p148293
see also
https://github.com/easylist/easylist/pull/3291
https://github.com/easylist/easylist/pull/3292
https://github.com/easylist/easylist/pull/3649

A: https://www.youtube-nocookie.com/embed/Dx01aFTyzgM

---

fanboy-addon/fanboy_cookie_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=62&t=43207

A: http://www.tabble.de/show.jsp?create=true

---

fanboy-addon/fanboy_annoyance_whitelist_general_hide.txt

https://i.imgur.com/KHMl6vk.jpg
https://forums.lanik.us/viewtopic.php?p=148409#p148409

P: https://mos.ru/my/#/settings/applications

---

easylist/easylist_adservers.txt
easylist/easylist_specific_block.txt
easylist/easylist_specific_hide.txt

https://reports.adblockplus.org/0b3dafea-6814-46c5-95d1-0a5af6619e3b#tab=screenshot

A:songspk.mobi

---

.travis.yml

By adding depth to git clone --depth=n
I have runned the complete script over travis from a fork and this is working.... in my case at least and running time was aroung 40 sec.
https://travis-ci.com/spirillen/easylist

Adding depth to git

---

easyprivacy/easyprivacy_specific.txt

https://forums.lanik.us/viewtopic.php?f=62&t=43162

A: https://www.fs.com/uk/

---

easylist/easylist_general_block.txt

Update filters https://github.com/uBlockOrigin/uAssets/issues/2364#issuecomment-395274400

M: Update filters (/pop.js & /pop2.js)

---

easyprivacy/easyprivacy_general.txt
easyprivacy/easyprivacy_trackingservers.txt

Example site: 
`https://www.lawinfo.com/`
Also, if there is some syntax to naming PRs for this repo, please let me know.

A: https://www.lawinfo.com/

---

easyprivacy/easyprivacy_specific.txt

```
https://fls-na.amazon.com/1/batch/1/OE/
https://fls-eu.amazon.co.uk/1/batch/1/OE/
https://fls-fe.amazon.co.jp/1/batch/1/OE/
https://fls-cn.amazon.cn/1/batch/1/OE/
```

A: https://www.amazon.com/

---

fanboy-addon/fanboy_annoyance_specific_hide.txt

A: https://search.yahoo.com/search?p=jxqhwelrih

---

fanboy-addon/fanboy_cookie_specific_hide.txt

https://forums.lanik.us/viewtopic.php?f=62&t=43659

A: https://www.sanitas.com/

---

easylist_adult/adult_adservers_popup.txt

https://forums.lanik.us/viewtopic.php?f=62&t=43246
https://github.com/abp-filters/abp-filters-anti-cv/issues/281

A: (NSFW) 0xxx.ws

---

fanboy-addon/fanboy_annoyance_whitelist_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=64&t=43698

P: https://www.ixbt.com/news/2019/10/14/xiaomi-miui-joy-ui.html

---

fanboy-addon/fanboy_cookie_whitelist_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=64&t=43717

P: https://aboutcookies.org/

---

easyprivacy/easyprivacy_specific_international.txt

https://forums.lanik.us/viewtopic.php?f=62&t=43702

A: https://wenku.baidu.com/view/7a882fed0975f46527d3e11a.html

---

fanboy-addon/fanboy_cookie_international_specific_hide.txt

https://forums.lanik.us/viewtopic.php?f=62&t=43673

A: https://www.baden-wuerttemberg.de/

---

easyprivacy/easyprivacy_thirdparty.txt

https://forums.lanik.us/viewtopic.php?p=150328#p150328

A: (Update 47c9de0c) contactatonce.com, contactatonce.co.uk & contactatonce.com.au

---

easylist/easylist_specific_block.txt

https://forums.lanik.us/viewtopic.php?p=149503#p149503

A: https://www.watchcartoononline.io/

---

fanboy-addon/fanboy_social_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=62&t=43662

A: https://www.collegeboard.org/

---

fanboy-addon/fanboy_annoyance_whitelist_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=64&t=43726

P: https://zoom.us/signup

---

easyprivacy/easyprivacy_thirdparty.txt

`https://data.pendo.io/data/ptm.gif/ecf957b6-77d5-4add-5477-5444ea4580e3?v=2.27.0_prod&ct=2615733519366&jzb=lB6hUNqnqqsgkj8TDGdXWScMXbPM-_724GLSBU-Hk6vweneJy1lMFv2jAUxD8YvsF9Jo6v_el4Rv8Vy5ddSGkKtCrHFjZR5ObqYjK8Hcqe9JnSxT7Pjv34S1JTgpzKxOhkKwdy7bDlkR380Xs2W8in-6b9vyK0tdja2MGcj624RPRAXgSyayKbwzOF4uVybdD88ZxPKgaW5geLPfN6j0wIStNRtkcjBYdAOIEKGSvoJkOELvQRG5dvm7PiUo_HQ7ruj4jp7Qksvp-xHuQyo72Wsm0F51ClZwkWQ5aVDXf-e-OyL-J4SKZoAl8EYTnYt8rK58HodioFAJtg6rkUtJWff_mPfz21W0XBxxW5rIsYBSZRB0I7-FOlgjERYnyVxwzjcBex8nIe0hHazb3H_CjQ5xTP9osEPW25m_Z5wcUtnEyj4tlnfy_hI-Yp8DDe9Sb5ezh-Cz3x0-RF-99I2lz3w95Q8rfmt3WPMHe6M8pIJys2gvfdu5xQzVbOVZH9MmLFb86glB8ARKfFiE7cNvyu2ElSdw7xQW_FbsQDTIMTZGZez8URrYkHxq7a0bAp4KL0bjl6dX8SeNug`

A: https://www.trainerroad.com/

---

fanboy-addon/fanboy_cookie_specific_hide.txt

https://forums.lanik.us/viewtopic.php?f=62&t=43731

A: https://www.shab.ch/

---

easylist_adult/adult_adservers.txt

[#3630](https://git.io/fjal4)
https://imgur.com/VDxKIHr.png

A: (nsfw) fembed.com/v/40oxmmy-zy9 #3630

---

easyprivacy/easyprivacy_general.txt

```
vMN1-2F-2F4nrEM-2Bf4Sr4NwY16Oh1K9C7vOFLGxCVhog4dzy-2BndMEQaifhB-2Bi-2FkaNY5=
PFpcLGBTv-2FmDEuIuUJI08dN-2FS8sYoejDcSL38dUxDdBc-2F0pe5uIqFIzUSHQvz0FMlt9KF=
5gGvRcJl-2BI78ju70EPkDmHaZShhpipO5uTStyjbwYWgDi2Q4xwY20e0aOETzEmO9hQn929R-2=
FoD888RLH4rqCNw5FUWwObqjqdN8h3YPtloG4CI2PufdQTT240MoJL0c83Rv9QxkzIws1ghsRei=
Vt4VSEaL06rhXSjLJYZXiXPSaDF2AIL80yYEHVtQwsfIHk35JKYF1N5CzJf7j2znMWKo8A8SPhz=
V5xgH1HVZeQ0sXJW55pNiuMdcrWRGA-3D-3D" alt=3D"" width=3D"1" height=3D"1" bor=
der=3D"0" style=3D"height:1px !important;width:1px !important;border-width:=
0 !important;margin-top:0 !important;margin-bottom:0 !important;margin-righ=
t:0 !important;margin-left:0 !important;padding-top:0 !important;padding-bo=
ttom:0 !important;padding-right:0 !important;padding-left:0 !important;"/><=
```

A: (klaviyo.com) opened email tracker

---

easylist/easylist_general_block.txt

https://forums.lanik.us/viewtopic.php?f=62&t=43088

A: https://gadgets.ndtv.com/

---

easyprivacy/easyprivacy_general.txt

```
https://weblications.guj.de/js/gujTracker.js
https://weblications.guj.de/js/gujTracker.min.js
```
https://forums.lanik.us/viewtopic.php?f=90&t=43083

A: https://www.geo.de/

---

easyprivacy/easyprivacy_thirdparty.txt

https://forums.lanik.us/viewtopic.php?f=62&t=43080

A: https://matichon.co.th/

---

easylist/easylist_general_block.txt

https://forums.lanik.us/viewtopic.php?f=64&t=43799

P: https://adcl.screenconnect.com/

---

fanboy-addon/fanboy_social_whitelist_general_hide.txt

https://i.ibb.co/MRCmmV6/111222333.png

A: https://sale.aliexpress.com/__pc/referral_entrance.htm

---

fanboy-addon/fanboy_cookie_general_hide.txt

https://forums.lanik.us/viewtopic.php?p=151076#p151076

A: https://coinmarketcap.com/currencies/bitcoin/

---

easylist/easylist_specific_block.txt

https://forums.lanik.us/viewtopic.php?f=62&t=43873

A: (nsfw) chan.sankakucomplex.com

---

fanboy-addon/fanboy_annoyance_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=64&t=43888

P: http://www.expo-service.kiev.ua/

---

easyprivacy/easyprivacy_whitelist_international.txt

https://forums.lanik.us/viewtopic.php?f=64&t=43914

P: http://alternathistory.com/kogda-strah-bolshe-dolga/#comments

---

easyprivacy/easyprivacy_whitelist.txt

https://forums.lanik.us/viewtopic.php?f=64&t=43866

P: https://www.canadiantire.ca/

---

easylist_cookie/easylist_cookie_general_hide.txt

Sample link: `https://www.tp-link.com/`

##.cookie-used-note general hide filter added

---

easylist/easylist_specific_block.txt

https://github.com/easylist/easylist/commit/5c7fc8f371509c6a0990927c89637e351509fbe7#diff-ce6ade6e52352499cfb347f46c329f9fL340
https://forums.lanik.us/viewtopic.php?p=151420#p151420

M: Re-add limesurvey.org

---

easylist/easylist_specific_hide.txt

You are currently blocking all content on ucas.com as brick__wrapper is used to wrap every content section, the change in the PR only targets the ads.

Correction to Ad blocking on ucas.com

---

fanboy-addon/fanboy_annoyance_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=64&t=43941

P: https://voshod-solnca.ru/sun

---

easyprivacy/easyprivacy_general.txt

https://forums.lanik.us/viewtopic.php?p=151451#p151451

A: https://zhuanlan.zhihu.com/p/51117616

---

easyprivacy/easyprivacy_specific_international.txt

https://forums.lanik.us/viewtopic.php?p=151448#p151448
https://forums.lanik.us/viewtopic.php?p=151450#p151450

A: https://image.baidu.com/ & https://news.baidu.com/

---

easylist/easylist_adservers.txt

```
http://be-notified.com/js/osw.js
http://notification-centar.com/js/osw.js
http://notification-list.com/js/osw.js
http://notify-monad.com/js/osw.js
http://premiumpushnotification.com/js/osw.js
http://notification-list.com/js/osw.js
http://cdn.hoood.info/sdk/osw.js
```

M: Update adservers

---

easylist/easylist_specific_block.txt

https://forums.lanik.us/viewtopic.php?p=151401#p151401

M: https://ytmp3.cc/

---

easyprivacy/easyprivacy_specific_international.txt

https://forums.lanik.us/viewtopic.php?p=151400#p151400

A: https://map.baidu.com/

---

easyprivacy/easyprivacy_specific_international.txt

https://forums.lanik.us/viewtopic.php?p=151398#p151398

A: https://mp.weixin.qq.com/s/f9GKQ6vfiiisHH6GAh7WEw

---

easyprivacy/easyprivacy_general.txt

https://forums.lanik.us/viewtopic.php?p=151399#p151399

A: https://www.qq.com/

---

fanboy-addon/fanboy_social_whitelist_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=64&t=43925

P: https://vaganovaacademy.ru/

---

easylist/easylist_specific_block.txt

example url:
```
https://ishort.live/#Ew8PC0FUVAwMDFUWHhwaCx4XEhgOFxoICRILVRUeD1QUDg9URBozKUsYPxQNN0kTDRg8LQwiIzVLIShOEBlIHw4ZPEITIThDVB8RSwM1ASpL
```

A: https://ishort.live/

---

easylist/easylist_general_hide.txt

ads url
```
https :// www . fwd28 . com /scripts/un123c6l?a_aid=b12345d3&a_bid=1234cfe0&chan=Download3EN&data1=Maths%20symbols%20name%20list
```

A: https://question2you.site/?q=Maths+symbols

---

easylist_cookie/easylist_cookie_general_hide.txt

Sample link: `https://www.tiendeo.fi/`

new filter ###cookiesModal_bottom added

---

easyprivacy/easyprivacy_specific_international.txt

https://github.com/easylist/easylist/pull/4346#issuecomment-559910228

Fix #4346 - More precise match on baidu tracker

---

easylist_cookie/easylist_cookie_general_hide.txt

Can be found here: `https://www.xxl.fi/`

##.cookies__message added

---

easyprivacy/easyprivacy_whitelist_international.txt

https://forums.lanik.us/viewtopic.php?f=64&t=43078

P: https://www.deutschlandfunkkultur.de/

---

easylist/easylist_specific_hide.txt

https://forums.lanik.us/viewtopic.php?p=151599#p151599

A: (dnsleaktest.com) update fbfd9fd

---

easylist/easylist_specific_hide.txt

https://forums.lanik.us/viewtopic.php?p=150630#p150630

A: (nsfw) gfycat.com

---

fanboy-addon/fanboy_annoyance_whitelist_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=64&t=43940

P: https://np.krasnodar.ru/

---

easylist_adult/adult_specific_block.txt

A: (nsfw) tbib.org

---

easylist_adult/adult_specific_block.txt

https://forums.lanik.us/viewtopic.php?p=150915#p150915

A: (nsfw) pornhat.com

---

easylist_adult/adult_specific_block.txt

https://github.com/abp-filters/abp-filters-anti-cv/issues/298
https://forums.lanik.us/viewtopic.php?f=62&t=43352

A: (nsfw) rule34hentai.net

---

easylist_cookie/easylist_cookie_specific_hide.txt

https://forums.lanik.us/viewtopic.php?p=151720#p151720

A: https://www.hackerone.com/

---

easylist_adult/adult_specific_block.txt

https://forums.lanik.us/viewtopic.php?p=151727#p151727

A: (nsfw) xbooru.com

---

easylist_cookie/easylist_cookie_international_specific_hide.txt

https://github.com/ryanbr/fanboy-adblock/issues/1241#issuecomment-562836569

P: Problematic and redundant rule, ba.no, ifinnmark.no, nettavisen.no, op.no

---

fanboy-addon/fanboy_annoyance_general_hide.txt

https://github.com/easylist/easylist/issues/1071

A: http://www.hxc-power.com/col.jsp?id=110

---

easylist/easylist_general_block.txt

https://forums.lanik.us/viewtopic.php?f=96&t=43982

A: https://www.tio.ch/

---

easylist_cookie/easylist_cookie_general_hide.txt

A: a general cookie filter, www.prisma.fi

---

fanboy-addon/fanboy_annoyance_general_hide.txt

A: https://www.pccomponentes.com/

---

easylist/easylist_whitelist.txt
easyprivacy/easyprivacy_whitelist.txt

Hi,
This PR fixes breakage on Discovery streaming sites. Without these whitelists, the player will not load at all. There are multiple URLs across domains where this issue occurs, and I have included test URLs below.
**The whitelist:** The player on Discovery streaming sites will not load unless all scripts from `fusion.ddmcdn.com` load. 
**Removing old whitelists:** I also removed the no longer needed `litix.io`, `imasdk.googleapis.com`, and `fwmrm.net` whitelists.
(Note: `vevo.com` no longer hosts videos, so that filter can be deleted entirely)
Old PR: https://github.com/easylist/easylist/pull/4102
Test links for each site:
```
! ahctv.com
https://www.ahctv.com/tv-shows/manhunt-kill-or-capture/full-episodes/whitey-bulger-boston-mob-king
! animalplanet.com …
```

P: Fix Discovery streaming sites breakage, remove old whitelists

---

easylist/easylist_whitelist.txt

P: videos don't start immediately, independent.co.uk

---

easylist/easylist_thirdparty.txt

A: Spam chat by justanswer.com

---

easylist_adult/adult_specific_block.txt

https://forums.lanik.us/viewtopic.php?f=114&t=43980

A: (nsfw) alastonsuomi.com

---

easylist/easylist_specific_block.txt

`https://gdtot.com/d/dindex.php/file/6148523063484d364c79396b636d6c325a53356e6232396e62475575593239744c324576625746706243356a59334e6d4c6d566b64533931597a39705a44307855334d7953555253655464505a456468544563334e4752315a7a5a6b54486c47624745795a4735314e466f3d`
https://github.com/easylist/easylist/pull/4461

A: https://gdtot.com/

---

easylist/easylist_specific_block.txt

A: (marketrealist.com) Update 9089a6f

---

easylist/easylist_general_hide.txt

https://github.com/abp-filters/abp-filters-anti-cv/issues/314

A: https://marketrealist.com/

---

easyprivacy/easyprivacy_thirdparty.txt

https://forums.lanik.us/viewtopic.php?p=151641#p151641

A: https://www.ossec.net/

---

easylist/easylist_thirdparty.txt

https://forums.lanik.us/viewtopic.php?f=90&t=43680

A: https://soundcloud.com/skysportsradio

---

easyprivacy/easyprivacy_whitelist_international.txt

https://forums.lanik.us/viewtopic.php?f=64&t=44111

P: https://krok8.com/bazovyy-metabolizm/

---

easyprivacy/easyprivacy_trackingservers_international.txt

`https://kiwi44.leiki.com/focus/mwidget?wname=sys_leiki_segments&first=undefined&cid=https%3A%2F%2Fkeskustelu.pakkotoisto.com%2F&referer=https%3A%2F%2Fwww.episodi.fi%2F&ts=1577069843812&userid=1875e965-76c0-8756-bf08-106f995b119a&callback=leikiComLoader.jsonCallback295471139`
sub-domains https://pastebin.com/raw/3C5U7130

A: https://www.episodi.fi/

---

easylist_adult/adult_specific_block.txt

Fix made as presented here:
https://forums.lanik.us/viewtopic.php?p=152010&sid=8e934b3f39541ec77b61df75537af40e#p152010

P: comment breakage, alastonsuomi.com (NSFW)

---

easyprivacy/easyprivacy_thirdparty_international.txt

https://forums.lanik.us/viewtopic.php?f=62&t=44049

A: https://mensfashion.cc/

---

easyprivacy/easyprivacy_thirdparty_international.txt

https://forums.lanik.us/viewtopic.php?f=62&t=44059

A: http://shopselect.net/

---

easyprivacy/easyprivacy_trackingservers_international.txt

https://forums.lanik.us/viewtopic.php?f=62&t=44066
https://forums.lanik.us/viewtopic.php?f=62&t=44067

A: http://kimonodaicho.co.jp/

---

easyprivacy/easyprivacy_general.txt

PR: https://forums.lanik.us/viewtopic.php?f=62&t=44056

A: https://www.rebates.jp/

---

easyprivacy/easyprivacy_general.txt

https://forums.lanik.us/viewtopic.php?f=62&t=44058

A: https://tower.jp/

---

easyprivacy/easyprivacy_thirdparty_international.txt

https://forums.lanik.us/viewtopic.php?f=62&t=44051

A: https://www.cotta.jp/

---

easyprivacy/easyprivacy_general.txt

https://forums.lanik.us/viewtopic.php?f=62&t=44061

A: https://warnerbros.co.jp/

---

easyprivacy/easyprivacy_trackingservers_international.txt

https://forums.lanik.us/viewtopic.php?f=62&t=44068

A: http://taidoo.a.la9.jp/

---

easyprivacy/easyprivacy_specific_international.txt

https://forums.lanik.us/viewtopic.php?f=62&t=44064

A: https://www.bookoffonline.co.jp/

---

easyprivacy/easyprivacy_general.txt

https://forums.lanik.us/viewtopic.php?f=62&t=44062

A: http://www.sara-style.com/

---

easyprivacy/easyprivacy_specific_international.txt

https://forums.lanik.us/viewtopic.php?f=62&t=44050

A: https://retty.me/

---

easylist_adult/adult_specific_block.txt

Fixed an issue reported here: https://github.com/easylist/easylist/pull/4549#issuecomment-569493335
This should be the final pull request concerning this issue :D as `madmen.alastonsuomi.com` is an exclusive ad server: https://forums.lanik.us/viewtopic.php?p=152222#p152222

P: user picture thumbnail breakage, alastonsuomi.com (NSFW)

---

easyprivacy/easyprivacy_trackingservers_international.txt

https://forums.lanik.us/viewtopic.php?f=62&t=44055

A: http://i-bbs.sijex.net/

---

easyprivacy/easyprivacy_thirdparty_international.txt

https://forums.lanik.us/viewtopic.php?f=62&t=44057

A: http://bingtsept.blog98.fc2.com/

---

easyprivacy/easyprivacy_trackingservers_international.txt

```
http://pingclock.net/metric/?mid=&wid=*&sid=&tid=*&rid=*&custom1=*&custom2=*&custom3=*&t=*
```

A: http://www.coco.fr/chat/index.html

---

easylist/easylist_specific_block.txt

Hey, there is space, which looks like added by accident

M: invalid space in csp filter

---

easylist_cookie/easylist_cookie_specific_hide.txt

see: https://github.com/easylist/easylist/pull/4685

P: bethesda.net

---

easyprivacy/easyprivacy_specific.txt

or change `/analytics.*/event?` to `/analytics.*/event`
request ==>  `https://analytics.sketchup.com/event`

A: https://app.sketchup.com/app?hl=en

---

easylist_cookie/easylist_cookie_specific_hide.txt

Sample link: https://www.redditinc.com/

A: cookie notification hide, redditinc.com

---

easylist/easylist_general_hide.txt

Sample link: https://www.cryptocompare.com/mining/asus/
­![kuva](https://user-images.githubusercontent.com/17256841/72223694-6d0be600-357a-11ea-9c22-aa2a5b7edf3c.png)
­
­
Sample link2: https://www.cryptocompare.com/coins/btc/overview/USD
­![kuva](https://user-images.githubusercontent.com/17256841/72223795-82354480-357b-11ea-95ee-9ef63cd14f24.png)
­
If this pull req is accepted, this one https://github.com/easylist/easylist/pull/2325 can be closed.

A: generic ad hide, cryptocompare.com

---

fanboy-addon/fanboy_social_general_hide.txt

`https://www.lespagesmaghreb.com/annuaire/alger/appareils-medicaux-et-chirurgicaux-detail/medicatech-siege-social/7622a3fbc2ce04ebc349b1efe2278ffff2bcebaf`

A: https://www.lespagesmaghreb.com/

---

easylist_cookie/easylist_cookie_general_hide.txt

https://forums.lanik.us/viewtopic.php?f=62&t=43868

A: https://mikrosteuer.ch/

---

easylist/easylist_specific_hide.txt

https://forums.lanik.us/viewtopic.php?p=147141#p147141

A: https://www.multiup.org/en/download/7876e6221a88de61dac17da4ad4bd73f/C.rar

---

easylist/easylist_general_hide.txt

https://imgur.com/uPQ9l4y.png
https://github.com/abp-filters/abp-filters-anti-cv/issues/154

A: https://www.pelispedia.tv/pelicula/mis-huellas-a-casa/

---

easylist/easylist_specific_hide.txt

A: Twitter ads in Finnish, twitter.com

---

fanboy-addon/fanboy_annoyance_thirdparty.txt

https://i.ibb.co/vk0HwXc/a.png

A: https://www.iphoshop.fr/

---

easylist_adult/adult_adservers.txt

ad server 
```
https://beavertron.com/oxb.php?c=21&camsodacb=1
```
mirror of 
```
https://serve.oxcluster.com/oxb.php?c=21&camsodacb=1
```

A: (nsfw) camsoda.com

---

easylist/easylist_general_block.txt

nsfw
```
bdsmporntub.com/ab_fl.js
femdomporntubes.com/ab_fl.js
vintageporntubes.com/ab_fl.js
vintagepornvideos.sexy/ab_fl.js
xxxmaturevideos.com/ab_fl.js
retroporn.sexy/ab_fl.js
wowpornvideos.com/ab_fl.js
```

A: (nsfw / exads) xxxmaturevideos.com

---

easylist_cookie/easylist_cookie_general_block.txt

```
123-comptons-les-croix.xooit.biz
miss-et-cie.com
chinese-quad.com
depiedencap.leforum.eu
```

A: http://www.xooit.com/

---

easylist_cookie/easylist_cookie_international_specific_hide.txt

https://github.com/ryanbr/fanboy-adblock/issues/1160
(Yes, this is a Finnish site even though it has a name "swedishforum" as a part of it.)

A: cookie note hide, vapaasana.swedishforum.net

---

easylist/easylist_specific_hide.txt

­
­
­
**This old pull req should be closed imo**: https://github.com/easylist/easylist/pull/2412

A: ad container remnants, electronicshub.org

---

easylist/easylist_specific_hide.txt

Main page:
­
­
­
And on this link: https://www.windowscentral.com/best-windows-laptop scroll down a bit and the shop ad bar will appear at the top:
­
­
­
**Old pull req that should be closed if this is merged**: https://github.com/easylist/easylist/pull/2410

A: top ad bars, windowscentral.com

---

easylist/easylist_specific_hide.txt

A: ad banner at the top, gamecopyworld.com / eu
