easylist/easylist

easyprivacy/easyprivacy_trackingservers.txt
I work at Sift Science and we provide fraud prevention services for online businesses. Most of our clients use a JavaScript snippet that is hosted on our domain to more accurately predict fraud on their sites.
We have noticed that our domain [siftscience.com](https://siftscience.com) is on the blocked list, which breaks our website. Please unblock this domain, as we no longer send user information to this domain. We have changed the endpoint to be hosted on [hexagon-analytics.com](http://hexagon-analytics.com) so that we may get our main domain unblocked.
=> Replace https://siftscience.com with https://hexagon-analytics.com

easylist/easylist_adservers.txt
Both zerozo.work and rolinda.work redirect to publited.com, which shows to be ad network business.
If you go to http://www.mejortorrent.com/ and click on any movie, for example see this one http://www.mejortorrent.com/peli-descargar-torrent-14552-Stereo.html , then click "Descargar" (spanish for "Download") and then finally click where it says "Pincha aquí para descargar el torrent." (spanish for "Click here to download torrent."). Popups will appear. I got one from URL rolinda.work. If you go to rolinda.work, it redirects to publited.com.
The other URL in the commit is zerozo.work, but I was not able to reproduce this one (this was originally reported in EasyList Spanish Forum a couple months ago, that's why it may have changed). But if you go to zerozo.work, it redirects to …
=> Additions to easylist_adservers.txt

easylist/easylist_general_hide.txt
Found several div IDs and classes that, imho, should be included into EasyList.
=> Additions to easylist_general_hide.txt

easylist/easylist_whitelist.txt
This is to delete anti adb filter from whitelist, for a spanish newspaper website. The anti adb filter already exists in EasyList Spanish. See https://github.com/easylist/easylistspanish/commit/b3e08018ffd43d88c962b8e0fd32cff1ed9ae0c9
=> Deletion of filter in easylist_whitelist.txt

easylist/easylist_adservers_popup.txt
I was able to see a popup from tagsd.com while looking at newpct.com, this happened a few days ago. Unfortunately, they appear to have changed the website source code, and I can not reproduce it any longer. But if you go to tags.com, you will see nothing; and also doing a [whois](https://whois.domaintools.com/tagsd.com) on the domain shows that it is owned by YESUP MEDIA INC. (advertising agency - website http://www.yesup.com/).
=> Addition to easylist_adservers_popup.txt

easylist/easylist_general_hide.txt
##.adLat - Reported by user over e-mail to EasyList Spanish. I believe it refers to "ad lateral", which applies in English as well, and so I thought it should be added to EasyList.
=> Addition to easylist_general_hide.txt

easylist/easylist_specific_block_popup.txt
This has better effect however: `about:blank$popup,domain=oload.tv`
=> Block popup on Openload's alternative domain

easylist/easylist_adservers.txt, easylist/easylist_adservers_popup.txt
URLs in commits.
**easylist_adservers.txt**
||toro-tags.com^$third-party -> It is already into EasyPrivacy, but not into EasyList.
||altpubli.com^$third-party -> Advertising Agency.
||leadzu.com^$third-party -> Advertising Agency. Note: disable ABP to see the ads. 
||35.184.98.90^$third-party -> Adserver.
||smartadtags.com^$third-party -> Advertising Agency
||bruceleadx1.com^$third-party -> Adserver.
||bruceleadx2.com^$third-party -> Adserver.
||bruceleadx3.com^$third-party -> Adserver.
||bruceleadx4.com^$third-party -> Adserver.
||bruceleadx.com^$third-party -> Adserver.
**easylist_adservers_popup.txt**
||smartadtags.com^$popup,third-party -> Popups launched from this one
=> Additions to easylist_adservers.txt and easylist_adservers_popup.txt

easylist/easylist_adservers_popup.txt
||35.184.98.90^popup,third-party  -> This was the address where popups were launched from, a few days ago when I checked.
||35.184.137.181^popup,third-party  -> This is the address where popups are launched from today.
=> Additions to easylist_adservers_popup.txt

easylist/easylist_whitelist.txt
@@||saikoanimes.net/adb/advert.js$script,domain=saikoanimes.net
Updated anti adb filter for saikoanimes.net. Removed the obsolete one.
Also moved the new filter into Non-English section, since the website is in Portuguese.
=> Update to anti adb filter for saikoanimes.net

easylist/easylist_whitelist_general_hide.txt
https://forums.digitalspy.com/discussion/2207363/recent-fixes-to-ds-forums-current-tasks/p2
Specifically, the first post on any page of any thread, excluding page 1, was hidden by the `##.has-ad` rule.
=> Digital Spy forum false positive

easyprivacy/easyprivacy_thirdparty.txt
`amp-error-reporting.appspot.com` does not track any private user information. It's an error reporting server we use to log errors generated by the AMP HTML runtime (these are javascript error messages and stack traces). At most the url, user agent, and referrer are recorded (the least amount of information we need), but these are **only** used to reproduce the error and never to track the user.
/cc @cramforce
=> Remove amp-error-reporting.appspot.com

easyprivacy/easyprivacy_trackingservers.txt
[TagTray](https://www.tagtray.com/) provides a way for people to embed a javascript image gallery that shows images of their brand being used on social media.  Blocking 3rd party from the entire domain prevents the gallery from rendering.  If we permit the domain itself but block the /api calls, we get to still show the gallery but block any kind of tracking of viewing the gallery.
I've created a [simple sample gallery example](http://eastcodes.com/test.html) for testing
=> M: allow tagtray.com gallery, block tracking requests

easylist/easylist_general_block.txt
AdEx.network is a decentralized advertising network; FYI not serving any ads from adex.* domains (not even live at the moment)
=> Exclude adex.network from the blocklist

easyprivacy/easyprivacy_trackingservers.txt
`addfreestats.com` (already blocked) becomes ==> `afsanalytics.com`
=> A: http://www.mariage-franco-marocain.net/

easylist/easylist_general_block.txt
in referral to this commit: https://github.com/easylist/easylist/commit/11e0d587b016d74b54122f8491f996d69e1c1a30
Fixed the whitelisting to include subdomains such as www. and app.
=> Fix whitelisting for advert.io

easylist/easylist_general_block.txt, easylist/easylist_whitelist.txt, easylist/easylist_whitelist_general_hide.txt
The iframe in the "Book an ADS flight" tab was blocked and hidden, making it impossible to book an ADS flight.
The image https://booking.loganair.co.uk/VARS/Public/CustomerFiles/LoganAir/images/ads-sm.png was also blocked.
(ADS = Air Discount Scheme)
=> P: https://www.loganair.co.uk/

easyprivacy/easyprivacy_specific.txt
Disclosure: I am a developer from omny.fm
I propose removing traffic.omny.fm from the privacy list because it is a first-party tracking solution for the purpose of only tracking audio play/pause events.
The data is anonymized and is only presented as an aggregated statistic (e.g. 50% of listeners played at 2:11). No personal data is available.
=> Remove traffic.omny.fm first-party tracking

easylist/easylist_whitelist.txt
This exception is no longer doing any good – only allows ads to be shown.
=> bbelements.com false whitelist

easyprivacy/easyprivacy_trackingservers.txt
As @Khrin  [said](https://forums.lanik.us/viewtopic.php?p=119756#p119756), we are not a tracking company. Our business is to protect websites from scraping bots. In order to do so, we have an Javascript tag that will get elements from the end-user browser not to have a global fingerprint of a device but to see if the elements returned by a device are coherent (and not an emulated browser like Selenium, Chrome Headless and so on).
=> Remove : datadome.co

easylist/easylist_adservers.txt
shinobi.jp is not an ad server.
However, adm.shinobi.jp is an ad server.
Since several Internet services are operated using shinobi.jp domain, I really hope that you accept this request.
For more information, I hope that you can see this content, which my colleagues posted in the past in the past.
https://forums.lanik.us/viewtopic.php?f=64&t=37393&p=120492&hilit=shinobi.jp#p120492
I'm sorry, my English is not good.
=> Fix shinobi.jp to subdomain adm.shinobi.jp for ad server.

easyprivacy/easyprivacy_general.txt
Hi,
The open source Google Analytics alternative Piwik has been renamed to Matomo, which causes the exceptions to not work anymore.
=> M: exclude matomo.org from blocking /piwik/

easylist/easylist_specific_hide.txt
Example:
`https://www.javacodegeeks.com/2014/07/devops-isnt-killing-developers-but-it-is-killing-development-and-developer-productivity.html?utm_content=bufferc23cf&utm_medium=social&utm_source=plus.google.com&utm_campaign=buffer`
`javacodegeeks.com##div[id^="ulp-"]` - fullpage overlay
`javacodegeeks.com##.x-white` - floating top panel
=> A: javacodegeeks.com

easylist/easylist_general_block.txt
It doesn´t allow forms to be submitted on bamboohr.
Example: https://exoclick.bamboohr.co.uk/jobs/view.php?id=19
=> exclude another exoclick subdomain

easylist/easylist_adservers.txt
`adtag.cc` and `tagbucket.cc` are a mirrors of `toro-tags.com`
=> A: http://www.divmusica.com/descargar-mp3/romeo-santos

easyprivacy/easyprivacy_trackingservers_international.txt
Along with svtrd.com, the same company has tracking scripts that uses 2 other domains. 
```
www.gamma.nl
www.postcodeloterij.nl
```
n/a
n/a
- OS/version:  
- Browser/version: Firefox / 59.0.2 (64-bit)
- Adblock Extension/version: uBlock Origin 1.5.24
n/a
=> A: svtrd.com extras

fanboy-addon/fanboy_social_whitelist_general_hide.txt
Example ("Share" button on audio player): https://logbuch-netzpolitik.de/lnp249-qualitaetspromo
=> Unhide link-sharing feature on some Podcast sites

easyprivacy/easyprivacy_trackingservers.txt
capture media is an advertisement tracking service: http://capturemedia.ch/
Scripts are loaded by the domain edge.capturemedia.network
Example Script
```
https://edge.capturemedia.network/sess.js
```
=> A: http://capturemedia.ch/

easylist/easylist_general_block.txt
Analytics platform domain being blocked. This is used for analytics and in no way is used to serve ads. Sending a PR for whitelisting the domain. Not sure if this is the process. Thank you!
=> update blocklist to whitelist smartads.io

easylist/easylist_adservers.txt
e.g.
```
http://rubular.com/
http://jsbin.com/
```
=> A: http://rubular.com/

easyprivacy/easyprivacy_thirdparty_international.txt
Other tracking domains used by leady.cz - current one is insufficient :-/.
=> A: Other leady.cz tracking domains

easyprivacy/easyprivacy_trackingservers.txt
```
https://www.nationalgeographic.fr/environnement/le-vortex-de-dechets-du-pacifique-nord-ferait-trois-fois-la-taille-de-la-france
```
=> A: https://www.nationalgeographic.fr/

easylist/easylist_specific_block.txt
- removed from line 1072 the domain 'rarbg.unblocked.work' as it no longer works
- added an extra filter (based on line 172, i.e. dyncdn.me) for 'totalstatic.com'
because for the domain rarbgproxy.org they've changed the URL for the `expla85.js` script from dyncdn.me to totalstatic.com, while for the other rarbg mirrors it's still dyncdn.me.
Screenshot from uBO's logger:
=> Update easylist_specific_block.txt - rarbg

easyprivacy/easyprivacy_trackingservers_international.txt
```
https://www.suedostschweiz.ch/
https://www.tagblatt.ch/
https://www.luzernerzeitung.ch/
https://www.ticinonews.ch/
https://www.rontaler.ch/
```
=> A: https://www.suedostschweiz.ch/

easyprivacy/easyprivacy_trackingservers.txt
Its purpose is web services testing, CMSes and the like, nothing to do with ads, tracking or privacy problems.
=> dadi.technology is not a tracking server

easylist_adult/adult_specific_block.txt
Er... uhm... somebody told me the following :innocent:
motherless.com has a new mobile page, all scripts but a few exceptions are blocked. The mobile page introduces a new script missing on the exception list. The mobile page is broken (for example no video playback) if this script is missing, seems like there is no advertising stuff in this file so I think it's safe to whitelist it.
=> (nsfw) Fixed motherless mobile page

easyprivacy/easyprivacy_trackingservers.txt
The **1st filter** will prevent the abuse of the absolute domain name [**FQDN**](https://en.wikipedia.org/wiki/Fully_qualified_domain_name) (_tld with a trailing dot_).
e.g. https://vgy.me/sVmCVJ.png
```
https://www.hostingcloud.science./URB0.js
https://www.freecontent.party./URB0.js
```
The **2nd filter** will
- merged the old existing `$websocket` [**TLD** filters](https://github.com/easylist/easylist/commit/ad1a0035ccb6696221d7151322db2fae7b678f6d#diff-dbc51871bdd5cf7971a65ef9684d2248L2402)  (e.g. `.accountant^$third-party,websocket`, ...) in to one regex filter.
- removed `btorrent.xyz` added [\_here\_](https://github.com/easylist/easylist/commit/e0a18ad) (not affected because of the `$third-party` option).
- fix `instant.io` and `file.pizza`
-- https://vgy.me/Dmkxzd.png
-- …
=> M: Tweak and Fix https://github.com/easylist/easylist/commit/ad1a003

easylist/easylist_whitelist_general_hide.txt
The addition of .ad-grid as a general blocker (https://github.com/easylist/easylist/commit/0f1aae82c5493b0a9e97940711eb844599735101#diff-eff6174a52fcc75be714f55adb5e94eb) broke non-ad sections of the wornandwound.com website. The site uses the term 'ad-grid' for sections unrelated to ads. Ads will still be blocked appropriately.
=> Fix wornandwound.com

easylist/easylist_general_block.txt
e.g. `https://static.opensubtitles.org/libs/js/urlshortener.js`
=> A: url shortener script (Advertising, Clicks Analytics)

easyprivacy/easyprivacy_specific_international.txt
```
https://player.cdn01.rambla.be/?account_id=VzaPKg&item_id=WXPZlG
```
=> A: https://www.focus-wtv.be/nieuws/schadeclaim-van-82-miljoen-euro-casinodossier

easyprivacy/easyprivacy_general.txt
Loglevel is browser console log wrapper. It offers a different API for logging instead of using the browser console interface.
It persists some data into localStorage, and cookies if localStorage is unavailable.
Check source: https://github.com/pimterry/loglevel/blob/master/dist/loglevel.js
=> R: /loglevel.js

easylist/easylist_adservers.txt, easylist/easylist_adservers_popup.txt
malvertising redirector, same as runtnc.net
=> A: tncred.com

easyprivacy/easyprivacy_whitelist.txt
legendstracking.com is a website to track people during sport events while running/cycling with a GPS chip.
The file
http://XXX.legendstracking.com/js/legends-tracking.js?00001 (where XXX is the name of the race)
is used to load the GPS tracking information, this is not about
tracking the visitor
For instance, go to http://beartrail.legendstracking.com/ getting a blank page instead of getting the map of the race because it matches the rule `-tracking.js?`
Warning, first time contributing to easylist, I am not sure it is the best syntax to do so, advises appreciated.
=> Do not block legendstracking.com js file

easylist/easylist_thirdparty.txt
The domain is used by Women’s Refuge New Zealand's Shielded Site Project, which is for victims of abuse to ask for help. See here: https://shielded.co.nz/
```
||d3f5l8ze0o4j2m.cloudfront.net^
```
* https://www.asb.co.nz/
* https://z.co.nz/
* https://www.stats.govt.nz/
* https://www.thewarehouse.co.nz/
* https://www.trademe.co.nz/
* https://www.countdown.co.nz/
* https://women.govt.nz/
* http://www.ausa.org.nz/
* https://imoved.me/
* http://www.olympic.org.nz/
* https://www.momentum.co.nz/
* https://www.sjs.co.nz/
* https://thespinoff.co.nz/
* https://www.pagani.co.nz/
* https://www.nzpost.co.nz/
* https://www.ird.govt.nz/
* https://www.easygiving.nz/charities/
* https://www.happymumhappychild.co.nz/
* https://www.bnz.co.nz/
* https://www.tower.co.nz/
* https://library.huttcity.govt.nz/
* …
=> R: d3f5l8ze0o4j2m.cloudfront.net from easylist_thirdparty.txt

easylist/easylist_general_block.txt
Added whitelist for Pingdoms sharing banners to this very hungry rule.
Example of banner can be found here;  https://share.pingdom.com/banners/0a7716fc
These images are generated by customers, and not meant for advertising.
=> Enable report banners for pingdom

easyprivacy/easyprivacy_whitelist.txt
Hello,
This PR restores a whitelist entry that was recently removed for `evestment.com`:
&nbsp;&nbsp;&nbsp;&nbsp;Original Addition: https://github.com/easylist/easylist/commit/62f09532389ec205ffdf7cc37fbf6574e3d61a07 by @monzta 
&nbsp;&nbsp;&nbsp;&nbsp;Recent Removal: https://github.com/easylist/easylist/commit/e95ef2da029ef7c648d60b5bdac1cacb7b4a5d5c
The removal of the whitelist entry is resulting in a broken experience for users of the evestment platform that are also using the privacy list.  Unfortunately, this means users have to disable their privacy extensions while using the application.  To learn more about eVestment:
- [crunchbase profile](https://www.crunchbase.com/organization/evestment-alliance)
- [glassdoor](https://www.glassdoor.com/Overview/Working-at-eVestment-EI_IE286633.1 …
=> P: evestment.com/api/analytics

fanboy-addon/fanboy_cookie_general_hide.txt
Element encountered on this site: `https://keepass.info/help/base/faq_tech.html` (I'll give a link to a subpage in order to show that hiding this element doesn't break scrolling.)
C is probably an abbreviation of cookie. That's why I think this would do as a general filter.
=> a general filter, ###consent_c added

easylist/easylist_general_hide.txt
Ad containers left unblocked (location: down from the middle page).
`https://www.tv7.fi/`
A general filter can be made:
`##.ad-banners`
(Originally mentioned here: `https://forums.lanik.us/viewtopic.php?f=62&t=43756`)
=> ##.ad-banners general filter added

fanboy-addon/fanboy_annoyance_whitelist_general_hide.txt
This widget is used to display the current price of the subscription, not to subscribe to a newsletter or shit
Before this commit the form on https://odoo.com/trial was hidden as the class subscription-widget is set on the main element of the form
_Disclaimer_: I am working for the company behind odoo.com but I don't think we are doing anything fishy
=> fanboy-addon: whitelist odoo.com for subscription widget

easylist_cookie/easylist_cookie_international_specific_block.txt
Sanoma Oyj has a new cookie scripts that are being used for example here: `https://www.is.fi/` 
But the old rule is still used also, here example: `https://www.hs.fi/`
That's why it's the best option to have every one of them.
If they add even more (d, e, f etc..) it's better to think another way for this.
=> Sanoma Oyj additional cookie script, blocking added

easylist/easylist_general_block.txt
Hi.
We are a web system and graphic design company in Japan, named "AD.BAR".
Now, our domain `adbar.jp` is blocked by easylist.
https://adbar.jp/
But we don't providing ads businesses on internet. And there is no plan.
Could you apply this rule?
Thanks.
Refs: #460
=> M: Unblocking adbar.jp

easylist_cookie/easylist_cookie_international_specific_hide.txt
That domain is not in use anymore as Sonera has changed it's name to Telia.
=>  M: An old rule, sonera.fi

easylist_cookie/easylist_cookie_specific_hide.txt
On `shirtsofcotton.com` there is a dark transparent cover. Obviously it's a leftover of the hidden cookie message.
=> A: Cookie blocking remnant, shirtsofcotton.com

easyprivacy/easyprivacy_specific_international.txt
Edit: The request `music.163.com/weapi/pl/count` will be triggered only when users login the account and click the play button.
=> A: https://music.163.com/

easyprivacy/easyprivacy_specific_international.txt
```
$ dig unstat.baidu.com @1.0.0.1
; <<>> DiG 9.11.5-P4-5.1-Debian <<>> unstat.baidu.com @1.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 64942
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
;; QUESTION SECTION:
;unstat.baidu.com.		IN	A
;; ANSWER SECTION:
unstat.baidu.com.	1200	IN	CNAME	uncode.e.shifen.com.
;; AUTHORITY SECTION:
e.shifen.com.		300	IN	SOA	ns1.e.shifen.com. baidu_dns_master.baidu.com. 1912220011 5 5 2592000 3600
;; Query time: 93 msec
;; SERVER: 1.0.0.1#53(1.0.0.1)
;; WHEN: Mon Dec 23 01:38:06 CST 2019
;; MSG SIZE  rcvd: 147
```
=> M: Removed unstat.baidu.com (NXDOMAIN)

easylist/easylist_general_hide.txt
As seen on: `https://ww.electrek.co/2020/01/06/tesla-model-3-to-be-5000-cheaper-in-new-jersey-turnpike-getting-electrified/#`
```html
<iframe id="ksskpi_ehw_mjveqi_/1049447/Ipigxvio_Wmkrep_1b1_0" title="3rd party ad content" name="google_ads_iframe_/1049447/Electrek_Signal_1x1_0" width="1" height="1" scrolling="no" marginwidth="0" marginheight="0" frameborder="0" srcdoc="<script>(function() { if (!window.$aproxy) {
let _aTopWin = window.parent.$aproxy.get_top_level_window(window.parent);window.$aproxy = _aTopWin.$aproxy_init(window, _aTopWin.$aproxy.config).inject();window.$aproxy.set_base_url(window.parent.$aproxy.get_base_url().href);window.$aproxy.set_ad_selectors(window.parent.$aproxy.ad_selectors);window.$aproxy.injectPostMessageLogic(window);
document.currentScript.remove(); } …
```
=> Block google_ads_iframe when name attribute is used instead of id

easylist_cookie/easylist_cookie_specific_hide.txt
`depositfiles.org###cookie_popup` has been made redundant by `###cookie_popup`
`dappertogs.co.uk###d-notification-bar` has been made redundant by `###d-notification-bar`
`shatter-box.com###elGuestTerms` has been made redundant by `###elGuestTerms`
This is a fixed version of my previous request from a couple of days ago. Checked for the usage of generichide. @Khrin
=> M: removed redundant rules

easylist_cookie/easylist_cookie_international_specific_hide.txt
`scheune-gluecksburg.de###d-notification-bar` has been made redundant by `###d-notification-bar`
`pricerunner.dk###data-protection-notification` has been made redundant by `###data-protection-notification`
`gehalt.de###datenschutzlayer` has been made redundant by `###datenschutzlayer`
`atman.pl###gbpl_oba` has been made redundant by `###gbpl_oba`
`ing.es,ingdirect.es###ico_banner` has been made redundant by `###ico_banner`
`klebetape.de###keksdose` has been made redundant by `###keksdose`
=>  M: removed rules - made redundant by generic ones

easyprivacy/easyprivacy_whitelist.txt
A Facebook game called Buggle2 won't load due to Easyprivacy rule.
https://www.facebook.com/search/apps/?q=buggle2&epa=SERP_TAB (here you can test the game if you have a Facebook account).
It's likely that other games could be affected so I whitelisted all Cookappsgames as there are many of them.
If I wanted to fix only this particular game, this rule would be enough:
`@@||pro.ip-api.com/json/$xmlhttprequest,domain=buggle2.cookappsgames.com`
But I consider it better to whitelist all Cookappsgames with this rule:
`@@||pro.ip-api.com/json/$xmlhttprequest,domain=cookappsgames.com`
=> P: A Facebook game won't load, buggle2.cookappsgames.com

easylist_cookie/easylist_cookie_general_block.txt
Easylist cookie already has rules to hide "oil cookie" notification:
`##.as-oil[data-qa="oil-Layer"]`
`##.as-oil-content-overlay`
I added a rule to block the script behind them.
=> A: general cookie block, www.blogit.fi

fanboy-addon/fanboy_social_whitelist.txt
`@@||aussieoutages.com^$generichide` reddirect to `downdetector.com.au`
`@@||canadianoutages.com^$generichide` reddirect to `downdetector.ca`
both have now incorrect hidden Twitter / Facebook / Instagram / Snapchat monitoring buttons.
---
Optionally, I can restore old domains ending with "`outages.com`"
=> M: downdetector Australian / Canadian

easyprivacy/easyprivacy_specific.txt
similar to https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_specific.txt#L510.
both VRV and Crunchyroll are operated by Otter Media.
example URL(geo-restricted to US): https://vrv.co/watch/G62P49XM6
request made from(`cx-vilos-ads` script): https://static.vrv.co/vilos/assets/vendri.js to: https://static.vrv.co/ip 
```js
function ipv4AddressFetch() {
var a,
b = new XMLHttpRequest,
c = 'object' == typeof device && device.hasOwnProperty('ip');
if (c) return a = '//' + window.location.host + '/ip',
console.log('Vendri; A9 API; ipv4AddressFetch; endpoint', a),
b.open('GET', a, !0),
b.onreadystatechange = function () {
b.readyState === b.DONE && (200 === b.status ? device.ip = parseIpv4Response(b.response)  : (console.warn('Vendri; A9 API; failure to retrieve client IP …
```
=> A: https://vrv.co/

easyprivacy/easyprivacy_trackingservers.txt
Hi, ReachFive is a CIAM (Customer Identity and Access Management) solution used to authenticate the end users, like Okta or Auth0.
We provide OIDC and OAuth2 authentication method and do not track any behaviour. Our documentation is available here : https://developer.reach5.co/
Our goal is to protect the access of end user to their resources thanks to OAuth2 application (clientId, Client Secret, JWT Token and Scope Management)
We do own reach5.net and og4.me (cf whois)
Our client can't authenticate their end user. 
- www.etam.com
- www.undiz.com
- boulanger.com
- ouibus
- OM
Feel free to contact me if needed, 
Thank you
etc, etc, ...
=> Remove CIAM ReachFive domain

fanboy-addon/fanboy_annoyance_general_hide.txt
.div[class^="MuiSnackbar-"] is blocked by Fanboy’s Annoyance List, but it's a class name of a core component of Material-UI. https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt. This library has more than 1m active developers using it, so it's probably affecting millions of end users 
We have seen a similar issue in the past with Material Design Lite: https://forums.lanik.us/viewtopic.php?f=64&t=35849&p=114412&hilit=Snackbar#p114412. 
This issue was first reported on GitHub by three of our users:
- https://github.com/mui-org/material-ui/issues/19124
- https://github.com/mui-org/material-ui/issues/19169
- https://github.com/mui-org/material-ui/issues/19564
We think that the rule should be removed from the list. Having the class name in the filter list doesn't help anyways …
=> Remove default Material-UI classname

easylist_cookie/easylist_cookie_general_block.txt
Cookie note hid by these rules:
`###cookie_hdr_showagain`
`###cookie-law-info-bar`
`###cookie-law-info-again`
`###cliSettingsPopup`
Added now a generic script to block it.
=> A: generic cookie note block, sm-mega.fi

easylist_cookie/easylist_cookie_general_hide.txt
This has changed. So that's why this update.
This is used on many domains, not on just `123pelit.com`
I however wonder if this rule would be better?
`##div#app-root.c > aside`
=> M: poki cookie element hide, 123pelit.com

easylist/easylist_adservers.txt, easyprivacy/easyprivacy_trackingservers_international.txt
It's listed under "Swedish" section. But it's headquarters are now in London so it's not "Swedish" anymore in that sense. :D
It can be encountered on this link: https://pakkotoisto.com/
It does connect to a domain that sounds like tracking (track.adtraction.com) but it's probably used for both ads and tracking. It's frontpage on adtraction.com suggests that it's for ads.
=> M: Moved an adserver Easyprivacy -> Easylist

easyprivacy/easyprivacy_whitelist_international.txt
This entry was made because I reported this issue in the past: https://github.com/easylist/easylist/issues/2859
The problem was that Easyprivacy broke order tracking on power.fi. However, order tracking api has been changed now:
ordertracking is now orderfollow.
https://www.power.fi/tuki/tilausten-seuranta/ can check on this link. Just write random numbers and random email and click "Hae" (Search).
=> M: power.fi

easyprivacy/easyprivacy_general.txt
```
https://www.lameridionale.fr/js/wreport.js
http://hepatoweb.com/script/wreport.js
https://www.acpm.fr/bundles/ojdfront/js/stats/wreport.js
```
related https://github.com/easylist/easylist/commit/f2da855cc3a330358840a346d47154394e66d77b
=> A: (weborama.fr profiling) https://www.acpm.fr/

easylist_cookie/easylist_cookie_specific_hide.txt
Note! This will only hide the banner that is visible for users not logged in:
Remade this old pull req https://github.com/easylist/easylist/pull/3277 that is partly redundant. The redundant rule it has is this one: `###global-alert-queue` that is not in use anymore in Linkedin.
That pull req also has this rule `###artdeco-global-alert-container` that is relevant, but it's a bit problematic. It's a filter to hide the cookie banner at the top for logged users, but if it's applied, the top banner will be detached from the top when the site is scrolled down. That's why I would not apply it. (This is occasional problem you probably are aware of). Check the screenshot below:
­
­
­![kuva](https://user-images.githubusercontent.com/17256841/75099579-e9f39c00-55cb-11ea-8633-1a6b7b04e350.png)
=> M: linkedin.com | cookie notification filter update

easylist_cookie/easylist_cookie_general_hide.txt
Remade this old pull req: https://github.com/easylist/easylist/pull/3076 with different domain.
This is a general cookie hiding rule.
=> A: cerealia.ch

easylist_cookie/easylist_cookie_general_block.txt
General cookie block.
(Not completely sure about this as I cannot see any visible notification. Here is a direct link to that .js file: https://m-bet.co.tz/assets/9bb7c334/main-ui/pop_up_cookie.js?v3.8.29)
=> A: m-bet.co.tz

easylist/easylist_adservers.txt
We aquired the domain simply.com and are launching a webhosting project on it. However the domain is blocked by you, due to past advertising activity (before we bought it).
Can you delist the domain from your blocklists?
=> Delist simply.com

easyprivacy/easyprivacy_thirdparty.txt
https://app.datadoghq.com/logs/livetail
Since [this commit](https://github.com/easylist/easylist/commit/accb36d7e0b0352bd7dd947a3c32b0f97c9b7c63), domain `logs.datadoghq.com` is blocked. But the Datadog website is using the domain `live.logs.datadoghq.com` as an API, so it breaks legitimate user usages.
easyprivacy
Block the `logs.datadoghq.com` domain only for third party usages.
=> M: https://app.datadoghq.com/

easylist/easylist_adservers.txt
> The push monetization is a form of advertising that relies on push notifications. This means that the ads are delivered to the browser or the device of the subscriber as push notifications...
=> A: https://yready.net/

fanboy-addon/fanboy_annoyance_general_block.txt
According to `https://forums.lanik.us/viewtopic.php?f=23&t=44444` app-banners on mobile sites should be addressed by Annoyances list. This script is quite commonly seen on my browsing e.g.
```{}
https://books.rakuten.co.jp/e-book/?l-id=ipn-header-menu-g101
https://www.livefans.jp/
https://www.swiss.com/
http://tabizine.jp/
```
and I haven't found a problem by blocking it. Of note, AdGuard Annoyances also has been blocking it.
=> A: add a common app-banner script

easyprivacy/easyprivacy_whitelist_international.txt
Related articles section after an article is blocked by Easyprivacy.
Sample link: https://www.soundi.fi/uutiset/bruce-springsteen-palasi-livemusiikin-pariin-keskella-pandemiaa-vieraili-kelttipunk-suuruuden-keikalla/
Fixed:
**EDIT**: all those sister sites suffer the same issue.
Sample links:
https://www.como.fi/uutiset/tapani-kansa-tahkoaa-edelleen-massia-firmansa-kera-nousu-100-prosenttia/
https://www.episodi.fi/uutiset/huippuluokan-scifi-toimintaleffa-saa-jatkoa-tv-sarja-luvassa/
https://www.fum.fi/uutiset/ruusut-julkaisi-odotetun-kakkosalbuminsa-kuuntele-se-tasta/
https://www.inferno.fi/uutiset/rockista-on-tullut-perinnemusiikkia-haastattelussa-timo-rautiainen-trio-niskalaukaus/
https://www.rumba.fi/uutiset/spotifyn-top-50-listalla-hammennysta-herattaneen-artistin-kappaleet-poistettu-pa …
=> P: como.fi|episodi.fi|fum.fi|inferno.fi|rumba.fi|soundi.fi|tilt.fi

easylist/easylist_adservers.txt
Adserver.
Sample link:
https://www.voice.fi/viihde/a-194146
Used on many other pages as well:
https://publicwww.com/websites/%22caroda.io%22/
Site tells that it's an adserver:
https://www.caroda.io/
=> A: voice.fi

easylist/easylist_whitelist_general_hide.txt
URL: `https://www.independent.com/`
Issue: Columns and Opinions are hidden.
Env: Brave 1.9.72 with its blocker turned off + uBO default settings
=> P: https://www.independent.com/

easyprivacy/easyprivacy_whitelist_international.txt
URL: `https://www.toonippo.co.jp/articles/-/359682`
Issue: video doesn't appear.
Env: Brave 1.8.96 (its blocker turned off) + uBO 1.27.10 with default filter lists
=> P: fix toonippo.co.jp videos

easyprivacy/easyprivacy_whitelist_international.txt
Easyprivacy removes this chat assistant.
=> P: veho.fi

easylist/easylist_general_block.txt
`https://adweb.pro`
False positive. Website blocked with filter `/adweb.` No ads on this website.
- Easylist
- OS/version: Windows 10 64-bit / Ubuntu 18.04
- Browser/version:  Opera 68.0 
- Adblock Extension/version: Adblock Plus 3.8
=> https://adweb.pro

easylist/easylist_general_block.txt
`https://adscale.pl`
False positive. Website blocked with filter `/adscale.`
- Easylist
- OS/version: Windows 10 64-bit / Ubuntu 18.04
- Browser/version:  Opera 68.0 
- Adblock Extension/version: Adblock Plus 3.8
=> https://adscale.pl

easyprivacy/easyprivacy_whitelist_international.txt
This rule:
`||cxense.com^`
Prevents most read articles section from showing articles.
("Luetuimmat" in Finnish).
https://www.ksml.fi/
https://www.savonsanomat.fi/
(Peter Lowe's list suffers the same issue @pgl)
=> P: ksml.fi|savonsanomat.fi

easyprivacy/easyprivacy_whitelist_international.txt
Easyprivacy prevents some articles from appearing.
Sample link: https://anna.fi/hyvinvointi/liikunta/anna-energiaa-livetreeniryhma-treenaa-kotona-liity-nyt
Suosittelemme (Recommended)
Lue myös (Also read)
Made a whitelist rule, I also simplied an existing rule as it's not reasonable to have separate rules with different subdomains. (kiwi45.leiki.com, kiwi66.leiki.com).
Edit: also `kaksplus.fi` suffers similar issue. "Suosittelemme" (Recommended) section is missing.
Sample link:
https://www.kaksplus.fi/lifestyle/lapsimessut-peruttiin-kokonaan-talta-vuodelta-ei-viela-ensi-maaliskuussakaan/
Before whitelisting:
After whitelisting:
=> P: anna.fi|kaksplus.fi

easylist/easylist_whitelist_general_hide.txt
URL: `https://www.minato-yamaguchi.co.jp/yama/index.html`
Issue: the site's internal links are hidden.
Env: Brave 1.9.76 + uBO 1.27.10 default settings, accessed from Japan
=> P: fix minato-yamaguchi.co.jp

easylist/easylist_whitelist_general_hide.txt
URL: `https://www.mashingup.jp/2020/05/citizen_xc_basiccollection_5.html?itm_source=article_link&itm_campaign=https://www.mashingup.jp/2020/05/iges_7_b.html&itm_content=https://www.mashingup.jp/2020/05/citizen_xc_basiccollection_5.html`
Issue: sponsored articles are completely hidden.
Env: Brave 1.9.76 (its blocker turned off) + uBO 1.27.10 default lists
=> P: fix mashingup.jp

easyprivacy/easyprivacy_whitelist.txt
Fixes an issue with tag popups not working correctly on the Stack Exchange network of Q&A sites, for tags whose names happen to correspond to those of tracking scripts (e.g. "google-analytics"). Relevant issue report: https://forums.lanik.us/viewtopic.php?f=64&t=44747
Full list of Stack Exchange Q&A domains: https://meta.stackexchange.com/questions/81379/can-we-have-a-list-of-all-the-stack-exchange-domains-somewhere-for-firewall-pur
=> Fixes https://forums.lanik.us/viewtopic.php?f=64&t=44747

easylist/easylist_whitelist.txt
This rule: `||2mdn.net^` blocks videos from playing. Added a whitelist rule. 
Sample link: https://www.tilt.fi/jaksot/jakso-14-kevat-2020/
=> P:  https://www.tilt.fi/jaksot/jakso-14-kevat-2020/

easylist_cookie/easylist_cookie_whitelist_general_hide.txt
`https://online.simplii.com/ebm-resources/public/client/web/index.html#/transfers/accounts/add/terms`
You must have a Simplii Financial bank account to access the above URL.
When Fanboy's Annoyance List is enabled, you can't consent to the pre-authorized debit agreement. If you can't consent, then no-fee bank-to-bank money transfers may be completely impossible.
I'm using uBO 1.27.10 on Chromium 81 on 32-bit Xubuntu 18.04.4 LTS.  I have Fanboy's Annoyance List enabled, which is the source of the problem.
I thank you for all the effort you put into maintaining your lists!
=> P: fix simplii.com

easylist_cookie/easylist_cookie_general_hide.txt
Cookie banner block, general rule.
https://www.online-convert.com/
Fixes #5549
=> A: online-convert.com

easylist/easylist_adservers_popup.txt
I found a small problem in a self-converted version of EasyList wherein `142.91.65.100.in-addr.arpa` was falsely blocked by `||142.91.`.
While I am aware that I've got a pretty weak point on stand on, considering entries with both `$popup` *and* `$third-party` were never meant to be used for broad IP blocking ever, I feel that the risk of blocking reverse lookups remain present even if just under pretty specific circumstances.
To my pleasant surprise, RegEx-based entries (At least those that were not specific) were unaffacted by this, which makes for a decent argument for not converting e.g. `/(https?:\/\/)104\.154\..{100,}/$document` into `://104.154.$document,domain=~in-addr.arpa` after all.
=> Amended 3 IP-based entries

easylist/easylist_allowlist.txt
URL: `https://www.jmedj.co.jp/`
Issue: Some useful images (e.g. article search, links to back issues of their magazine) are blocked by EasyList rules `files/ad/*` and `banner/ad/*`
Env: Brave 1.10.97 (own blocker disabled) + uBO 1.27.10 default settings
=> P: fix jmedj.co.jp

easylist/easylist_allowlist_general_hide.txt
URL: `https://spjai.com/chatbot-merit-demerit/`
Issue: tag cloud is wrongly hidden.
Env: Brave 1.10.97 + uBO 1.27.10 default settings
=> Fix spjai.com

easyprivacy/easyprivacy_thirdparty.txt
This is not a telemetry/tracking service but a channel for delivering some backend-to-client notifications.
Various features don't work in Skype on web if blocked: audio/video calls, contact list updates, profile/avatar changes don't appear until manually reloaded etc.
=> M: go.trouter.skype.com is not a tracker

easylist_cookie/easylist_cookie_allowlist.txt
Videos don't work. Added a whitelist rule.
Sample video: https://www.southparkstudios.nu/full-episodes/s02e15-spookyfish#source=94aaabd4-cb94-40e1-82fb-a158ba09aa67%3A25eeb97e-ed8e-11e0-aca6-0026b9414f30&position=15&sort=%21airdate&autoPlay=true
Note: you must have a Finnish ip.
=> P: southparkstudios.nu

easyprivacy/easyprivacy_specific_international.txt
https://www.tori.fi/
Note, I think it's better to retain prefix `www.` in this case because the word `tori` is a general Finnish word that could be used as a suffix in other domain names.
One example: http://keskustori.fi/ (could be more)
=> A: www.tori.fi

easylist/easylist_allowlist.txt
URL: `https://locipo.jp/creative/b8d8898e-b493-42bc-a890-6eb175a47a8e?list=b2b78c58-38c3-4e40-aab3-7ba636cedb4d`
Issue: video can't be played.
Env: Brave 1.10.97 (its blocker turned off) + uBO 1.27.10 default lists + AG JPN
Note: apparently the page itself is not geo-restricted but if I use US VPN I got an error on playing the video.
=> P: fix locipo.jp videos

easylist/easylist_specific_hide.txt
hides affiliate product ads on G/O Media properties.
affiliate links are served in a JS-inserted  DOM node with the class `js_commerce-inset-permalink` that includes several nested divs including the text "G/O Media may get a commission" and an anchor element with the attribute of `data-ga["Commerce Inset"]` or `data-ga["CommerceInset"]` but a different domain for each `href` value.  Hiding the whole inserted DOM node is the most consistent way to remove the ads. and removing only the anchor leaves the green bordered div and the commission text.
related: #5539
=> A: G/O Media Affiliate Link Ads

easylist/easylist_allowlist.txt
URL: `https://tver.jp/corner/f0054634`
Issue: video images not shown - only sounds play.
Env: Brave 1.11.101 + uBO 1.27.10 default lists + AGJPN
Steps to reproduce:
1. As the contents is geo-restricted, use Japanese VPN - but it's possible they block some known VPN IPs.
2. If you get this questionnaire, just click "あとで" on to skip it.
3. Usually the video automatically starts, but you can of course click the play button if not. Now you'll get only sounds and not movie.
It should be:
=> P: fix tver.jp video

easyprivacy/easyprivacy_allowlist.txt
URL: `https://www.takeda.com/ja-jp/`
Issue: Broken layout by EasyPrivacy rule `||episerver.net^$third-party` on Firefox + uBO
Env: Firefox 79.0 + uBO 1.28.4 <strong>+ CleanBrowsing DNS</strong>
With this fix still the rest of episerver trackers are blocked. It's not necessary to allow scripts too for layout but apparently they're necessary for some site function.
=> A: https://www.takeda.com/ja-jp/ CNAME issue

easylist/easylist_specific_hide.txt
Hi! Will building a new website for Nation.co.ke (for the Nation Media Group), I encountered the issues that our footer (with classname `.footer`) was getting removed by ad blockers. Since this was a hide for previous versions of websites of the Nation Media Group, this can be removed.
=> Remove Nation Media Group specific hide

easylist/easylist_allowlist.txt, fanboy-addon/fanboy_notifications_general_block.txt
URL: `https://akiba-souken.com/article/46268/`
Issue: push notification not blocked by current rules of Fanboy Annoyances/Notifications Blocking List.
Env: Brave 1.11.104 + uBO 1.28.4 default + Fanboy Annoyances lists
=> A: block akiba-souken.com push notification

easylist/easylist_general_hide.txt
Remove links to gitads.io's tracking server.
Example repo containing an ad: https://github.com/acmesh-official/acme.sh/blob/bb7c11adf1c5940990f58b99dc7db9f0e1ab1a1a/README.md
=> A: https://gitads.io/

easyprivacy/easyprivacy_specific.txt
Remove `$~ping`, beacon tracking is getting through. I use bing pretty regularly & this will not break anything.
```
+11			www.bing.com	1	beacon	https://www.bing.com/fd/ls/lsp.aspx
+4			www.bing.com	1	beacon	https://www.bing.com/fd/ls/lsp.aspx?
+2	/ls.gif?	--	www.bing.com	1	beacon	https://www.bing.com/fd/ls/ls.gif?IG=E5AFB588F44A41F29F84FE11819A60B7&Type=Event.ClientInst&DATA=%7B%22T%22%3A%22CI.Info%22%2C%22TS%22%3A1596650620567%2C%22AppNS%22%3A%22idpfs_1.LB.1_1%22%2C%22K%22%3A%225118.1%22%2C%22Name%22%3A%22ImageViewer%22%2C%22Component%22%3A%22currentimg%22%2C%22url%22%3A%22https%3A%2F%2Fgraphene.limited%2F_Media%2Fhardware_faults-2.jpeg%22%2C%22page%22%3A%22ImageDetailMainImage%22%7D&log=UserEvent
+2	/ls.gif?	--	www.bing.com	1	beacon …
```
=> M: bing.com

easyprivacy/easyprivacy_allowlist.txt
Without this exception, the script at `https://assets.adobedtm.com/launch-ENe8f70e36bc2f473e93435c31a9a5ba80.min.js` throws an error and deletes the whole body element... 😅 Easy to reproduce in ABP by enabling EasyPrivacy.
Fixed in uBo unbreak already: https://github.com/NanoMeow/QuickReports/issues/1477 (since Jul 2019)
Alternatively, you could modify this allow filter `@@||adobedtm.com/launch-$script` to 
```
@@||adobedtm.com/launch-$script,domain=~bellinghamherald.com|~bnd.com|~bradenton.com|~centredaily.com|~charlotteobserver.com|~elnuevoherald.com|~fresnobee.com|~heraldonline.com|~heraldsun.com|~idahostatesman.com|~islandpacket.com|~kansas.com|~kansascity.com|~kentucky.com|~ledger-enquirer.com|~macon.com|~mcclatchydc.com|~mercedsunstar.com|~miamiherald.com|~modbee.com|~myrtlebeachonli …
```
=> Fix breakage on McClatchy sites

easylist_cookie/easylist_cookie_international_specific_block.txt
Alma media's cookie notification block for several websites, such as:
https://www.tivi.fi/
https://www.mikrobitti.fi/
https://www.arvopaperi.fi/
(There are more but those samples are probably enough.)
=> A: tivi.fi

easylist/easylist_adservers.txt, easyprivacy/easyprivacy_thirdparty.txt
pageviews.io is not an adserver, but a pageview counter service.
https://pageviews.io/privacy/ disclosure
pjtsu.com is a hosting internal subdomain that is used by hundreds of
legitimate websites, pv. is just one of them that happens to host a
pageview counter API.
All questions can be directed to support@pressjitsu.com
=> Move pv.pjtsu.com to privacy

easylist/easylist_allowlist_general_hide.txt
URL:
```
https://www.isewanferry.co.jp/
http://jreu-h.jp/
https://www.nexco-hoken.co.jp/
```
Issue: isewanferry and jreu-h: contact info hidden
nexco-hoken: Privacy-mark which is a Japanese certification seal for privacy is hidden.
<details>
</details>
Env: Firefox 79.0 + uBO 1.29.2 default lists and AGJPN
=> P: fix FP on three JP sites

easylist/easylist_allowlist.txt
Banners showing suppliers are blocked by an EL rule `/images/adv/*`.
<details>
</details>
=> P: https://www.velet.jp/ breakage

easyprivacy/easyprivacy_allowlist_international.txt
URL: `https://www.sony.jp/`
Issue: You can't switch tabs on the page:
Env: Firefox 80.0.1 + uBO 1.29.2 default lists
Note: another fix is needed on uBlock Unbreak to allow tiqcdn.
=> P: www.sony.jp can't switch tabs

easylist_cookie/easylist_cookie_general_hide.txt
Generic cookie hiding rule.
"evasteseloste" means "cookie description" if translated.
=> A: autoq.fi (generic Easylist cookie)

easylist/easylist_allowlist_general_hide.txt
https://www.metropoli.net/lifestyle/elokuvat/kriitikoiden-parjaama-sonic-the-movie-saa-jatko-osan/
Easylist hides an element that is just a link to a podcast page.
=> P: metropoli.net

easylist/easylist_allowlist_general_hide.txt, easylist/easylist_specific_hide.txt, easyprivacy/easyprivacy_allowlist_international.txt
https://seura.fi/hyvinvointi/vaarantaako-maito-terveyden-laillistettu-ravitsemusterapeutti-vastaa/
Easylist hides articles under "Lisää aiheesta" (More on this topic) section. Those should not be hid.
Also some whitelistings for Easyprivacy are needed as well (added).
Also added a hiding rule to hide nativead elements in a proper way so that non-ads won't be hid.
=> P: seura.fi

easylist_cookie/easylist_cookie_general_hide.txt
Generic hiding rule.
https://www.autouncle.fi/
For this specific page, it hides a remnant cookie overlay element.
=> A: autouncle.fi (generic Easylist cookie)

easylist/easylist_allowlist.txt, easylist/easylist_allowlist_general_hide.txt
URL: `https://www.iejima.org/`
Issue: This is an official home page of a village but banner links to sub pages are blocked by `.org/ad-` in EL.
<details>
</details>
Tested on Firefox 81.0.2 + uBO 1.30.4 default + AGJPN
=> P: fix iejima.org banner links

easylist/easylist_allowlist.txt
URL: `https://ascii.jp/elem/000/004/030/4030245/`
Issue: A minor FP, the number indicator on a ranking widget is blocked by EL:
<details>
</details>
Env: Firefox 81.0.2/uBO 1.30.4 default + AGJPN
Note: originally PRed to regional list: https://github.com/AdguardTeam/AdguardFilters/pull/65635
=> P: fix https://ascii.jp/elem/000/004/030/4030245/ ranking numbers

easyprivacy/easyprivacy_allowlist.txt
URL: `https://www.jmp.com/ja_jp/search/jmp.html?q=%E7%B5%B1%E8%A8%88` (same results for en_us)
Issue: search results not shown
Env: Firefox 81.0.2 + uBO 1.30.4 default lists
=> Fix www.jmp.com search

easyprivacy/easyprivacy_thirdparty.txt
https://app.datadoghq.eu/logs/livetail
Since [this commit](https://github.com/easylist/easylist/commit/dc6029beea066465a09f76aa6e61945cbb375430), domain `logs.datadoghq.eu` is blocked. But the Datadog website is using the domain `live.logs.datadoghq.eu` as an API, so it breaks legitimate user usages.
easyprivacy
Block the `logs.datadoghq.eu` domain only for third party usages, same as `logs.datadoghq.com`.
Related PR: https://github.com/easylist/easylist/pull/5107
=> M: https://app.datadoghq.eu/

easyprivacy/easyprivacy_allowlist.txt
URL: `https://www.lacoste.com/us/lacoste/men/clothing/jackets-coats/men-s-motion-water-resistant-colorblock-zip-jacket-/BH5316-51.html?color=WBE`
Issue: size selection for wear doesn't work due to `/click-analytics.`:
<details>
</details>
Env: Firefox 82.0.2 + uBO 1.30.6 default + AGJPN
=> P: fix www.lacoste.com size selection

easylist/easylist_allowlist_general_hide.txt
URL: `https://gotoeat.maff.go.jp/`
Issue: Contact info wrongly hidden:
<details>
</details>
Env: Firefox 82.0.3 + uBO 1.30.6 default + AGJPN
=> P: fix https://gotoeat.maff.go.jp/ contact info hidden

easyprivacy/easyprivacy_allowlist_international.txt
URL: `https://marshmallow-qa.com/marshmallow`
Issue Send (おくる in Japanese) button in comment form doesn't work.
<details>
</details>
Env: Firefox 82.0.3 + uBO 1.30.6 default + AGJPN
=> fix https://marshmallow-qa.com/marshmallow Send button

easylist/easylist_adservers.txt
URL: `https://manganelo.link/manga/read-miss-not-so-sidekickk/chapter-118/`
Issue: popup:
<details>
</details>
Env: Firefox 83.0 + uBO 1.30.6 default lists
=> A: https://manganelo.link/manga/read-miss-not-so-sidekickk/chapter-118/

easyprivacy/easyprivacy_specific_international.txt
URL (use Chrome, the game refuses other browser and redirect you): `http://game.granbluefantasy.jp/`
Note: I created an account and played the game shortly, so far no issue by blocking this analytics. You don't need account to see the request.
=> A: http://game.granbluefantasy.jp/

easyprivacy/easyprivacy_allowlist_international.txt
URL: `https://www.pizzahut.jp/`
Issue: address search doesn't properly work.
<details>
</details>
Env: Firefox 84.0.1 + uBO 1.32.5b0 default lists + AGJPN
=> P: https://www.pizzahut.jp/ (fix address search)

easyprivacy/easyprivacy_thirdparty.txt
filter 
```
||tra.scds.pmdstatic.net/pmc-starter/$script
```
problem
* Prevent authentication to private space on : programme-tv.net, programme.tv, cesoirtv.com, voici.fr, gala.fr ...
source : 
* https://forums.lanik.us/viewtopic.php?p=158583#p158583
=> P: (prismaconnect.fr) https://www.programme-tv.net/

easylist_cookie/easylist_cookie_specific_hide.txt
https://www.sfanytime.com/
Note: this site is multilingual site (4 languages) but doesn't have English. Hopefully this list is still the correct one.
Language selector is located at the bottom right of the page:
=> sfanytime.com (specific cookie hide)

easylist_cookie/easylist_cookie_general_block.txt
A generic rule to block GDPR banner.
https://duunitori.fi/
=> A: duunitori.fi (generic cookie block)

easylist_cookie/easylist_cookie_general_hide.txt
Creating a new account cannot be done on https://www.tori.fi/tili because a necessary checkbox is being removed. Added a fix. I have seen this issue before so I made a modification to the generic rule instead of creating a whitelist rule for this site.
Before:
After:
=> P: tori.fi (cookie hiding rule removes a checkbox)

easyprivacy/easyprivacy_trackingservers_international.txt
<details>
</details>
Tracker path: `https://cdn.activity.smart-bdash.com/tag-manager/bd-2vtywl/btm.js`
Partly blocked by `/tracking-script/*` but if allowed xhr for `
https://tracker.smart-bdash.com/tracking` will also be called.
=> A: www.onamae.com

easylist_cookie/easylist_cookie_allowlist_general_hide.txt, easylist_cookie/easylist_cookie_general_hide.txt
I think this modification could potentially fix many sites where a checkboxes are being removed because they have an id "privacypolicy".
I also removed filter added by this pull req: https://github.com/easylist/easylist/pull/6597 as it becomes redundant
I got inspiration for this change from here: https://github.com/easylist/easylist/pull/7309
=> M: ###privacypolicy -> ###privacypolicy:not(input)

easylist/easylist_allowlist.txt
New entries never load:
<details>
</details>
The same happens at `https://baseball.yahoo.co.jp/npb/`. There's also mobile-only issue by the same script at `https://creators.yahoo.co.jp/nikunokoujinikuyo/0300078364` I forgot to report. At this point it will be better to exclude the whole `yahoo.co.jp` but `/yads/*$domain=~yahoo.co.jp` is not viable as there are other patterns of `/yads/*` such as `||yimg.jp/images/listing/tool/yads/yads-iframe.html?` and `yads-` brings other issues.
=> P: https://soccer.yahoo.co.jp/jleague/

easylist_cookie/easylist_cookie_allowlist.txt
Due to this https://github.com/easylist/easylist/issues/4629 issue report, this whitelist rule was added. I tested and now downloading counter starts and I can download normally even if I block that address.
Sample link to test with: https://sourceforge.net/projects/megui/
=> M: sourceforge.net (removing a cookie whitelist rule)

fanboy-addon/fanboy_notifications_allowlist.txt, fanboy-addon/fanboy_notifications_general_block.txt
Another problem by `jquery.smartbanner.js|` at `https://www.levi.jp/home`:
<details>
</details>
Rather than individual fixes I propose to change to `/js/jquery.smartbanner.js|` following AG Annoyances, which also fixes https://github.com/easylist/easylist/pull/7406 and still covers what are blocked by the rule in the original PR: https://github.com/easylist/easylist/pull/5285
=> M: make more specific

easylist_cookie/easylist_cookie_allowlist_general_hide.txt
The page cannot be used without a whitelist rule. Both rules are needed - the other for the banner to be visible, other for giving an access to cookie settings ("Evästeasetukset" in Finnish).
Sample link: https://www.datakauppa.fi/tuote/deltaco-uh-408-usb-2-0-hubi/
=> P: datakauppa.fi (cookie banner hiding breaks the page)

easylist/easylist_specific_block.txt
Reproducing issue doesn't require account, but fix confirmation does.
Another request `https://api.nicoad.nicovideo.jp/v1/live/statusarea/lv330945055` is also not for ads, it's kinda notification and no need to block.
<details>
</details>
=> P: https://live.nicovideo.jp/watch/lv330945055

easylist_cookie/easylist_cookie_international_specific_hide.txt
Cookie Banner was already blocked, but a background overlay still remained.
https://imgur.com/a/NY8vFEq
=> Hide cookie banner background overlay on buecher.de

easylist_cookie/easylist_cookie_international_specific_hide.txt
https://www.helmet.fi/ - no sign of cookie banner. I loaded the page in incognito mode, disabled Ubo and still no banner.
=> M: redundant filter

easylist_cookie/easylist_cookie_specific_hide.txt
A rule to hide cookie banner on the login page and on the "checkpoint" page only. Doesn't hide cookie banner on fan pages, which causes scrolling issues.
Samples:
https://www.facebook.com/ - banner hid
https://www.facebook.com/Motorhead-Fan-Page-188921241129818/ - banner not hid
https://github.com/easylist/easylist/issues/6129
=> A: facebook.com (cookie hide)

easylist_cookie/easylist_cookie_specific_hide.txt
The current filter blocks all banners used on Patreon, including important parts of the user experience. This fix will block only the cookie disclosure banner.
=> Fix Patreon cookie banner filter

easylist_cookie/easylist_cookie_general_block.txt
Redundant by `/cookie-consent-`
=> M: remove redundant filters

easylist/easylist_thirdparty.txt
Hello,
I noticed that on a site I'm using one of the main functionalities is blocked by the following rule:
```
||widget.justwatch.com^$third-party
```
Is there a way this can be made more fine grained?
Site: https://www.clapper.com.br/titulo/it-a-coisa
Screenshot:
=> clapper.com.br

easyprivacy/easyprivacy_thirdparty.txt
gem.com is often used for tracking email access and click throughs by recruiters
=> Block tracking from gem.com domain

easyprivacy/easyprivacy_thirdparty_international.txt
Search for `电脑桌面小火箭加速器_【一键访问国外网站】` in Google will be better than direct visit. Since `s.cdin.me/i.php` which is only to get IP geolocation info (so not much worth blocking) is not always fired, here's log:
=> A: https://content.huchezai.com/weibo/1693163980/K0Z3ixtvy

fanboy-addon/fanboy_social_thirdparty.txt
`https://b.hatena.ne.jp/entry/s/b.hatena.ne.jp/15th`
The filters including Fanboy’s Social which block Hatena Bookmark widgets break the social bookmark service itself.
=> P: https://b.hatena.ne.jp/entry/s/b.hatena.ne.jp/15th

easyprivacy/easyprivacy_allowlist.txt
The website displays nothing but its header.
</details>
=> P: https://book.dmm.com/

easylist_cookie/easylist_cookie_specific_block.txt
https://asmand.wordpress.com/
A generic cookie blocking rule for wordpress-sites.
=> A: asmand.wordpress.com (generic cookie block)

easylist/easylist_allowlist_general_hide.txt
EasyList hides information about where the products are sold.
</details>
=> P: https://www.flexjapan.co.jp/site/toukenranbu

easylist/easylist_general_hide.txt
Ex.
<details>
</details>
The rest:
```
www.milffabrik.com
www.xhamster-sexvideos.com
www.hdpornos.net
www.gutesexfilme.com
```
=> M: fix ad-leftover on various NSFW sites

easylist/easylist_allowlist_general_hide.txt, easylist_adult/adult_specific_hide.txt
`https://javynow.com/`
Issue: Hot Videos (not ads but links to actual videos) hidden:
<details>
</details>
Addressing the right black space requires CSS injection but already done on uBO and on AG:
https://github.com/uBlockOrigin/uAssets/commit/f4428524b19e7ecf0dccf47cab817533fc7d5997
https://github.com/AdguardTeam/AdguardFilters/commit/6675c6a80cceb5a67c6748323af47f98721634d8
=> P: (nsfw) https://javynow.com/

easyprivacy/easyprivacy_allowlist_international.txt
`https://friday.kodansha.co.jp/ranking` 
1. The ranking of most viewed articles doesn't appear.
`@@||api.cxense.com/document/search$xmlhttprequest,domain=friday.kodansha.co.jp`<details><summary>Screenshot:</summary>
</details>
2. The article search doesn't works correctly.
`@@||api.cxense.com/public/widget/data$xmlhttprequest,domain=friday.kodansha.co.jp`<details><summary>Screenshot:</summary>
</details>
=> P: friday.kodansha.co.jp

easylist/easylist_adservers.txt
Overlay causing popup:
IDK if the DOWNLOAD and PLAY NOW buttons should be addressed. Maybe in Annoyance?
=> A: dcraddock.uk

easylist/easylist_allowlist.txt
Images blocked by `.com/ads/$image,object,subdocument,domain=~developers.google.com|~sabotage-films.com`:
Fix on your side if `domain=~` is preferred.
=> P: https://www.asahi.com/ads/clients/bonmarche/life/life20201119.html

easylist/easylist_general_hide.txt, easylist/easylist_specific_hide.txt
**Account required**
Caused by a generic cosmetic filter `#ad_sidebar` from EasyList
=> P: https://admin.blog.fc2.com/control.php?lang=ja&change_lang=true

easylist/easylist_allowlist.txt, easylist/easylist_allowlist_general_hide.txt
The whole page is hidden by generic cosmetic `#page_ad` and `/img/ad/*` blocks non-ads images.
=> P: https://gunosy.co.jp/ad/

easylist_cookie/easylist_cookie_specific_uBO.txt
https://ubuntu.com/
Added a filter to block cookie notification. Hiding the cookie banner does not always work fast enough, I occasionally see a blink.
=> A: ubuntu.com (cookie block, ubo)

easylist/easylist_adservers.txt, easyprivacy/easyprivacy_trackingservers_international.txt
`||seesaa.jp^$third-part` added by 5cf8ea7 causes FP largely on blogging services made by seesaa.
ex. Can't play audio.
`http://nuru8-tasogare.seesaa.net/article/481336062.html`
`||sda.seesaa.jp^` is can be found on `http://brow2ing.com/` and `https://blog.ss-blog.jp/`, for example.
See also: AdguardTeam/AdguardFilters#47404
=> M: ||seesaa.jp^$third-part is problematic

easylist/easylist_thirdparty.txt
Japanese site but this is used by a few other international sites too.
=> A: https://bhnotes.com/2017/02/14/web-moved-rental-server/

easylist_cookie/easylist_cookie_international_specific_hide.txt
Currently, Easylist breaks time appointment:
https://www.parturikampaamodiva.fi/ajanvaraus
I added a fix to block cookie banner properly without breakages.
Note, that appointment function is loaded through an iframe which is why it needs a different url for the actual filter.
=> P: parturikampaamodiva.fi (broken cookie blocking)

easyprivacy/easyprivacy_trackingservers_international.txt, fanboy-addon/fanboy_social_thirdparty.txt
digitiminimi.com is not a tracking server. It provides a Twitter button and retrieves the number of shares and likes on Twitter.
ex. `https://diamond.jp/articles/-/224881`
=> M: digitiminimi.com from tracking to social

easyprivacy/easyprivacy_general.txt
`/entry.count.image?` is added by https://github.com/easylist/easylist/commit/12fa20426b014f4d733400778147ffb84ca6e5a3
The commit is associated with a 404 URL, but since it's a hatenablog article, I think `/entry.count.image?` was introduced to block 
`s.st-hatena.com/entry.count.image?uri=`
This is used to get the number of likes pressed to quoted hatenablogs.
URL: `https://honeshabri.hatenablog.com/entry/hatebu_pv`
`/entry.count?` is added by https://github.com/easylist/easylist/commit/b9ab14237d7814b1e2cfbab6aaa07dd8a7c1431f
The commit is associated with `http://jisakutech.com/archives/2017/04/33003` and the added filter blocks
`b.hatena.ne.jp/entry.count?`.
This is used to get the number of people who have socially bookmarked the …
=> M: /entry.count.image? & /entry.count? is not a tracker

easylist/easylist_allowlist_dimensions.txt
Non-ads images are blocked on some blogs hosted on livedoor Blog.
~~~
blog.livedoor.jp/news23vip
yurukuyaru.com
sakaguchiyuko.blog.jp
~~~
=> P: blog.livedoor.jp

easyprivacy/easyprivacy_allowlist_international.txt, easyprivacy/easyprivacy_general.txt
EasyPrivasy already has three exceptions in allowlist, `kobe-np.co.jp` : https://github.com/easylist/easylist/commit/85053012d5194f3cf04fdc65a977baf7cc93d568 `toonippo.co.jp`: https://github.com/easylist/easylist/pull/5452 `jsports.co.jp`: https://github.com/easylist/easylist/pull/7131.
I found three more similar examples  `https://theatrelive.mu-mo.net/plus-a/audition`, `http://pc.jtta-shidou.jp/`, and `https://kbc.co.jp/movie/`.
The problematic filter was added by easylist/easylist@b4fad44, which is associated with `http://www.fnn-news.com/`, Japanese TV news websites. 
I don't know what @Khrin blocked, but the website used uliza's video player at that time according to  [Internet Archive](https://web.archive.org/web/20180617053135mp_/http://www.fnn-news.com/news/headlines/articles/CONN0 …
=> M: `/RequestVideoTag` is useless and breaks the uliza's video player.

easylist/easylist_allowlist_general_hide.txt
The entire page is hidden by a generic cosmetic filter, `.sp-ad`.
<details><summary>Screenshot01</summary>
</details>
<details><summary>Screenshot02</summary>
</details>
=> P: https://www.itempost.jp/

easyprivacy/easyprivacy_thirdparty.txt
Hi guys! :wave:
I'm Ansgar. We (`https://arc.io/team`) build Arc (`https://arc.io/`), a
peer-to-peer content delivery network (CDN) that runs in the browser.
Like many, we use Sentry (`https://sentry.io/`) to monitor and improve
our software. It was for this use of Sentry that Arc was added to
`easyprivacy_thirdparty.txt` in https://github.com/easylist/easylist/commit/76167fc006588056a05cef3c1eaf415591a2115d.
See here for prior discussion on Sentry:
* https://github.com/easylist/easylist/pull/7207
* https://github.com/easylist/easylist/issues/6963
Since we self host Sentry, I created this PR to more accurately block
Arc's Sentry, at `sentry.arc.io`, and not Arc's entire widget.
Thank you!
=> More accurately block arc.io's Sentry, sentry.arc.io, instead of Arc's entire widget.

easyprivacy/easyprivacy_allowlist.txt
`https://automate-frontend.linksynergy.com/minified_logic.js`
According to my observation, blocking this script occasionally prevents with image loading and always breaks embedded tweets and instagrams.
It is often used on Japanese sites, but is also used on English sites.
It can also be fixed with a scriptlet such as `4meee.com##+js(aopw, _rakuten_automate)`, which is the best solution, but cannot makes generic.
**Example**
Broken images
`https://4meee.com/articles/view/30008569`
`https://jamalouki.net/`
`https://www.winecompanion.com.au/`
Broken embed tweets and/or instagram
`https://www.gamespark.jp/article/2017/12/14/77430.html`
`https://petpedia.net/article/894/neko_hetakuso`
`https://www.sassyhongkong.com/lifestyle-culture-instagram-apps-insta-story-tips/`
=> M: Blocking Rakuten Automate scripts causes breakages of images or embed social media posts.

easyprivacy/easyprivacy_allowlist_international.txt
Account required
Play button doesn't work due to `/scripts/analytics/*`:
=> P: https://game-tsutaya.tsite.jp/game/detail/209

easylist/easylist_general_hide.txt, easylist/easylist_specific_hide.txt
`msn.com##.replacead23` is blocking normal articles (confirmed both on Japanese and English locale):
FP in https://github.com/easylist/easylist/commit/e40af52d8971eea577d95dd7e7d1ad990a800ef9 can be avoided by adding either `.secondary` or `[data-id]`:
The last one will be difficult to reproduce, URL is `https://www.msn.com/en-us/health/fitness/khloe-kardashian-reveals-her-challenging-butt-toning-workout/ar-AALoNIi?li=BBnba9O` but just visiting doesn't work. On my end only shown if I choose "MSN World wide" at the bottom of the top page, set to US version, and then visit the URL - but even with this procedure only on one Firefox profile and not on another. Hope you can reproduce or else these screenshots are enough as an evidence:
=> M: update msn.com

easylist/easylist_allowlist.txt, easylist/easylist_allowlist_general_hide.txt, easyprivacy/easyprivacy_allowlist_international.txt
`https://hatenacorp.jp/`
`https://hatenacorp.jp/ads`
See screenshots below.
Screenshot 1: `hatenacorp.jp#@#.ads-link` (EasyList)
Screenshot 2-1: `@@||googletagmanager.com/gtm.js$script,domain=hatenacorp.jp` (EasyPrivasy)
Screenshot 2-2: `@@||hatenacorp.jp/_next/static/chunks/pages/ads-$script,~third-party` (EasyList)
<details>
<summary>Screenshot 1</summary>
</details>
<details>
<summary>Screenshot 2</summary>
</details>
=> P: hatenacorp.jp

easylist/easylist_specific_block.txt
`nicoad.nicovideo.jp` is solely used for user-based recommendation and not for ads. Many exception have already been added and possibly more to come. It's better to remove the blocking unless they start to abuse the domain to deliver ads.
An example of nicoad can be found here if you unblock the request: `https://www.nicovideo.jp/video_top?cmnhd_ref=device%3Dpc%26site%3Dniconico%26pos%3Dheader_servicelink%26page%3Dwatch`
This is more comparable to "Top recommended video" of a kind.
=> M: remove nicoad.nicovideo.jp blocking

easylist/easylist_allowlist_general_hide.txt
A filter rule hides product info texts, whitelisting added.
Sample site: https://m.nettiauto.com/ford/mondeo/12210087?vifAdCount=28&vifNav=Y
info texts blocked:
whitelisted:
Multiple domains. All these sites belong to the same site cluster and they have a desktop version (with www-prefix). Though m.nettivuokraus.com does not actually exist currently, I hope it could still be included because some day nettivuokraus.com could have a mobile version of m.nettivuokraus.com and if that happens, this issue would happen with that domain as well and nobody is notifying when that site goes to live. All these other domains have a m-prefixed mobile version.
(The mobile version I linked, can be accessed on desktop by this button:)
=> P: m.nettiauto.com (multiple domains, product info texts hid)

easylist_cookie/easylist_cookie_specific_uBO.txt
https://elisaviihde.fi
I know that `##.ea-cookie-disclaimer` exists as a generic filter already, but as Ubo does not inject all thousands of generic filters unconditionally on each and page (which is a great performance optimization), it may lead to a situation where a generic filter causes the element to flicker once before it's hidden. I experience flickering somewhat often on this page, which is why I want to add a specific filter in order to avoid flickering.
https://www.reddit.com/r/uBlockOrigin/comments/ok2u55/how_to_block_a_cookie_banner_via_scriplets/
=> A: elisaviihde.fi (cookie banner hide, Ubo)

easylist/easylist_allowlist.txt
`https://kmsv.jp/`
I don't know why they assigned such path names but internal links are badly broken by `/images/ad/*`:
=> P: kmsv.jp

easylist/easylist_allowlist.txt
(Real) Address info at the bottom of the page is blocked by `/images/ad.$domain=~ngohq.com`:
=> P: http://kaitaro.jp/

easylist/easylist_adservers.txt
`http://www.medyagundem.com/parkta-icerde-dehseti/`
<details> <summary>Screenshot</summary>
</details>
The rule breaks the `medyagundem.com` site. Also site has very few visitors.  Actually, it doesn't look like an ad server. I think it should be removed permanently.
=> Added `third-party`

easylist_cookie/easylist_cookie_international_specific_hide.txt
https://www.scandinavianphoto.fi/
The height of the cookie banner is dependant on browser window size so height can't be used used directly in the filter. Rephrased the filter in a way that height is skipped.
=> M: update broken cookie filter, scandinavianphoto.fi

easylist_cookie/easylist_cookie_general_hide.txt
https://www.utorrent.com/
I added `:not(body):not(html)` as as precaution because it's too common for these entries to blank out websites by matching body or html element.
Imo, precaution entries should be used even more widely in the Cookie list, see my suggestion here:
https://github.com/easylist/easylist/issues/8367
=> A: utorrent.com (generic cookie hide)

easylist/easylist_allowlist_general_hide.txt
`##.adrect` hides too many on the page, hiding e.g. Twitter widget.
<details>
</details>
=> P: https://ascii.jp/

easylist/easylist_allowlist.txt
This is a high-school site and a button to check results of **ad**mission is blocked by `images/ad.` The button currently returns 404 but this is no wonder as now it's not the season of admission here in Japan.
=> P: http://tcm-koko.ed.jp/

fanboy-addon/fanboy_notifications_general_hide.txt
https://www.hardware.fi/uutiset/artikkeli.cfm/2021/07/28/windows-11-markkinaosuus-nousi-jo-hammentavan-suureksi-windows-10-kayttajien-laiska-paivitystahti-paljastui-sekin
=> A: hardware.fi (generic newsletter form)

easylist_cookie/easylist_cookie_general_hide.txt
https://www.metsakeskus.fi/fi
Element name used widely:
https://publicwww.com/websites/%22cookiesjsr%22/
=> A: metsakeskus.fi (generic cookie hide)

easyprivacy/easyprivacy_thirdparty.txt
Fixes issue where customer service chatbot does not appear on page.
`events/pixelEvent` listed on [easyprivacy_general.txt](https://github.com/easylist/easylist/blob/8a64d461463d0ead5142bfd3dd69f993b345532b/easyprivacy/easyprivacy_general.txt#L1758) successfully blocks calls to the Snaps tracking endpoint.
=> P: https://bluenile.com/

easylist_cookie/easylist_cookie_allowlist.txt, easylist_cookie/easylist_cookie_general_hide.txt
https://www.iltalehti.fi/kotimaa/a/7bda0d36-ad9d-4221-9f71-371881a1eb4f
```
Sisältöä ei voida näyttää evästeasetusten vuoksi. Nähdäksesi sisällön,
hyväksy evästeiden käyttö.
```
Translation:
```
Content can't be shown due to cookie settings. In order to see the content,
please accept cookies.
```
But the accept button is removed due this filter, so added exception...
EDIT:
I also found out that a whitelist rule (network filter) is needed so that the button can be clicked.
=> P: iltalehti.fi (cookie accept button removed, and the button can't be clicked)

easyprivacy/easyprivacy_specific_international.txt
There are many trackers on this page, and after rough testing, disabling them did not affect any normal functionality
You may need to log in to see these trackers
=> A: https://user.qzone.qq.com/

fanboy-addon/fanboy_annoyance_international.txt
Fixes https://github.com/easylist/easylistchina/issues/47#issuecomment-890927381
They are indeed self-promotion, not advertising
> 分别是起点的vip卡, 起点的游戏, 所以确实是自我推广, 中文规则不处理自我推广的. 由于也不属于弹窗,或闪烁 也不加入去自我推广列表 .These are self promotions.
=> A: https://www.qidian.com/

easylist/easylist_general_block.txt
Hi!
We are service allowing business to reach advertising platforms the easy way oriented to a wide spectre of customers some of them may use a various range of adblocking software.
We are not ad's or tracking software, please add us to the exclusion list.
=> P: reklama.tochka.com

easylist/easylist_specific_block.txt
Not sure whether `||cnn.com/ad/` is still in use.
=> A: edition.cnn.com

easyprivacy/easyprivacy_trackingservers.txt
I saw this only once while addressing reported scam sites:
=> A: (nsfw) c.datingdeserving.com

easylist_cookie/easylist_cookie_allowlist.txt, easylist_cookie/easylist_cookie_general_block.txt
A generic cookie blocking rule.
Sample page: https://www.puuilo.fi/
Used widely:
https://publicwww.com/websites/Amasty_GdprCookie/
Edit, also added whitelisting for `eckeroline.fi` because blocking this script causes some content not load on the home page.
=> A: puuilo.fi (generic cookie block)

easylist/easylist_allowlist_general_hide.txt
https://www.studio55.fi/
Easylist removes a couple of legit articles (red square around them).
=> P: studio55.fi (article(s) removed)

easylist/easylist_allowlist_dimensions.txt
Dimensional rules need whitelisting, non-ad pictures are removed.
https://radiosun.fi/
Link to a removed image:
https://radiosun.fi/wp-content/uploads/2021/08/RL_300x250.jpg
This image was removed also, noticed it one year ago (not in the front page anymore:
https://radiosun.fi/wp-content/uploads/2020/09/Ylojarven-keilahalli-300x250-1.jpg
=> P: radiosun.fi (images blocking)

easylist_cookie/easylist_cookie_general_hide.txt
Rule `###ot-sdk-btn` might in some cases remove legit buttons, like it does on https://www.maaseuduntulevaisuus.fi/ it removes a button where you can access website's cookie settings. That should not in my opinion be blocked.
Modifying the rule to be like this `###ot-sdk-btn:not(button)` fixes the issue.
Sample picture: 
(Scroll to the bottom of the page. _Evästeasetukset_ means "Cookie settings" in English.
=> M: generic cookie filter modified to avoid unwanted blockings

FOP.py
Based on a request from @ryanbr 
If a filter contains less than three characters and is _not_ a comment, it should be dropped.
Input:
```
a
ab
abc
```
Output:
```
abc
```
=> Drop too short filters in FOP.py

easyprivacy/easyprivacy_allowlist.txt
This is needed for the customer support chat widget ("Need help?") to appear at the bottom right on https://personal.natwest.com/personal/support-centre/cora.html.
=> easyprivacy_allowlist.txt: adobedtm.com exception

easylist/easylist_general_block.txt
Hello,
If a [Dailymotion](https://www.dailymotion.com/) player embed uses the `?ads_params` query parameter, then the entire player, including video playback, is blocked, because of the current generic rule in `easylist_general_block.txt`:
```
?ads_params=
```
Example of mistakenly impacted URL:
```
https://www.dailymotion.com/embed/video/x82dy9e?ads_params=myAdsParams
```
Suggested solution: excluding `dailymotion.com` for this specific rule:
```diff
-?ads_params=
+?ads_params=$domain=~dailymotion.com
```
(Note there are other rules in easylist that already block advertising and tracking efficiently in Dailymotion players, such as 
[`||dmxleo.dailymotion.com^` in `easylist/easylist_specific_block.txt`](https://github.com/easylist/easylist/blob/d1049ad1d3d3747ead78bd76deb040456c956965/easy …
=> ads_params usage on dailymotion.com

fanboy-addon/fanboy_social_allowlist_general_hide.txt
https://www.iltalehti.fi/kotimaa/a/ab17fc98-f600-4ce3-a92e-51753726b467
Social blocking list removes embedded tweets.
=> P: iltalehti.fi (Twitter tweets removed)

easyprivacy/easyprivacy_general.txt
fixes https://github.com/uBlockOrigin/uBlock-issues/issues/1708
This allows no additional tracking, but makes sure that the HeatmapSessionRecording plugin can be bought here successfully:
https://plugins.matomo.org/HeatmapSessionRecording
=> M: fix Matomo Marketplace HeatmapSessionRecording plugin

easylist_cookie/easylist_cookie_specific_hide.txt
https://www.iltalehti.fi/
Note: this site has cookie script allowed because blocking of it causes issues: https://github.com/easylist/easylist/pull/8508
But the cookie overlay can be safely hid without an issue.
=> A: iltalehti.fi (cookie banner hide)

fanboy-addon/fanboy_social_allowlist_general_hide.txt, fanboy-addon/fanboy_social_international.txt
Fixed the wrong hiding rule (follow button in the station, see the top right corner of the image) and hid the share button (see the bottom of the image)
=> A: https://www.bilibili.com/video/BV19L411b7uS

easylist_cookie/easylist_cookie_specific_uBO.txt
https://www.vuokraovi.com/
Generic filter to hide this: `.alma-data-policy-banner` blinks occasionally in uBO, so a specific filter is needed.
=> A: vuokraovi.com (specific data policy banner hide for uBO)

fanboy-addon/fanboy_notifications_specific_hide.txt
https://www.aamuposti.fi/
https://www.heinavedenlehti.fi/
etc...
Hides their "install our app" notification.
The same thing for every of these domains.
=> A: / M: aamuposti.fi + sister sites (app installation notify)

easyprivacy/easyprivacy_general.txt
What had been caught by now-removed `/tracker?*=`.
=> A: www.future-labo.com

easylist_cookie/easylist_cookie_specific_uBO.txt
https://kiuruvesilehti.fi/
https://urjalansanomat.fi/
When cookies are not accepted on these sites, they will limit your scrolling so that you can only scroll and view a small part of the site.
Added fixes. Code responsible for this behavior:
```
function cm_limit(elh) {
window.scrollTo(0,0);
var vh = window.innerHeight;
if (vh > elh) elh = vh;
cm_elh = elh;
var doc = document.documentElement;
window.addEventListener('scroll',function(e) {
var vh = window.innerHeight;
var allow = cm_elh; /* - vh + 0; */
var top = (window.pageYOffset || doc.scrollTop)  - (doc.clientTop || 0);
if (top > allow) 
window.scrollTo(0, allow);
});
}
```
=> P: kiuruvesilehti.fi,urjalansanomat.fi (scrolling blocked if cookies not accepted)

easyprivacy/easyprivacy_general.txt
What had been caught by now-removed `/track?*http$image`.
=> A: re-doing.com

fanboy-addon/fanboy_annoyance_international.txt
This web script will automatically add the tracking parameter `?spm_id_from` after the link on the page
But since it's adding tracking parameters to the link, I don't know if this needs to be added to `EasyPrivacy`
=> A: https://www.bilibili.com/

fanboy-addon/fanboy_social_international.txt
When scrolling the page down, there will be a white bar at the bottom of window. It's a social element hiding remnant.
https://www.forssanlehti.fi/lounais-hame/kanta-hameen-pandemiaryhma-paattaa-uusista-koronasuosituksista-torstaina-1319078
I used a procedural rule because I feel it's more safe in the long term as the page has many elements containing word "herald".
=> A: forssanlehti.fi (Social hiding remnants)

easylist_cookie/easylist_cookie_general_hide.txt
https://www.jarviseudunsanomat.fi/
=> A: jarviseudunsanomat.fi (generic cookie hide)

easylist_cookie/easylist_cookie_specific_uBO.txt
The element blinked on this domain https://vapaavuoro.uusisuomi.fi/
But it's reasonable to cover the main domain as well, and also it's subdomains via one rule.
Subdomains:
https://vapaavuoro.uusisuomi.fi/
https://puheenvuoro.uusisuomi.fi/
Main domain:
https://www.uusisuomi.fi/
=> A: uusisuomi.fi (specific cookie hide uBO)

easylist/easylist_adservers.txt, easylist/easylist_specific_block.txt
Filters for blocking scripts and subdocument related to ads at [readcomicsonline](https://readcomicsonline.ru/comic/inferno-2021/1/3)
Proposed blocking filters: 
Placeholders in all subpages and main page: `||windsplay.com$script`
Referrals after clicking the comics to pass the page: `||everalwerf.xyz^`
How to reproduce the referral: Go to [comics](https://readcomicsonline.ru/comic/sword-2020/8) and click above the cartoon or try to click at "home" button at the header.
Screenshot of placeholders + script:
=> A: https://readcomicsonline.ru

easylist_cookie/easylist_cookie_specific_uBO.txt
Cookie dialog hiding rule hides also the login dialog. The issue is that the cookie dialog and login dialog have the exact same name:
`##div[data-testid="modal"]`
And using pseudo selectors such as `:nth-of-type()` won't help here because those elements change their position, depending if you have previously accepted cookies for this site or not. Also opening the login dialog changes things.
So I took a different approach. I'll let `##div[data-testid="modal"]` to hide the dialog but I added another rule: `##div[data-testid="modal"]:not(:has(div[data-testid="cookie-consent-modal"])):style(display: block !important)` to force the (login) dialog to go visible, if the dialog doesn't contain `cookie-consent-modal` as a descendant. The latter rule is indeed a procedural but it doesn't matter, …
=> P: vr.fi (login dialog blocked)

easylist_cookie/easylist_cookie_specific_hide.txt
In this site, cookies have to be accepted in order to see embedded videos. But as not all articles have embedded videos, it's not needed to whitelist the whole site, only those articles that actually have videos (one browsing the site might not always read articles that have videos, those articles are a minority.).
I know this filter blinks sometimes but it will be fixed when browsers start to support CSS4 (and native `:has`). But even a small blink is better than not to hide that big annoying banner at all.
Article having an embedded video (banner won't be hid):
https://www.theverge.com/2018/8/21/17761424/
Article not having an embedded video: (banner will be hid)
https://www.theverge.com/22705148/windows-11-upgrade-beta-release-preview-impressions
=> A: theverge.com (cookie banner hide for non video articles)

easylist/easylist_adservers_popup.txt
Filter for blocking adserver responsable for redirect popups at [9anime](https://9anime.to/)
Proposed filter: `||kolkwi4tzicraamabilis.com^$popup`
How to reproduce: 
As the webpage won't allow you to open the devtools, the way is to try to play the video using the VideoVard server, after that you will be redirect to the following
=> A: https://9anime.to/

easylist/easylist_specific_hide.txt
Filter for hiding popup messages placeholders and "fake buttons ads" at [ytmp3](https://ytmp3.cc/en26/)
`ytmp3.cc###a-320-50` - fake buttons ads
`ytmp3.cc##iframe[style*="z-index: 2147483647"]` - message popups placeholders. To reproduce you will need to place some link.
Screenshots:
=> A: https://ytmp3.cc/en26/

easylist/easylist_adservers.txt, easylist/easylist_specific_hide.txt
Filters for blocking adservers (popup messages + redirects) and hiding VPN ad at [torlock](https://www.torlock.com/all/torrents/no-time-to-die.html)
`||setflooded.cam^` - popup messages
`||fowink.com^` - script responsible for some of the redirects (click in any content) 
`torlock.com##table.hidden-xs` - specific hide for VPN ad
Screenshots:
Example of the redirect by the filter mentioned above: https://adhied.com/aliexpress/index.html?&sourceid=gpdes2585611&clickid=16353496903007572011039844242491697&nor=1
=> A: https://www.torlock.com/

easylist/easylist_adservers_popup.txt
Filter for blocking adserver responsible for redirect popups after clicking in any content at [porn00](http://porn00.org)
Proposed filter: `||clodsplit.com^$popup`
<details>
<summary>Screenshot:</summary>
</details>
=> A: [NSFW] http://porn00.org

easylist/easylist_specific_hide.txt
Block `.da` on <counter.dev> (they changed the div class name from `ad` to `da`).
Test page where the ad appears: https://counter.dev/dashboard.html?demo=1
=> M: counter.dev

easylist/easylist_adservers.txt
Filter to block adserver responsible for popup messages at [animeheaven](https://animeheaven.ru/)
Proposed filter: `||poodsboiko.com^`
Screenshot:
=> A: https://animeheaven.ru/

easylist/easylist_adservers.txt
Filter for blocking adserver script responsible for redirect popups at [skidrowreloaded](https://www.skidrowreloaded.com/)
Proposed filter: `||poenem.com^`
Screenshot:
=> A: https://www.skidrowreloaded.com/

easylist/easylist_adservers.txt, easylist_adult/adult_adservers.txt
Filter for fix broken webpage + adding adserver responsible for redirect popups
M: `||freeadultcomix.com` to `||freeadultcomix.com^$third-party`
A: `||hentaimotel.com^$third-party`
Screenshots:
=> M: [NSFW] (Fix) https://freeadultcomix.com/

easyprivacy/easyprivacy_specific.txt
Blocks tracking requests to `https://console-telemetry.oci.oraclecloud.com/v1/metrics` and ` https://console-telemetry.oci.oraclecloud.com/v1/tracking-events`.
=> Block tracking requests on Oracle cloud console

easylist/easylist_adservers.txt
Filter to block adserver responsible for popunders at [pxrnxx](https://pxrnxx.xyz/)
Proposed filter: `||routemomentarilydiscovering.com^`
Screenshot:
=> A: [NSFW] https://pxrnxx.xyz/

easylist/easylist_adservers.txt
Filters to block adservers at [123animes](https://w1.123animes.mobi/) responsible for popup messages / redirects
Filters (main page): 
```
||alisierboutell.com
||euscaroversing.com
||visagedbeard.com
```
Filters (any movie subpage) - they are randomised, i could caught the following ones: 
```
||gbjvangbtxlb.xyz
||daipsuwi.net
||cjsossrbji.xyz
```
=> A: https://w1.123animes.mobi/

easylist_cookie/easylist_cookie_specific_block.txt
=> A: kotaku.com (specific cookie block)

easylist/easylist_thirdparty.txt
Filter to block hosted adserver at desktophut.com
Proposed filter: `||d38goz54x5g9rw.cloudfront.net`
screenshots:
=> A: https://www.desktophut.com/

easylist_cookie/easylist_cookie_specific_hide.txt
`https://www.cbsnews.com/`
Seems to need specific filter for it.
=> A: cbsnews.com (Hide cookie banner background overlay)

easylist_cookie/easylist_cookie_thirdparty.txt
https://www.ruohonjuuri.fi/
Used widely: https://publicwww.com/websites/%22gdpr-legal-cookie.beeclever.app%22/
=> A: ruohonjuuri.fi (generic cookie block, 3rd party)

easyprivacy/easyprivacy_specific_international.txt
`||beacon.qq.com^` has long been blocked by AGTPF and no breakage reported.
=> M: make generic

easylist_cookie/easylist_cookie_international_specific_block.txt
https://www.kuntsari.fi/
Used in some Finnish sites: https://publicwww.com/websites/cdn.gravito.net%2Fcmp%2F/
=> A: kuntsari.fi + other sites (generic cookie block)

easylist_cookie/easylist_cookie_specific_uBO.txt
Cookie dialog hide for non-video pages. If the dialog is hid for video pages, videos won't sometimes start and sometimes it takes a lot of time.
Sample links:
Cookie dialog won't be hid:
https://www.bloomberg.com/live/europe
https://www.bloomberg.com/qt/live
https://www.bloomberg.com/news/articles/2021-11-19/germany-s-coronavirus-crisis-is-getting-out-of-control
https://www.bloomberg.com/news/videos/2021-11-19/reaction-from-kenosha-after-rittenhouse-found-not-guilty-video
Cookie dialog will be hid:
https://www.bloomberg.com/europe
https://www.bloomberg.com/news/features/2021-11-18/tirana-2030-design-plan-pits-density-against-history
https://www.bloomberg.com/news/articles/2021-11-20/coffee-prices-are-climbing-and-roasters-are-switching-beans
=> A: bloomberg.com (cookie hide, uBO)

easyprivacy/easyprivacy_specific.txt
Adds two endpoints used for tracking by Booking.
To reproduce: Open https://www.booking.com/ and check network requests.
=> A: https://www.booking.com/

easyprivacy/easyprivacy_general.txt
`||cn.dap.dmm.co.jp^` is blocked in JPF (not pure tracking server) but it'll be worth their tracking pixel blocked in EP as well.
<details>
</details>
=> A: (nsfw) book.dmm.co.jp

easylist_cookie/easylist_cookie_specific_hide.txt
This PR addresses https://github.com/uBlockOrigin/uAssets/issues/10644 by adding `mgtv.com##.m-agreement` to the Easylist Cookie specific hide area
- Visit mgtv.com
- Clear the cookies for that side and reload (only if you have already visited this site) or use a private browsing window
- Notice the cookie consent
=> Fix https://github.com/uBlockOrigin/uAssets/issues/10644

easylist/easylist_adservers.txt
Block adserver responsible for popup messages at https://aa01.to/
Proposed filter: `||stelagharris.com^`
Screenshot:
=> A: https://aa01.to/

easyprivacy/easyprivacy_allowlist_international.txt
Contents not shown:
Frankly, I think the blocking rule can be removed - it partly blocks consensu and all the problems by this which should arise only by Annoyance list do happen by EP too. https://github.com/uBlockOrigin/uAssets/issues/10491
=> P: https://www.bs11.jp/program/

easylist/easylist_allowlist_general_hide.txt
https://pokeminers.com/ is breaking with the following filter applied : ##.ad-container
Screenshot:
=> A: [Fix] https://pokeminers.com/

easylist/easylist_adservers.txt
Block adserver responsible for redirect popups at https://flixrs.com/
proposed filter: `||specialscammerinitially.com^`
Screenshot:
=> A: https://flixrs.com/

easylist_adult/adult_thirdparty.txt
#9991 created a rule that was too broad
Proposed Change:
`||icfcdn.com^$third-party` -> `||smpop.icfcdn.com^$third-party`
This causes requests to fail on streamate.com
=> M: [NSFW] Fix Broad Third-Party Rule 321bcdb

easyprivacy/easyprivacy_thirdparty_international.txt
> `ga.giuem.com` is a domain that hold google analysis proxy service, so users in china mainland can be tracked by google analysis. However, many users are not aware of being tracked by this.
For more information, please see - https://github.com/uBlockOrigin/uAssets/pull/10452 and https://github.com/Crystal-RainSlide/AdditionalFiltersCN/issues/1 (in Chinese)
=> M: Fix https://github.com/uBlockOrigin/uAssets/pull/10452

easyprivacy/easyprivacy_specific_international.txt
This must be the script used to track
`http://static.funshion.com/open/fis/js/v12/common/log/thirdlog_a0ffe888c6.js`
=> A: http://www.fun.tv/

fanboy-addon/fanboy_annoyance_specific_uBO.txt
This page has an annoying self-promotion on the background page (see screenshot) and it doesn't seem to be able to be hidden.
=> A: http://www.4399.com/

easylist/easylist_allowlist.txt
Fixes https://github.com/uBlockOrigin/uAssets/issues/11091
Reported by @gitbobbed 
Adds the filter `@@||googleoptimize.com/optimize.js$script,domain=wallapop.com` as recommended by @uBlock-user
=> Fix es[.]wallapop[.]com

easylist_cookie/easylist_cookie_general_hide.txt
Generic filter. Finnish word "evaste" means "cookie".
Used e.g.:
https://korkeinoikeus.fi
https://oikeus.fi
=> A: generic cookie hide (oikeus.fi)

easylist/easylist_adservers.txt
Block adserver responsible for redirects at https://bt4g.org/
Screenshot:
=> A: https://bt4g.org/

easylist/easylist_adservers.txt
Block adservers responsible for popups at https://herogayab.net/
Screenshots:
=> A: https://herogayab.net/

easylist_cookie/easylist_cookie_specific_hide.txt
Needs specific filter because there's `$generichide` filter for this site in main EasyList.
=> A: paramountplus.com (specific cookie hide)

fanboy-addon/fanboy_social_specific_hide.txt
Hides annoying "follow us" social media promo overlay
=> A: https://www.govtrack.us

easylist/easylist_adservers.txt
Block adservers at https://www.usagoals.sx/
also: `||oqhedrmfet.com` `||zewhpnrmykj.com`
mentioned at: #https://github.com/easylist/easylist/pull/10398
Screenshot:
=> A: https://www.usagoals.sx/

easylist/easylist_adservers.txt
Block adserver related to redirects (playing videos) at https://bflix.watch/
Screenshot:
=> A: https://bflix.watch/

easylist/easylist_adservers.txt
Block adserver related to redirect popups at https://ytmp3.sh/
Screenshots:
=> A: https://ytmp3.sh/

easylist/easylist_specific_hide.txt
I tried coming up with a more general rule, but couldn't get it to work. Fortunately this seems like the only ad left,
On a sidenote;
i see that other PRs are following some convention w.r.t. title (e.h. "A:"). I cant find where it says what this convention exactly is
=> hide realbooru ad on gelbooru

easylist_cookie/easylist_cookie_general_hide.txt
JS needs to be enabled in order for the cookie notification to appear (bottom of the page).
=> A: https://flutter.dev/

easylist/easylist_specific_hide.txt
This filter rule is too broad, please see https://github.com/easylist/easylist/issues/10639
=> Fix #10639 (broken content on realpython.com)

easylist/easylist_adservers.txt
Block adserver responsible for redirects at https://www2.zoechip.com/
Screenshots:
=> A: https://www2.zoechip.com/

easylist/easylist_specific_hide.txt
CSS class seems to have changed from `.show-gtty-item` to `.display-gtty-item`.
Cf. https://github.com/easylist/easylist/issues/10769
=> M: https://pixabay.com/

easylist/easylist_specific_hide.txt
Some article related videos are currently being hidden because of this filter, like for example the YouTube video here:
https://www.digitaltrends.com/gaming/nintendo-switch-sports-announcement/
I guess this filter has been added because of those "RECOMMENDED CONTENT" videos, like the one that can be found here:
https://www.digitaltrends.com/mobile/android-12-dynamic-theming-gms/
The change I'm suggesting should take care of those but still allow other videos.
=> P: digitaltrends.com

easyprivacy/easyprivacy_trackingservers.txt
Has login page `https://stat.pet/login` so third-party
=> A: baku.ws

easylist_cookie/easylist_cookie_specific_hide.txt
The currently used `appear-enter-done` class is used in a lot of places in mubi, and everything with this animation is removed when this filter list is active. It is unclear whether the automatically generated classname I replaced it with changes over time, but it is better to see the cookie banner then instead of not being able to start watching a movie.
Fixes https://github.com/easylist/easylist/issues/10877
=> P: https://mubi.com

fanboy-addon/fanboy_social_allowlist.txt
The generic filter `/images/social-` blocked screenshots in books, e.g. here: https://bookdown.org/yihui/bookdown/features-for-html-publishing.html#metadata-for-sharing
=> Handle false positives on https://bookdown.org/

easylist/easylist_allowlist.txt
https://github.com/easylist/easylist/pull/9136 but `@@||gamebox.gesoten.com/googleads_ima_html5_samples/advanced/ads.js` is nore more needed as bait was removed.
What about always prioritize P:  PR (at least those from long-term contributor) than others.
=> P: https://gamebox.gesoten.com/zakzak/game/411 (mobile UA, #9136)

easylist_cookie/easylist_cookie_allowlist_general_hide.txt
https://www.vaasa.fi/asu-ja-ela/sosiaalipalvelut-ja-arjen-tuki/arjen-tuki-vammaisille/
`##.pum[data-popmake*="cookies"]` blocks this notification:
Which is not a cookie dialog. It's about organizational changes. Scrolling is also broken. Added a fix.
=> P: vaasa.fi (incorrect blocking & scrolling broken)

easylist/easylist_adservers.txt, easylist/easylist_general_block.txt
May I ask you please if you can block in EasyList an adQuery script serving ads on mobile. The reason why I'm asking is because website is also available in English: https://adquery.io/en/ so blocking in EasyList could cover more websites.
**Steps to reproduce:**
-Sample URL: https://www.instalki.pl/aktualnosci/hardware/53225-doogee-s98-preorder.html
-ABP for Samsung Internet
-English + Polski list
-AA disabled
-Polish VPN
=> A: adQuery script

easylist/easylist_general_block.txt, easylist/easylist_specific_block.txt
`kiss-anime.org` => `kiss-anime.ws` Better generic, otherwise we have to enjoy domain-chasing.
=> A: ww.animeland.tv, ww.kiss-anime.ws

easylist/easylist_adservers.txt, easyprivacy/easyprivacy_general.txt
https://github.com/AdguardTeam/AdguardFilters/issues/114884
Not 100% sure if `/video.counters.` is safe, but guess you prefer this than having `/video.counters.js` and `/video.counters.2.`
=> A: (nsfw) https://www.erotikfilmsitesi1.com/co-ed-confidential-s1/ (fixes https://github.com/AdguardTeam/AdguardFilters/issues/114884)

easylist/easylist_allowlist.txt
Video lagging issue at pch.com. It takes about 1 min for the **Play Now!** option to show up. 
In the meanwhile a black box displays message: "Please watch a message from our sponsor while your game is loading".
**Website:** pch.com (Publishers Clearing House)
**Sample URL:** https://www.pch.com/games/minute-mania/mahjongg-minute/gameplay
**EasyList filter causing the issue:** `||imasdk.googleapis.com^`
**Script blocked:** https://imasdk.googleapis.com/js/sdkloader/ima3_debug.js
**Suggested filter: add domain to existing rule:**
`@@||imasdk.googleapis.com/js/sdkloader/ima3_debug.js$domain=abcnews.go.com|brightcove.net|pch.com`
=> P: https://www.pch.com/games/minute-mania/mahjongg-minute/gameplay

easylist/easylist_allowlist_popup.txt
"https://ads.shopee.com.br",
"https://ads.shopee.tw",
"https://ads.shopee.sg",
"https://ads.shopee.com.my",
"https://ads.shopee.vn",
"https://ads.shopee.co.th",
"https://ads.shopee.ph",
"https://ads.shopee.cn",
"https://ads.shopee.kr",
"https://ads.shopee.com.mx"
Above lists our affected sites,
Our site will be intercepted by the $popup rules
While we can open our sites by in the address bar, we cannot open them through new windows, especially for AdGuard interceptors.
The sites above are actually block, and although we use the CDN to record the static resources, we still can't use the site properly
I really hope that you can reply to us
I wish you a happy work
=> A: https://ads.shopee.sg/

easylist/easylist_general_block.txt, easylist/easylist_specific_hide.txt
Ads appear when downloading images from unsplash
=> A: Hide ads on Unsplash.com

easylist/easylist_general_block.txt
EL filter: `/adcreative.` breaking http://adcreative.es/
=> P: http://adcreative.es/

easylist_cookie/easylist_cookie_specific_uBO.txt
https://www.stadium.fi/
A specific filter to overcome blinking issues on uBO with the generic filter.
=>  A: stadium.fi (specific cookie banner filter for uBO)

easylist/easylist_specific_hide.txt
Hide placeholders at  https://www.news18.com/ 
Search for: `.NAT_add` and `.closestickybtn`
Search for: `.rhs_ad` and `.outBrainWrapper`
=> A: https://www.news18.com/

easylist/easylist_specific_hide.txt
Hide ads at https://unsplash.com/t/history AND https://unsplash.com/photos/tSp5_w9h5TQ
Related commits: 
https://github.com/easylist/easylist/commit/103f783
https://github.com/easylist/easylist/commit/e5e76ce
**Suggestion:**
1. Remove: `unsplash.com##.Z9B2b`
2. Add `unsplash.com##a[rel^="sponsored"][target="_blank"]` instead: 
2.1. To hide ads when you click on the **Download free** button  + **iStock images** at https://unsplash.com/photos/tSp5_w9h5TQ 
2.2. To also hide banner ads at https://unsplash.com/t/history 
3. Add `unsplash.com##.eziW_` to hide remaining **Ad** label at https://unsplash.com/t/history
=> A: https://unsplash.com/t/history

easylist/easylist_specific_hide.txt
below the article [class="wp-container-6 wp-block-columns alignwide"]
=> A: remove ad from onepagerules.com

easylist/easylist_general_block.txt, easylist/easylist_specific_hide.txt, easylist/easylist_specific_hide_abp.txt
Block redirect popups at https://yts.mx/movies/turning-red-2022 and also at https://eztv.tf/ + https://eztv.yt/
* Added `/script/nwsu.js$third-party`  to block script serving the ads, since it has changed from: https://factermer.com/script/nwsu.js to https://cernamer.com/script/nwsu.js
Reference commit: https://github.com/easylist/easylist/pull/11722 so maybe is better to make it general as it would also block at **eztv.tf** and **eztv.yt**
* Added`yts.mx##.aoiwjs` to block banner VPN ad
Also adding
=> A: https://yts.mx/movies/turning-red-2022

easylist/easylist_specific_block_popup.txt
Block popups at all the subdomains of https://unblockedstreaming.net/ and https://piraproxy.info/
Example: 
http://gogoanime.unblockedstreaming.net/
http://1337x.piraproxy.info/
Could also be an option:
```
/hkz*^$popup,domain=
/&*^$popup,domain=
```
=> A: https://unblockedstreaming.net/

easylist/easylist_thirdparty.txt
- banners (top & bottom) ([src^="https://hosting.photobucket.com/images/f369/"])
=> A: hide banner on urbanartassociation.com

easyprivacy/easyprivacy_specific.txt
Self-hosted amplitude-js server at ampltd.top.gg.
=> A: https://top.gg/

easylist_cookie/easylist_cookie_international_specific_hide.txt
http://becteroradio.com/
https://teroradio.com/
https://www.bnn.in.th/
https://classic.set.or.th/
https://www.settrade.com/
https://www.komchadluek.net/
https://nipa.co.th/
https://www.posttoday.com/
https://www.punpro.com/
https://www.set.or.th/
https://www.siamsport.co.th/
https://techsauce.co/
https://thaiza.com/
https://vroom.truevirtualworld.com/
=> Add 14 Thai Websites to easylist cookie

easylist/easylist_general_block.txt
Block redirect popus on yts.mx eztv.tf and eztv.yt
yts.mx - popups come up when you click on any item.
eztv.tf and eztv.yt - popups come up when you click on any item and also on the video controller (try to advance the video for example).
Reference PR: https://github.com/easylist/easylist/pull/11800 seem not enough to block these popups.
Rule:`/script/ut.js?cb=$third-party` is already in EasyList.
https://yts.mx/movies/the-bad-guys-2022
https://eztv.tf/ep/1787100/judge-steve-harvey-s01e12-480p-x264-msd/
https://eztv.yt/ep/1785750/61st-street-s01e04-1080p-hevc-x265-megusta/
=> A: https://yts.mx/

easylist/easylist_general_block.txt
Website blocked by EasyList rule: 
`/adx.$domain=~adx.business|~adx.co.nz|~adx.cx|~adx.nz|~adx.rs|~adx.ru|~adx.traveledge.com|~adx.tribefire.com|~adx.uk.com|~adx.world|~adx.wowfi.com|~journals.uchicago.edu`
https://adx.solutionshill.com/
https://solutionshill.com/
=> P: https://adx.solutionshill.com/

easylist/easylist_specific_hide.txt
Hide banner ads on https://mtaeta.info/
Reference PR: https://github.com/easylist/easylist/pull/11719
Note: Please let me know whether it would be better to hide the entire `Partners table` instead.
Suggestion: `mtaeta.info##div[class="container"][style="margin-bottom: 0px;"]`
=> A: https://mtaeta.info/

easylist/easylist_thirdparty.txt
On Google map click bottom-left Layers => More and Globe view will be partly broken:
This seems to be a CNAME issue by Brave's uncloak, adding `@@||gstaticadssl.l.google.com^$domain=google.co.jp|google.com` to custom filter fixes it on my end. The responsible rule is `||gstaticadssl.l.google.com^$~font,third-party,~xmlhttprequest` and `third-party` doesn't help due to cname uncloaking:
On uBO + Firefox it doesn't happen thx to `@@||google.*^$cname` in Unbreak, but apparently Brave can't interpret `$cname`. @pes10k is there a plan to support the modifier?
=> P: https://www.google.*/maps/* (Brave-specific CNAME issue)

easylist/easylist_specific_hide.txt
Hide affiliate animated banners on https://exportfromnigeria.info/
Reference commit: https://github.com/easylist/easylist/commit/a62baca
_Note: Please let me know whether it would be better to hide the entire affiliate table instead `###easy_aff_table`_
=> A: https://exportfromnigeria.info/

easylist/easylist_specific_hide.txt
Ads reported on https://autental.com/2021/10/03/e-bujshme-ka-fshehur-pasurite-jashte-vendit-kush-eshte-politikani-shqiptar-i-pandora-papers/
=> A: Hide widgets on audental.com

easylist/easylist_specific_block.txt
Script to insert ads in the upper left corner of videos delivered via Hydrax (inserted ads will vary depending on viewing region).
Example of use:
https://theflixer.tv/watch-movie/watch-roman-holiday-full-17088.2227356
https://series2watch.tv/watch-movie/watch-gone-with-the-wind-hd-19002.2221903
=> A: playhydraxs.min.js

easyprivacy/easyprivacy_allowlist_international.txt
When the filter `-google-analytics/$domain=~wordpress.org` hits, the site doesn't load.
=> A: https://doctorzerenia.com/

easylist/easylist_allowlist.txt
`http://buy.livedoor.biz/archives/51621754.html`
breakage
Similar issue: https://github.com/easylist/easylist/pull/8837
When you click the product image, you will redirect to the shopping website.
When you click the product image, you will get stuck on the cushion page in the middle of the redirect.
<details>
</details>
<details>
```yaml
uBlock Origin: 1.39.0
Firefox: 94
filterset (summary): 
network: 80972
cosmetic: 43544
scriptlet: 16198
html: 598
listset (total-discarded, last updated): 
default: 
ublock-filters: 30283-29, now
ublock-badware: 3494-1, now
ublock-privacy: 183-0, now
ublock-abuse: 74-0, now
ublock-unbreak: 1708-0, now
easylist: 61300-629, now
easyprivacy: 26396-496, now
urlhaus-1: 10185-0, now
plowe-0: 3697-3, now
JPN-1: 5311-14, now …
```
=> P: https://www.e-trend.co.jp/cart/value_commerse_cushion.html

easylist/easylist_adservers.txt
Very popular international adserver, other examples:
```
http://hornydragon.blogspot.com/
https://topicks.jp/
https://www.misterikisah.com/
```
=> A: www.metalbridges.com

easylist/easylist_allowlist.txt, easylist/easylist_allowlist_general_hide.txt, easylist/easylist_general_block.txt, easylist/easylist_specific_hide.txt
1 - EasyList rule blocks image icons
`/advertisers/*$domain=~ads.pinterest.com|~datalift360.com|~home.tapjoy.com|~panel.rightflow.com|~propelmedia.com|~publisuites.com|~qubeslate.com`
2 - EasyList rules hide widget under **Multiple Ad Formats**
```
##.widget-ads
##.ad-push
##.ad-btn
##.ad-banner
##.ad-full
##.ad-img
```
=> P: https://ad-maven.com/advertisers

easylist/easylist_general_hide.txt, easylist/easylist_specific_hide.txt
**1 - Hide image slider (.gif) under Affiliate Partners**
_Please let me me know if it should be added to Annoyance List instead_
**2 - Hide ad labels throughout out the page**
=> A: https://bucksco.today/

easylist/easylist_specific_block.txt
I have added a new regular expression rule for the video hosting service dood.pm, as the old one did not seem to work.
Example of use [NSFW];
https://dood.pm/d/e0f94s0j6zav
https://dood.pm/d/j4z0pj7zvxs4
=> A: dood.pm

easylist_cookie/easylist_cookie_general_hide.txt
https://www.lielahdenapteekki.fi/
Other sites use as well:
https://www.nerdydata.com/reports/primus-cc/2e50a905-57ff-415d-8baa-4e41e7d6cf26
https://publicwww.com/websites/%22primus-cc%22/
=> A: lielahdenapteekki.fi (generic cookie banner hide)

easylist/easylist_specific_hide.txt, easylist_cookie/easylist_cookie_specific_hide.txt
Filter added on commit https://github.com/easylist/easylist/commit/7e4c3b7 hides the cookie consent on https://abetterrouteplanner.com/
suggesting to move filter to EL cookie instead.
=> M: move to easylist_cookie

fanboy-addon/fanboy_notifications_specific_uBO.txt
https://www.puuilo.fi/farmari-aitaverkko-80cm-x-20m
Translation of the title:
"Answer the survey and win a € 100 gift card to Puuilo!"
Depending what filter settings you have, it might look like this as well:
When the page is refreshed, that notification goes away. You'll have to use incognito mode or clear the cache to see it again.
=> A: puuilo.fi (notification hide, uBO)

easylist/easylist_specific_hide.txt
Hide sticky ads on https://www.apotelyt.com/
I've made the following changes:
**1 - Removed** 
`apotelyt.com###heDoCon` (https://github.com/easylist/easylist/commit/816284c) and `apotelyt.com###wiDoCon` (https://github.com/easylist/easylist/commit/607c897) as they no longer hide these sticky ads.
**2 - Added** instead:
`apotelyt.com##aside[id^="hedoApp"]`
`apotelyt.com##aside[id^="widoApp"]`
=> M: https://www.apotelyt.com/

easylist/easylist_specific_hide.txt, fanboy-addon/fanboy_newsletter_specific_hide.txt
Reference [commit](https://github.com/easylist/easylist/commit/2910858)
**Fixes:** 
1 - Delete `techrepublic.com##.jotform-twenty-pro-tips` since is already on **fanboy-addon/fanboy_newsletter_specific_hide.txt**
2 - Move `techrepublic.com##.jotform-top-story-of-the-day` to **fanboy-addon/fanboy_newsletter_specific_hide.txt** since it hides Top Story of the Day newsletter.
=> M: Fixes https://www.techrepublic.com/

easylist/easylist_specific_hide.txt
Reference: https://github.com/easylist/easylist/commit/feca9cb
Sample URL: https://bossip.com/2136035/steve-harvey-lori-michael-b-jordan-split/
1 - Suggest: `bossip.com##.player-wrapper-inner` instead of `bossip.com###video-expanded` as it hides the top title info.
2 - Suggest:
`bossip.com##.fsb-desktop` to hide the sticky ad overlay
`bossip.com##.fsb-toggle` to hide the close button
=> M: Fixes https://bossip.com

easylist/easylist_specific_hide.txt
Hide top banners at https://www.breitbart.com/
Screenshot:
=> A: https://www.breitbart.com/

easylist/easylist_general_hide.txt, easylist/easylist_specific_hide.txt
Make rule generic since **incentrev ads** are showing on more domains:
Rule originally added on [commit](https://github.com/easylist/easylist/commit/c735eb1)
https://bigdawgfm.com/
https://cumberlandsmagic.com/
https://panhandlenewsnetwork.com/
https://sky1065.com/
https://todays975.com/
https://tristateswolf.com/
https://wajr.com/
https://wchsnetwork.com/
https://wdnefm.com/
https://wfby.com/
https://wjls.com/
https://wjlsam.com/
https://wkkwfm.com/
http://wkmznews.com/
http://www.wky930am.com/
https://wvaq.com/
https://v100.fm/
https://929wxdc.com/
https://941qzk.com/
https://947welk.com/
https://995wdzn.com/
https://961kws.com/
https://987thebeat.com/
**https://1013thebear.com/**
Related open PR: https://github.com/easylist/easylist/pull/12254/commits/724743c3579ae3f2e642c69e6b44a2aface …
=> M: make it generic

easyprivacy/easyprivacy_thirdparty_international.txt, easyprivacy/easyprivacy_trackingservers_international.txt
Added by https://github.com/easylist/easylist/commit/58d4d0550f4691571e8c376b9ba77511268eb9bd
Now is breaking `For You`:
IDK if you prefer exception.
=> P: https://www.freaksstore.com/item/3039147200020.html

easylist/easylist_specific_hide.txt
Rule: `#top_outside` hides a banner with an Adblock message on https://www.anisearch.com/
Reference commit: https://github.com/easylist/easylist/commit/7e51196
=> P: https://www.anisearch.com/

easylist/easylist_specific_hide.txt
Remove duplicates `92kqrs.com,93x.com##.block-content > a[href^="https://www.sweetdeals.com/minneapolis/deals"]` as rule `##a[href*="https://www.sweetdeals.com/"] img` added on commit: https://github.com/easylist/easylist/commit/f5ced43 fixes it.
=> D: remove duplicates

easylist/easylist_specific_hide.txt
Left ad labels on https://pastebin.com/
Commit: https://github.com/easylist/easylist/commit/988b9a7
=> A: https://pastebin.com/

easylist/easylist_specific_hide.txt
Banner ads on the following domains:
https://www.newcountry963.com/
https://www.wbap.com/
https://www.995thewolf.com/  
https://www.hot933hits.com/
Look for: 
https://www.gasbuddy.com/gasprices/texas/dallas
And https://www.cumulusmedia.com/careers/
I did not add only `.widget_simpleimage` because it would hide the banner below the main gallery: `CLICK HERE FOR COVID-19 VACCINATION LOCATIONS & INFORMATION`
=> A: cumulus and gasbuddy banner ads

easylist/easylist_specific_hide.txt
Rule: `news24online.com##.db_shw_mb_blk ` meant to hide ad labels also hides the website footer.
Sample URL: https://news24online.com/news/world/peace-talk-between-ttp-pakistani-govt-concludes-kabul-be9c87ba/
Rule added on commit: https://github.com/easylist/easylist/commit/26bd9bd
Reference: https://github.com/easylist/easylist/commit/2a39117
=> P: https://news24online.com/news/world/peace-talk-between-ttp-pakistani-govt-concludes-kabul-be9c87ba/

easylist/easylist_general_hide.txt
Noticed that filter: `##section[class^="recirclist_recircList__"]` added on [commit](https://github.com/easylist/easylist/commit/6bd03eb) blocks the section called **もっと読む** below Outbrain widget (with ABP disabled) on https://www.buzzfeed.com/jp/ryosukekamba/lisa4?ref=hpsplash
Removed the rule as it could be affecting other sites as well but please let me know if an exception for this particular domain would be better.
Steps to reproduce: 
ABP Lists:  ABP filters + EasyList
VPN location: Japan and US
=> P: https://www.buzzfeed.com/jp/ryosukekamba/lisa4?ref=hpsplash

easylist/easylist_general_hide.txt
Hide leftover video ad overlay.
Video ad is blocked by `||nitropay.com^$third-party` added on commit: https://github.com/easylist/easylist/commit/9f27e28
=> A: https://genshin-impact-map.appsample.com/

easyprivacy/easyprivacy_thirdparty.txt
Example URL: `https://www.hcaptcha.com`
Example analytics request (simplified):
```
POST /api/event
{"n":"pageview","u":"https://www.hcaptcha.com/","d":null,"r":null,"w":1337}
```
=> Add a.hcaptcha.com analytics host

easylist/easylist_specific_hide_abp.txt
Unlabelled sponsored ad on https://digg.com/
Element is not labelled as **Sponsored** on the home page but once you click on it you will see the label `WITH LARQ | SPONSORED` 
Link: https://digg.com/larq/link/larq-filter-purevis-microplastics-GtLNeNxEeR?utm_source=digg and has
=> A: https://digg.com/

easylist/easylist_general_hide.txt, easylist/easylist_specific_hide.txt, easyprivacy/easyprivacy_specific.txt
`##.dfp-native` hides contents on top page, replaced by `webmd.com##.module-top-picks` to hide placeholder on articles. `||webmd.com/pixel/` removed by https://github.com/easylist/easylist/commit/8aebd443facdbf8e2f396fcc34cdd6f1e340fd16 is still in use in articles.
=> P: www.webmd.com

easylist_cookie/easylist_cookie_specific_uBO.txt
https://www.nhl.com/
uBO's internal filters have a generichide for nhl.com, which is why uBO needs a specific filter.
(Filter suggestion added under "! Generichide fixes" section.)
=> A: nhl.com (specific filter needed for uBO cookie hide)

fanboy-addon/fanboy_newsletter_specific_uBO.txt
https://www.tietoevry.com/fi/toimialat/sosiaali-ja-terveydenhuolto/terveydenhuolto/perusterveydenhuolto-ja-erikoissairaanhoito/
After scrolling the page a while and waiting 30 secs, scrolling will be locked. It's because of a newsletter dialog (which is hidden by FA already).
=> P: tietoevry.com (scrolling not working, uBO fix)

easylist_cookie/easylist_cookie_specific_block.txt
https://www.foreca.fi/
Requesting this entry to be added back. It was removed because it was thought that it causes issues by blocking scrolling. But after investigating this thoroughly, the culprit was Easyprivacy list after all, it was not caused by blocking this cmp script.
Before testing this out, please disable EP list or add this to your filters temporarily:
`@@||survey.userneeds.com^$subdocument,domain=foreca.fi`
Also, the page has to be loaded in incognito mode. Then press F5 and you can reliably test this out. If testing this again after that, close the browser window, open incognito again, load the page and then press F5. Note that only the first page refresh by F5 gives a reliable result.
https://github.com/easylist/easylist/pull/12490#issuecomment-1177795097 …
=> A: foreca.fi (cookie banner block)

easylist/easylist_allowlist.txt, easylist/easylist_general_hide.txt, easylist/easylist_specific_hide.txt
1 - Remove wbwn.com | wbnq.com and wjbc.com from existing rule: `##.widget_media_image` and `##.widget_simpleimage` as it may hide self-promo.
2 - Add instead specific rules to hide `stjude` and `menards` banner ads on wbwn.com | wbnq.com and wjbc.com
`wbnq.com,wbwn.com,wjbc.com##a[href^="https://stjude.org/radio/"]`
`wbnq.com,wbwn.com,wjbc.com##a[href^="https://www.menards.com/main/home.html"]`
3 - Add specific filter to hide `farmweeknow` banner ad sweetdeals top menu button on wjbc.com
`wjbc.com##a[href^="https://www.farmweeknow.com/rfd_radio/"]`
`wjbc.com##a[href^="http://sweetdeals.com/bloomington/deals"]`
4 - Adding exception to allow self-promo image on wbnq.com as it's blocked by EL rule `/300x150_` 
`@@||franklymedia.com/*/300x150_WBNQ_TEXT.png$image,domain=wbnq.com`
Reference …
=> Fixes for wbnq wbwn and wjbc.com

easylist/easylist_general_hide.txt
Taboola widget label leftover.
=> https://likeswifty.com/s/bad-breakfast-food

easylist/easylist_adservers.txt
The site is empty except for DMM ads which I'll soon address in JPF, but hilltopad servers should be added to EL.
=> A: (nsfw) www.uraaka-joshi.com

fanboy-addon/fanboy_newsletter_specific_uBO.txt
Made this rule more domain specific. It prevents scrolling if used on Teams Web (teams.microsoft.com).
Better to have www-prefix in order to avoid other potential issues with Microsoft web apps.
=> P: teams.microsoft.com (scrolling blocked)

easylist_cookie/easylist_cookie_specific_uBO.txt
https://www.myabandonware.com/
Needed, because uBO's Unreak list whitelists the script.
=> A: myabandonware.com (cookie dialog hide for uBO)

easylist_cookie/easylist_cookie_specific_block.txt
`https://eurheilu.org/oleksandr-s1mple-kostyliev-oli-kolnin-mvp-katso-jaatavat-suoritukset/`
=> A: eurheilu.org (cookie script)

easylist_cookie/easylist_cookie_specific_block.txt
When blocking `cookielaw.org` related requests, wouldn't it be better to block the whole domain instead of one or two scripts?
`cookielaw.org` gives partially different requests for different sites:
rollingstone.com
ign.com
`ign.com` doesn't have `otCCPAiab.js` or `otsdkstub.js`.
Videos work fine on `ign.com` so it's safe to block. Sample link: https://www.ign.com/articles/backbone-one-playstation-controller-announced
=> A: / M: ign.com (cookie dialog block)

easylist/easylist_adservers.txt
Adding `$third-party` since [eksiup.com](https://eksiup.com/) seems to be a real site.
Reference https://github.com/easylist/easylist/commit/8cb177d
=> M: Make third-party

easylist_cookie/easylist_cookie_specific_block.txt, easylist_cookie/easylist_cookie_specific_uBO.txt
https://elisa.fi/
https://elisaviihde.fi/
https://www.maaseuduntulevaisuus.fi/uutiset/84084a42-be65-48ff-a5ed-6eba564b6083 (this is the only news website, this link contains a video, that works fine if consent script is blocked.
=> A: elisa.fi (+others) (cookie dialog block)

easylist/easylist_adservers.txt
This was previously moved from ad-network to third party, however, it is not an ad network in any way. Requests get blocked on Chrome Ad block & Ad block plus, for example requesting to our cdn. This site should not be classified as ad network, neither directly, nor from third parties, since it is none. Kindly remove from the ad servers list completely. Thank you!
@Khrin @ryanbr 
Ref: https://github.com/easylist/easylist/issues/11950
=> Fix: remove false positive

easylist_cookie/easylist_cookie_allowlist_general_hide.txt
I think these rules aren't necessary anymore. I don't see any issues in blocking the banner.
Video works: https://www.nytimes.com/video/us/100000008467540/kentucky-flood-death-toll.html?playlistId=video/latest-video
And embedded tweet appears in the article: https://www.nytimes.com/2022/07/12/technology/twitter-lawsuit-musk-acquisition.html
=> M: nytimes.com (removing cookie banner whitelistings)

easylist_cookie/easylist_cookie_specific_uBO.txt
In https://github.com/easylist/easylist/tree/master/easylist_cookie there's a warning that hiding the dialog prevents zooming of products.
That depends what element is being hid. Using this rule to hide the dialog, zooming in product images work just fine:
`etsy.com###gdpr-single-choice-overlay`
In addition to that, also this rule is required:
`etsy.com##body:style(padding-right: 0 !important)`
Reason: when opening and closing a product image, the body element shifts to the left a bit. If a product image is opened and closed many times, the body shifts even more to the left. This is caused by the cookie dialog: every time it tries to show itself, it shifts the page to the left. But this rule prevents the shifting.
Sample link to test these rules with: …
=> A: etsy.com (cookie dialog hide, uBO)

fanboy-addon/fanboy_newsletter_specific_hide.txt, fanboy-addon/fanboy_notifications_specific_hide.txt
When subscribing to FA subsections separately (`newsletter`, `notifications`), their uBO specific fixes won't load automatically. Added a fix for that.
=> Include uBO specific lists for FA subsections

fanboy-addon/fanboy_social_allowlist_general_hide.txt, fanboy-addon/fanboy_social_international.txt
https://www.ampparit.com/
On ampparit.com, the social media box is hid by `##.social-media-links`, but the issue is that the same box also contains the site's feedback button. ("Anna palautetta").
I constructed the social media box hiding differently. I hid everything else but I'll leave the feedback button there. Looks good to me this way.
=> P: ampparit.com (feedback button hid by social media list)

fanboy-addon/fanboy_notifications_specific_hide.txt
When browsing Chrome's addon store on a different browser, they show a nag whether you want to switch to Chrome.
https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm
=> A: chrome.google.com (switch to Chrome nag)

easylist/easylist_specific_hide.txt
Ads on https://sharylattkisson.com/2022/07/study-unvaccinated-covid-patients-contagious-for-shorter-period-of-time-than-vaccinated/
The other banners are self-promo that links to https://store.sharylattkisson.com/
=> A: https://sharylattkisson.com/2022/07/study-unvaccinated-covid-patients-contagious-for-shorter-period-of-time-than-vaccinated/

easyprivacy/easyprivacy_specific.txt, easyprivacy/easyprivacy_trackingservers_international.txt
Removed the blocking of the whole altruja.de domain and added a specific script to specific.txt.
This script contains all "tracking related" code as discussed here: https://forums.lanik.us/viewtopic.php?p=164754-altruja-de#p164754
=> Moved altruja.de from tracking_servers to specific

easylist/easylist_specific_hide.txt
"Buy at Amazon" link ad.
Sample link: https://www.opensubtitles.org/en/subtitles/5639181/a-nightmare-on-elm-street-5-the-dream-child-en
Also, on the search page https://www.opensubtitles.org/en/search2/sublanguageid-all/moviename-street, there are ad container remnants:
This is partially a re-open of this old PR: https://github.com/easylist/easylist/pull/7435 - all specific rules concerning `opensubtitles.org` that are currenly in EL, are relevant.
These current rules in EL:
`opensubtitles.org###watch_online`
`opensubtitles.org##div[itemscope=""][itemtype="http://schema.org/Movie"] > fieldset`
Are both active in https://www.opensubtitles.org/en/subtitles/5639181/a-nightmare-on-elm-street-5-the-dream-child-en
This rule:
`opensubtitles.org##.a_1.a.p`
is active on the search page: …
=>  A: opensubtitles.org (specific ad hide)

easylist/easylist_allowlist_general_hide.txt
EL rule: `##.publicidade` is preventing [galaopublicidade.com](https://www.galaopublicidade.com) from loading.
_Please let me know if it's be better to add the exception to [EL Portuguese](https://easylist-downloads.adblockplus.org/easylistportuguese+easylist.txt) instead._
=> P: https://www.galaopublicidade.com/

fanboy-addon/fanboy_notifications_specific_hide.txt
When pausing a video on `areena.yle.fi`, it shows a slider of "recommended videos" at the top which clutters the video annoyingly.
Also, there's "Jaa ohjelma" (=Share the program) button. It's not social media share but generic sharing button, that appears when howering a mouse over a video.
Sample: https://areena.yle.fi/1-916098
=> A: areena.yle.fi (pauserecommendations during a video + sharing button)

fanboy-addon/fanboy_notifications_specific_uBO.txt
When viewing a page in `ask.fm`, it shows a dialog that asks to either login or download their mobile app.
Sample page:
https://ask.fm/paivankysymyksia
=> A: ask.fm (forced app download / login page)

easylist_cookie/easylist_cookie_specific_uBO.txt
All these sites are owned by Sanoma Corporation. On these sites, cookies have to be accepted in order to see embedded content.
This set of filters will unlock the scrolling for each page (via `:style`), and hide the consent dialog only, if the page doesn't have any embedded content.
There are two types of sites on this PR: news websites and magazine/forum based.
For news websites, this rule is being used:
`##body:not(:has(.embed-cookie-consent-icon)) > div[id^="sp_message_container"]`
For magazine/forum based:
`##body:not(:has(.consent_required_iframe)) > div[id^="sp_message_container"]`
Note!
This rule should not be used this time:
`##+js(rc, sp-message-open, html, stay)`
Because it suffers from a glitch: even if the consent dialog is hid, it still tries to disable scrolling, leading to …
=> A: aamulehti.fi + others (consent dialog hide, uBO)

easylist/easylist_general_block.txt
Because of:
https://github.com/easylist/easylist/blob/ee23e100c14a7dd419f02f12d4802fcaae46fd07/easylist/easylist_general_block.txt#L209
=> M: redundant rule

easylist_cookie/easylist_cookie_specific_block.txt
https://www.aarrelehti.fi/
https://www.koneviesti.fi/
https://www.suomela.fi/
https://viestimedia.fi/
=> A: aarrelehti.fi + others (gdpr block)

easylist/easylist_allowlist_general_hide.txt
https://tapahtumat.iijokiseutu.fi/fi-FI/page/62c1a9c051cccb6db5d7daf6
`https://tapahtumat.kaleva.fi/`
`https://tapahtumat.koillissanomat.fi/`
`https://tapahtumat.lapinkansa.fi/`
`https://tapahtumat.pyhajokiseutu.fi/`
`https://tapahtumat.raahenseutu.fi/`
`https://tapahtumat.rantalakeus.fi/`
`https://tapahtumat.siikajokilaakso.fi/`
This "MAINOSTA TAPAHTUMAA" button:
should show this popup allowing you to pay to advertise your event:
but currently EasyList hides it and by clicking it you only get dark overlay and can't do anything after.
=> P: tapahtumat.iijokiseutu.fi + more (Fixes popup)

easylist/easylist_specific_hide.txt
Ad promotions leftovers on [msn.com.](https://www.msn.com/)
Redirect link has [redirect.viglink.com](https://redirect.viglink.com)
=> A: https://www.msn.com/

easylist/easylist_adservers.txt
Filter breaks **r2b2.io**, adding `$third-party` option.
=> P: https://r2b2.io/

easylist_cookie/easylist_cookie_specific_uBO.txt
This PR unlocks scrolling, and hides the GDPR dialog, unless the page has a video or stock listings. For those, cookies have to be accepted. Otherwise they won't work (sidebar stock listings work though.)
Sample links:
Cookie dialog won't be hid:
https://www.bloomberg.com/profile/company/1041347D:LN
https://www.bloomberg.com/quote/FAST:US
https://www.bloomberg.com/live/europe
https://www.bloomberg.com/qt/live
https://www.bloomberg.com/news/articles/2021-11-19/germany-s-coronavirus-crisis-is-getting-out-of-control
https://www.bloomberg.com/news/videos/2021-11-19/reaction-from-kenosha-after-rittenhouse-found-not-guilty-video
Cookie dialog will be hid:
https://www.bloomberg.com/news/articles/2022-08-13/ukraine-latest-kyiv-debt-downgrade-kremlin-braces-for-long-war …
=> A: bloomberg.com (GDPR dialog, uBO)

easylist_cookie/easylist_cookie_specific_block.txt
GDPR stuff can't be blocked on `bloomberg.com`, only handled partially through cosmetics.
(I recently made cosmetics for the site: https://github.com/easylist/easylist/pull/12928)
=> M: obsolete filter

easylist/easylist_adservers.txt
Sample link: https://www.synonyymit.fi/audienssi
`watwait.com` loads ads:
Not solely Finnish related:
https://www.nerdydata.com/reports/watwait-com/e76469c6-af15-4af2-8d0a-6bbe57df1f40
=> A: synonyymit.fi (generic ad server)

easylist/easylist_specific_block.txt
ref: https://github.com/AdguardTeam/AdguardFilters/issues/123169
vizcloud changed TLD to .site and thus the rule is anyway obsolete.
=> M: remove obsolete filter for vizcloud

easylist/easylist_general_hide.txt
Add rule from EasyList Spanish: `bluradio.com,caracoltv.com,shock.co##.GoogleDfpAd-Float` to EasyList  as generic, so it could more sites.
PR to remove the specific filter from EasyList Spanish and avoid redundancy: https://github.com/easylist/easylistspanish/pull/280
Rule hides sticky ads.
Sample URLs:
https://sports.caracoltv.com/
https://gol.caracoltv.com/
=> A: https://sports.caracoltv.com

easylist_cookie/easylist_cookie_international_specific_block.txt
On `elisa.fi` GDPR script cannot be blocked as it causes content loading issues on this link:
https://elisa.fi/kauppa/puhelinliittymat
But blocking these xmlhttprequests won't cause issues - also blocking them will also prevent the banner from loading.
=> A: elisa.fi (GDPR specific block)

easylist_cookie/easylist_cookie_allowlist.txt, easylist_cookie/easylist_cookie_general_hide.txt, easylist_cookie/easylist_cookie_international_specific_block.txt, easylist_cookie/easylist_cookie_specific_uBO.txt, easylist_cookie/easylist_cookie_thirdparty.txt, easyprivacy/easyprivacy_allowlist_international.txt
On Alma Media's news websites, tweets won't work without accepting cookies. So I'm making Alma Media related GDPR blocking rule to exclude their news websites and also remove obsolete cosmetics / block rules. Also googletagmanager has to be whitelisted as well as it prevents GDPR stuff from loading. (Easyprivacy).
I'm later going to make selective blocking rules for these domains (hide GDPR dialog only if there are no embedded content). But making it after this PR is handled. Otherwise it will get too complicated.
Samples:
https://www.iltalehti.fi/digiuutiset/a/d2af6105-d363-47b2-9a21-5a07fcee22ba (already whitelisted, but just mentioning it as it relates to these other sites)
https://www.kauppalehti.fi/uutiset/suomen-kylat-ilahtui-keskustan-edistamasta-kokeilusta-kannustaisi-koulutettuja- …
=> M: / P: Obsoletes + whitelistings (GDPR, Alma Media)

easyprivacy/easyprivacy_general.txt
Blocks Confection.io wordpress integration, that is a server-side tracking/proxy service.
Plugin: https://wordpress.org/plugins/confection/
Seen in the wild at https://alllife.co.za/ that calls https://alllife.co.za/wp-content/plugins/confection/bridge.php
Seen https://www.4lifedirect.pl/ that calls https://www.4lifedirect.pl/wp-content/plugins/confection/bridge.php
Confection.io is already partially blocked at https://github.com/easylist/easylist/blob/79dd21808d4cf2ef04def6501753d017c57dca76/easyprivacy/easyprivacy_specific.txt#L1081
=> A: Confection.io wordpress integration

easyprivacy/easyprivacy_allowlist_international.txt
This bank website uses fingerprint2.js as part of its login form for the "remember me" feature, in a way that looks like to be able to trust the device. Without the script, the "remember me" function blocks connexions.
=> A: https://mabanque.fortuneo.fr fix login

easylist/easylist_allowlist.txt
Video player from `Popular Videos` section is blocked by EasyList rule: `-prebid.$script`
Error message: "video cannot be played because of a technical error. (Error Code: 100000)"
=> P: https://www.texasmonthly.com/bbq/texas-style-bbq-invades-oklahoma/

fanboy-addon/fanboy_newsletter_specific_hide.txt
Fixes boxzilla overlay selector.
e.g. `https://thebaffler.com/salvos/dystopia-for-realists-oshea`
=> Fix boxzilla filters

easylist_cookie/easylist_cookie_specific_uBO.txt
- `https://www.quantamagazine.org/`
- There is white space above header due to cookie removal. It can be fixed with:
`quantamagazine.org##+js(rc, cookie-not-accepted, #app)`
<details><summary>Configuration</summary>
```yaml
uBlock Origin: 1.44.0
Firefox: 103
listset: 
added:
fanboy-cookiemonster
default:
user-filters
ublock-filters
ublock-badware
ublock-privacy
ublock-abuse
ublock-unbreak
ublock-quick-fixes
easylist
easyprivacy
urlhaus-1
plowe-0
```
</details>
<details><summary>Screenshot 1</summary>
</details>
=> Fix quantamagazine.org cookie notice removal

easyprivacy/easyprivacy_specific_international.txt
https://orange.fr loads https://z.woopic.com/z.gif with tracking values as params. Some other subdomain are used too, but others are already handled by others filters, only this one remains. woopic.com belongs to Orange.
=> A: https://orange.fr tracking

easylist/easylist_specific_hide.txt
The footer of thedriven.com has been hidden after [this filter](https://github.com/easylist/easylist/commit/ce7f2a4b9cca95709faa9163d39257e36a728164) was added. 
I assume that the idea was to block the banner ad below. I have added a suggestion to replace the class with an id.
=> F: Hidden Footer on thedriven.io

fanboy-addon/fanboy_newsletter_thirdparty.txt
https://www.ecoteekki.fi/
Mailchimp seems to be a popular newsletter provider. Their script is used very widely:
https://publicwww.com/websites/downloads.mailchimp.com%2Fjs%2Fsignup-forms%2Fpopup%2Funique-methods%2Fembed.js/
I don't feel safe blocking the whole domain so made the rule quite specific. But it will still block widely.
=> A: ecoteekki.fi (generic newsletter block)

easylist/easylist_specific_block.txt
Image backgrounds ad on thejournal.ie
The links is blocked by EL rule: `||doubleclick.net^$third-party` but image background remains unblocked.
=> A: https://www.thejournal.ie/

easylist_cookie/easylist_cookie_specific_uBO.txt
This is a continuation for this PR: https://github.com/easylist/easylist/pull/12990
This PR hides the GDPR dialog for these domains, but restores it if the article has embedded content such as tweets. For `iltalehti.fi` it's possible to make videos to work without accepting cookies via scriplet (included) though it doesn't work for tweets. In other domains videos work without accepting cookies, but tweets won't.
Other domains than `iltalehti.fi` show this error text when content couldn't be loaded:
It means: `Content couldn't be loaded. This could be due to a browser extension`.
This text doesn't appear immediately so the GDPR dialog won't appear either immediately as it's showing is related to that error text. Before that text appears, there's a colorful loading icon:
It would be …
=> A: arvopaperi.fi + others (GDPR dialog hide)

easyprivacy/easyprivacy_allowlist_international.txt
Can't offer a flower to Sinzo Abe at final step if `https://api.ipify.org/?format=json` is blocked (maybe 1 offer/ 1 IP restriction)
=> P: offering-flower.com

easylist/easylist_specific_hide.txt
`https://www.bloomberg.com/features/2022-mbs-neom-saudi-arabia/?srnd=businessweek-v2`
Scripts on the page sometimes modify classes of the div, invalidating the selector, so `class*=` is needed here.
=> M: fix bloomberg.com ad selector

easyprivacy/easyprivacy_specific.txt
The domain `plausible.bots.gg` hosts a Plausible instance for loading and sending analytics.
=> A: https://discord.bots.gg/

easyprivacy/easyprivacy_general.txt
also on https://askfigarorecruteur.zendesk.com, and so on on all zendesk websites
i took the liberty to remove `/hc/tracking/*`, as I don't see it anywhere, I guess it was replaced by this new one.
=> A: https://support.nfl.com zendesk tracking

fanboy-addon/fanboy_newsletter_international_hide.txt
Sample link: https://moottori.fi/liikenne/jutut/hirvet-liikkuvat-entista-enemman-pysy-valppaana-hirvivaara-alueella/
`Tilaa uutiskirje ja osallistu arvontaan` translates to `Subscribe to a newsletter and participate in a draw.`
Using a procedural because I feel that it's safer.
`a[href="/tilaa-moottorin-uutiskirje/"]` -> `tilaa-moottorin-uutiskirje` translates to `subscribe to moottori's newsletter`.
=> A: moottori.fi (newsletter)

easylist_cookie/easylist_cookie_allowlist_general_hide.txt
https://www.hankosushi.fi/
This site uses a pre-order dialog. When it's hid, scrolling and using the site becomes impossible because the pre-order dialog locks scrolling at the same time.
Translation:
https://translate.google.fi/?hl=fi&sl=fi&tl=en&text=Tilaa%20ennakkoon%0ATee%20tilaus%20verkkokaupasta%0AValitse%20ravintola%20t%C3%A4%C3%A4lt%C3%A4&op=translate
=> P: hankosushi.fi (pre-order form and scrolling blocked)

easylist/easylist_specific_hide.txt
**atalayar.com** has **English**, **Spanish** and **French** versions and filter added on [commit](https://github.com/easylist/easylist/commit/b61e9a4) doesn't seem to hide the top banner in all versions, so I'm suggesting `##.superbanner` to hide this top ad.
Also suggesting `atalayar.com##.column-content > .megabanner` (or simply `atalayar.com##.megabanner`) to hide in-content ads with PUBLICIDAD labels.
And `atalayar.com##.rotulo-publi` to hide PUBLICIDAD labels on the home page and article pages.
=> A: https://atalayar.com/en

easylist/easylist_allowlist_general_hide.txt
EL blocking content on labartt.com
**Sample URL:** https://www.labartt.com/detail-nemovitosti/pronajem/komercni-prostor/pronajem-obchodniho-prostoru-58-m-670916
Another way to reproduce the issue is to go to https://www.labartt.com/nabidka-nemovitosti/ search for some property, choose one of the available options and you will get a page with missing content such as picture and text.
=> P: https://www.labartt.com/detail-nemovitosti/pronajem/komercni-prostor/pronajem-obchodniho-prostoru-58-m-670916

easylist/easylist_specific_hide.txt
EL rule: `addictivetips.com,gamerevolution.com##.custom-html-widget` hides the website logo
**Note: on addictivetips.com filter works fine; it hids a VPN deal banner on [sampleURL](https://www.addictivetips.com/vpn/instagram-account-hacked/)**
=> P: https://www.gamerevolution.com

fanboy-addon/fanboy_annoyance_specific_hide.txt
Block #post_more_wrapper on crimereads.com (lithub.com sister site)
e.g. `https://crimereads.com/conspiracy-theory-seth-rich/`
=> A: crimereads.com

easyprivacy/easyprivacy_allowlist.txt
Fixes https://forums.lanik.us/viewtopic.php?t=47798-ride-guru.
The location autocomplete functionality of the site is broken if this is blocked. See the forum post for more details.
=> Fixes forum report regarding ride.guru

easylist/easylist_allowlist_popup.txt
Dashboard table with campaign list seem to be blocked  by EasyList filter `://ads.$popup`
Link is used for the Campaign Manager tool Doordash for advertisers to manage their campaigns.
https://ads.doordash.com/api/reporting/v1/sp/metrics/advertiser?startDate=2012-09-09%2000%3A00%3A00&useTestData=false
https://ads.doordash.com/api/reporting/v1/sp/metrics/campaigns?count=8&startDate=2012-09-09%2000%3A00%3A00&startIndex=0&useTestData=false
=> P: https://ads.doordash.com/portal

easylist/easylist_specific_hide.txt
VPN to US, EL + ABP
Go to https://chloeting.com/recipes/high-protein-creamy-garlic-chive-dip
There is a white sticky bar at the bottom of the viewport (div[class^="StickyFooterAds__Wrapper"])
=> A: Unblocked element on chloeting.com

easylist/easylist_specific_hide.txt
This PR removes false positives that were hiding author info on `healthline.com` articles.
e.g., `https://www.healthline.com/health/acne/definitive-guide-to-acne-everything-you-need-to-know`
Current:
With false positives removed:
=> healthline.com - remove false positives

easylist_cookie/easylist_cookie_general_hide.txt
Remove uk-notify, as it is breaks some webpages.
Our developers could not see any error messages (`class="uk-notify-message uk-notify-message-danger"`) due to the blocked popup.
I am not familiar to how easylist operates, but I see this annoying, as error messages are blocked. Only blocking `uk-notify-message-info` would be better maybe?
Also I'm failing to understand how a disappearing notification could be a valid cookie form :D Maybe this really is a false positive?
=> Remove uk-notify class from easylist cookies

easylist/easylist_general_block.txt, easylist/easylist_thirdparty.txt
Most of links are NSFW
`.club/js/popunder.js`: 
```
movies24.club
dating-24.club
girlss.club
```
`/sponsors/popunder.`: 
```
https://javsister.com/erofc-103-studio-love-girlfriend-new-graduates-beauty-surgery-reception-older-sister-nampa-gonzo/
https://xxx-picture.com/alessandra-ambrosio/alessandra-ambrosio-gives-a-busty-display-after-a-yoga-class-49-photos/
```
`||akamaized.net/mr/popunder.js`: 
```
https://dakshaventures.com/download-now-1/
londonbespokeinteriors.co.uk
individualki-all.ru
```
`||scriptadmin.com/scripts/popunder.js`:
```
www.daily-camshow-report.com
chaturqate.com
```
`||toplist.raidrush.ws^$third-party`: 
`bestoflinks.synology.me`
(`https://toplist.raidrush.ws/` is a website so needing `$third-party`)
=> M: replace /popunder. with specific rules

easylist_cookie/easylist_cookie_international_specific_hide.txt
https://www.apteekkiverkkokauppa.fi/
Even if the class name might sound generic, it's not widely used, so specific better. https://publicwww.com/websites/GBaseGDPRConsentDialog/
=> A: apteekkiverkkokauppa.fi (GDPR banner)

easylist/easylist_adservers.txt, easylist/easylist_specific_block.txt
`iolenproces.asia` is a FingerprintJS server called from sw.js and will change soon:
=> A: apkmaven.io

easylist/easylist_adservers.txt, easylist/easylist_specific_block.txt
I'm pretty sure the target of `/^https?:\/\/.*\/sw.js?.[a-zA-Z0-9%]{50,}/$script,~third-party` is these: `https://apkmaven.io/sw.js?TTJPNUUWEHYDdn8CdhdpbxBjF3Z7CnwCdXgFYgUjfQdiAXcsVmJXI39XYg0mKFZ%2EVnN0C3wHd28ebQN1Lgt5AXd7H38HfC8fewF2fB8tAnV%2EH3cGJnpXegBwKFcqUWdhEDxCZ2EQPVwmKEUuQSA%2EWiBAazVLNRdpbwN%2EG3BvHilUKT5XY1MkIUEqGSMsXjxQGA` so removed unneeded period after `?`.
=> M: properly escape in regex rules

easyprivacy/easyprivacy_specific.txt
jse is the error reporting stuff, only appears when there is a JS error in the page. Mine was caused by one of my browser extensions, https://addons.mozilla.org/fr/firefox/addon/dark-background-light-text/.
=> A: https://dropbox.com/s/jtvozx5213xjghy/20220908%20BPEA%20comment.pdf

easylist/easylist_allowlist.txt
Even if The `https://adservice.sbs.co.kr/NetInsight/vast/` request is blocked, any anti-adblock script does not active.
<details>
</details>
The change related to `@@||ad.smartmediarep.com/NetInsight/$domain=programs.sbs.co.kr` improves the  anti-adblock prevention without allowing logging requests.
<details>
</details>
The changes that will be updated is added at https://github.com/easylist/easylist/commit/d26456b198f1490e75280ec0f9de5f7e5e842acd.
Related Issue: https://github.com/AdguardTeam/AdguardFilters/issues/132176
=> M: programs.sbs.co.kr

easyprivacy/easyprivacy_specific.txt
looks like the whole domain is only used for tracking purposes despite its name. i was able to login, and then go to the payment process with domain blocked.
=> A: https://www.instacart.com/store/hub/grocery

easylist/easylist_adservers.txt
Seems to be a parking domain, if not, ||123movies.to/js/parking.2.99.0.js can be blocked as it's redirecting to another page.
=> A: http://123movies.to/ [Parking]

easyprivacy/easyprivacy_trackingservers_international.txt
attr-2p.com domain is related with 2Performant affiliate network and is used for tracking.
=> A: attr-2p.com

easyprivacy/easyprivacy_allowlist.txt, easyprivacy/easyprivacy_general.txt
The fix added with `33dc423` (allowing the `transparent.gif`request) is not required to pass Cloudflare challenges pages and can be removed.
Additionally, the endpoint `/cdn-cgi/bm/cv/*` isn't used by Cloudflare anymore and can also be removed.
The one starting with `/cgi-bin/` was never used by Cloudflare and seems to be a typo coming from
`https://github.com/easylist/easylist/issues/5416#issuecomment-636283302`.
=> Remove legacy Cloudflare endpoints

easyprivacy/easyprivacy_thirdparty.txt
enter a dummy address on https://www.linforme.com/abonnements then you'll have the  stripe form that sends tracking to both domains.
r.stripe.com receives bunch of tracking data in cleartext, whereas m.stripe.com receives encoded tracking stuff. Payment-related data are sent to other endpoints.
I've tested by clocking both domains and was able to successfully make a payment.
=> A: https://www.linforme.com/abonnements

easyprivacy/easyprivacy_general.txt
`https://www.maaseuduntulevaisuus.fi`
`https://www.koneviesti.fi/`
Tracks articles you read.
=> A: maaseuduntulevaisuus.fi + koneviesti.fi

easyprivacy/easyprivacy_general.txt
This classic tracking pixel is added to emails, example:
```
<div class="tracking"><img alt="" height="0" src="
https://opens.jscrambler.com/home/index/?token=XXX" width="0"></div>
```
=> Add Jscrambler email tracking pixel host

easylist/easylist_allowlist.txt
While the situation with the Advertising Board image on Nookipedia was mostly fixed, the full size image is still blocked as the URL is only whitelisting thumbnails instead of full images.
=> Fixing dodo.ac link

easylist_cookie/easylist_cookie_specific_uBO.txt
On `fandom.com`, cookies have to be accepted to get videos to work. Made rules to hide to dialog but restore it if the page has videos on it.
Video pages:
https://www.fandom.com/video/FoKuC1r0/its-a-me-mario-the-loop
https://www.fandom.com/articles/hgt-wow-wrath-of-the-lich-king
https://www.fandom.com/articles/the-weird-wonderful-history-of-maniac-mansion (after the article)
Non-video pages:
https://naruto.fandom.com/wiki/Hashirama_Senju
=> A: fandom.com (GDPR dialog hide, uBO)

easylist/easylist_specific_hide.txt
Those selectors are not related to sponsored content. Zalando uses utility classes (e.g. `lRlpGv` is used to set padding). Using those generic selectors will hide a lot of elements that may or may not be sponsored content resulting in a broken experience.
We could eventually maintain the `(span:-abp-contains(/Gesponsert|Gesponsord|Patrocinado|Sponset|Sponsitud|Sponsored|Sponsoreret|Sponsorēts|Sponsorizzato|Sponsorisé|Sponsoroitu|Sponsorowane|Sponsrad|Sponzorirano|Sponzorováno/))`, but not sure how to rewrite it without the hardcoded utility class `Uxq3DH`?
abp-contains may also result in an unwanted behavior here: a sponsored content may have a possibly parent, sibling, or child element that contains the word "sponsored", hiding that element will hide the sponsored flag, but preserve the …
=> Remove blocked generic utility classes for Zalando

easylist_cookie/easylist_cookie_specific_uBO.txt
Filter update.
https://www.whatsapp.com/
Added also `www.`-prefix because these filters are not needed on https://web.whatsapp.com/.
=> M: whatsapp.com (GDPR hide, uBO)

easylist-cookie-uBO.template, easylist-cookie.template, easylist.template, easyprivacy.template, fanboy-annoyance-uBO.template, fanboy-annoyance.template, fanboy-cookie.template, fanboy-newsletter-uBO.template, fanboy-newsletter.template, fanboy-notifications-uBO.template, fanboy-notifications.template, fanboy-social-uBO.template, fanboy-social.template, fanboy-sounds.template, template_header.txt
Before, many lists had different license information and forum/email links.
Now, all this is included from a single template file.
=> Use common header text for all lists

easyprivacy/easyprivacy_allowlist.txt
CNAME breakage, login failed
I succeeded to login only by allowing script (images and frames still blocked)
=> P: https://www.eki-net.com/Personal/Top/Index (account required)

easylist/easylist_general_block.txt
Domains which requests are affected: adv2.com www.adv2.com wallet.adv2.com static.adv2.com adv2.zendesk.com
It seems to be related to financial/crypto topics.
=> M: https://adv2.com/

easyprivacy/easyprivacy_general.txt, easyprivacy/easyprivacy_specific.txt
substack can be on self-domain.
Also https://www.platformer.news/p/elon-takes-over-twitter https://www.lescryptosdecaro.com/recommendations ...
=> A: https://newsletter.mem.ai/about

easylist_cookie/easylist_cookie_specific_uBO.txt
it break all modals, including functional ones (once logged-in). Ie. try to add api key on https://console.scaleway.com/project/credentials, and many others.
revert https://github.com/easylist/easylist/commit/5211a37327c9bfd42e591db85989d0fb965e3f0c
=> P: https://console.scaleway.com

easyprivacy/easyprivacy_specific_international.txt
same owner than lemonde.fr, same ATInternet.Tracker calls
=> A: https://www.courrierinternational.com/

easyprivacy/easyprivacy_specific_international.txt
function that does this call is named ATInternet.Tracker... linked to cookiewall
that was not present few weeks ago when i looked at this site, that's alive! so let's block all ATInternet calls instead of this single path that will probably change soon
=> A: https://www.lemonde.fr/

easylist/easylist_allowlist.txt
Blocking rule was removed and thus no longer needed (+ `search.news24.jp` is no more in active use).
=> M: remove obsolete rules

easyprivacy/easyprivacy_specific.txt
The rule is too wide and breaking legitimate transition when user visit non-existing page e.g. `https://nikkanerog.com/blog-entry-21.html`
See https://github.com/easylist/easylist/commit/d4d17f529677acf1857361ed1979e9c810c309b0#commitcomment-53891583
=> M: make specific

easylist/easylist_specific_hide.txt
Hi, 
I would really appreciate if you can add this filter to the list as it was reported as containing ads and although some filters were added after my first request [in here](https://github.com/easylist/easylist/commit/323d7cca8cfd350f238b5d6f17037f1f8d6c4adb) the home page of the websites still has ads, as the proposed earlier filters only hide the ads on subpages. And I was trying to get in touch with author on this regards yet was not able to.
Please note that the filter I am trying to add would hade the ads on both main page and subpages of the same domain. 
Thank you in advance.
=> A: `https://greyhound-data.com/`

easyprivacy/easyprivacy_thirdparty.txt
looks adobe tracking by proxify
on all norauto national websites
=> A: https://www.norauto.it/

easyprivacy/easyprivacy_thirdparty.txt
this p.typekit.net domain seams to serve exclusively trackers, ie. empty pixel on https://crypto.com/fr (already blocked) and empty css on https://group.accor.com/ (not blocked). Real resources are on use.typekit.net.
=> A: https://group.accor.com/

easyprivacy/easyprivacy_general.txt
more strict to catch only readthedocs
test on https://picostory.com/en/latest/
fix #14634
=> P: https://prime.coinbase.com/

easyprivacy/easyprivacy_allowlist.txt
Given the typekit rule is here to stay (see https://github.com/easylist/easylist/pull/14759), this is adding robertsspaceindustries.com to the allow list for `p.typekit.net/p.css`.
The current impact is the store is not loading at all with Easylist enabled, see details here: https://github.com/easylist/easylist/issues/14723#issuecomment-1400797333
=> M: Allow p.typekit.net/p.css for robertsspaceindustries.com

easylist/easylist_general_hide.txt, easylist/easylist_thirdparty.txt, easyprivacy/easyprivacy_thirdparty_international.txt, fanboy-addon/fanboy_annoyance_international.txt
After https://github.com/easylist/easylist/commit/f5454f43fe82f77984f7025024360feb4a3b9e8f all popIn staff was working fine, but these two rules added later have been breaking all popIn widgets (e.g. `https://otekomachi.yomiuri.co.jp/lifestyle/20220126-OKT8T329272/`). This PR fixes them while still blocks their tracking staff and ads. OTOH blocks popIn more aggressively as annoyances and cosmetically cleaned them up by rules taken from AG Annoyances.
=> M: unbreak popIn widgets, update #6009

easyprivacy/easyprivacy_thirdparty.txt
They have www. too, so an international site. Fingerprint for the sake of security, I don't see breakage by blocking them.
=> A: jp.shein.com

easylist/easylist_general_block.txt
`webryblog.biglobe.ne.jp` was EOL today, can safely be removed.
=> M: remove dead service webryblog.biglobe.ne.jp

easyprivacy/easyprivacy_allowlist.txt
Adding business.untappd.com to the allow list for p.typekit.net/p.css
The current impact is our menu builder that is used by our customers stops functioning and hangs indefinitely. Same situation as https://github.com/easylist/easylist/issues/14723#issuecomment-1400797333
=> M: Allow p.typekit.net/p.css for business.untappd.com

easylist/easylist_general_hide.txt
Hi, please remove filter from the generic it's breaking this page 'https://subsbr.net/' appears absolutely blank and the users cant access it.
=> D: `##.quads-location `

easylist/easylist_adservers.txt
Block links like it https://z.cdn.trafficbass.com/load?o=v&z=1727922201&random=124124557 to stop playing advertisement video.
=> add trafficbass.com to servers list.

easylist/easylist_general_block.txt
Hi, Could you please add the exception `~accesdiffusion.com` to the existing filter `/adshare.$domain=` 
The company is  running a website for sharing to technical files with our customers and partners (B2B business). And uses  “adshare” because of our Company name (A)cces (D)iffusion. Therefore their contact form is getting blocked by the existing filter in the list.  
Thank you
=> A: `https://adshare.accesdiffusion.com`

easylist/easylist_general_block.txt
Hi, please add the exception for `https://adops.gr/` on the existing filter `/adops.$domain=`. The page content it’s being blocked by EasyList and the page maintainer said this: "We're an Ad Operations agency based in Greece and our website is for presentation purposes only. There are no ads included. Our site has a problem when the adblock is active, the filter which blocks us is 'easylist' list. Domain with problem is: `https://adops.gr/`"
Thank you
=> A: `https://adops.gr/`

easyprivacy/easyprivacy_specific_international.txt
Blocks tracking images and pings sent on various page loads and events.
I believe the existing filter was detected by the devs and they just inversed the letters `ptag`/`vtag`. Still kept the old one, you never know.
Some examples:
````
https://www.lemonde.fr/cc3303527dc0fa0a9037bc650805c0e0f6c041a6?s=43260&vc=false&vm=exempt&ts=1676319490964&vtag=5.28.1&gatp=js&r=1920x1200x24x24&re=1087x1046&p=Home::Beta::default::Home&s2=5&stc={"Pagetype":"Home","Population":"Premium","Producteur":"Edito","ir":"false","consent":"not found","consent AT":"false"}&ref=https://www.lemonde.fr/societe/article/2023/02/13/violences-au-stade-de-france-planification-ratee-modele-de-police-inapproprie-un-rapport-sans-concession-sur-le-fiasco-de-la-finale-liverpool-madrid_6161670_3224.html …
```
=> A: https://lemonde.fr

easyprivacy/easyprivacy_thirdparty_international.txt
On articles from lemonde.fr, sends regular events of your reading status when you're logged-in.
The domain contains a js file, and endpoints like /hello, /ping, and /bye (when you're navigating to another tab)
=> A: https://capping.sirius.press

easyprivacy/easyprivacy_specific_international.txt
Domain used for a rehost of Google's gtag, and various custom tracking scripts.
Doesn't seem to block user interaction, including subscription and login.
=> A: https://www.bouyguestelecom.fr

easyprivacy/easyprivacy_specific_international.txt
The path `lepoint.fr/img-l/*` only contains 1*1px images hidden with `position:absolute; top:-50000px;`
Doesn't seem to block real images on pages I've visited.
=> A: https://www.lepoint.fr

easyprivacy/easyprivacy_trackingservers.txt
Adds extra logrocket tracking domains, as listed on https://docs.logrocket.com/docs/troubleshooting-sessions
Logrocket is already on this list (lr-ingest.io, logrocket.io, logrocket.com), this just makes coverage more complete.
=> A: lr-in.com, lr-in-prod.com

easylist_cookie/easylist_cookie_specific_hide.txt
https://deals.ghacks.net/
https://deals.thehackernews.com/
=> A: deals.ghacks.net + deals.thehackernews.com

easylist/easylist_specific_hide.txt
Article title hidden behind navbar on mobile
now:
after:
______
For top one:
Takes care of other placeholders:
=> P: https://www.irishnews.com/

easyprivacy/easyprivacy_general.txt
also seen on https://hookupsofficial.myshopify.com/
they are bypassing #13038
=> A: https://fr.delsey.com/ shopify tracking

easylist_cookie/easylist_cookie_specific_uBO.txt
These rules cause breakages on Adguard Safari. Added a pre-parsing directive, to mark these rules not to load on Adguard Safari.
See:
https://github.com/AdguardTeam/AdguardFilters/issues/144434
https://app.slack.com/client/T010N0F70N4/C010N14G4TF/thread/C010N14G4TF-1679324071.857329
=> P: bloomberg.com (ELC issue on Adguard Safari)

easylist_cookie/easylist_cookie_specific_hide.txt
Rule overblocked the whole content of the page.
Site to test: https://studio.glassnode.com/metrics?a=BTC&m=indicators.StockToFlowRatio
=> M: https://studio.glassnode.com/

easyprivacy/easyprivacy_allowlist.txt
Hi, 👋  could you please add the allowlisting filter to the list.  Easy privacy breaks the search engine (top bar one ☝️ ) on this website `www.insiderintelligence.com`. This filter fixes the issue. Thank you in advance.
=> M: Fix for `www.insiderintelligence.com`

easyprivacy/easyprivacy_specific_international.txt, easyprivacy/easyprivacy_trackingservers_international.txt
l.bfmtv.com is an alias for non.li
https://www.nonli.com/
=> A: https://www.bfmtv.com

easyprivacy/easyprivacy_specific_international.txt
Changed to block tracking request `https://rac.ruutu.fi/json/rac-supla` (POST) on `www.supla.fi/radio/53`. `rac.ruutu.fi` can be fully blocked as it is only used for tracking.
=> M: Fully block rac.ruutu.fi

easylist/easylist_general_hide.txt
Ad placeholders on https://www.thelocal.it (including article pages)
=> A: https://www.thelocal.it

fanboy-addon/fanboy_social_general_hide.txt
Some example sites
`aamuposti.fi`
`esaimaa.fi`
`ess.fi`
`forssanlehti.fi`
`hameensanomat.fi`
`hankasalmensanomat.fi`
`heinavedenlehti.fi`
links to more sites can be found in the footers of these sites
=> A: Multiple sites (generic social hide)

easylist/easylist_specific_hide_abp.txt
Hi please review and add these filters to block ads on `booking.com` There are ads on desktop view for which this filter can be used `booking.com#?#div[data-testid="property-card"]:-abp-has(div[data-testid="new-ad-design-badge"])`
Ads on lower screen, like tablets for which this filter would work: `booking.com#?#div[data-testid="property-card"]:-abp-has(span[data-testid="new-ad-design-badge"])` 
Thank you in advance
=> A: `booking.com`

easylist_cookie/easylist_cookie_specific_hide.txt
Without the additional filter rule the page stays greyed out with no apparent reason since the cookie info container itself is already blocked.
Site to test: https://estore.asus.com/de/90nr0bp0-p10020-rog-xg-mobile-2023.html
=> A: https://asus.com

easyprivacy/easyprivacy_general.txt
This is the GitHub Pages domain used for Criteo open source documentation
=> Add an exception for criteo.github.io

easylist/easylist_specific_hide.txt
There's also floating video annoyance, maybe `||dailymail.co.uk/static/mol-adverts/$domain=thisismoney.co.uk` but don't know if 100% safe.
=> A: www.thisismoney.co.uk

fanboy-addon/fanboy_notifications_specific_hide.txt
Because of this entry, the whole notification list is now unloadable in uBO, as easylist-downloads.adblockplus.org doesn't host this file: fanboy_notifications_specific_uBO.txt
This doesn't work in uBO: https://easylist-downloads.adblockplus.org/fanboy-notifications.txt
As now this whole list is unloadable in uBO, It's better to leave uBO section out rather than drop the whole list from uBO. If this change is made, the list should work in uBO as before.
=> Remove !#include uBO Fanboy notifications

easyprivacy/easyprivacy_specific_international.txt
hlms.ecologie.gouv.fr is an alias for minecologie.ent.et-gv.fr. minecologie.ent.et-gv.fr is an alias for gva.et-gv.fr.
et-gv.fr is Eulerian tracking corp (may be needed to add gva.et-gv.fr to the CNAME list?)
=> A: https://www.ecologie.gouv.fr/

easyprivacy/easyprivacy_specific_international.txt
wrhv.education.gouv.fr is an alias for mineductandem.ent.et-gv.fr.,  is an alias for gva.et-gv.fr.
et-gv.fr is Eulerian tracking corp (may be needed to add gva.et-gv.fr to the CNAME list?)
=> A: https://www.education.gouv.fr/

easyprivacy/easyprivacy_specific_international.txt
domain changed.
`||jen.jiji.com/cookie.html` -> `||mng.jiji.com/cookie.html`
Related Commits:
https://github.com/easylist/easylist/commit/1a81a02e4e5f4dfb7ee59d41fd8b13c37cb07b63
=> M: https://www.jiji.com/jc/article?k=2023041800146&g=eco

easyprivacy/easyprivacy_specific_international.txt, easyprivacy/easyprivacy_trackingservers_international.txt
bmly.impots.gouv.fr is an alias for mineco.ent.et-gv.fr. is an alias for gva.et-gv.fr.
et-gv.fr belongs to Eulerian, big tracking corp
=> A: https://impots.gouv.fr

easyprivacy/easyprivacy_trackingservers.txt
tracking seen on https://usermaven.com/ page itself, also on third-party like blog.contentstudio.io
tracking company
=> A: https://usermaven.com/

easyprivacy/easyprivacy_specific.txt
um.contentstudio.io is an alias for whitelabel.usermaven.com
fix #15576
=> A: https://blog.contentstudio.io/

easyprivacy/easyprivacy_specific.txt
Needs to have `?amp=` parameter in the url to show up.
e.g. `https://www.newsweek.com/lake-tulare-california-filling-water-return-1795617?amp=1`
=> A: https://www.newsweek.com/

easylist/easylist_thirdparty.txt
Used worldwide, already in AG Base: `https://publicwww.com/websites/%22feed.mikle.com%22/`
=> A: www.bodysense.jp

easylist/easylist_adservers.txt
Hey guys! 👋 
This PR removes `orchestrator.strn.pl` from `easylist_adservers.txt`.
Why should `orchestrator.strn.pl` be removed? In short, it's a network orchestration service for [Saturn](https://saturn.tech/), a Content Delivery Network (CDN), and not an ad server. It's unrelated to ads.
* `strn.pl` is the CDN domain of [Saturn](https://saturn.tech/), a decentralized CDN for [IPFS](https://ipfs.tech/) and [Filecoin](https://filecoin.io/). Here's an example `strn.pl` URL which returns a [CAR file](https://ipld.io/specs/transport/car/): https://strn.pl/ipfs/bafybeifx7yeb55armcsxwwitkymga5xf53dxiarykms3ygqic223w5sk3m.
* The `orchestrator.strn.pl` subdomain is the orchestrator service of Saturn. The orchestrator keeps track of, and manages, CDN nodes and content in Saturn's network and …
=> Remove orchestrator.strn.pl.

easylist/easylist_general_hide.txt
https://www.pyhajokiseutu.fi/
Ad separator, visible if you resize your screen to small.
EL already has this rule:
`###ad-separator`
So the class version would be a good generic also imo.
=> A: pyhajokiseutu.fi (generic hide)

easylist/easylist_general_block.txt
Used e.g. on `https://www.nei-isep.org`
Their site `https://wp-time.com/popad-ultimate-popup-ads-plugin/` is broken by 12 years old rule `/popad-` and I can't easily find usefulness of the rule: `https://publicwww.com/websites/%22%2Fpopad-%22/`
=> M: block PopAd plugin, fixes their site

easyprivacy/easyprivacy_trackingservers_international.txt
`talpa-analytics.com` on `zigstyle.jp` and `talpa-analytics.work` on `cosmeadviser.com`. Used internationally but the company looks to be headquartered in Japan.
=> A: zigstyle.jp, cosmeadviser.com

easyprivacy/easyprivacy_general.txt, easyprivacy/easyprivacy_trackingservers_international.txt
`https://ac.dmtag.jp/fpc/cookie_js.php` on `www.rosettastone-lc.jp` too, they share the same pattern `/fpc/cookie_js.php`.
=> Tracker acaric.jp

easylist/easylist_thirdparty.txt
This reverts part of f316bc037d570532987ce6964b579b52fcaf9861 from #16310 which included `d1ayxb9ooonjts.cloudfront.net` a false positive.
This causes a regression loading https://bitly.com/ and this domain is not used for Ads. (disclosure: I work @bitly)
=> bitly.com regression

easylist/easylist_specific_hide.txt
Hi please review and add this filter to block the ads and empty space on this webpage:  
- ads on the background 
`mediaweek.com.au###wallpaper`
- left over space at the top
`mediaweek.com.au##.leader-wrap-out`
Thank you
=> A:`mediaweek.com.au`

easylist_cookie/easylist_cookie_international_specific_hide.txt
The EasyList Cookies contains two lines for the site pr0gramm.com:
```
1. pr0gramm.com###overlay
2. pr0gramm.com##.overlay-consent
```
This PR removes both, because of:
1. is a wrapper element for all kinds of overlays. This rule blocks essential functionality of the site, such as logging in, resetting passwords and more specific features, such as content collection (marking content as favorites). This rule also removes the possibility for users to report inappropiate content. It is not used for cookie consents and also not for ads. It only wraps site specific features and is not used for tracking elements.
2. pr0gramm.com switched to a third-party cookie consent management called Quantcast, which is already covered by this list. Therefore, this rule is no longer needed.
=> Remove pr0gramm.com overlay-rule as it blocks too much

easylist_cookie/easylist_cookie_specific_uBO.txt
https://historianet.fi/kulttuuri/arkeologia/3d-kuvat-paljastavat-uskomattoman-loydon-titanicin-hylysta
https://tieku.fi/teknologia/twitterin-perustaja-loi-uuden-sosiaalisen-verkoston
Needed for embedded content.
In order to reproduce this, might need to block tinypass.com temporarily (unlock articles).
`##.topscroll-banner` is a banner that appears at the top occasionally, warning about content that might not be visible because of GDPR. But content works just fine.
=> A: historianet.fi,tieku.fi (GDPR, uBO)

easylist_cookie/easylist_cookie_general_block.txt
https://www.kaypahoito.fi/
https://www.gogolf.fi/
No problems with tweets https://www.gogolf.fi/artikkelit/charlie-woods-haluaa-osansa-tigerille-myonnetysta-8-miljoonasta-lisaa-viikkorahaa-ilman-minua-et-olisi-ollut-kymmenen-joukossa/
I think this generic wp script is ok to block.
Or if `-gdpr-cookie-consent/` is too generic, this can also be used:
`/webtoffee-gdpr-cookie-consent/*`
=> A: kaypahoito.fi & gogolf.fi (generic block, GDPR)

easyprivacy/easyprivacy_general.txt
Included in emails for tracking email being opened/read.
Example: https://secure.booking.com/email_opened_tracking_pixel?lang=es&aid=2090014&token=xxx&type=confirmation_guest
=> A: secure.booking.com

easylist/easylist_specific_hide.txt
This PR removes generic bootstrap rules from blacklist. 
pb-1 is used for setting padding bottom to 1rem.
w-100 is used for setting width to 100%.
With these rules website gets broken, and useful content to users is not properly displayed.
=> M: Remove bootstrap generic rules: bitdegree.org, ebook-searcher.com

easylist/easylist_specific_hide.txt
After closing the modal that appears upon entering the site, there will be an ad banner on the bottom left. This pull request hides that banner.
<details>
</details>
This pull request fixes https://github.com/uBlockOrigin/uAssets/issues/18567.
=> A: `mybib.com`

easylist_cookie/easylist_cookie_specific_hide.txt
=> A: https://www.shuttle.rs/ (Fix #16234)

fanboy-addon/fanboy_newsletter_specific_hide.txt
Hides newsletter popup leftovers.
This pull request fixes #13223.
=> A: `delacortereview.org`

easyprivacy/easyprivacy_specific_international.txt
`https://vatandas.iys.org.tr/giris?redirect=%2Fprofil`
I have tested this rule for a long time. It does not break the website.
</details>
=> iys.org.tr

fanboy-addon/fanboy_social_specific_hide.txt
Hides social banner.
<details>
<summary>Screenshot:</summary>
</details>
This pull request fixes #14230.
=> A: `infobyip.com`

easyprivacy/easyprivacy_specific.txt
The domain `fp.heavybit.com` is used to track page impressions.
This pull request fixes #14187.
=> A: `heavybit.com`

easyprivacy/easyprivacy_trackingservers.txt
The domain `fourtimessmelly.com` is used to load pixel tracker and send page analytics.
<details>
<summary>Screenshot:</summary>
</details>
This pull request fixes #14831.
=> A: `game.co.uk`

easylist/easylist_specific_hide.txt
Hides ad banner leftover.
This pull request fixes #15184.
=> A: `unogs.com`

easylist/easylist_specific_hide.txt
Hides advertisement squares.
This pull request fixes #15224.
=> A: `appatic.com`

easyprivacy/easyprivacy_specific.txt
The domain `api.privacyguides.net` is used to log page-view events. It logs current page, page referrer, and viewport width.
<details>
<summary>Screenshot:</summary>
</details>
=> A: `privacyguides.org`

easylist/easylist_thirdparty.txt, easyprivacy/easyprivacy_thirdparty.txt
To address the ad/tracker on `https://www.freeroms.com/sega_dreamcast.htm`.
https://github.com/easylist/easylist/assets/89158249/27702b2e-6617-4dbb-aa39-ebe9f7d55d2c
=> Update EasyList/EasyPrivacy Third Party

easylist/easylist_specific_hide.txt
Hides ad leftover.
This pull request fixes #15259.
=> A: `1000logos.net`

easylist/easylist_specific_hide.txt
This pull request fixes #15295.
=> A: `who-called.co.uk`

easylist_cookie/easylist_cookie_specific_hide.txt
cookie banners
https://www.just-eat.ch/
https://www.just-eat.co.uk/
https://www.just-eat.dk/
https://www.just-eat.es/
https://www.just-eat.fr/
https://www.just-eat.ie/
https://www.justeat.it/
https://www.lieferando.at/
https://www.lieferando.de/
https://www.pyszne.pl/
https://www.takeaway.com/be
https://www.thuisbezorgd.nl/
=> A: just-eat.*

easylist/easylist_adservers.txt
Used on: https://rpgcodex.net/forums/threads/why-is-there-some-twitch-stream-embed-popup-on-a-thread-page.147802/
Loaded script: https://go.twads.gg/adsbytwadsgg.js?client=...
Ads are a promoted twitch stream (video) which is embedded in a floating window. Example images from the linked thread:
https://i.imgur.com/Uo6XNqp.png
https://i.imgur.com/DmQ0Zt5.png
https://i.imgur.com/2rQSmQC.png
Script is always loaded but ads only appear sometimes.
=> Add https://twads.gg/ - Advertising Network for Streaming Promotion 

easylist/easylist_specific_hide.txt
Banner on top of the page, reported in this[ issue](https://github.com/easylist/easylist/issues/16937) :
=> A:`fmforums.com`

easylist/easylist_adservers.txt
From `gartic.io`:
Weirdly, `adinplay.com` does not appear to be blocked even though it is present in the list.
=> Add adinplay.workers.dev to adservers list

easylist/easylist_specific_hide.txt
Hides ad banner and ad banner leftover.
This pull request fixes #15511.
=> A: `copyprogramming.com`

easylist/easylist_specific_hide.txt, fanboy-addon/fanboy_newsletter_specific_hide.txt
Hides ad popup and newsletter form.
This pull request fixes #14658 and fixes #15505.
=> A: `techspree.net`

easylist/easylist_allowlist_general_hide.txt
Hi, could you please add the filter to the existing allowlisting filter.  The generic filter is hiding one of the websites heading at the moment: 
Thank you
=> A:`macys.com`

easylist/easylist_specific_hide.txt
Advertisement feature on the domain redirecting to 3-rd party providers next to ingredients on this [page for example](https://www.allrecipes.com/recipe/272546/enchilada-baked-chicken-thighs/):
=> A:`allrecipes.com`

easylist/easylist_general_block.txt
Sample page:
https://www.manuals.co.uk/
Others:
`bedienungsanleitu.ng|bruksanvisni.ng|bruksanvisningpdf.no|handleidi.ng|hasznalati-utasitasok.hu|huang-dan.vn|instrukcjaobslugipdf.pl|juhend.ee|kayttooh.je|kullanimkilavuzu.com.tr|manua.ls|manual.ar|manual.bo|manual.com.ve|manual.cr|manual.do|manual.ec|manual.gt|manual.hn|manual.md|manual.nz|manual.pa|manual.pe|manual.sv|manualdeinstructiuni.ro|manualeduso.it|manuales.com.co|manuales.mx|manualpdf.cl|manualpdf.co.il|manualpdf.com.br|manualpdf.es|manualpdf.ge|manualpdf.in|manualpdf.pt|manuals.ca|manuals.co.uk|manualspdf.ru|manualypdf.cz|modesdemploi.fr|pdfmanualer.dk|petunjuk.co.id|prirocnikpdf.si|prirucky.sk|prirucnici.hr|qollanmalar.uz|rokasgramataspdf.lv|udhezimet.al|uputstvo.rs|usermanuals.au|vadovaspdf.lt|xn----2lbcmca4cdtsdb1c.gr|xn--80aw …
=> A: manuals.co.uk (generic block)

easyprivacy/easyprivacy_general.txt
Adds `_vercel/insights/*` route to general easyprivacy list
Description of their analytics service can be found here: https://vercel.com/docs/concepts/analytics
On quickstart page they specifically list proposed route https://vercel.com/docs/concepts/analytics/quickstart
You can check if it works on following websites:
- https://agentgpt.reworkd.ai/
- https://nodejs.org/en
- https://formik.org/
=> A: _vercel/insights/*

easyprivacy/easyprivacy_trackingservers.txt
The domain `simpleanalyticsexternal.com` is used to load third party analytics script and pixel tracker. At the very least, it tracks host name, user agent, time zone, path name, view port size, screen size, browser language, and page-view events.
=> A: `kvak.io`

fanboy-addon/fanboy_annoyance_specific_hide.txt
Hides scroll to top button.
This pull request fixes https://github.com/easylist/easylist/issues/15889.
=> A: `bl.uk`

easylist/easylist_specific_hide.txt, fanboy-addon/fanboy_annoyance_specific_hide.txt
Hides web ad placeholders, mobile ad placeholders, and scroll to top button. 
This pull request fixes https://github.com/easylist/easylist/issues/15588.
=> A: `kiz10.com`

easylist/easylist_specific_hide.txt
Hides ad banner leftover.
This pull request fixes https://github.com/easylist/easylist/issues/16058.
=> A: `eweek.com`

easylist/easylist_specific_hide.txt
Hides ad box placeholder.
This pull request fixes https://github.com/easylist/easylist/issues/15987.
=> A: `titter.com`

easyprivacy/easyprivacy_thirdparty.txt
Blocks pixel tracker.
This pull request fixes https://github.com/easylist/easylist/issues/16013.
=> A: `d1f0tbk1v3e25u.cloudfront.net`

easyprivacy/easyprivacy_specific.txt, fanboy-addon/fanboy_annoyance_specific_hide.txt, fanboy-addon/fanboy_social_specific_block.txt
Hopefully fixes https://github.com/easylist/easylist/issues/15926.
Wasn't sure about the so called ad scripts, so I left them out.
Fanboy's Social change may not be needed, but thought it would be useful since it entirely prevents the social media buttons from ever showing up, even without cosmetic filtering. (And a possible benefit to a bit less bandwidth being used)
=> Update EasyPrivacy, and Fanboy's Social/Annoyance

easylist/easylist_general_hide.txt, easyprivacy/easyprivacy_specific.txt
Blocks first-party page-view logging and hides ad banner placeholder. 
This pull request fixes https://github.com/easylist/easylist/issues/15942.
=> A: `kkam.com`

easyprivacy/easyprivacy_general.txt
Cloudflare challenge pages used to include an image tag loading a transparent gif. This was used to flag issues with loading the JavaScript required to solve the "I'm a human" challenge.
This hasn't been used for a long time, and has recently been removed by Cloudflare from these pages. Thus, we can clean it up from here too.
**For reviewers:**
Example Cloudflare challenge page that shows a request to the gif is no longer made: https://migueldemoura.com/challenge.
=> Remove obsolete Cloudflare challenge transparent.gif

easylist/easylist_specific_hide.txt
Hides ad banner and ad banner leftover.
An example of the ad banner can be found in `https://hiphopkit.com/music-mp3/digga-d-cherish-god-more/`
This pull request fixes https://github.com/easylist/easylist/issues/15910.
=> A: `hiphopkit.com`

easyprivacy/easyprivacy_specific.txt
Related to this request https://github.com/easylist/easylist/issues/16413
=> Fix a small typo in figma domain name. Related to #16413

easylist/easylist_specific_block.txt
Hi 👋  could you please add this filter to the list. There are a couple of domains in which this image ad is embedded into the play/pause function and redirects the user to 3rd-party domains. For example:
- https://fbox.to/tv/one-piece-mjxqz/1-1
- https://fmovies.wtf/movie/indiana-jones-and-the-dial-of-destiny-ro2jn/1-1
- https://hurawatch.at/movie/meg-2-the-trench-x1kkq/1-1
The blank space is still there, but at least it's not redirecting anymore.
=> A:`fmovies.wtf`

easyprivacy/easyprivacy_specific.txt
Edmentum is an online learning program, they have a clickstream analytics server that isn't blocked in this list.
=> Block Edmentum's Clickstream Server

easyprivacy/easyprivacy_specific.txt
The endpoint `github.dev/diagnostic` is used to receive page analytics. At the very least, it tracks browser, operating system, location, session identifier, and session identifier.
=> A: `github.dev`

easylist/easylist_specific_hide.txt
Hides ad banner.
This pull request fixes https://github.com/easylist/easylist/issues/16159.
=> A: `yidio.com`

fanboy-addon/fanboy_social_international.txt
Share leftovers:
`https://etusuora.com/uutiset/tama-ihmeellinen-yleisurheiluennatys-on-ollut-voimassa-jo-95-vuotta`
I used `> *` because with only `.some` the "Lue myös" header comes very close to the article text and IMO looks stupid.
=> A: https://etusuora.com/

easyprivacy/easyprivacy_thirdparty.txt
The domain `events.elev.io` is used to send page analytics. At the very least, it tracks user ID, page referrer, time zone, and view port size.
=> A: `support.shorthand.com`

easyprivacy/easyprivacy_thirdparty.txt
Blocks tracking script.
This pull request fixes https://github.com/easylist/easylist/issues/16064.
=> A: `nrc.no`

easylist/easylist_specific_hide.txt
Hides ad box placeholder.
This pull request fixes https://github.com/easylist/easylist/issues/16088.
=> A: `weatherboy.com`

easylist/easylist_specific_hide.txt
Hides ad banner and ad banner placeholder.
This pull request fixes https://github.com/easylist/easylist/issues/16141.
=> A: `messitv.net`

easylist/easylist_specific_hide.txt
Hides desktop and mobile ad placeholder.
This pull request fixes https://github.com/easylist/easylist/issues/16140.
=> A: `playstore.pw`

easylist/easylist_specific_hide.txt
On this article `https://www.thingstodovalencia.com/who-is-santiago-calatrava/` on the right side there is a `get your guide` widget, both filters are required because once the id is hidden the class is being displayed:
=> A:`thingstodovalencia.com`

easylist_cookie/easylist_cookie_specific_uBO.txt
I am one of the developers who works on [call-a-pizza.de](https://www.call-a-pizza.de/)
Recently we have heard from customers that the website does not work on the Brave browser, which uses the Easylist by default.
The problem is that the filter list not only removes the cookie message. It removes all popups. This includes information  at startup (like opening hours) and the possibility to add a product to the cart, because there are multiplie choices of extra ingredients.
So, the website is currently completely broken.
We decided to add the id **cookies-fancybox** to our overlay when it's the cookie popup, which is a part of the [easylist_cookie_general_hide.txt](https://github.com/easylist/easylist/blob/29c2d87237cc4a314fe014732aefe85cb38c2f5f/easylist_cookie/easylist_cookie_general_hide …
=> remove call-a-pizza.de from easylist_cookie_specific_uBO.txt

easylist_cookie/easylist_cookie_specific_hide.txt
Hide cookie consent banner and remove obsolete rule (I think it's obsolete).
=> M: https://www.nytimes.com/

fanboy-addon/fanboy_notifications_specific_hide.txt
"To continue translating, create a free account at DeepL."
"Try again later or continue translating now with a DeepL account. Create an account to increase your translation limit and translate texts of up to 5,000 characters."
"Sign up for free" "Sign in"
This PR fix others notifications like that above from deepl (you can't translate if this is only hided)
https://github.com/easylist/easylist/pull/17439
=> M: deepl.com

easylist/easylist_specific_hide.txt, easyprivacy/easyprivacy_specific.txt
Blocks page hit counter and hides ad links.
This pull request fixes https://github.com/easylist/easylist/issues/16197.
=> A: `beforeitsnews.com`

easylist/easylist_specific_hide.txt, fanboy-addon/fanboy_newsletter_specific_hide.txt, fanboy-addon/fanboy_social_specific_hide.txt
This pull request
- hides desktop ad banner leftover, 
- hides mobile ad banner leftover, 
- hides social banner, and 
- hides newsletter form.
This pull request fixes https://github.com/easylist/easylist/issues/16193.
=> A: `openspeedtest.com`

easylist/easylist_allowlist_popup.txt
Hello,
I am an engineer at Snap Inc.
I am requesting that we register our [ads.snapchat.com](https://ads.snapchat.com) website to the popup allow list.  This domain is equivalent to other authenticated ad campaign management websites that are listed in the allow list - e.g. [ads.twitter.com](https://ads.twitter.com/), [ads.google.com](https://ads.google.com/), and [ads.microsoft.com](ads.microsoft.com).
If there is any additional information or context I can provide regarding this request please me know!
Thank you,
Jason
=> Add ads.snapchat.com to popup allow list

easylist/easylist_specific_hide.txt
Hides ad box leftover.
This pull request fixes https://github.com/easylist/easylist/issues/16196.
=> A: `linguisticsociety.org`

easylist/easylist_specific_hide.txt
Fix for this issue https://github.com/easylist/easylist/issues/17503
`namepros.com##.np--shadow` covers most of the banners on the page
`namepros.com##.np-iu34fdg` left over banner in the middle of the page
Thanks
=> M: Fix for #17503

easylist/easylist_general_block.txt
The rule `/adverts.$~script,domain=~adverts.ie|~adverts.org.ua` blocks non-ad requests on two pages, resulting in breakage:
```
https://github.com/duckduckgo/tracker-radar/blob/af63042a7cc32c499b0adf5e2d2958bf641762a0/entities/Adverts.ie.json#L4
https://0xacab.org/dCF/deCloudflare/-/blob/master/subfiles/cloudflared/adverts.md?ref_type=heads
```
In both of these cases, the XmlHTTPRequests loading the content of the file is blocked:
Thus, I have excluded both domains. 0xacab runs GitLab, and I am sure projects including the word "adverts." exist, but I was unable to find a file containing `adverts.` due to GitLab's search being horrible. I have nevertheless excluded it. I can remove it if the lack of an example is problematic.
Thanks
=> P: 0xacab.org

easylist/easylist_specific_hide.txt
Hi, please add this filter to the list to hide this gaming widget on this page for example `https://beyondtheflag.com/2023/10/26/nascar-one-driver-faces-must-win-situation-martinsville/`: 
Thanks
=> A:`beyondtheflag.com`

easyprivacy/easyprivacy_thirdparty.txt
Blocks Typeform analytics endpoint.
Here's an accessible test link: `https://www.themarshallproject.org/2022/09/01/they-lost-their-pregnancies-then-prosecutors-sent-them-to-prison`
=> A: `themarshallproject.org`

fanboy-addon/fanboy_social_specific_hide.txt
Hides social buttons.
This pull request fixes https://github.com/easylist/easylist/issues/16243.
=> A: `livescience.com`

easylist/easylist_adservers.txt
Hides ad banner at bottom of `crypto.news` site.
https://github.com/uBlockOrigin/uAssets/issues/20842
=> A: `cryptoecom.care`

easylist/easylist_specific_hide.txt, easylist_cookie/easylist_cookie_specific_uBO.txt
Hides ad banners and cookie notice.
This pull request fixes https://github.com/easylist/easylist/issues/16403.
=> A: `serverstoplist.com`

easylist/easylist_specific_hide_abp.txt
Hides ad banner leftover.
This pull request fixes https://github.com/easylist/easylist/issues/14876.
=> A: `neonheightsservers.com`

easylist/easylist_allowlist.txt
Makes videos playable on `eurogamer.net`, `vg247.com`, and `xxlmag.com`.
```
xxlmag.com/xxl-cypher-lab/
vg247.com/the-best-games-ever-show-episode-80
eurogamer.net/digitalfoundry-2023-after-25-years-daytona-usa-2-is-finally-available-to-play-at-home-and-its-brilliant
```
=> P: videos on `eurogamer.net`, `vg247.com`; A: `xxlmag.com`

easylist/easylist_allowlist_general_hide.txt
Images in `muzines.co.uk/ads` search results do not display properly such as in `muzines.co.uk/ad/9120`.
This PR makes the images display.
=> A: `muzines.co.uk`

easyprivacy/easyprivacy_specific.txt
See #17477, #17651, #17818 for background info.
`kemono.su` and `coomer.su` both use first party analytics. It seems the admins of the site change the url they report back to from time to time in a deliberate attempt to circumvent adblockers.
=> [NSFW] Update url for kemono.su and coomer.su first-party analytics

easyprivacy/easyprivacy_specific.txt
See #17477, #17651, #17818, and #17946 for info.
URL for first party tracking on both sites has once again changed.
=> [NSFW] First-party kemono.su and coomer.su

easylist_cookie/easylist_cookie_specific_block.txt
Videos won't work because of blocked GDPR dialog.
https://www.unilad.com/celebrity/news/big-bang-theory-kate-micucci-cancer-free-950283-20231218
I'll handle the dialog in uAssets.
=> P: unilad.com

easylist/easylist_adservers.txt
EasyList now contains this URL widget.packeta.com, but it match to **legit** script (https://widget.packeta.com/v6/www/js/library.js) and this will make it impossible for anyone to load Packeta branches and make order. So, Packeta branches are totally broken now for everyone, who is loading this script and trying to make order on e-shop, what is connected to Packeta.
[Packeta ](https://www.packeta.com/global) is big global genuine company.
**It should we merged ASAP.**
Thousands customers are using this...
Related commit:
https://github.com/easylist/easylist/commit/adf202c4c4e170373134addc97c4940164c86146
=> URGENT - Allow https://widget.packeta.com/v6/www/js/library.js - it's legit

easylist/easylist_specific_hide.txt
Hi could you please add this filter to the list there are some 3-rd party advertisements banners on the right side of the page on both pages(might need to refresh a couple of times for them to appear) : 
Best regards,
=> A:`boatsonline.com.au,yachthub.com`

fanboy-addon/fanboy_newsletter_general_block.txt
Properly block the newsletter dialog.
Another option:
Change:
`/modals/newsletter?` -> `/modals/newsletter`
=> A: / P: mulletoi.com

easylist/easylist_specific_hide.txt
Hi, can you please review and add the filter to the list if you check this[ page](https://datareportal.com/reports/digital-2022-social-commerce-takes-off?rq=ads)  there is a sticky ads container at the bottom:
Thank you
=> A:`datareportal.com`

easylist/easylist_allowlist_popup.txt
**Adding Exception for Finder Domains**
This pull request proposes an update to the existing `doubleclick.net` filter exception rule to include [Finder](finder.com.au) domains `finder.com.au`, `finder.com` and `creditcard.com.au`.
This change addresses the issue where ad blockers were inadvertently closing user-intentionally opened tabs due to redirects involving `ad.doubleclick.net`.
The issue has been first detected while using uBlock Origin and discussed also here: https://github.com/uBlockOrigin/uAssets/issues/21939
=> A: exception for doubleclick redirects from finder.com.au and finder.com

easylist_cookie/easylist_cookie_specific_hide.txt
Fixes https://github.com/easylist/easylist/issues/18389.
This changes the cookie snackbar filter to match the filter used for cs.android.com, which is a website which is using the same software and where the filter is working correctly.
=> P: https://source.chromium.org

fanboy-addon/fanboy_newsletter_specific_hide.txt
in article newsletter
`https://themarkup.org/machine-learning/2024/01/10/plagiarism-detection-tools-offer-a-false-sense-of-accuracy`
=> A: https://themarkup.org/

easyprivacy/easyprivacy_specific.txt
Looks like `/api/analytics` is a proxy for the Amplitude API as it appears to take a payload matching that which is used by Amplitude analytics + also mentions amplitude by name:
=> Block navan.com Amplitude proxy

easylist/easylist_allowlist_popup.txt
This change adds `whatphone.com.au` to the doubleclick popup exception to cover the same [issue](https://github.com/easylist/easylist/issues/18277) that was previously happening on `finder.com.au` pages fixed by this PR: https://github.com/easylist/easylist/pull/18276
>This change addresses the issue where ad blockers were inadvertently closing user-intentionally opened tabs due to redirects involving ad.doubleclick.net.
Could you please add `whatphone.com.au` domain too 🙏
cc: @monzta
=> A: whatphone.com.au

easylist/easylist_specific_hide.txt
Hides ad banner.
This pull request fixes https://github.com/easylist/easylist/issues/14881.
=> A: `carbuyer.co.uk`

easylist/easylist_specific_block.txt
Banners at https://www.thespike.gg/
Different VPN regions, ex:
`https://www.thespike.gg/images/bc-game/br/300x600.gif `
`https://www.thespike.gg/images/bc-game/de/300x600.gif`
=> A: https://www.thespike.gg/

easylist_cookie/easylist_cookie_specific_hide.txt
This `#alert` box is used for documentation of assembly instructions. I don't get any cookie notice when opening the website, but I'm not in the EU.
https://github.com/compiler-explorer/compiler-explorer/issues/3174
=> Don't hide alert box on godbolt.org

easyprivacy/easyprivacy_thirdparty_international.txt
The domain `tracker.oval.id` is used to track page analytics. At the very least, it tracks user id, event id, user agent, time zone, time stamp, user action, and input count.
=> A: `kompas.com`

easylist/easylist_specific_hide.txt
Hides ad square leftover.
This pull request fixes https://github.com/easylist/easylist/issues/15014.
=> A: `wordcounter.icu`

easylist/easylist_specific_hide.txt
Hides ad square.
This pull request fixes https://github.com/easylist/easylist/issues/15025.
=> A: `getfreecourses.co.websiteoutlook.com`

easyprivacy/easyprivacy_thirdparty.txt
PostHog will be adding some new capture endpoints to replace the existing `app.posthog.com` ones that are blocked
We don't want this change to impact adblock users so we want to preemptively add the new domain (anything under `*.i.posthog.com` should be blocked)
=> A: i.posthog.com

easylist/easylist_specific_hide.txt
Hides ad banner leftovers.
This pull request fixes https://github.com/easylist/easylist/issues/15026.
=> A: `crossian.net.seowebstat.com`

easyprivacy/easyprivacy_thirdparty_international.txt
Blocks third-party page view analytics.
This pull request fixes https://github.com/easylist/easylist/issues/15214.
=> A: `game.granbluefantasy.jp` (JP IP)

easyprivacy/easyprivacy_specific.txt
The domain `events-ingestion.services.gorgias.com` is used to receive page-view analytics. At the very least, the domain logs user agent, page url, curent article, and page referrer. A test link can be accessed via `https://coldplayeu.gorgias.help/en-US/mens-size-guide-430709`
=> A: `coldplayeu.gorgias.help`

easyprivacy/easyprivacy_general.txt, easyprivacy/easyprivacy_specific.txt
The endpoint `/log/client/messages` is used to receive error logs. At the very least, the endpoint logs user agent, view port size, adblocker status, and error stack trace. To view the connection, one must wait about a minute after the page has fully loaded.
=> A: `kayak.co.id`

easyprivacy/easyprivacy_specific.txt
The endpoint `/tokei/do/ev` is used to receive page-view analytics. At the very least, the endpoint logs page-view events, page referrer, and page href.
=> A: `upstract.com`

easyprivacy/easyprivacy_thirdparty.txt
Blocks location getter.
This pull request fixes https://github.com/easylist/easylist/issues/15384.
=> A: `pocketovens.com`

easyprivacy/easyprivacy_specific.txt
https://backend.academy.cs.cmu.edu/api/v0/track/ is used to receive analytics.
=> A: `academy.cs.cmu.edu/ide`

easyprivacy/easyprivacy_allowlist_international.txt
*Maybe we should just remove the whole filter*
Images not being rendered at:
https://www.fitbook.de/suche#gsc.q=sleep
https://www.computerbild.de/artikel/cb-News-eKitchen-Computer-Bild-25654273.html
German VPN.
=> A: [breakage] https://www.fitbook.de/

easylist/easylist_specific_hide.txt
Hides ad placeholders at https://torontolife.com/real-estate/condo-of-the-week-knitting-mill-lofts/
=> A: `torontolife.com`

easyprivacy/easyprivacy_allowlist.txt
This fixes an issue on ocado.com where when editing an order, the info ("i") button on each product does nothing.
=> easyprivacy_allowlist.txt: unbreak ocado.com for browser.sentry-cdn.com

easylist/easylist_specific_hide.txt
Hides desktop and mobile ad banner placeholders.
This pull request fixes https://github.com/easylist/easylist/issues/14996.
=> A: `timesnownews.com` & `zoomtventertainment.com`

fanboy-addon/fanboy_social_specific_hide.txt
Hides social icons.
This pull request fixes https://github.com/easylist/easylist/issues/15407.
=> A: `bylancer.com`

easylist/easylist_allowlist_popup.txt
This change adds `findershopping.com.au`, `debitcards.com.au` to the doubleclick popup exception to cover the same [issue](https://github.com/easylist/easylist/issues/18277) that was previously happening on `finder.com.au` pages fixed by these 2 PRs: https://github.com/easylist/easylist/pull/18276, https://github.com/easylist/easylist/pull/18516
>This change addresses the issue where ad blockers were inadvertently closing user-intentionally opened tabs due to redirects involving ad.doubleclick.net.
Could you please add our new domains `findershopping.com.au` and `debitcards.com.au` too 🙏
cc: @monzta
=> A: findershopping.com.au

easyprivacy/easyprivacy_specific.txt
URL has changed from backend.academy.cs.cmu.edu/api/v0/track to backend.academy.cs.cmu.edu/api/v0/event/
=> M: `academy.cs.cmu.edu/ide`

easyprivacy/easyprivacy_specific.txt
Blocks analytics endpoints.
This pull request fixes https://github.com/easylist/easylist/issues/15503.
=> A: `miro.com`

easyprivacy/easyprivacy_specific.txt
Unblocks Talktrack functionality.
This pull request fixes https://github.com/easylist/easylist/issues/18917.
=> P: `miro.com`

easylist/easylist_general_block.txt, easylist/easylist_specific_block.txt
Needed to block SERP ads on search.brave.com. Without this rule, `https://search.brave.com/api/ads/metric/rendered?` network requests still happen on search.brave.com.
Test case:
https://search.brave.com/search?q=vpn&source=web
Check DevTools for request to search.brave.com/api/ads/metric/rendered
=> Add rule to block ad-related requests on search.brave.com

easyprivacy/easyprivacy_specific_international.txt
Blocks location getter.
This pull request fixes https://github.com/easylist/easylist/issues/15507.
=> A: `delfi.lt`

easylist_cookie/easylist_cookie_specific_hide.txt, easyprivacy/easyprivacy_specific.txt
Blocks location getter and hides cookie notice.
This pull request fixes https://github.com/easylist/easylist/issues/15498.
=> A: `oppo.com`

easyprivacy/easyprivacy_specific_international.txt
The domain `event-tracking.hellohealthgroup.com` is used to receive page-view analytics. At the very least, it logs user agent, page url, user id, and page access time.
=> A: `hellodoktor.com`

fanboy-addon/fanboy_annoyance_specific_hide.txt, fanboy-addon/fanboy_social_specific_hide.txt
Hides social buttons and back to top button.
This pull request fixes https://github.com/easylist/easylist/issues/15567.
=> A: `bikerumor.com`

easylist_cookie/easylist_cookie_international_specific_hide.txt
Hides cookie pop up leftover.
This pull request fixes https://github.com/easylist/easylist/issues/15519.
=> A: `jolstad.no`

easyprivacy/easyprivacy_trackingservers_thirdparty.txt
Narrows the rule for birdeatsbug.com to just the SDK embedded as 3rd party code into other websites.
Resolves overblocking where ad blockers using the `easyprivacy` list would experience broken flows when using the official Bird Eats Bug browser extension https://chrome.google.com/webstore/detail/bird-eats-bug-effortless/mdplmiioglkpgkdblijgilgebpppgblm, e.g. when the extension was trying to authenticate the user by making API calls to accounts.birdeatsbug.com.
I'm still [making the argument](https://github.com/easylist/easylist/pull/18781) that the domain should be entirely removed, but removing a rule that breaks first party usage hopefully is in everybody's shared interest.
=> Resolve overblocking for birdeatsbug.com

fanboy-addon/fanboy_social_specific_hide.txt
Hides social icons.
This pull request fixes https://github.com/easylist/easylist/issues/15591.
=> A: `geekflare.com`

easylist/easylist_specific_hide.txt
The box--bg-grey-20 is used to show the element's background color as grey. Other general elements other than advertisements will not be displayed on the web page.
https://www.chosun.com/national/welfare-medical/2024/04/24/RHXAEOKNL5EPVGT36BMFB46YGE/
=> M: chosun.com

easylist/easylist_adservers.txt
the domain is not an advertising site it's using for sportsbook solution. Blocking domain affects loading all the sportsbook
=> sptpub.com

easyprivacy/easyprivacy_trackingservers_general.txt
Example:
`https://drako.cafirebreather.com/i/0009cd7673176c779954540ce369af68.js` being loaded on `https://www.marian.edu/`
Similar concerns as #19133, #19134 and #19135, appears to be the same/similar script
=> A: https://*.cafirebreather.com/

easyprivacy/easyprivacy_trackingservers_general.txt
Similar concerns as #19133
For example, on `https://pendo.io`, `https://spider.australiarevival.com/i/56155956522daf11926d9b0916f97ba2.js` gets loaded which appears to bundle a old version of fingerprintjs. For example:
```js
ae = function() {
if (n.ucf && o.R(n.ucf)) {
var t = +new Date
, r = f.createElement("canvas");
r.height = 60,
r.width = 400;
var e = r.getContext("2d");
return r.style.display = "inline",
e.textBaseline = "alphabetic",
e.fillStyle = "#f60",
e.fillRect(125, 1, 62, 20),
e.fillStyle = "#069",
e.font = "11pt n0-r3al-f0nt-123",
e.fillText("Cwm fjordbank glyphs vext quiz, 😃", 2, 15),
e.fillStyle = "rgba(102, 204, 0, 0.7)",
e.font = "18pt Arial",
e.fillText("Cwm fjordbank glyphs vext quiz, 😃", 4, 45),
[new Date - t, o.Z(r.toDataURL())].join()
}
}
```
Performs canvas …
=> A: https://*.australiarevival.com/

easyprivacy/easyprivacy_trackingservers_general.txt
Rationale: Domain loads fingerprinting scripts per #19133
Fixes: #19133
Found using analysis performed on [VisibleV8](https://github.com/wspr-ncsu/visiblev8) logs :)
=> A: https://*.powerrobotflower.com/

fanboy-addon/fanboy_social_specific_hide.txt
Hides social icons.
This pull request fixes https://github.com/easylist/easylist/issues/15977.
=> A: `commentpicker.com`

easylist/easylist_specific_hide.txt
This pull request fixes https://github.com/easylist/easylist/issues/15956.
=> A: `mathgames.com`

easylist/easylist_specific_hide.txt
ads appearing on [thesun.co.uk ](https://www.thesun.co.uk/)
on homepage: top banner & banners within body
[https://www.thesun.co.uk/money/28061924/rejected-dragons-den-business-owner-entrepreneur-matcha-tea/](https://www.thesun.co.uk/money/28061924/rejected-dragons-den-business-owner-entrepreneur-matcha-tea/)
on article page: sidebar & bottom of page tiles
tested on Chrome & Firefox with AdBlock 6.2.0 & Adblock Plus 4.0
=> M: thesun.co.uk

easyprivacy/easyprivacy_trackingservers_general.txt
Example: `https://rocky.lordofthesuperfrogs.com/i/0c928789f9e0fe002203675ad3b9fdd2.js` in https://press.princeton.edu/books
Similar concerns as #19133, #19134 and #19135, #19136 appears to be the same/similar script.
=> A: https://lordofthesuperfrogs.com/

easyprivacy/easyprivacy_specific.txt
Blocks Plausible page-view analytics endpoint.
=> A: `streamed.su`

easylist/easylist_specific_hide.txt
ads appear above legitimate emails in aol inbox
Tested using Adblock & Adblock Plus
Using Easylist & ABP Filters
=> M: mail.aol.com

easyprivacy/easyprivacy_specific.txt
=> A: `developers.miro.com`

easyprivacy/easyprivacy_specific.txt
=> A: `support.github.com`

easylist_cookie/easylist_cookie_international_specific_hide.txt
This website no longer uses the `cerez` class.
=> M: No longer needed

easylist/easylist_adservers.txt
https://www.vdo.ai/ serves videos ads
Seems to be used widely: https://publicwww.com/websites/%22vdo.ai%2Fcore%22/
Examples: 
- empty ad container on https://www.java67.com/2022/02/top-5-microservice-courses-for-java.html
- video ad in body of https://education-load.com/
- empty ad container on https://classnotes.org.in/class-8/english-8/
- video ad on https://samajaepaper.in/epaper/1/73/2024-06-13/1
=> M: java67.com

easyprivacy/easyprivacy_general.txt
those links are sent over email so when open in the browser have no initiator
=> Allow UPS delivery tracking when open directly

fanboy-addon/fanboy_social_specific_hide.txt
Hides social icon.
This pull request fixes https://github.com/easylist/easylist/issues/16073.
=> A: `nist.gov`

easylist/easylist_specific_hide.txt
Wolt.com have some sponsored restaurants that should be hide.
=> A: wolt.com

easylist/easylist_specific_hide.txt
**found in url**: https://www.indiatimes.com/health/why-walking-backwards-better-than-jog-637210.html
=> A:indiatimes.com

easyprivacy/easyprivacy_specific.txt
Blocks page-view analytics.
The endpoints submitted logs event type and current page url.
=> A: `toms.com`

fanboy-addon/fanboy_social_international.txt
Hides social container.
This pull request fixes https://github.com/easylist/easylist/issues/17515.
=> A: `fellahe.com`

easylist/easylist_specific_hide.txt
See https://github.com/uBlockOrigin/uAssets/commit/dd171dd2c141eff384784062960396ad4961aef4 for more details. Some domains are formatted differently and not caught by the current filters.
=> Add missing modrinth ad detections to easylist_specific_hide.txt

easyprivacy/easyprivacy_specific.txt
Blocks analytics endpoint.
This pull request fixes https://github.com/easylist/easylist/issues/17520.
=> A: `poki.com`

easylist_cookie/easylist_cookie_general_hide.txt
This pull request fixes https://github.com/easylist/easylist/issues/17546.
=> A: `gazetememur.com`

easylist/easylist_specific_hide.txt
A test page can be accessed via `https://genius.com/Kendrick-lamar-not-like-us-lyrics`.
=> A: `genius.com` (mobile UA)

easyprivacy/easyprivacy_specific_international.txt
Blocks event logging.
The blocked endpoints at the very least logs client id, user platform, user action, and page referrer.
=> A: `bukalapak.com`

easyprivacy/easyprivacy_trackingservers_general.txt
Blocks CHEQ analytics endpoint.
This pull request fixes https://github.com/easylist/easylist/issues/17553.
=> A: `mongodb.com`

easylist/easylist_general_hide.txt
Example: https://frequentmiler.com/stop-putting-spend-on-your-delta-card/
body element of page is given 'adhesion' classname after scrolling, which results in a blank page.
=> A: frequentmiler.com

easyprivacy/easyprivacy_specific_international.txt
Blocks client error logging and pixel tracker.
<details>
<summary>Steps to reproduce:</summary>
Using .id IP should not be necessary, but try using one if needed.
1. Disable `uBlock filters – Ads` if checked.
2. Open `tokopedia.com` using mobile UA.
3. Using the search bar on the top, search for the keyword "ringke".
4. After the search completed, both connection should appear.
</details>
=> A: `tokopedia.com` (mobile UA)

easyprivacy/easyprivacy_specific.txt
Blocks first-party page-view logging.
This pull request fixes https://github.com/easylist/easylist/issues/17576.
=> A: `abillion.com`

easylist_cookie/easylist_cookie_international_specific_hide.txt
This pull request fixes https://github.com/easylist/easylist/issues/17580.
=> A: `frogmobile.gr`

easyprivacy/easyprivacy_specific.txt
Blocks Snowplow analytics endpoint.
=> A: `quillbot.com`

easylist/easylist_specific_hide.txt
Hides ad banner leftovers.
This pull request fixes https://github.com/easylist/easylist/issues/17623.
=> A: `animetrilogy.com`

easyprivacy/easyprivacy_specific.txt
Blocks Plausible analytics endpoint.
=> A: `lucida.to`

easyprivacy/easyprivacy_thirdparty_international.txt
Blocks third-party event tracking.
=> A: `cnbcindonesia.com`

fanboy-addon/fanboy_chatapps_third-party.txt
Blocks third-party chatbot.
This pull request fixes https://github.com/easylist/easylist/issues/17656.
=> A: `havas.net`

fanboy-addon/fanboy_newsletter_specific_hide.txt
Hides newsletter form.
This pull request fixes https://github.com/easylist/easylist/issues/17637.
=> A: `thomasnet.com`

easylist_cookie/easylist_cookie_specific_hide.txt, fanboy-addon/fanboy_newsletter_specific_hide.txt, fanboy-addon/fanboy_newsletter_specific_uBO.txt
Hides newsletter popup, newsletter banner, and cookie banner.
This pull request fixes https://github.com/easylist/easylist/issues/17705.
=> A: `monarchmoney.com`

fanboy-addon/fanboy_annoyance_specific_hide.txt
Hides scroll-to-top button.
This pull request fixes https://github.com/easylist/easylist/issues/17695.
=> A: `skial.com`

easylist/easylist_specific_block.txt
`https://www.worldhistory.org/js/ay-ad-loader.js` is a unblocked ad script
=> address worldhistory.org ad script

easyprivacy/easyprivacy_specific.txt
`https://www.autotrader.com/cars-for-sale/electric/cars-between-17000-and-26000/alpharetta-ga`
=> address autotrader.com tracking ping

easyprivacy/easyprivacy_general.txt
tracking used on multiply porn sites like `jzzo.com` & `xxxvogue.net`
=> address tracking on NSFW sites

easyprivacy/easyprivacy_specific.txt
Blocks pixel trackers.
A test page can be accessed via `https://gamemonetize.com/real-flight-simulator-game`.
=> A: `gamemonetize.com`

easyprivacy/easyprivacy_specific.txt
Tracking such as on `https://imgupscaler.media.io/` and `https://vidbgrem.media.io/`
=> A: `media.io`

easyprivacy/easyprivacy_specific.txt, easyprivacy/easyprivacy_thirdparty_international.txt
Tracking and third-party event logging
Visiting `cartx.cloud` redirects to `cartsee.com`, a Chinese website
=> A: `unibling.com`

easyprivacy/easyprivacy_specific.txt
=> A: `id.investing.com`

easyprivacy/easyprivacy_trackingservers_thirdparty.txt
Proxy domain for LogRocket on the page `https://app.alignerr.com/signin?`
The domain is also mentioned on `https://docs.logrocket.com/docs/proxying-traffic-through-your-own-domain`
=> A: `alignerr.com`

easyprivacy/easyprivacy_specific.txt, easyprivacy/easyprivacy_thirdparty.txt
Event logging on the page `https://www.deel.com/hire-employees/`
Scroll down the page to the `Experience the seamless process of hiring globally` section for the third-party event logging.
Can't use `||capture.navattic.com^` because it breaks the demo.
=> A: `deel.com`

easyprivacy/easyprivacy_specific_international.txt
=> A: `cilipadi.mygostore.com`

easylist_cookie/easylist_cookie_specific_hide.txt
This pull request fixes https://github.com/easylist/easylist/issues/17817.
=> A: `orico.cc`

easyprivacy/easyprivacy_thirdparty.txt, fanboy-addon/fanboy_notifications_specific_hide.txt
Blocks tracker loaders and hides promotion notification.
This pull request fixes https://github.com/easylist/easylist/issues/17805.
=> A: `northlandfence.com`

easyprivacy/easyprivacy_specific.txt, easyprivacy/easyprivacy_specific_perimeterx.txt
Blocks PerimeterX script initialiser and event logging endpoint.
A test page can be accessed via `https://cookpad.com/us/search/mac%20n%20cheese`.
=> A: `cookpad.com`

easyprivacy/easyprivacy_specific.txt
Midjourney Event/Analytics service. The `proxima` subdomain is likely a proxy for [Amplitude Analytics](https://amplitude.com/). Attaching screenshot below of an excerpt of a request my browser sent.
I also confirmed that the filter explicitly blocks analytics without altering the functionality of the site.
=> A: https://proxima.midjourney.com/

easylist/easylist_specific_hide.txt
Hides desktop and mobile ad placeholders.
This pull request fixes https://github.com/easylist/easylist/issues/18081.
=> A: `wordreference.com`

fanboy-addon/fanboy_annoyance_thirdparty.txt
37signals.com is a company responsible for Basecamp and Ruby on Rails. Given a lack of a reason for its inclusion via `git blame` I recommend removing it.
=> Remove 37signals.com from Fanboy 3rd Party List

easyprivacy/easyprivacy_thirdparty.txt
This makes it such that the script is available for loading when on a first party site such as https://crypto.sardine.ai/buy where the page breaks if this script doesn't load.
In this case, it's 1P fingerprinting occuring, but in all other contexts this script gets loaded as a 3P tracker and should be blocked.
Fixes https://github.com/easylist/easylist/issues/19401 and follows on from https://github.com/easylist/easylist/commit/ff59ff5f0b6009bfd0881669fa9268ed044388d5 which was meant to fix it, but introduced a webcompat issue on https://crypto.sardine.ai/buy
=> Isolates sardine.ai tracking script to 3P only

easyprivacy/easyprivacy_trackingservers_general.txt
Another domain of segmentify.com
```
https://br.puma.com/
https://sa.puma.com/en/
https://ae.puma.com/
https://cl.puma.com/
https://tr.puma.com/
https://mx.puma.com/
```
=> A: https://br.puma.com/

easyprivacy/easyprivacy_trackingservers_thirdparty.txt
It is a tracker and the owner openly mocks people complaining about his non-compliance.
=> A: https://datafa.st/

easylist/easylist_specific_hide.txt
Reverts part of [db9929e](https://github.com/easylist/easylist/commit/db9929e8ded5dd81d5cec28ff57926c54c841523).
Closes  #20637
=> Fix false-positive on cults3d.com

fanboy-addon/fanboy_annoyance_specific_hide.txt
Hides scroll-to-top and scroll-to-bottom buttons.
This pull request fixes https://github.com/easylist/easylist/issues/18189.
=> A: `webmasterworld.com`

fanboy-addon/fanboy_annoyance_specific_hide.txt
Hides scroll-to-top button.
This pull request fixes https://github.com/easylist/easylist/issues/18142.
=> A: `health.harvard.edu`

easyprivacy/easyprivacy_trackingservers_thirdparty.txt
`pikapod.net` host `umami.is` tracking script.
examples: 
```
https://groovy-manul.pikapod.net/script.js
https://celadon-seriema.pikapod.net/script.js
https://darandil.pikapod.net/script.js
https://df-analytics.pikapod.net/script.js
https://energetic-swan.pikapod.net/script.js
https://jstats.pikapod.net/script.js
https://nebulous-lyrebird.pikapod.net/script.js
https://none-analytics.pikapod.net/script.js
https://platinum-ibis.pikapod.net/script.js
https://qodeer-analytics.pikapod.net/script.js
https://sondercare-umami.pikapod.net/script.js
https://splendid-stingray.pikapod.net/script.js
```
=> A: (umami.is) pikapod.net

easyprivacy/easyprivacy_allowlist_international.txt
=> A: 11freunde.de

easylist/easylist_specific_hide.txt
Site to test: https://www.wionews.com/world/trumps-deportation-flights-costing-852000-for-every-80-migrants-report-8656141
=> A: Hide ad containers on wionews.com

easylist/easylist_specific_hide.txt
Banner ads are appearing in Yahoo inbox - only in emails from specific companies (i.e. Amazon, TurboTax)
=> A: mail.yahoo.com

easylist/easylist_specific_hide.txt
`economictimes.com` is already defined for `##.ads` 
`yourdictionary.com` is already defined for `##.ui-advertisement`
=> removed redundant subdomains

fanboy-addon/fanboy_notifications_specific_block.txt
`/push-sw.js` already exists as a general blocking rule in `fanboy_notifications_general_block.txt`
=> removed redundant filter

easylist/easylist_specific_hide.txt
https://www.ft.com/: make rule more specific for AdGuard apps (not browser extension)
=> P: https://www.ft.com/

easyprivacy/easyprivacy_trackingservers_thirdparty.txt
Was added in 12032dcc9501b382e0464a2e3496bd4328eced08
Reason:
This breaks Azure Data Explorer - A tool by Microsoft to look at telemetry. The URL is present in the learning material by Microsoft.
https://learn.microsoft.com/en-us/azure/data-explorer/query-monitor-data#add-a-log-analytics-workspaceapplication-insights-resource-to-azure-data-explorer-client-tools
Issue: #21268
=> Remove applicationinsights.io

easyprivacy/easyprivacy_general.txt
Just blocking /orichipixel.min.js seems to be enough.
`https://zaikashop.com/`
</details>
---
`https://www.whatgeek.com/`
</details>
=> A: https://zaikashop.com/

easyprivacy/easyprivacy_thirdparty_international.txt
`analytics.skroutz.gr` was not added to the filter because it caused breakage
https://github.com/easylist/easylist/commit/a700c43010c10514e0f7d887542174eeac4ed919
https://github.com/uBlockOrigin/uAssets/issues/15697
=> https://fit1.gr/

easylist_cookie/easylist_cookie_international_specific_hide.txt
Note that campax.org is multilingual (FR and IT besides DE). Also, there's another rule for a hebrew site with the same selector:
https://github.com/easylist/easylist/blob/f434e9fafed029d0391496ec805d93c761c48a60/easylist_cookie/easylist_cookie_international_specific_hide.txt#L1515
So, these rules could be merged and moved to [`easylist_cookie/easylist_cookie_specific_hide.txt`](https://github.com/easylist/easylist/blob/master/easylist_cookie/easylist_cookie_specific_hide.txt), I guess. Let me know if I should file a PR.
=> A: https://act.campax.org

easylist/easylist_specific_hide.txt
Remove sponsored ads.
Example: `https://thenewstack.io/inside-javas-language-renaissance/`
Before:
<details>
</details>
After:
<details> 
</details>
=> A: https://thenewstack.io/

easylist/easylist_specific_hide.txt
Hi, your latest additions motivated by this issue https://github.com/uBlockOrigin/uAssets/issues/29046 break `sofascore.com` site features. That is because you target classes which are used for content styling.
Because of this, we at Sofascore have decided to add a class which will transparently target all ads content on the site, but won't break any of the features.
Comparison between your targeting and what I commit can be seen on the screen recording.
You can see that by using the old targets the user can't see player statistics for the match (targeted by `z_fixed` class) and can't change seasons on competition page (also targeted by `z_fixed` class). Using this new class will target only ad content and won't break any of the features. …
=> M: https://www.sofascore.com

fanboy-addon/fanboy_social_specific_hide.txt
The old rule was hiding relevant scene properties such as the release date and duration, this will just hide the annoying "Share" button
=> Fix overly strict rule for social share buttons

easylist/easylist_specific_hide.txt
`https://partners.titantv.com/default.aspx`
blank ad container is visible when user clicks on one of the programs
=> M: titantv.com

easylist/easylist_allowlist_general_hide.txt
Entire top section is hidden by the following EasyList filter: ##.full-ad Although website serves a wall/paywall this part of the website content is mistakenly hidden by EasyList.
Debugging steps:
When EasyList filter is enabled the website content starts from Big Stories section instead.
When EasyList is disabled the website content starts from Trending / Opinion / Featured sections (expected behavior).
=> A: [Breakage] rawstory.com

easyprivacy/easyprivacy_general.txt
This code is the client-side script of an analytics tool called Hardal.
The code collects various information such as the user's screen resolution, browser language, device type, browser type and version, URL, page title, and more.
`https://www.havelsan.com`
</details>
`https://www.aldoshoes.com.tr`
`https://www.englishhome.com`
`https://www.dynavit.com.tr`
---
`https://www.enplus.com.tr`
</details>
`https://www.markaplus.com`
`https://www.recete.com`
`https://kolayik.com`
`https://www.hofsilk.com`
`https://www.ifocus.sk`
---
`https://www.workinton.com`
</details>
---
reference:
https://usehardal.com/customers
=> A: `Hardal` server-side measurement platform

easylist/easylist_allowlist_general_hide.txt
on `https://www.wfmz.com/news/#tncms-source=Top-Navigation-News` the "make account/sign up" CTAs in the side bar are not visible
=> P: wfmz.com

easylist/easylist_specific_hide.txt
`gamesradar.com,livescience.com,pcgamer.com,space.com,techradar.com,tomsguide.com,tomshardware.com` all these websites are from the same owner and have the same ad-placeholders, so the same ##.sponsored-card rule works for all of them.
`fitandwell.com,homesandgardens.com,idealhome.co.uk,marieclaire.com` also seem to have the same owner and the rule ##.sponsored-post--placeholder works for all of them.
Example sites, 
`https://www.space.com/space-exploration/launches-spacecraft/spacex-starlink-launch-group-17-10-vandenberg-space-force-base` 
`https://www.tomsguide.com/ai/i-used-googles-nano-banana-to-transform-my-kids-artwork-here-are-the-5-prompts-that-worked-best`
`https://www.marieclaire.com/fashion/celebrity-style/lily-collins-calvin-klein-new-york-fashion-week-front-row/` …
=> Remove ad-placeholders from multiple websites

easylist/easylist_specific_block.txt
on `https://www.cnn.com/2025/10/01/politics/video/hakeem-jeffries-ai-video-trump-government-shutdown-ldn-digvid`, there are pre-roll ads before the video news content begins
=> M: cnn.com
