easylist/easylist

- easylist_cookie/easylist_cookie_general_hide.txt
Remade this older pull req:
https://github.com/easylist/easylist/pull/3271
> A: cookie general hide, publiceye.ch

- easyprivacy/easyprivacy_trackingservers.txt
* `https://www.fembed.com/v/5jo4zq24x90`
* **nsfw** `embed . media/v/8xvpekj5qo7`
> A: https://embed.media/

- easyprivacy/easyprivacy_specific_international.txt
> A: https://www.nextinpact.com/

- easylist_cookie/easylist_cookie_general_hide.txt
General cookie notification hiding rule.
> A: webtoons.com

- easylist/easylist_adservers.txt
https://github.com/abp-filters/abp-filters-anti-cv/issues/346
> A: https://vidfast.co/embed-72mmuhxinz1q.html

- easylist/easylist_thirdparty_popup.txt
`https://easyplayer.cc/pl.php?fc=71f25c6513f4cd7aa9a14d42f0ef9ad3`
> A: https://www.core1player.com/v/35qjycmj288m3pq

- easylist/easylist_general_block.txt
https://github.com/abp-filters/abp-filters-anti-cv/issues/348
> A: https://exe.io/dYSQc

- fanboy-addon/fanboy_annoyance_whitelist.txt
https://forums.lanik.us/viewtopic.php?f=64&t=42607
> P: https://arsenal.army/shop/individualnaya-zashchita

- easylist_cookie/easylist_cookie_international_specific_hide.txt
> A: sttinfo.fi

- easylist/easylist_general_block.txt
**nsfw** 
- `e-wok.tv/player/index/30516/131/14536`
> A: (nsfw) e-wok.tv

- easylist_cookie/easylist_cookie_general_block.txt
General cookie block, this is a remade of this old pull req: https://github.com/easylist/easylist/pull/3240
> A: pccomponentes.com

- easylist_cookie/easylist_cookie_general_hide.txt
General cookie banner hide filter.
Sample site: https://www.horze.fi/
> A: horze.fi

- easylist_cookie/easylist_cookie_international_specific_hide.txt
Cookie notification hide.
https://www.lehtodigital.fi/
> A: lehtodigital.fi

- fanboy-addon/fanboy_annoyance_thirdparty.txt
- https://i.imgur.com/RYNzXwn.png
> A: https://www.1001gedichten.nl/

- easylist/easylist_adservers_popup.txt
https://i.imgur.com/br8gKr4.png
https://forums.lanik.us/viewtopic.php?p=145348#p145348
> A: https://vip7stream.pw/bc0069a07bf78daa34378fca6f0f3f59-live.html

- easylist_adult/adult_adservers.txt
> A: (nsfw) omasex.tv

- fanboy-addon/fanboy_annoyance_whitelist.txt
Fixing same issue referenced.
Blocked script is: https://www.abc.net.au/assets/radio-2.52/js/components/newsletter/wcms.newsletter.jquery.min.js
> P: ryanbr/fanboy-adblock#613

- easylist/easylist_general_hide.txt
> M: youtube.com #5085

- easylist/easylist_general_block.txt
https://github.com/abp-filters/abp-filters-anti-cv/issues/126
> A: http://europixhd.net/

- easylist/easylist_adservers.txt
https://github.com/abp-filters/abp-filters-anti-cv/issues/364
> A: https://www.pstream.net/e/KJxQ2W0P91WW00L

- easylist_cookie/easylist_cookie_specific_hide.txt
> A: displays.agneovo.com

- easylist/easylist_general_block.txt
> http://www.advert.org.pl

- easylist/easylist_specific_hide.txt
https://i.imgur.com/17hwrKw.png
> A: https://www.truecaller.com/search/uk/0612345678

- easylist/easylist_adservers_popup.txt
* `https://flvto-mp3.com/js/search.js`
* https://imgur.com/6YJodfL.png
> A: https://flvto-mp3.com/

- easylist_cookie/easylist_cookie_general_hide.txt
A general cookie banner hiding rule.
https://www.lahitapiola.fi/henkilo/vakuutukset-ja-elake/koti-ja-mokki/kotivakuutus/mita-korvataan
> A: lahitapiola.fi

- easylist/easylist_general_hide.txt
https://gomovies-online.me/watch-film/fantasy-island/Z0WByoZt/QwNHnmBH-online-for-free.html
`##.popOverForADSInPlayer`
Click to play the video and it will appear.
> A: https://gomovies-online.me

- fanboy-addon/fanboy_annoyance_international.txt
- fanboy-addon/fanboy_annoyance_specific_hide.txt
Intrusive video when scrolling.
https://github.com/easylist/easylistspanish/issues/91
> A:paginasiete.bo

- easylist/easylist_specific_hide.txt
Want to remove that ad box as it suggests.
> A: cellmapper.net

- easylist_adult/adult_thirdparty.txt
https://forums.lanik.us/viewtopic.php?f=62&t=42570
> A: (NSFW) 4fuckr.com

- easyprivacy/easyprivacy_thirdparty_international.txt
```
http://x7.shinobi.jp/Zen?0945496Naaacaaacfduwyvtfduwyvtcvwbpoayp00__B
https://cnobi.jp/v1/gazorss/recommend/js/imp.1.6.8.js
```
> A: http://tokkaban.com/

- easylist_cookie/easylist_cookie_whitelist_general_hide.txt
https://forums.lanik.us/viewtopic.php?f=64&t=44690
> P: https://proglib.io/

- easylist_cookie/easylist_cookie_international_specific_hide.txt
Cookie banner hide (at the top).
> A: yhteiso.telia.fi

- easylist/easylist_whitelist.txt
https://github.com/AdguardTeam/AdguardFilters/issues/55823
The second report.
> A: https://github.com/AdguardTeam/AdguardFilters/issues/55823

- easylist_cookie/easylist_cookie_general_hide.txt
General cookie banner hiding rule.
> A: staypro.fi

- easylist/easylist_specific_block.txt
Rule to block ads.
Sample link: https://www.brighteon.com/5972440643001
> A: brighteon.com

- easylist_cookie/easylist_cookie_international_specific_hide.txt
Cookie banner hide.
https://www.inmicsnebula.fi/fi
> A: inmicsnebula.fi

- easylist_cookie/easylist_cookie_whitelist_general_hide.txt
Product reviews are not visible if cookies are not accepted.
Sample link: https://www.power.fi/kodinkoneet/astianpesukoneet/p-876549/
Reviews not visible:
Reviews visible after accepting cookies:
> P: power.fi

- easylist_cookie/easylist_cookie_general_hide.txt
General cookie banner hiding rule.
https://www.varusteleka.fi/fi
> A: varusteleka.fi

- easyprivacy/easyprivacy_specific_international.txt
Tracking. Sample links:
https://puutarha.net/
https://puutarha.net/artikkelit/17363/tutustu_esimerkkikohteisiin_jatevesijarjestelman_valinta_vestelli.htm
> A: https://puutarha.net/

- easyprivacy/easyprivacy_specific_international.txt
Tracking. Sample link: https://www.omataloyhtio.fi/osallistu/17315/kerrostaloasuja_testaajaksi_alylammityspalvelulle_ilmoita_lammitysongelmasta.htm
> A: https://www.omataloyhtio.fi/

- easyprivacy/easyprivacy_specific_international.txt
> A: https://www.ruutu.fi/

- easyprivacy/easyprivacy_specific_international.txt
- easyprivacy/easyprivacy_trackingservers_international.txt
> A: https://www.hs.fi/

- easyprivacy/easyprivacy_trackingservers_international.txt
Tracking server. (Note, valmet.com has Finnish nationality).
> A: valmet.com

- easylist_cookie/easylist_cookie_general_hide.txt
> A: https://www.jyu.fi/

- easylist/easylist_allowlist_general_hide.txt
> http://memytutaj.pl/

- easyprivacy/easyprivacy_general.txt
e.g.
```
https://wawacity.ninja/bypassmajs
https://annuaire-telechargement.best/bypassmajs
https://zone-telechargement.ninja/bypassmajs
```
> A: https://annuaire-telechargement.best/

- easylist_cookie/easylist_cookie_international_specific_hide.txt
> A: https://www.matkahuolto.fi/

- easylist_cookie/easylist_cookie_specific_hide.txt
Cookie notification hide.
EDIT. Simplified the rule.
Sample link: https://www.quora.com/What-are-the-best-Ad-blockers-to-use-while-browsing-the-web?share=1
> A: quora.com

- easylist_adult/adult_thirdparty.txt
https://github.com/abp-filters/abp-filters-anti-cv/issues/426
> A: (nsfw) javjunkies.com

- easyprivacy/easyprivacy_general.txt
https://github.com/uBlockOrigin/uAssets/issues/7676
> P: cand.li

- fanboy-addon/fanboy_annoyance_general_hide.txt
> wp-cookie-notification-banner

- easyprivacy/easyprivacy_specific.txt
Fingerprinting on PNC website homepage and online banking login
```
https://www.pnc.com/en/personal-banking.html
https://www.onlinebanking.pnc.com/alservlet/OnlineBankingServlet
```
> A: pnc.com

- easylist/easylist_specific_hide.txt
This is essentially the same as https://github.com/uBlockOrigin/uAssets/issues/7321 but please add Japanese expression too.
> P: Add Japanese to Twitter hiding rules

- easylist_cookie/easylist_cookie_general_hide.txt
This PR blocks kuki (source https://github.com/lctdnl/kuki) from websites.
Example website: https://www.amerlingbeisl.at/
> block kuki

- easylist/easylist_specific_block.txt
**found in url:** https://telugubullet.com/
> A:telugubullet.com

- easylist/easylist_specific_block.txt
3rd-party subdoc will be fixed by >> https://git.io/JJMGr
> A: https://series.movie/

- fanboy-addon/fanboy_notifications_thirdparty.txt
as requested >>  https://github.com/easylist/easylist/pull/5867#issuecomment-671042215
> A: https://search.playgamenowtab1.com/

- easylist/easylist_specific_block.txt
https://github.com/AdguardTeam/AdguardFilters/issues/62485
> A: fix https://github.com/AdguardTeam/AdguardFilters/issues/62485

- easylist_cookie/easylist_cookie_allowlist_general_hide.txt
Access to the website is blocked, added a fix.
https://www.tennisassa.fi/
> P: https://www.tennisassa.fi/

- fanboy-addon/fanboy_annoyance_specific_hide.txt
https://i.ibb.co/7Rq42NK/zh.png
> A: https://mail.zoho.com/zm/

- easyprivacy/easyprivacy_specific_international.txt
> A: adlibris.com (tracking pixel)

- dispute_resolution.md
Correct typos and improve grammar while I'm at it.  (I was going to change to "Describe why" but "Description of why" changes less and works better with the colon.
> Update dispute_resolution.md: Correct typos and improve grammar.

- easylist/easylist_general_hide.txt
Generic filter.
https://www.ampparit.com/
> A: ampparit.com (generic Easylist hide)

- easylist/easylist_specific_hide.txt
(unsure what the first character of all the issues, PRs and commits mean, so sorry if I got it wrong)
> M: Fix ebay.com Sponsored Listings

- easylist_cookie/easylist_cookie_specific_hide.txt
https://www.nperf.com/
(multilanguage site)
>  A: nperf.com (cookie specific hide)

- fanboy-addon/fanboy_annoyance_international.txt
> A: https://www.comment-economiser.fr/

- easylist/easylist_general_hide.txt
- easylist_adult/adult_adservers.txt
Example URLs (nsfw):
```
https://angryboy.tv/ja/video/3824942637455611082/
https://extremeporn.tv/ja/video/3824942636553831065/
http://fraxinellaporn.com/ja/video/3824942638589585451/
```
[EDIT] `showmeyouradsnow.com` needs to be blocked first, otherwise another overlay appears.
> M: address leftover of many porn sites

- easylist_adult/adult_specific_block.txt
https://github.com/easylist/easylist/pull/5986#pullrequestreview-484458358
> A: (nsfw) tits-guru.com

- easylist/easylist_specific_block.txt
update domains
```
thekat.app
thekat.nl
```
> A: (update #5768) https://kickass-kat.com/

- easylist/easylist_general_hide.txt
#5760
https://imgur.com/QyP1EN2.png
> A: https://zooqle.com/the-old-guard-2020-1080p-dual-xq1f7.html

- easylist/easylist_allowlist_general_hide.txt
URL: `https://www.adaware.com/ja/ad-block`
Issue: Image hidden
<details>
</details>
> P: fix https://www.adaware.com/ja/ad-block image

- easylist/easylist_specific_block.txt
**found in url:** https://www.5dariyanews.com/
> A:5dariyanews.com

- easylist/easylist_specific_hide.txt
https://forums.lanik.us/viewtopic.php?f=62&t=43992
https://forums.lanik.us/viewtopic.php?f=91&t=45369
> A: http://windowsbulletin.com/what-is-windows-bt-folder-is-it-safe-to-delete/

- easylist_adult/adult_thirdparty.txt
https://forums.lanik.us/viewtopic.php?f=64&t=45411
https://github.com/easylist/easylist/commit/2209fc19579b63013266645ade9cad4b5804ff5b
> M: Removed obsolete filter (nsfw - xnxx.com)

- fanboy-addon/fanboy_social_general_hide.txt
> A: (pixabay.com) #6491

- easyprivacy/easyprivacy_trackingservers.txt
https://github.com/hoshsadiq/adblock-nocoin-list/issues/410
> A: Update mining domainds

- easyprivacy/easyprivacy_specific_international.txt
Fixes: https://github.com/easylist/easylist/issues/6633
> P: adlibris.com (images won't always load without a page refresh)

- fanboy-addon/fanboy_annoyance_international.txt
> A: https://www.samastech.com/2019/03/Top-software-to-design-logo-for-the-computer.html

- fanboy-addon/fanboy_annoyance_allowlist_general_hide.txt
Screenshot follows.
P.S. I thank you all for all the time and effort you've put into the lists!
> P: fix redflagdeals.com

- fanboy-addon/fanboy_social_allowlist.txt
https://forums.lanik.us/viewtopic.php?f=64&t=45472
> P: (fb99a5d) https://iomqt-vo.edu.rosminzdrav.ru/

- easyprivacy/easyprivacy_thirdparty.txt
https://forums.lanik.us/viewtopic.php?f=62&t=45520
> A: https://hackernoon.com/

- easylist_adult/adult_specific_hide.txt
> A: (nsfw - bdsmlr.com) https://forums.lanik.us/viewtopic.php?p=157863#p157863

- fanboy-addon/fanboy_social_general_hide.txt
https://i.ibb.co/cC4B9yC/shorturl-at.png
> A: https://www.shorturl.at/

- easylist/easylist_adservers.txt
https://github.com/easylist/easylist/pull/6777
(Maybe I could just ping you on Slack.
> M: update #6777 (missed adserver)

- easylist/easylist_allowlist_general_hide.txt
URL: `https://www.realgfporn.com/`
Issue: "Top Uploaders" hidden by `##.large-right-ad`:
<details>
</details>
> P: (nsfw) https://www.realgfporn.com/

- easylist_adult/adult_specific_block.txt
URL: `https://www.pornrabbit.com/` and all its subpages
Issue: placeholder:
<details>
</details>
> A: (nsfw) https://www.pornrabbit.com/

- easylist_adult/adult_specific_hide.txt
Related: https://github.com/AdguardTeam/AdguardFilters/issues/74243
> A: (nsfw) https://momxxxfun.com/your-sister-catches-you/

- fanboy-addon/fanboy_annoyance_international.txt
> A: https://www.rambler.ru/

- fanboy-addon/fanboy_social_allowlist.txt
https://github.com/easylist/easylist/commit/08ab4a760692c572cb820fb420218375fed3acae#diff-f17190f80cc292ec410efb2c109ebc72aec5842d598dfcc5afb0476ad2f1d223R109
> P: https://iconarchive.com/search?q=twitter

- fanboy-addon/fanboy_social_allowlist_general_hide.txt
Problem 
* Share link is hidden.
for testing... login credential sent to `easylist@` and `mp3geek@`
> P: https://app.degoo.com/search?category=3

- easylist/easylist_specific_hide.txt
> A: https://2conv.com/jp67/

- easylist/easylist_specific_hide.txt
The new domain of previous `loveheaven.net`, leftover:
<details>
</details>
I avoided to hide center, as that caused FP on loveheaven in past. But `.chapter-content >` is not necessary - ready to remove if you prefer that.
> A: https://lovehug.net/787/44829/

- easylist/easylist_specific_hide.txt
Placeholders / ad spaces (at least two of them)
> A: keygames.com placehoders

- easylist_cookie/easylist_cookie_international_specific_block.txt
https://github.com/easylist/easylistgermany/issues/114
> A: https://www.jameda.de/arztsuche/?fachgebiet=S53&new_search=1

- easyprivacy/easyprivacy_trackingservers_international.txt
Tracker paths:
```
https://as.uncn.jp/uwt/2620/uwt.js
https://uncn.jp/astraea/access_log?
https://yb.uncn.jp/t.gif
```
> A: https://bluearchive.jp/

- easylist/easylist_adservers.txt
Found through https://www.mypdns.org/T3969
> ethereumads.com || https://www.mypdns.org/T3970

- easylist_cookie/easylist_cookie_specific_hide.txt
> A: jooble.org (specific cookie hide)

- easylist_cookie/easylist_cookie_thirdparty.txt
https://github.com/easylist/easylist/pull/7300#pullrequestreview-600307256
> A: Update #7300

- easyprivacy/easyprivacy_thirdparty_international.txt
> A: comic.k-manga.jp

- easylist_cookie/easylist_cookie_general_hide.txt
> A: nordnet.fi (generic cookie hide)

- easylist/easylist_adservers.txt
- easylist/easylist_specific_block.txt
From: https://www.mypdns.org/T4272
Related to: https://github.com/easylist/easylist/issues/7331
> speedostream.com | https://www.mypdns.org/T4272

- easylist_cookie/easylist_cookie_allowlist_general_hide.txt
- easylist_cookie/easylist_cookie_general_hide.txt
Another modification to fix checkbox being removed issues more generally.
Same principle as here: https://github.com/easylist/easylist/pull/7309
Sample site: https://account.sonymobile.com/
> M: ###privacy-statement -> ###privacy-statement:not(.checkbox)

- easylist/easylist_specific_hide.txt
> A: www.defenseone.com

- fanboy-addon/fanboy_notifications_allowlist.txt
"次へ" (Next) button broken:
<details>
</details>
> P: https://www.jrepoint.jp/entry/provisional/

- fanboy-addon/fanboy_annoyance_international.txt
https://i.ibb.co/WVvrnCp/nl.png
> A: https://www.telesatellite.com/actu/57351-m.html

- easyprivacy/easyprivacy_trackingservers_international.txt
> A: www.55truck.com

- easyprivacy/easyprivacy_allowlist.txt
Video broken:
<details>
</details>
> P: bloomberg.co.jp, bloomberg.com

- easylist_cookie/easylist_cookie_international_specific_hide.txt
Cookie banner hide.
https://www.scandinavianphoto.fi/
> A: scandinavianphoto.fi (specific cookie banner)

- easylist/easylist_specific_hide.txt
Sample link: https://www.opensubtitles.org/en/subtitles/5639181/a-nightmare-on-elm-street-5-the-dream-child-en
Will hide "Hide ads" section.
> A: https://www.opensubtitles.org

- easylist/easylist_allowlist.txt
- easyprivacy/easyprivacy_specific_international.txt
- easyprivacy/easyprivacy_thirdparty_international.txt
- easyprivacy/easyprivacy_trackingservers_international.txt
https://github.com/AdguardTeam/AdguardFilters/issues/78094
Resource redirect works so I'll add redirect rules with `$important` for AG/uBO.
> P: real-sports.jp (fixes AdguardTeam/AdguardFilters#78094)

- easyprivacy/easyprivacy_thirdparty.txt
- easyprivacy/easyprivacy_trackingservers.txt
> A: (nsfw) www.baberoad.com

- easyprivacy/easyprivacy_allowlist.txt
Please review https://github.com/easylist/easylist/pull/4259 for a previous iteration and company details. 
Our entry was removed again via https://github.com/easylist/easylist/commit/e90534c628b65bf757a17e73f3c6f1d8367a143e and has resulted in outages.
@ryanbr
> P: evestment.com/api/analytics

- easylist_cookie/easylist_cookie_international_specific_hide.txt
https://vapaasana.swedishforum.net/
> M: removed redundant filter

- easylist_cookie/easylist_cookie_international_specific_hide.txt
https://www.scandinavianphoto.fi/ they use element name randomizing so I targeted style instead of class names.
> M: scandinavianphoto.fi (updated broken filter)

- easylist_cookie/easylist_cookie_international_specific_hide.txt
For cookie banner, they use .notification now (already in the list).
> M: redundant filter

- easyprivacy/easyprivacy_allowlist_international.txt
> P: www.kenko-tokina.co.jp

- easylist/easylist_general_block.txt
> P: https://games.wkb.jp/html5games/play/testyourmemory/

- easylist/easylist_adservers.txt
- easylist_adult/adult_specific_hide.txt
Related: https://github.com/AdguardTeam/AdguardFilters/issues/78766
> A: (nsfw) https://www.mumbaiporn.com/indian-video/7057426

- easyprivacy/easyprivacy_allowlist_international.txt
Video broken:
<details>
</details>
> P: https://jod.jsports.co.jp/about

- easylist_cookie/easylist_cookie_general_hide.txt
> A: tulikulma.fi (generic cookie hide)

- easyprivacy/easyprivacy_allowlist_international.txt
1. `http://www.jp.square-enix.com/seiken2_som/news.html`
News broken:
<details>
<summary>Screenshots 1</summary>
</details>
2. `http://www.jp.square-enix.com/jc3/`
Click News -> blank page
<details>
<summary>Screenshots 2</summary>
</details>
> P: www.jp.square-enix.com

- easylist/easylist_allowlist_general_hide.txt
> P: www.wsj.com

- easylist_adult/adult_specific_hide.txt
- easylist_adult/adult_thirdparty.txt
> A: (nsfw) 69gfs.com

- easyprivacy/easyprivacy_thirdparty_international.txt
> A: www.starq-online.com

- easyprivacy/easyprivacy_specific_international.txt
> A: www.caliente.mx

- easylist/easylist_allowlist.txt
"View more" button does not work.
> P: https://www.friendcafe.jp/media/all

- easylist/easylist_allowlist.txt
</details>
Related: brave/brave-browser#11448 (not currently reproduced without the allow filter)
> P: https://www.nintendo.co.jp/ring/adv/index.html

- README.md
> M: improve README

- easylist_adult/adult_specific_hide.txt
> A: (nsfw) milf.dk

- easylist_cookie/easylist_cookie_specific_block.txt
> A: asus.com (specific cookie block)

- easylist_adult/adult_specific_block.txt
Popup on clicking articles
<details>
</details>
> A: (nsfw) dragonthumbs.com - popup

- easylist_cookie/easylist_cookie_general_hide.txt
Sample link: https://steamcommunity.com/app/42700/discussions/0/1694921076570808585/
> A: steamcommunity.com (generic cookie hide)

- easylist_cookie/easylist_cookie_specific_hide.txt
> A: speedtest.net (specific cookie hide)

- easylist_cookie/easylist_cookie_general_block.txt
https://community.spiceworks.com/
> A: community.spiceworks.com (generic cookie block)

- easylist_cookie/easylist_cookie_general_hide.txt
> A: icecat.biz (generic cookie hide)

- easylist_cookie/easylist_cookie_general_block.txt
- easylist_cookie/easylist_cookie_general_hide.txt
- easylist_cookie/easylist_cookie_international_specific_hide.txt
Generic cookie block & specific hide rule.
Sample pages:
https://www.tuska.fi/
http://kalkinpoisto.com/
https://www.nuudelit.fi/
https://www.oivasivut.fi/
https://paajala.fi/
https://www.linseed.fi/
http://mokkivesi.fi/
http://hanavesi.fi/
http://hanavesitesti.fi/
http://www.keskustaopiskelijat.fi/
Note: "banneri" is a Finnish variant of "banner".
> A: nuudelit.fi (generic cookie block & specific hide)

- easylist/easylist_general_block.txt
> P: www.rakuten.co.jp

- easylist/easylist_specific_hide.txt
found in url: https://presskitaquat.com/
> A:presskitaquat.com

- easylist/easylist_general_block.txt
https://keskustelu.suomi24.fi/
> A: keskustelu.suomi24.fi (generic ad block)

- easylist/easylist_specific_block.txt
> A: https://www.qwant.com/?q=iphone&t=web

- fanboy-addon/fanboy_annoyance_specific_block.txt
* https://i.ibb.co/sWf2qRq/qwant-com.png
> A: https://www.qwant.com/

- easyprivacy/easyprivacy_trackingservers.txt
* `https://megastats.net/js/script.js`
*  `https://megastats.net/api/event`
> A: https://streamonsports.cc/eurosport-1.php

- easylist/easylist_specific_hide.txt
> A: https://www.dictionary.com/browse/test

- easylist/easylist_allowlist.txt
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1800
> P: https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1800

- easylist_cookie/easylist_cookie_specific_uBO.txt
https://www.terveyskirjasto.fi/
> A: terveyskirjasto.fi (cookie hide, ubo)

- easylist/easylist_specific_hide.txt
> A: ja.linkfang.org

- easyprivacy/easyprivacy_allowlist_international.txt
Image and some information is not displayed.
</details>
> P: https://lexus.jp/

- easyprivacy/easyprivacy_trackingservers_international.txt
> A: https://dpoint.jp/cp_2/googleplay_210428_2138/contents02.html

- easyprivacy/easyprivacy_allowlist_international.txt
- Some images are not displayed.
- Clicking on internal links does not cause any change.
> P: https://voguegirl.jp/

- easylist/easylist_allowlist.txt
`https://ganma.jp/bokuriyu/87dd00c0-399c-11e9-a4ed-06e4e79605e7/36`
Can't move to the previous / next story in the manga viewer 
</details>
> P: https://ganma.jp

- easyprivacy/easyprivacy_allowlist_international.txt
1. Some images are not displayed.
~~~
@@||api.cxense.com/public/widget/data?$xmlhttprequest,domain=cyclestyle.net
@@||scdn.cxense.com/cx.js$script,domain=cyclestyle.net
~~~
2. Can't use Google custom search
~~~
@@||googletagmanager.com/gtm.js$script,domain=cyclestyle.net
~~~
> P: https://cyclestyle.net/

- easyprivacy/easyprivacy_allowlist_international.txt
If you try to search, the layout will be broken.
</details>
> P: https://o-uccino.com/front

- easylist_cookie/easylist_cookie_specific_uBO.txt
https://www.espoo.fi/en-US
https://www.esbo.fi/sv-FI
> A: esbo.fi / espoo.fi (cookie block, ubo)

- easylist/easylist_general_hide.txt
- easylist/easylist_specific_hide.txt
> A: www.msn.com

- easylist/easylist_general_hide.txt
- easylist/easylist_specific_hide.txt
> A: romhustler.org

- easylist/easylist_allowlist_general_hide.txt
> P: https://sozai-good.com/illust/note/

- easyprivacy/easyprivacy_allowlist_international.txt
The Delivery Method column disappears.
**Step to Reproduce**
1. Click `Delivery`
2. Input `1000001` in `Postal Code` and click `Search`
3. Click `CHIYODA, CHIYODA-KU, TOKYO`
4. Click `ASAP`
5. Select the pizza to order
6. Click `Go to Payment`
</details>
> P: internetorder.dominos.jp/estore/en/Checkout

- easylist/easylist_allowlist.txt
`$image,stylesheet,font,script` if you want to specify request type.
> P: https://bloominc.jp/adtool/

- easylist_adult/adult_specific_hide.txt
All the thumbnails are hidden.
> P: (nsfw) http://www.pussy.org/

- easylist_adult/adult_specific_hide.txt
> P: (nsfw) https://xxxymovies.com/

- easylist/easylist_allowlist_general_hide.txt
> P: (nsfw) https://porndoo.com/videos/trending/

- easyprivacy/easyprivacy_general.txt
```
stats.zone-annuaire.casa/bypassma.js
stats.extreme-down.work/bypassma.js
```
> A: https://www.extreme-down.work/

- easylist/easylist_specific_hide.txt
Closes https://github.com/easylist/easylist/pull/8009
> addresses silverprice.org ads

- easyprivacy/easyprivacy_allowlist_international.txt
> P: https://www.t-fashion.jp/shop/abahouse/goods/13587212

- fanboy-addon/fanboy_notifications_specific_hide.txt
> reddit.com - block popup

- easyprivacy/easyprivacy_allowlist_international.txt
The product image is not displayed and the layout is broken.
<details><summary>Screenshot (broken)</summary>
</details>
<details><summary>Screenshot (fixed by the PR)</summary>
</details>
> P: https://www.epson.jp/products/ecotank/ewm752t/

- easylist/easylist_general_hide.txt
@ryanbr would this be ok then if https://github.com/easylist/easylist/pull/7973 was not safe?
https://jaatama.fi/
> A: jaatama.fi (generic hide)

- easyprivacy/easyprivacy_allowlist_international.txt
You cannot move the product pages by clicking the product images. 
> P: https://www.matsukiyo.co.jp/store/online/search

- easylist_adult/adult_specific_hide.txt
Related to:
- https://github.com/easylist/easylist/issues/8078
- https://www.mypdns.org/T4697
```
##.happy-under-player
##.happy-footer
```
<details><summary>Sreenshots</summary>
</details>
> NSFW: gigapornmovies.com .happy-footer + .happy-under-player

- easylist/easylist_adservers_popup.txt
https://github.com/abp-filters/abp-filters-anti-cv/pull/613
> A: https://hxfile.co/qend73rq3i15

- easylist/easylist_allowlist.txt
Some images are blocked.
</details>
> P: https://cinema.pia.co.jp/

- easylist/easylist_allowlist.txt
Nothing happens when you click on the map.
> P: https://www.chintaistyle.jp/

- easyprivacy/easyprivacy_allowlist_international.txt
1. `https://radiko.jp/` (PC)
2. `https://radiko.jp/mobile/trial/` (Mobile)
1. Can't click "Accept the terms of use".
2. See https://github.com/AdguardTeam/AdguardFilters/issues/83956
<details>
</details>
> P: https://radiko.jp/ (fixes https://github.com/AdguardTeam/AdguardFilters/issues/83956 )

- easyprivacy/easyprivacy_allowlist_international.txt
`https://stage.parco.jp/`
The chatbot does not show up.
<details>
<summary>Screenshot 1</summary>
</details>
<details>
<summary>Screenshot 2</summary>
</details>
> P: https://stage.parco.jp/

- easyprivacy/easyprivacy_allowlist_international.txt
`https://www.viviennewestwood-tokyo.com/f/dsg-2196535`
Virtual trying-on doesn't work.
Already fixed in uBlock filters – Unbreak by https://github.com/uBlockOrigin/uAssets/commit/d111d9c
<details>
<summary>Screenshot 1</summary>
</details>
<details>
<summary>Screenshot 2</summary>
</details>
> P: https://www.viviennewestwood-tokyo.com/f/dsg-2196535

- easylist/easylist_allowlist.txt
- easylist/easylist_allowlist_general_hide.txt
> P: www.yuukinohana.co.jp

- easylist_cookie/easylist_cookie_specific_uBO.txt
> A: danskebank.fi (cookie banner hide, Ubo)

- easylist_cookie/easylist_cookie_allowlist_general_hide.txt
Cookie banner blocking breaks the site by making it unaccessible.
https://danskebank.fi
> P: danskebank.fi (site unaccessible)

- fanboy-addon/fanboy_annoyance_specific_hide.txt
https://github.com/easylist/easylist/issues/8165
> A: https://699pic.com/

- easylist/easylist_general_block.txt
`https://pc-play.games.dmm.com/play/pluslinks/` (**accounts needed**)
Download fails when starting the game.
`https://twitter.com/Plus_Links/status/1406821512091291650`
</details>
<details><summary>Logger output</summary>
| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +8 | \_ad01\_ | -- | d2yx903p3mbthv.cloudfront.net | 3,3 | script | `https://d12p4bs8f6ikug.cloudfront.net/webgl/sound/bgm_ad01_01.001/index.js` |
| +8 | \_ad01\_ | -- | d2yx903p3mbthv.cloudfront.net | 3,3 | xhr | `https://d12p4bs8f6ikug.cloudfront.net/webgl/sound/bgm_ad01_01.001/config.json` |
| +6 | \_ad01\_ | -- | d2yx903p3mbthv.cloudfront.net | 3,3 | script | `https://d12p4bs8f6ikug.cloudfront.net/webgl/sound/bgm_ad01_01.001/index.js` |
| +6 | \_ad01\_ | -- | …
> P: https://pc-play.games.dmm.com/play/pluslinks/

- easylist/easylist_specific_block_popup.txt
https://pastebin.com/raw/j97ysR5B
> A: https://www.sendspace.com/file/47sdqw

- easylist_adult/adult_specific_block.txt
> A: (nsfw) broncs.net

- WEBCOMPAT.md
Pretty much what the title says.
> Added Melhusbanken + Performed spellchecking

- easylist/easylist_general_hide.txt
- easylist/easylist_specific_hide.txt
Both found on pypi.org
```
pypi.org##.sponsor-grid__sponsor
pypi.org##.sponsors
```
> ##.sponsor-grid__sponsor + ##.sponsors

- easylist/easylist_general_hide.txt
See `https://scammer.info/t/vote-for-my-cs-go-team-scam/75870` for example
Was pointed there by https://github.com/mitchellkrogza/phishing/pull/7
So Thanks to: Zachinquarantine
> ##.discourse-adplugin

- easylist/easylist_allowlist_general_hide.txt
> P: job.inshokuten.com

- fanboy-addon/fanboy_annoyance_specific_block.txt
- https://imgur.com/RGVJKTS.png
> A: (google.com) #8211

- easylist_cookie/easylist_cookie_specific_uBO.txt
Cosmetic filter works too slowly, I see blinks of it occasionally. Added a scriptlet to block it.
https://sss.fi/
> A: sss.fi (cookie block, Ubo)

- easylist_adult/adult_specific_hide.txt
> A: (nsfw) pornchimp.com

- WEBCOMPAT.md
> Finally got around to handle ABP and Brave in the Webcompat list

- fanboy-addon/fanboy_social_international.txt
Fix #8263
The button will cover up the title of the article.
> P: https://www.jiji.com/jc/article?k=2021070100898

- fanboy-addon/fanboy_social_allowlist_general_hide.txt
Fix #8133
Follow button is hidden. (like Youtube follow button.)
> P: https://www.nicovideo.jp/watch/sm21813482

- fanboy-addon/fanboy_annoyance_allowlist_general_hide.txt
> P: https://www.iosysos.com/

- fanboy-addon/fanboy_annoyance_specific_hide.txt
to encounter the annoyance: scroll towards the bottom of the page
> addresses annoyance on ziarulevenimentul.ro

- easylist/easylist_general_hide.txt
> A: myanimals.com (generic hide)

- easylist/easylist_allowlist.txt
Similar to https://github.com/easylist/easylist/pull/8376
> P: http://banc.jp/career/

- easylist_cookie/easylist_cookie_general_hide.txt
https://webshop.elektroskandia.no/nor/
> P: webshop.elektroskandia.no (cookie list breakage, general issue)

- easylist_cookie/easylist_cookie_specific_uBO.txt
https://www.aixfoam.fi
Multiple TLD's. For e.g.: https://www.aixfoam.com, https://www.aixfoam.se and even more.
> A: aixfoam.fi | .* (cookie hide, Ubo)

- easylist/easylist_specific_hide.txt
Hide job advertisements on StackOverflow.com.  I have only seen these ads on the main StackOverflow site and not on any of the other StackExchange network sites.
> A: stackoverflow.com

- easylist_cookie/easylist_cookie_general_hide.txt
- easylist_cookie/easylist_cookie_specific_uBO.txt
https://www.veikkaus.fi/
.. and also a specific for Ubo to fix blinking.
> A: veikkaus.fi (generic cookie hide)

- fanboy-addon/fanboy_annoyance_international.txt
> A: https://w.mail.qq.com

- easylist/easylist_specific_hide.txt
https://github.com/easylist/easylist/pull/8171
> A: https://www.last.fm/home

- easylist_cookie/easylist_cookie_specific_uBO.txt
https://www.taloon.com/
The scriptlet or styling rules work alone as well but that site suffers race-condition occasionally so I decided to add both: the scriptlet and styling rules, in order to avoid race-condition as much as possible.
> A: taloon.com (cookie banner, Ubo)

- easylist_cookie/easylist_cookie_specific_uBO.txt
Added a specific filter to avoid blinking issues.
https://www.varusteleka.com/
> A: varusteleka.com|.fi (cookie hide, Ubo)

- easylist/easylist_allowlist.txt
Sample link: https://seura.fi/ilmiot/tiede-ja-luonto/pepe-forsberg-majava-luottaa-yhteistyon-voimaan/
> P: seura.fi (videos broken)

- fanboy-addon/fanboy_social_general_hide.txt
https://github.com/SlashArash/adblockfa/issues/16
> A: https://soft98.ir/

- easylist_cookie/easylist_cookie_specific_uBO.txt
> A: airam.fi (cookie notification, Ubo)

- fanboy-addon/fanboy_annoyance_international.txt
- fanboy-addon/fanboy_annoyance_specific_hide.txt
fix (partial) https://github.com/uBlockOrigin/uAssets/issues/9634
fix https://github.com/easylist/easylist/pull/8166
close https://github.com/easylist/easylist/pull/8400
close https://github.com/easylist/easylist/pull/8433
> A: https://699pic.com/tupian-401953471.html

- fanboy-addon/fanboy_annoyance_international.txt
Fix https://github.com/easylist/easylist/pull/8444
Self-promotion
Thank you
> A: https://fanyi.sogou.com/text

- fanboy-addon/fanboy_annoyance_international.txt
> A: https://juejin.cn/post/6988139732018397215

- fanboy-addon/fanboy_annoyance_international.txt
> A: https://wap.sogou.com/

- fanboy-addon/fanboy_annoyance_international.txt
rebase: https://github.com/easylist/easylist/pull/8397
Hello!
This is a pop-up window in the middle
Self-promotion
> A: https://fanyi.baidu.com/

- easylist/easylist_specific_hide.txt
OverLay Ads + one banner (video ad) in right sidebar
> ottverse.com

- easylist_adult/adult_specific_hide.txt
Blocks popup commercial
External related:
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/177
> instantfap.com###af

- easyprivacy/easyprivacy_specific_international.txt
> Tencent Tracker

- easyprivacy/easyprivacy_specific.txt
> A: https://pg.surveymonkey.com/

- easyprivacy/easyprivacy_specific_international.txt
> Fix https://github.com/AdguardTeam/AdguardFilters/issues/89992

- easyprivacy/easyprivacy_specific.txt
The part 1 of https://github.com/uBlockOrigin/uAssets/commit/2c512264e6701a4698ce0dad9ad29d3ea88b1aaf
> A: https://www.racerstar.com/

- easyprivacy/easyprivacy_specific.txt
> A: accounts.reddit.com​

- easyprivacy/easyprivacy_specific_international.txt
> Xiaomi tracker

- easyprivacy/easyprivacy_allowlist_international.txt
Sample site: https://www.hardware.fi/uutiset/artikkeli.cfm/2021/07/28/windows-11-markkinaosuus-nousi-jo-hammentavan-suureksi-windows-10-kayttajien-laiska-paivitystahti-paljastui-sekin
Edit, also:
https://fin.afterdawn.com/uutiset/artikkeli.cfm/2021/08/05/deezer-hinnankorotus-2021-hifi-aanenlaatu
> P: hardware.fi / fin.afterdawn.com (article pictures blocked)

- README.md
Pretty much what the title says, really.
> Grammar improvements + Added info on PRs and placeholders

- easyprivacy/easyprivacy_specific_international.txt
> A: http://aliotop.fr/aliotop/7QLDONPzhcr

- fanboy-addon/fanboy_annoyance_general_block.txt
```
https://www.cap-direct.fr/
https://www.herault-direct.fr/
https://www.occitanie-tribune.com/
```
> A: https://www.cap-direct.fr/

- easylist_cookie/easylist_cookie_specific_ABP.txt
Remade of https://github.com/easylist/easylist/pull/8349
I don't know if ABP accepts this for Cookie list but will see.
>  A: podleze-piekielko.pl (ABP, cookie)

- easylist_cookie/easylist_cookie_allowlist_general_hide.txt
- easylist_cookie/easylist_cookie_general_hide.txt
I think that instead of whitelisting this site, it'd better instead to edit the original rule to make sure it never breaks any sites by matching body elements.
> M: changed generic filter to make it more safe

- fanboy-addon/fanboy_notifications_general_hide.txt
https://www.maaseuduntulevaisuus.fi/politiikka/artikkeli-1.1505374
`###uutiskirje-nosto` -> "uutiskirje" means "newsletter" and "nosto" means lift/lifting, something that has been lifted.
> A: maaseuduntulevaisuus.fi (generic newsletter hide)

- easylist_adult/adult_specific_hide.txt
Related to #8439
<details><Summary>Screenshot required</summary>
</details>
<details><summary>note to self (@spirillen)</summary>
https://mypdns.org/my-privacy-dns/matrix/-/issues/1276
</details>
> ##.bb_desktop

- easylist_cookie/easylist_cookie_international_specific_hide.txt
https://www.kuntarekry.fi/fi/tyopaikat/it-tietohallinto/
> A: kuntarekry.fi (cookie hide)

- easylist/easylist_allowlist.txt
https://science.howstuffworks.com/question112.htm
https://www.reddit.com/r/uBlockOrigin/comments/p0ina2/blocked_video_on_howstuffworkscom/
> P: howstuffworks.com (videos are blocked)

- easylist/easylist_allowlist_general_hide.txt
> P: m.motonet.fi (product images blocked)

- fanboy-addon/fanboy_notifications_specific_block.txt
- fanboy-addon/fanboy_notifications_specific_hide.txt
- fanboy-addon/fanboy_notifications_specific_uBO.txt
https://www.rd.fi/
These rules will block self-promotion elements and newsletter stuff. (I hope this is the correct category).
Ubo rule is not absolutely necessary, but it will remove the sliderelement, which would otherwise spin in the backround even though it's hidden.
> A: rd.fi (notifications)

- fanboy-addon/fanboy_social_international.txt
https://www.rd.fi/
Blocks the Facebook banner.
vp-`fbssa`-banner
"fbssa" means "In Facebook".
> A: rd.fi (social block)

- easylist/easylist_allowlist.txt
> P: https://www.arukikata.co.jp/city/MIL/ (fixes search-hotel widget)

- easylist_cookie/easylist_cookie_general_hide.txt
https://bestsimilar.com/movies/26957-riddick
Banner (or a remnant of it) will appear after a while.
> A: bestsimilar.com (generic cookie hide)

- fanboy-addon/fanboy_annoyance_specific_hide.txt
**Issue URL (Annoyance)**: https://www.medianama.com/2020/08/223-ai-proctored-exams-privacy/
> medianama.com

- fanboy-addon/fanboy_notifications_specific_hide.txt
"Subscribe to our newsletter" - boxes.
https://www.kokemaenjokilaakso.fi/2021/08/15/kauvatsan-apteekkiin-murtauduttiin-isosta-ikkunasta/
> A: kokemaenjokilaakso.fi (notifications hide)

- easyprivacy/easyprivacy_thirdparty_international.txt
> A: https://wowma.jp/item/349293475?spe_id=top_rank_1

- easylist/easylist_allowlist_general_hide.txt
https://www.edukas.fi/
Same thing here: https://www.download.fi/
> P: edukas.fi / download.fi (top bar overlap breakage)

- fanboy-addon/fanboy_social_allowlist.txt
> P: jaatama.fi (all front page pictures are blocked)

- easyprivacy/easyprivacy_allowlist_international.txt
https://www.kauppahalli24.fi/
Filter needs to be updated, otherwise displaying of products is blocked again.
Old issue report https://github.com/easylist/easylist/issues/3727
> P: / M: kauppahalli24.fi (filter broken, products won't display)

- fanboy-addon/fanboy_annoyance_specific_hide.txt
- fanboy-addon/fanboy_social_specific_hide.txt
**Issue URL (Annoyance)**: https://colibriwp.com/blog/website-ideas/
> colibriwp.com

- easylist/easylist_general_block.txt
> P: https://webst8.com/blog/blog-genre/

- easyprivacy/easyprivacy_specific.txt
> address ping on cnn.com | address https://github.com/AdguardTeam/AdguardFilters/issues/91414

- fanboy-addon/fanboy_annoyance_specific_hide.txt
**Issue URL (Annoyance)**: https://www.topuniversities.com/blog/how-becoming-youtuber-changed-my-life
> topuniversities.com

- easylist_adult/adult_specific_hide.txt
Removes the top banner on front page
Related https://github.com/easylist/easylist/pull/8352
<details><summary>NSFW Screenshot</summary>
</details>
> NSFW: javfor.tv##.my-2.container M: #8352

- fanboy-addon/fanboy_notifications_general_hide.txt
- fanboy-addon/fanboy_notifications_specific_hide.txt
https://www.tokmanni.fi/
Wait a while for the popup to appear.
> A: tokmanni.fi (newsletter modal)

- easylist/easylist_general_hide.txt
> Added `##.adace-slideup-slot-wrap`

- easylist_cookie/easylist_cookie_specific_block.txt
Fixes #8777
https://play.google.com/store
> A: play.google.com (cookie banner block)

- easylist_cookie/easylist_cookie_general_hide.txt
https://www.verkkokauppa.com/
Accept ("Hyväksyn" in Finnish) button should not be removed.
> P: / M: verkkokauppa.com (cookie accept button removed, modified generic filter)

- easyprivacy/easyprivacy_specific.txt
```
https://mollusk.apis.ign.com/metrics/vitals
```
> A: (ign.com) #8787

- easylist/easylist_specific_block.txt
```
https://sm.ign.com/zdadkit2.js?
https://me.ign.com/s/js/zad.js?
```
> A: https://www.ign.com/

- easylist_cookie/easylist_cookie_general_hide.txt
https://www.elo.fi/
It's a large insurance company in Finland, so preferably it should be fixed asap.
@Khrin ?
> A: / P: elo.fi (cookie notification background remnant blocks usage of the site)

- fanboy-addon/fanboy_notifications_specific_hide.txt
Hide notification that asks to install their app.
> A: savonsanomat.fi (app installation notify)

- fanboy-addon/fanboy_notifications_general_block.txt
```
https://s1.twnmm.com/js/en_ca/r1314900/web/modules/notifications.js
https://s1.twnmm.com/js/fr_fr/r1314900/web/modules/notifications.js
```
> A: https://www.theweathernetwork.com/ (meteomedia.com)

- fanboy-addon/fanboy_social_international.txt
https://github.com/easylist/easylist/pull/8791#issuecomment-905216559
> A: (allocine.fr) #8791

- fanboy-addon/fanboy_annoyance_allowlist.txt
- fanboy-addon/fanboy_social_allowlist.txt
> P: instalki.pl (some pictures blocked by Social list)

- easyprivacy/easyprivacy_allowlist.txt
`https://right-on.co.jp/`
</details>
</details>
> P: https://right-on.co.jp/

- easylist_cookie/easylist_cookie_general_hide.txt
> P: docs.axway.com (generic cookie hide matches body element)

- fanboy-addon/fanboy_annoyance_specific_hide.txt
**Issue URL (Annoyance)**:
http://www.markammay.com/100-creative-ideas-for-a-website/
> markammay.com

- easylist/easylist_general_hide.txt
- easylist/easylist_specific_hide.txt
> A: www1.kiss-anime.asia,www2.kissanime.mobi

- easylist/easylist_general_hide.txt
> A: https://tsri.ch/zh/

- easyprivacy/easyprivacy_thirdparty.txt
> A: https://sociallinks.io/

- fanboy-addon/fanboy_social_allowlist.txt
Sample link: https://www.verkkouutiset.fi/petteri-orpon-oikeiston-iskunkestavyys-testissa/
Big slider image won't load, added a fix.
> P: verkkouutiset.fi (big slider image won't load)

- easylist_cookie/easylist_cookie_general_hide.txt
https://www.tiendeo.fi/myymalat/tampere/lidl
> A: tiendeo.fi (generic cookie hide)

- easylist/easylist_adservers.txt
See (Screenshot is kinda / contains NSFW)https://github.com/AdguardTeam/AdguardFilters/issues/93179
> A: https://watchserieshd.co/film/reservation-dogs-season-1/watching.html?ep=5 (in-player ad)

- easylist_cookie/easylist_cookie_general_hide.txt
- easylist_cookie/easylist_cookie_specific_hide.txt
**Issue URL (Annoyance)**:
https://www.advancedassessments.co.uk/Depression/Depression-Test/
> advancedassessments.co.uk

- fanboy-addon/fanboy_annoyance_international.txt
> A: http://bbs.sg169.com/forum-16-1.html

- fanboy-addon/fanboy_annoyance_international.txt
Hello!
This is self-promotion.
> A: https://pan.huang1111.cn/s/OxbHL

- fanboy-addon/fanboy_annoyance_international.txt
> A: https://news.cctv.com/2021/09/02/ARTIFUwQmxK5zsdKVlRMlOiE210902.shtml

- fanboy-addon/fanboy_annoyance_international.txt
> A: https://www.acfun.cn/

- fanboy-addon/fanboy_social_specific_hide.txt
> A: https://cybermap.kaspersky.com

- fanboy-addon/fanboy_annoyance_specific_hide.txt
**Issue URL (Annoyance)**: https://www.familyaware.org/help-someone/take-the-depression-and-bipolar-test/
> familyaware.org

- fanboy-addon/fanboy_annoyance_general_hide.txt
- fanboy-addon/fanboy_annoyance_specific_hide.txt
**Issue URL (Annoyance)**: https://www.phoneworld.com.pk/bankislami-enables-its-account-holders-on-nift-epay/
> phoneworld.com.pk

- fanboy-addon/fanboy_annoyance_general_hide.txt
- fanboy-addon/fanboy_annoyance_specific_hide.txt
**Issue URL (Annoyance)**: https://screening.mhanational.org/screening-tools/depression/#gf_1
> screening.mhanational.org

- easyprivacy/easyprivacy_allowlist_international.txt
https://www.kauppahalli24.fi/ content won't load, added a fix. Problem clearly visible.
> P: kauppahalli24.fi (EP breaks content)

- easylist/easylist_specific_hide.txt
For a gigantic international site like Amazon, I think EL should should cover all major locale. I confirmed some of these filters are effective on JP locale.
> M: add to Amazon TLDs

- fanboy-addon/fanboy_annoyance_international.txt
The page prompts the user to close the ad blocking software
> A: https://www.pcbeta.com/

- easylist/easylist_allowlist.txt
- easyprivacy/easyprivacy_allowlist_international.txt
https://kaaoszine.fi/children-of-bodomin-entinen-kitaristi-roope-latvala-chaoszinen-videohaastattelussa-bandista-potkujen-saannin-myota-elamasta-katosi-pohja-mutta-olen-nyt-viime-ajat-kirjoittanut-paljon-uutta-musiikk/
EL and EP remove "Lue myös nämä" (Also read these) section:
> P: kaaoszine.fi (fix also read article section removal)

- easylist/easylist_specific_hide.txt
filter to hide placeholders on poki.com. 
[Sample URL](https://poki.com/en/g/subway-surfers)
`poki.com##div[class^="Advertisement__AdvertisementContainer"]`
> A: https://poki.com/

- easyprivacy/easyprivacy_specific_international.txt
> A: https://www.sohu.com/a/488013591_267106

- fanboy-addon/fanboy_social_international.txt
> A: https://www.lizhi.fm/

- easyprivacy/easyprivacy_specific_international.txt
You must be **_logged in_** to see these trackers
> A: https://pan.baidu.com/disk/home

- easylist/easylist_adservers.txt
https://elmotv.com/
Can be found on many page's source code: https://publicwww.com/websites/interactiveads.ai/
> A: elmotv.com (generic adserver)

- easylist_cookie/easylist_cookie_specific_uBO.txt
https://paihdelinkki.fi/
Generic filter causes occasionally blinking issues, added a specific filter to avoid blinking.
> A: paihdelinkki.fi (cookie hide uBO)

- easyprivacy/easyprivacy_allowlist_international.txt
https://www.power.fi/puhelimet-ja-kamerat/alykellot-ja-puettavat-laitteet/alykellot/samsung-galaxy-watch4-classic-46-mm-bt-hopeahopea/p-1192405/
1. Click a button to send a review
2. There will a warning "Ole hyvä ja poista mainosten esto, joka voi estää onnistuneen arvostelun esittämisen." (Please disable adblocking that might prevent sending a review successfully.)
3. Fill required fields and click "Lähetä arvostelu" (Send a review)
4. There will be notification about unsuccessful sending: "Mainosten esto esti sinua esittämästä arvostelun. Poista mainosten esto käytöstä tältä sivulta, yritä sitten uudelleen lähettää arvostelusi." (Adblocking prevented you from sending a review. Disable adblocking for this site and then try again send your review).
> P: power.fi (EP prevents sending product reviews)

- easyprivacy/easyprivacy_allowlist_international.txt
https://elisa.fi/kauppa/puhelinliittymat
Fix for endless loading:
> P: elisa.fi (endless loading)

- easylist_cookie/easylist_cookie_general_block.txt
> A: anna.fi (generic cookie block)

- easyprivacy/easyprivacy_allowlist_international.txt
https://github.com/easylist/easylist/pull/9037#issuecomment-915999830
> P: https://support.nec-lavie.jp/driverlist?searchType=1 (update #9037)

- easylist/easylist_general_block.txt
https://github.com/abp-filters/abp-filters-anti-cv/issues/677
> A: https://mainnews.center/

- easylist_adult/adult_adservers.txt
**nsfw ads**
```
www.dwetwdstom1020.com/zone/21088/?autocamp=UP728x90
www.dwetwdstom1020.com/zone/21055/?autocamp=NTVA_300x250
```
> A: #8996 (itsup.com)

- easylist_adult/adult_specific_block.txt
**nsfw**
```
spankbang.com/
spankbang.com/s/azerty/
```
> A: (nsfw) spankbang.com

- easyprivacy/easyprivacy_specific_international.txt
Ref: https://github.com/AdguardTeam/AdguardFilters/issues/90004#issuecomment-896715642
> M: Fixes https://github.com/AdguardTeam/AdguardFilters/issues/90004

- easylist/easylist_allowlist.txt
Remove cnn exceptions that are no longer needed in https://github.com/easylist/easylist/commit/2c6419a37eafcb20a6c971f11e9c59bbc7f4d767
> M: Remove duplicate cnn exception filters

- easylist_cookie/easylist_cookie_general_hide.txt
> A: velimark.com (generic cookie hide)

- fanboy-addon/fanboy_annoyance_international.txt
This is a floating annoying element that interferes with the user's normal navigation
> A: http://www.jzhx.net/gjb

- easyprivacy/easyprivacy_specific_international.txt
This is the script used to report
> A: https://blog.csdn.net/nyist_zxp/article/details/120031279

- easyprivacy/easyprivacy_thirdparty_international.txt
`https://www.iltalehti.fi/`
`https://publicwww.com/websites/%22dnt-userreport.com%22/`
> A: iltalehti.fi (tracking server)

- easylist/easylist_allowlist.txt
- easylist/easylist_allowlist_general_hide.txt
> P: https://www.libhunt.com/t/ublock-origin

- easylist/easylist_specific_hide.txt
Remove "sponsor" sidebar on https://ldjam.com/
> A: https://ldjam.com/

- easylist_cookie/easylist_cookie_specific_uBO.txt
EasyList Cookie breaks scrolling.
`https://luhta.com/fi/fi`
> luhta.com - Fix scrolling

- easyprivacy/easyprivacy_specific_international.txt
- fanboy-addon/fanboy_annoyance_international.txt
This should be the tracker
Another problem is that there is also an annoying element here that reminds users to turn off the ad filter
> A: https://www.iqiyi.com/

- easyprivacy/easyprivacy_allowlist_international.txt
> P: www.benesse-style-care.co.jp

- easyprivacy/easyprivacy_specific_international.txt
Sample pages:
https://www.nettimoto.com/
https://www.nettikone.com/
There are more as well.
> A: nettimoto.com (tracking pixel)

- easylist/easylist_specific_hide.txt
hides ad containers; fixes #9095; removes outdated rules
> A: https://www.tumblr.com/

- easyprivacy/easyprivacy_specific_international.txt
- fanboy-addon/fanboy_annoyance_international.txt
- fanboy-addon/fanboy_social_allowlist.txt
- fanboy-addon/fanboy_social_allowlist_general_hide.txt
You should **login** to see these
1. Tracker exists on this page
<details>
</details>
2. There are self-promoting pop-ups on this page (I'm sorry I can't reproduce them at the moment, so I can't provide screenshots at the moment)
3. The icon for sharing files is blocked and the sharing element is also hidden, disrupting normal function
<details>
</details>
> P: https://www.weiyun.com/disk

- easylist_cookie/easylist_cookie_specific_uBO.txt
https://www.ylasatakunta.fi/
Specific hiding rule for uBO, due to blinking issue with generic filter.
> A: ylasatakunta.fi (cookie specific hide uBO)

- easylist_cookie/easylist_cookie_international_specific_hide.txt
> A: lauttakyla.fi (cookie hiding)

- easyprivacy/easyprivacy_allowlist_international.txt
> P: https://mangaseek.net/magazine/618.html

- easylist_adult/adult_specific_hide.txt
```
https://www.igayporn.tv/video/2011971/infornia-sc3.php
```
- https://github.com/Import-External-Sources/pornhosts/issues/255
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/1024
<details><summary>Click to expand</summary>
</details>
- uBlock filters
- uBlock filters – Badware risks
- uBlock filters – Privacy
- uBlock filters – Resource abuse
- EasyList
- EasyPrivacy
- Online Malicious URL Blocklist
- Peter Lowe’s Ad and tracking server list
- Spirillen's – Adblock Rules (https://mypdns.org/my-external-stuff/ublockorigin-rules/)
- OS/version: Ubuntu 20.04.2
- Browser/version: Tor-Browser & FF latest stable from Ubuntu repo
- Adblock Extension/version: uBlock Origin 1.37.2
> NSFW: igayporn.tv (##.ae-player__itv)

- easylist_adult/adult_specific_hide.txt
Player overlay for popunder + redirect
Related externals
- https://github.com/Import-External-Sources/pornhosts/issues/249
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/1051
> NSFW: hqasianporn.org##.coverup

- easylist_cookie/easylist_cookie_international_specific_hide.txt
> A: alasatakunta.fi / lapuansanomat.fi (cookie banner hide)

- fanboy-addon/fanboy_social_allowlist.txt
https://www.forssanlehti.fi/
After whitelisting:
> P: forssanlehti.fi (title of the page not loaded)

- easylist_adult/adult_specific_hide.txt
Closes https://github.com/easylist/easylist/issues/9238
Other related places:
- https://github.com/Import-External-Sources/pornhosts/issues/259
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/1019
> NSFW: japaneseporn.xxx #9238

- easylist_cookie/easylist_cookie_international_specific_hide.txt
> NSFW: sexedchat.com (Cookie banner.)

- easylist_cookie/easylist_cookie_specific_uBO.txt
To fix blinking issues on uBO, specific cosmetic filters are needed.
https://luhta.com/
> A: luhta.com (specific cookie hide for uBO)

- fanboy-addon/fanboy_annoyance_international.txt
- fanboy-addon/fanboy_social_international.txt
You may need to **login** to view this content
There are some annoying elements on this page, as well as share buttons
> A: https://tieba.baidu.com/index.html

- easylist/easylist_specific_hide.txt
New ad container spotted (`adTimelineObject`)
> A: www.tumblr.com/dashboard

- easylist_cookie/easylist_cookie_international_specific_hide.txt
URL: `https://kalkulatori.lv/en/`
> kalkulatori.lv (cookies)

- easylist/easylist_specific_hide.txt
Filter for hide placeholders all over the page [puzzlegarage](https://puzzlegarage.com)
Proposed filter: `puzzlegarage.com##.banner--inside`
Screenshot:
> A: https://puzzlegarage.com

- easylist_cookie/easylist_cookie_international_specific_hide.txt
Sample link: https://www.apteekkari.fi/uutiset/farmasian-opetus-hakee-vauhtia-virtuaalitodellisuudesta
> A: apteekkari.fi (cookie hide specific)

- easylist_cookie/easylist_cookie_international_specific_block.txt
Cookie script.
Sample sites:
https://www.prisma.fi/
https://www.alepa.fi/
https://www.sokoshotels.fi/
https://www.foodie.fi/
https://www.raflaamo.fi/fi
> A: prisma.fi (gdpr block)

- fanboy-addon/fanboy_annoyance_specific_hide.txt
**Issue URL (Annoyance)**: https://africacheck.org/fact-checks/fbchecks/woman-gives-birth-puppies-no-humans-and-dogs-cant-reproduce
> africacheck.org

- fanboy-addon/fanboy_social_specific_hide.txt
**Issue URL (Annoyance)**: https://ceoworld.biz/2021/06/20/the-worlds-best-countries-for-quality-of-life-2021/
> ceoworld.biz

- easylist_adult/adult_specific_hide.txt
Filter for hiding side and bottom ads at [cumlouder](https://www.cumlouder.com/)
Proposed filter: `cumlouder.com##[class^="sml-"]`
<details>
</details>
> A: [NSFW] https://www.cumlouder.com/

- easylist/easylist_specific_hide.txt
Fixes https://github.com/easylist/easylist/issues/8076
> M: videogameschronicle.com

- easylist/easylist_specific_hide.txt
`https://www.playstationtrophies.org/`
> A: playstationtrophies.org (Ad placeholder)

- fanboy-addon/fanboy_annoyance_international.txt
> A: https://www.mothhel.net/post/62263 (mobile user agent)

- easyprivacy/easyprivacy_thirdparty.txt
> A: https://signup.oxfordclub.jp/six_forever_stocks_s_gdn

- easylist_adult/adult_adservers.txt
Filter for blocking NSFW adserver responsible for popunders at [theyarehuge](https://www.theyarehuge.com/)
Proposed filter: `||shemale.house^$third-party`
Screenshots:
> A: [NSFW] https://www.theyarehuge.com/

- easylist_adult/adult_specific_block.txt
- easylist_adult/adult_specific_hide.txt
Filter for blocking script responsible for ads + filter to hide placeholders at [amateur8.com](https://www.amateur8.com/)
```
||amateur8.com/nb/frot_lod.js
amateur8.com##.is-av
```
<details>
</details>
> A: [NSFW] https://www.amateur8.com/

- easylist_adult/adult_specific_block.txt
Filter for blocking popunders at [txxx](https://txxx.com/)
Proposed filter: `||txxx.com/diarrhoeatablets/`
Screenshot:
> A: [NSFW] https://txxx.com/

- easylist_adult/adult_specific_block.txt
Filter to block script responsible for ads at [tube-bunny](https://www.tube-bunny.com/)
Proposed filter: `||bunnycontents.com/f.js`
Screenshot:
> A: [NSFW] https://www.tube-bunny.com/

- easylist/easylist_specific_hide.txt
Filter to hide amazon ads at [flicksmore](https://www.flicksmore.com/)
Proposed filter: `flicksmore.com###pc_show`
Screenshots:
> A: https://www.flicksmore.com/

- easyprivacy/easyprivacy_specific_international.txt
You need to login in order to view this tracker.
> A: https://mail.qq.com/

- easyprivacy/easyprivacy_allowlist_international.txt
This is in the wrong place, not a Finnish site.
> M: collectandgo.be

- easylist_adult/adult_specific_block.txt
Filter to block popunders at [hotmovs](https://hotmovs.com/)
Proposed filter: `||hotmovs.com/suhum/`
Screenshots:
> A: [NSFW] https://hotmovs.com/

- easylist/easylist_adservers.txt
Filter to block adserver related to popup messages inside the video at [animekisa](https://animekisa.tv/mushoku-tensei-isekai-ittara-honki-dasu-2nd-season-episode-7)
Proposed filter: ||daipsuwi.net^
Screenshot:
> A: https://animekisa.tv/

- easylist_cookie/easylist_cookie_general_hide.txt
https://hammasoskari.fi/
Wait a white for the banner to appear.
> A: hammasoskari.fi (generic cookie hide)

- easylist/easylist_specific_hide.txt
Filter to hide banner ads at : [hltv](https://www.hltv.org/)
Proposed filter: `hltv.org##.bitskins`
Screenshot:
> A: https://www.hltv.org/

- easylist/easylist_general_hide.txt
Site to test: https://tsri.ch/zh/derby-pizza-pizza-niente-rothausbar-kreis4/
> A: https://tsri.ch/

- easylist_adult/adult_specific_hide.txt
Ref: https://mypdns.org/my-privacy-dns/porn-records/-/issues/1593
> 3dtube.xxx##.promotionbox

- easylist_cookie/easylist_cookie_specific_hide.txt
> globalblue (cookies)

- easylist/easylist_adservers.txt
- easylist/easylist_specific_block.txt
Filters to block adserver and block image at [freebookspot](http://www.freebookspot.club/)
Screenshot:
> A: http://www.freebookspot.club/

- easylist_cookie/easylist_cookie_specific_uBO.txt
https://elisa.fi/
Added a specific filter to overcome blinking issues caused by generic filter.
> A: elisa.fi (specific cookie hide, uBO)

- fanboy-addon/fanboy_annoyance_specific_hide.txt
https://i.postimg.cc/bwKVrvGn/image.png
> A: https://mail.zoho.com/zm/#mail/folder/inbox

- easyprivacy/easyprivacy_trackingservers_international.txt
> A: ruohonjuuri.fi (stats server)

- easylist_cookie/easylist_cookie_international_specific_hide.txt
> A: fyndiq.fi (cookie banner hide)

- easylist/easylist_adservers_popup.txt
Block redirect popups at [ytmp3](https://ytmp3.cc/)
Screenshot:
> A: https://ytmp3.cc/

- easylist/easylist_adservers.txt
Block adserver related to redirect popups at [gogoanime](https://gogoanime.wiki/)
Proposed filter: `||lmntcjtrhcjrlc.top^`
Screenshot:
> A: https://gogoanime.wiki/

- easylist/easylist_adservers.txt
Filter to block ads at [fxporn](http://www.fxporn.net/)
Proposed filter: `||wcjlsohd.com^`
Screenshot:
> A: [NSFW] http://www.fxporn.net/

- easylist/easylist_adservers.txt
External source:
- https://mypdns.org/my-privacy-dns/matrix/-/issues/3600
- `https://jistenbefor.space/SkpkUXkxaBcmJj84CHNDaCIQJQk5cEt%2BDDkvFiIdOCMSNFcpJQl%2BCj1kDiJbZmgXPB9ocFV9WzknEnNDaHlKZVtmaBAwHhUjAHNDaHJTZUt5fEZ9Wzk%2FBg4QLnhGa1t5c1NjSil8VHwffn4HfE1yfQV8QSt6UXwaenxcZBpzeVAwHCloGQ`
Closes https://github.com/easylist/easylist/issues/9802
> jistenbefor.space #9802

- easylist_adult/adult_specific_hide.txt
Hide bottom banner at [xfantansy](https://xfantazy.com/)
screenshot:
> A: [NSFW] https://xfantazy.com/

- easyprivacy/easyprivacy_specific_international.txt
> A: https://www.sogou.com/web?query=Test

- easyprivacy/easyprivacy_specific_international.txt
> A: https://new.qq.com/newsvideo.htm#/cover/mzc002008ssw79b/j3307cbquqh

- easylist/easylist_adservers.txt
Block adserver related to redirect popups at [skidrowreloaded](https://www.skidrowreloaded.com/)
Proposed filter: `||ormome.com^`
Screenshot:
> A: https://www.skidrowreloaded.com/

- fanboy-addon/fanboy_annoyance_international.txt
https://github.com/AdguardTeam/AdguardFilters/issues/101165
> P: newsis.com

- easyprivacy/easyprivacy_trackingservers.txt
Admiral homepage: https://www.getadmiral.com/.
> Add another Admiral host

- easyprivacy/easyprivacy_thirdparty_international.txt
Re-opening this: https://github.com/easylist/easylist/pull/9793
The generic filter that was added by ryanbr was good generic but still the filter I proposed is needed as well.
>  A: aamulehti (statistics)

- easylist_cookie/easylist_cookie_general_hide.txt
```
scootergear.dk
```
- 
- uBlock filters
- uBlock filters – Badware risks
- uBlock filters – Privacy
- uBlock filters – Resource abuse
- EasyList
- EasyPrivacy
- Online Malicious URL Blocklist
- Peter Lowe’s Ad and tracking server list
- Spirillen's – Adblock Rules (https://mypdns.org/my-external-stuff/ublockorigin-rules/)
- OS/version: Ubuntu 20.04.2
- Browser/version: Tor-Browser & FF latest stable from Ubuntu repository (apt-get)
- Adblock Extension/version: uBlock Origin 1.38.6
> scootergear.dk

- easyprivacy/easyprivacy_allowlist_international.txt
`https://b-cloud.templatebank.com/brother/`
When you click on the highlighted button on the screenshot, nothing happens.
</details>
The following pop-up window will appear.
</details>
You can access the website from November to early January every year.
> P: https://b-cloud.templatebank.com/brother/

- fanboy-addon/fanboy_annoyance_specific_hide.txt
Supplement to https://github.com/easylist/easylist/pull/9705
> book.dmm.co.jp #9705

- fanboy-addon/fanboy_annoyance_international.txt
> A: https://pan.baidu.com/s/1HHtHltCCitsfmJGNsx6Fig

- easylist_cookie/easylist_cookie_international_specific_hide.txt
> A: epressi.com (cookie banner hide)

- easylist_cookie/easylist_cookie_general_hide.txt
> A: autokeskus.fi (cookie banner generic hide)

- easyprivacy/easyprivacy_allowlist_international.txt
Fixes https://github.com/finnish-easylist-addition/finnish-easylist-addition/issues/367
> P: hobbyhall.fi (content won't load)

- easylist/easylist_specific_hide.txt
Hide ad placeholders at https://chromoscience.com/
proposed filter: `chromoscience.com##.wpa`
Screenshot:
> A: https://chromoscience.com/

- easylist_adult/adult_specific_hide.txt
Hide ads placeholder inside the videos at https://www.deviants.com/
Proposed filter: `deviants.com###_iframe_content`
Screenshot:
> A: [NSFW] https://www.deviants.com/

- easylist_adult/adult_specific_block.txt
- easylist_adult/adult_specific_hide.txt
Filter to block image ads + placeholders at https://www.porn300.com/
Proposed filters: `||pics99.porn300.com` Maybe it could be `||pics99.*.com`
`||porn300.com/nbjs/`
Placeholders: `porn300.com##.wrapper__related-sites` Maybe it could be `porn300.com##[class*="related-sites"]`
`porn300.com##[class^="abcnn_"]`
Screenshots:
> A: [NSFW] https://www.porn300.com/

- easylist_adult/adult_specific_hide.txt
Hide top banner at https://pornguide.info/
Proposed filter: `pornguide.info##.twp-adv-header`
Screenshot:
> A: [NSFW] https://pornguide.info/

- easylist_adult/adult_specific_block.txt
- easylist_adult/adult_specific_hide.txt
Block redirect popups at https://chikiporn.com/
```
||chikiporn.com/poppy/
/^https?:\/\/.*\/.*sw[0-9._].*/$script,xmlhttprequest
```
Hide placeholders: `chikiporn.com##.thumb--adv`
Screenshots:
> A: [NSFW] https://chikiporn.com/

- easylist/easylist_adservers.txt
Block adserver at https://yts.mx/
Proposed filter: `||sucloe.com^`
Screenshot:
> A: https://yts.mx/

- easylist_adult/adult_specific_hide.txt
Hide placeholders at https://crocotube.com/
Screenshots:
> A: [NSFW] https://crocotube.com/

- easylist/easylist_thirdparty.txt
- easylist_adult/adult_thirdparty.txt
Block redirect popups at https://efukt.com/
`||d31qbv1cthcecs.cloudfront.net^`
`||icfcdn.com^$third-party`
Screenshots:
> A: [NSFW] https://efukt.com/

- easyprivacy/easyprivacy_general.txt
Address: `https://www.yuketang.cn/training/index`
Tracker link: `https://www.yuketang.cn/video-log/log/track/`
> A: https://www.yuketang.cn/training/index

- easylist/easylist_adservers.txt
- easylist/easylist_specific_block.txt
Block adservers at https://manhuascan.com/
```
||amyrinunshoed.com^
||strandicterus.com^
```
Screenshots:
Screenshots:
> A: https://manhuascan.com/

- easylist/easylist_adservers.txt
Block adserver responsible for redirect popups at https://www.dramacool9.c0/
> A: https://www.dramacool9.co/

- easylist/easylist_specific_hide.txt
Hide side banner at https://www.visualcapitalist.com/
screenshot:
> A: https://www.visualcapitalist.com/

- easylist/easylist_adservers.txt
Block adservers 
||clucti.com
||yoiprqtykkhhfq.com - added in https://github.com/easylist/easylist/pull/9963
Screenshot:
> A: https://www4.watchseries.ninja/

- easylist/easylist_specific_hide.txt
Hide banners at https://coinlisting.info/
coinlisting.info#?#.panel:-abp-has(h3:-abp-contains(Sponsored Ad))
coinlisting.info###carousel-example-generic
> A: https://coinlisting.info/

- easylist/easylist_adservers.txt
- easylist/easylist_specific_block.txt
Block adservers responsible for redirect popups
https://srsone.top/show/the-good-doctor-s01e18/season/1/episode/18
`||jeersweepwaxworks.com`
https://strtpe.link/v/zlrgaG64BWIY6AR/The.Good.Doctor.S01E18.HDTV.x264-KILLERS.mkv.mp4
```
||azoqypmjsvulo.com
||sincerelyinnovationturner.com
||yoiprqtykkhhfq.com
||diiojifu.top
||strtpe.link/ppmain.js
```
Screenshots:
> A: https://srsone.top/ & https://strtpe.link/

- fanboy-addon/fanboy_notifications_specific_hide.txt
It's a sister domain for these: https://github.com/easylist/easylist/pull/9236
> A: tamperelainen.fi (install our app notify)

- easyprivacy/easyprivacy_allowlist_international.txt
First, as this is my first contribution here, I'd like to thanks you for spending this much time maintaining this list! :heart: 
**What this pull request does:**
- Fix the blank page for any authenticated pages on red-by-sfr.fr
- Remove obsolete/useless sfr exceptions
-----------
PS: I'm not sure to understand your naming convention for commits. I didn't find any info on the wiki or in a `CONTRIBUTING.md` file.
If `M:` is for modification then why is there `P:` (for Precision?). I guess `A:` is for addition of a new resource to block/whitelist.
> M/P: Update sfr.fr exceptions

- easylist/easylist_general_hide.txt
- easylist/easylist_specific_hide.txt
> A: heraldsheets.com

- easylist_cookie/easylist_cookie_specific_hide.txt
Adds `thisoldhouse.com##.m-privacy-options`
> Fix thisoldhouse.com cookie consent

- easyprivacy/easyprivacy_specific_international.txt
It is also concluded in https://github.com/privacy-protection-tools/anti-AD/blob/5963788fd10ce935fb057e6db425cde3a6c6f2d9/anti-ad-easylist.txt#L6240
> A: https://cloud.baidu.com/doc/SUGAR/s/Jkdzgmc01

- easylist/easylist_specific_hide.txt
Reported by user: [#4256](https://github.com/mediumkreation/IndianList/issues/4256)
**found in url:** https://indianexpress.com/
> A:indianexpress.com

- easylist/easylist_specific_hide.txt
I don't see all this banners as self-promo so here it is: 
`perfectdailygrind.com##.gpdgeng`
Screenshot:
> A: https://perfectdailygrind.com/

- easylist/easylist_adservers.txt
Block adserver responsible to redirect popups at http://watchsexandthecity.com/
> A: http://watchsexandthecity.com/

- easylist_cookie/easylist_cookie_international_specific_hide.txt
> P: vierumaki.fi (Hide cookie banner background overlay)

- fanboy-addon/fanboy_social_international.txt
> A: https://new.qq.com/omn/20211207/20211207A07LK400.html

- easyprivacy/easyprivacy_specific_international.txt
For more information, please see
https://github.com/uBlockOrigin/uAssets/pull/10350
https://github.com/easylist/easylist/pull/9509
> fix https://github.com/uBlockOrigin/uAssets/pull/10350 and fix https://github.com/easylist/easylist/pull/9509

- easylist/easylist_adservers.txt
Block adserver responsible for redirects
Screenshot:
> A: [NSFW] https://manhwax.com/

- easylist/easylist_adservers.txt
Block adserver (redirects)
Screenshot:
> A: https://www6.f2movies.to/

- easylist/easylist_specific_hide.txt
Reported by user: [#4256](https://github.com/mediumkreation/IndianList/issues/4256)
found in url: https://www.oneindia.com/ 
list of sister sites:
1. https://www.drivespark.com/
2. https://www.goodreturns.in
3. https://www.boldsky.com
4. https://www.filmibeat.com/ 
5. https://www.gizbot.com/
6. https://www.drivespark.com/
7. https://www.nativeplanet.com/
8.
> A: oneindia.com and sister sites

- easylist/easylist_adservers.txt
- easylist/easylist_specific_hide.txt
Block adserver related to banners at https://ww8.readonepiece.com/
Screenshots:
> A: https://ww8.readonepiece.com/

- easylist/easylist_adservers.txt
Block adserver at https://gogoanime.ac/
screenshots:
> A: https://gogoanime.ac/

- easylist/easylist_adservers.txt
Block adserver at https://ca123movies.com/
Screenshot:
> A: https://ca123movies.com/

- easylist/easylist_adservers.txt
Block adserver responsible for redirects at http://mangastream.mobi/
Screenshots:
> A: http://mangastream.mobi/

- fanboy-addon/fanboy_annoyance_international.txt
> A: https://m.qidian.com/book/1982186.html

- easylist/easylist_adservers.txt
Block adservers at https://porncomics.to/
Screenshots:
> A: [NSFW] https://porncomics.to/

- easylist_adult/adult_specific_block.txt
- easylist_adult/adult_thirdparty.txt
Block popunders at https://allporncomic.com/
Screenshots:
> A: [NSFW] https://allporncomic.com/

- easylist/easylist_adservers.txt
Block adservers related to Redirects and Popups at https://1anime.to/
Screenshots:
> A: https://1anime.to/

- easylist/easylist_adservers.txt
Block adservers at https://kissasians.org/
Screenshot:
> https://kissasians.org/

- easylist/easylist_adservers.txt
- easylist_adult/adult_specific_block.txt
Block adserver and scripts related to banner ads and popups at https://manga18fx.com/
Screenshots:
> A: [NSFW] https://manga18fx.com/

- easylist/easylist_adservers.txt
Block adservers at https://hentai20.com/
Screenshots:
> A: [NSFW] https://hentai20.com/

- easylist/easylist_adservers.txt
Block adservers responsible for redirect popups
Screenshots:
> A: https://animedao.to/

- easylist/easylist_adservers.txt
Block adservers responsible for banners and redirects at https://mangahub.io/
> A: https://mangahub.io/

- easylist/easylist_adservers.txt
Block adserver related to popunders at https://sxyprn.com/
Screenshots:
> A: [NSFW] https://sxyprn.com/

- easylist/easylist_adservers.txt
Block adserver related to redirects at http://www.grannyhd.net/
Screenshot:
> A: [NSFW] http://www.grannyhd.net/

- fanboy-addon/fanboy_annoyance_international.txt
> A: https://bbs.pcbeta.com/viewthread-1913063-1-1.html

- easylist_cookie/easylist_cookie_specific_uBO.txt
https://www.datakauppa.fi/
Hides cookie dialog and fixes scrolling.
> A: datakauppa.fi (cookie hide for uBO)

- easyprivacy/easyprivacy_specific_international.txt
> A: http://www.cntcm.com.cn/xueshu/2016-08/25/content_20007.htm

- easylist/easylist_adservers.txt
- easylist_adult/adult_adservers_popup.txt
Block adserver related to redirect popups
Screenshots:
> A: https://gomovies.lv/

- easylist/easylist_adservers.txt
Block adservers related to redirect popups and popup messages
Screenshots:
> A: https://herogayabmodeon.net/

- easylist/easylist_adservers.txt
Block adserver related to redirect popups
Screenshot:
> A: https://katmoviehd.nz/

- easylist_adult/adult_specific_block.txt
Block scripts related to ads at https://manhwa18.cc/
Screenshots:
> A: [NSFW] https://manhwa18.cc/

- easylist/easylist_adservers.txt
Closes https://github.com/easylist/easylist/issues/10210
<details><summary>note to self (@spirillen)</summary>
https://mypdns.org/my-privacy-dns/matrix/-/issues/4019
</details>
> paydemic.com #10210

- easyprivacy/easyprivacy_trackingservers.txt
Admiral homepage: https://www.getadmiral.com/.
> Add Admiral filter

- easylist/easylist_specific_hide.txt
Hide banner at https://goosegame.io/
Screenshot:
> A: https://goosegame.io/

- easylist_cookie/easylist_cookie_specific_uBO.txt
> P: https://www.withings.com/fi/en/ (Fix scrolling)

- fanboy-addon/fanboy_annoyance_international.txt
> A: https://mail.qq.com

- fanboy-addon/fanboy_annoyance_international.txt
> A: https://haokan.baidu.com/v?vid=5765942094359842803

- fanboy-addon/fanboy_annoyance_general_hide.txt
> A: https://www.bilibili.com/kuawan/2021zmdy/pc/

- easylist/easylist_adservers.txt
- easylist/easylist_specific_hide.txt
Block adserver related to redirects at https://pinoymovies.es/
Screenshot:
> A: https://pinoymovies.es/

- easylist/easylist_adservers.txt
Block adserver responsible for redirects at https://javdisk.com/
Screenshots:
> A: [NSFW] https://javdisk.com/

- easylist/easylist_adservers.txt
Block adserver at https://www.japscan.ws/
Screenshot:
> A: https://www.japscan.ws/

- easylist/easylist_specific_hide.txt
Hide banner at https://fmoviesto.cc/
Screenshots:
> A: https://fmoviesto.cc/

- easylist/easylist_thirdparty.txt
Block popup messages at https://wwv.la123movies.com/ (Gomo server)
Screenshot:
> A: https://wwv.la123movies.com/

- easylist_cookie/easylist_cookie_international_specific_hide.txt
> A: voima.fi (Hide cookie banner background overlay)

- easylist/easylist_adservers.txt
Block adserver related to banners at https://teenager365.com/
Screenshots:
> A: [NSFW] https://teenager365.com/

- easylist_cookie/easylist_cookie_general_hide.txt
- easylist_cookie/easylist_cookie_specific_hide.txt
This PR fixes https://github.com/easylist/easylist/issues/10303
I used a specific rule as I wanted to avoid breakage, however, I can switch to a generic one if needed
> Address asahi-kasei.com cookie consent

- easylist/easylist_specific_block.txt
- easylist_adult/adult_specific_block.txt
Block script related to redirect popups at https://hitomi.la/
Screenshot:
> A: [NSFW] https://hitomi.la/

- easylist/easylist_adservers.txt
Block adserver related to redirects at https://ww2.torrentz2.cyou/
Screenshots:
> A: https://ww2.torrentz2.cyou/

- easylist/easylist_adservers.txt
Block adserver at https://www.princessmovies.io/
Screenshot:
> A: https://www.princessmovies.io/

- easylist/easylist_adservers.txt
Block adserver at https://kissasian.watch/
Screenshots:
> A: https://kissasian.watch/

- easylist/easylist_adservers.txt
Block adserver related to redirects at https://komi-san.com/
Screenshot:
> A: https://komi-san.com/

- easylist/easylist_adservers.txt
Block adserver related to redirect popups and popup messages at https://gogoanime.run/
Screenshot:
> A: https://gogoanime.run/

- fanboy-addon/fanboy_social_general_hide.txt
Share button
This word may be misspelled
> A: http://blog.sina.com.cn/s/blog_635c86d50102zvmo.html

- easylist/easylist_adservers.txt
Block adservers at https://123moviesgoto.com/
Screenshots:
> A: https://123moviesgoto.com/

- easylist/easylist_adservers.txt
Block adserver responsible for redirects at https://dramacool1.org/
Screenshot:
> A: https://dramacool1.org/

- easylist/easylist_adservers.txt
Block adserver at https://www.dramacool9.at/
Screenshot:
> A: https://www.dramacool9.at/

- easylist_cookie/easylist_cookie_general_block.txt
> P: www.cookielaw.org

- easylist/easylist_adservers.txt
Block adservers at https://idolsblog.tv/
Screenshots:
> A: [NSFW] https://idolsblog.tv/

- easylist/easylist_adservers.txt
Block adserver at https://readcomiconline.li/
Screenshot:
> A: https://readcomiconline.li/

- easylist/easylist_specific_hide.txt
Hide placeholder at https://earnmoneyhub.com/#
Screenshot:
> A: https://earnmoneyhub.com/#

- easylist/easylist_adservers.txt
Block adserver at https://streamzz.to/
Screenshot:
> A: https://streamzz.to/

- easylist/easylist_adservers.txt
Block adservers related to redirect popups and popup messages at https://moviecrumbs.net/
Screenshots:
> A: https://moviecrumbs.net/

- easylist/easylist_adservers.txt
Block adserver at https://www.webcamrips.com/
Screenshots:
> A: [NSFW] https://www.webcamrips.com/

- easylist_cookie/easylist_cookie_international_specific_hide.txt
> A: https://www.tekniikkaosat.fi/

- easylist/easylist_adservers.txt
- easylist_adult/adult_specific_hide.txt
Hide banners and link ads at https://javgg.net/
Screenshots:
> A: [NSFW] https://javgg.net/

- easylist/easylist_adservers.txt
Block adserver related to redirects at https://ruvideos.net/
Screenshot:
> A: [NSFW] https://ruvideos.net/

- easylist/easylist_adservers.txt
Block adserver at https://ettv.unblockit.how/
Screenshot:
> A: https://ettv.unblockit.how/

- easylist/easylist_adservers.txt
Block adserver responsible for redirects at https://1337x.unblockit.how/
Screenshots:
> A: https://1337x.unblockit.how/

- easylist_adult/adult_specific_block.txt
- easylist_adult/adult_specific_hide.txt
Block scripts related to banners + text placeholders at https://buondua.com/
Screeenshots:
> A: [NSFW] https://buondua.com/

- easylist/easylist_adservers.txt
Popup messages at http://1stream.top/game/OTEwMzMzNjY=?sport=*
Screenshot:
> A: http://1stream.top/

- easylist/easylist_adservers.txt
Block adserver related to popup messages at https://beginningmanga.com/
Screenshots:
> A: https://beginningmanga.com/

- easylist/easylist_adservers.txt
Block adserver at https://www.mp3juices.cc/
Screenshot:
> A: https://www.mp3juices.cc/

- easylist/easylist_adservers.txt
Block adserver responsible for redirects at http://tamilyogi.best/
Screenshot:
> A: http://tamilyogi.best/

- easylist/easylist_adservers.txt
Block adserver at https://www3.musichq.net/
Screenshot:
> A: https://www3.musichq.net/

- easylist/easylist_adservers.txt
- easylist/easylist_specific_block.txt
- easylist/easylist_specific_hide.txt
Block adserver responsible for redirects, third-part script related to bg color + hide animation popup at https://www.lineageos18.com/
Screenshots:
> A: https://www.lineageos18.com/

- easylist/easylist_adservers.txt
Block adserver related to redirects at https://7hitmovies.bond/
Screenshot:
> A: https://7hitmovies.bond/

- easylist/easylist_adservers.txt
Block adserver responsible for ads at https://manhwa18.net/
Screenshots:
> A: [NSFW] https://manhwa18.net/

- easylist/easylist_specific_hide.txt
Hide placeholder + ad at https://www.polygon.com/
Screenshots:
> A: https://www.polygon.com/

- easyprivacy/easyprivacy_allowlist_international.txt
At https://netmede.pt/, if you don't allow netmede.pt/code/ga.min.js the site breaks the main button "INICIAR TESTE" click event
> Allow netmede.pt/code/ga.min.js

- easylist/easylist_adservers.txt
Block adservers related to redirects at https://www.livegore.com/
Screenshot:
> A: https://www.livegore.com/

- easylist/easylist_adservers.txt
Block adserver at https://www.uwatchfree.do/
Screenshot:
> A: https://www.uwatchfree.do/

- easylist/easylist_adservers.txt
Block adserver at https://yts.torrentbay.to/
Screenshot:
> A: https://yts.torrentbay.to/

- easylist/easylist_specific_block.txt
Block third-party script responsible for redirects at https://animebee.to/
Screenshot:
> A: https://animebee.to/

- easylist/easylist_adservers.txt
Block Streamtape adserver at https://voiranime.com/anime/tesla-note/tesla-note-01-vostfr/
(French webpage, but third-party streamtape EN)
Screenshot:
> A: https://voiranime.com/

- easylist/easylist_specific_hide.txt
Hide button placeholder at https://kissanime.com.ru/
Screenshot:
> A: https://kissanime.com.ru/

- easylist/easylist_specific_block.txt
- easylist_adult/adult_adservers.txt
Block third-part API at https://flizmovies.cc/
Screenshots:
> A: [NSFW] https://flizmovies.cc/

- easylist/easylist_adservers.txt
Block adserver at https://nitroscans.com/
Screenshot:
> A: https://nitroscans.com/

- easylist_cookie/easylist_cookie_allowlist_general_hide.txt
- fanboy-addon/fanboy_annoyance_allowlist_general_hide.txt
> M: https://attestation.app/privacy-policy, https://grapheneos.org/faq

- easylist/easylist_general_hide.txt
Replacement for https://github.com/easylist/easylist/pull/10504/
> M: https://m.dict.cc/

- easylist/easylist_adservers.txt
Block adserver related to redirects at http://kissmanga.nl/
Screenshot:
> A: http://kissmanga.nl/

- easylist/easylist_adservers.txt
Block adsever at https://chroniclesofheavenlydemon.com/
Screenshots:
> A: https://chroniclesofheavenlydemon.com/

- easylist/easylist_adservers.txt
Block adserver at https://nudeof.com/
Screenshot:
> A: [NSFW] https://nudeof.com/

- easylist/easylist_adservers.txt
Block adserver at https://porn7days.xyz/
Screenshot:
> A: [NSFW] https://porn7days.xyz/

- easylist/easylist_adservers.txt
Block adserver at https://povcum.com/
Screenshot:
> A: [NSFW] https://povcum.com/

- easylist/easylist_adservers.txt
Block adserver at https://fbstream.tv/
Screenshot:
> A: https://fbstream.tv/

- easylist/easylist_adservers.txt
Block adserver at https://moviesjoy.to/
Screenshot:
> A: https://moviesjoy.to/

- easylist/easylist_adservers.txt
block adserver at https://mult34.com/
Screenshot:
> A: [NSFW] https://mult34.com/

- easylist/easylist_adservers.txt
Block adserver at https://youporn.fyi/
Screenshot:
> A: [NSFW] https://youporn.fyi/

- easylist/easylist_adservers.txt
Block adserver at https://kantotinyo.com/
Screenshot:
> A: [NSFW] https://kantotinyo.com/

- easylist/easylist_adservers.txt
Block adserver at https://animedao-tv.com/
Screenshot:
> A: https://animedao-tv.com/

- easylist/easylist_adservers.txt
Block adserver at https://ca.stream2watch.sx/
Screenshot:
> A: https://ca.stream2watch.sx/

- easylist/easylist_adservers.txt
Block adserver at https://www.dnoid.to/
Screenshot:
> A: https://www.dnoid.to/

- easylist/easylist_adservers.txt
Block adserver at http://www.incestflix.com/
Screenshot:
> A: [NSFW] http://www.incestflix.com/

- easylist/easylist_adservers.txt
Block redirects at https://tabooporns.com/
Screenshot:
> A: [NSFW] https://tabooporns.com/

- easylist/easylist_adservers.txt
Block adserver responsible for redirects at https://fmmods.com/
Screenshots:
> A: https://fmmods.com/

- easylist/easylist_adservers.txt
Block adserver related to redirect popups at https://animenana.com/
Screenshot:
> A: https://animenana.com/

- easylist/easylist_adservers.txt
Block adserver related to redirect popups at https://kissasia.cc/
Screenshots:
> A: https://kissasia.cc/

- easylist/easylist_adservers.txt
- easylist/easylist_specific_hide.txt
Block Adserver + fake buttons at https://yifymovies.one/
Screenshots:
> A: https://yifymovies.one/

- easylist/easylist_adservers.txt
Block redirects at https://avgle.com/
Screenshots:
> A: [NSFW] https://avgle.com/

- easylist_cookie/easylist_cookie_general_hide.txt
> A: sign.aatos.app (generic cookie hide)

- easylist_adult/adult_specific_hide.txt
Hide side banners at https://familyporn.tv/
Screenshot:
> A: [NSFW] https://familyporn.tv/

- easylist/easylist_adservers.txt
Block adservers at https://dramacool.pk/
Screenshot:
> A: https://dramacool.pk/

- easylist/easylist_adservers.txt
Block adserver at https://ww22.watchfilm.net/
Screenshot:
> A: https://ww22.watchfilm.net/

- easylist/easylist_adservers.txt
Block adserver at https://kimcartoon.li/
Screenshot:
> A: https://kimcartoon.li/

- easylist/easylist_adservers.txt
Block adserver at https://dramacool.by/
Screenshot:
> A: https://dramacool.by/

- easylist/easylist_adservers.txt
Block adserver at https://camcaps.to/
Screenshot:
> A: [NSFW] https://camcaps.to/

- easylist/easylist_adservers.txt
Block adservers at https://pastemytxt.com/
Screenshot:
> A: https://pastemytxt.com/

- easylist/easylist_adservers.txt
Block adservers at https://hdmoviesflix.rest/
Screenshots:
> A: https://hdmoviesflix.rest/

- easylist/easylist_adservers.txt
Block adserver at https://projectfreetv2.com/home/ 
Screenshots:
> A: https://projectfreetv2.com/

- easylist/easylist_adservers.txt
Block adserver at https://supjav.com/
Screenshot:
> A: [NSFW] https://supjav.com/

- easylist/easylist_adservers.txt
Block adserver at https://w1.123animes.mobi/
Screenshot:
> A: https://w1.123animes.mobi/

- easylist/easylist_adservers.txt
Block adservers at http://kissorg.net/
Screenshot:
> A: http://kissorg.net/

- easylist/easylist_adservers.txt
Block adservers at https://sexvibe.me/
Screenshots:
> A: [NSFW] https://sexvibe.me/

- easylist/easylist_adservers.txt
Block adserver at https://movgotv.com/
Screenshot:
> A: https://movgotv.com/

- easylist/easylist_adservers.txt
Block adserver at http://javtorrent.re/
Screenshot:
> A: [NSFW] http://javtorrent.re/

- easylist/easylist_adservers.txt
Block adserver at http://goodsexporn.org/
Screenshot:
> A: [NSFW] http://goodsexporn.org/

- easylist/easylist_adservers.txt
Block adservers at https://hayav.com/
Screenshot:
> A: [NSFW] https://hayav.com/

- easylist/easylist_adservers.txt
Block adservers at https://fap-nation.org/
Screenshot:
> A: [NSFW] https://fap-nation.org/

- easylist/easylist_adservers.txt
Block adserver at http://www.cloudisexy.com/
Screenshot:
> A: [NSFW] http://www.cloudisexy.com/

- easylist/easylist_adservers.txt
Block adserver at https://kissasian.li/
Screenshot:
> A: https://kissasian.li/

- easylist/easylist_adservers.txt
Block adserver at https://streamm4u.com/
Screenshot:
> A: https://streamm4u.com/

- easylist/easylist_adservers.txt
Block adservers at https://xfantasy.su/
Screenshot:
> A: [NSFW] https://xfantasy.su/

- easylist/easylist_adservers.txt
Block adservers at https://watchhouseonline.net/
Screenshot:
> A: https://watchhouseonline.net/

- easylist/easylist_adservers.txt
Block adserver at https://sukidesuost.info/
Screenshot:
> A: https://sukidesuost.info/

- easylist/easylist_adservers.txt
Block adserver at https://manhwa18.cc/
Screenshot:
> A: https://manhwa18.cc/

- easylist_cookie/easylist_cookie_allowlist.txt
Videos won't show up.
Sample link:
https://www.crunchyroll.com/attack-on-titan/episode-78-two-brothers-823856
> P: crunchyroll.com (broken videos)

- easylist/easylist_specific_hide.txt
Hide banners at https://www.mma-core.com/
Screenshot:
> A: https://www.mma-core.com/

- fanboy-addon/fanboy_newsletter_specific_hide.txt
* https://i.ibb.co/VJP1SY6/00.jpg
> A: https://www.jumia.com.eg/

- easylist_cookie/easylist_cookie_international_specific_hide.txt
https://www.arsadata.se/sv-se/default/
> A: arsadata.se (specific cookie hide)

- easylist_cookie/easylist_cookie_general_hide.txt
> A: aatos.app (generic cookie hide)

- easylist_cookie/easylist_cookie_allowlist_general_hide.txt
- easylist_cookie/easylist_cookie_general_hide.txt
- easylist_cookie/easylist_cookie_specific_uBO.txt
> A: voas.fi (generic cookie hide)

- easylist_cookie/easylist_cookie_general_hide.txt
> A: koas.fi (generic cookie hide)

- easylist/easylist_adservers.txt
Block adserver at https://javtiful.com/
Screenshot:
> A: [NSFW] https://javtiful.com/

- easylist/easylist_adservers.txt
Block adserver related to adult images at https://upornia.com/
Screenshot:
> A: [NSFW] https://upornia.com/

- easylist/easylist_adservers.txt
Block adserver at https://ww16.myheroacademiaepisodes.com/
Screenshot:
> A: https://ww16.myheroacademiaepisodes.com/

- easylist_adult/adult_specific_hide.txt
Hide top banner at https://hentaiworld.tv/
Screenshot:
> A: [NSFW] https://hentaiworld.tv/

- easylist/easylist_adservers.txt
Block adserver at http://iporntv.net/
Screenshot:
> A: [NSFW] http://iporntv.net/

- easylist/easylist_adservers.txt
Block adserver at https://eztv.re/ 
Screenshots:
> A: https://eztv.re/

- easylist/easylist_adservers.txt
Block adserver at https://soap2day.rs/
Screenshot:
> A: https://soap2day.rs/

- easylist/easylist_adservers.txt
Block adserver at https://www.hitprn.com/
Screenshot:
> A: [NSFW] https://www.hitprn.com/

- easylist/easylist_adservers.txt
Block adservers at https://gomovies.fan/
Screenshots:
> A: https://gomovies.fan/

- easylist/easylist_adservers.txt
Block adserver at https://123moviesme.online/
Screenshot:
> A: https://123moviesme.online/

- easylist/easylist_adservers.txt
Block adserver at https://123animehub.cc/
Screenshot:
> A: https://123animehub.cc/

- easylist/easylist_adservers.txt
Block adserver at https://123moviesh.to/
Screenshot:
> A: https://123moviesh.to/

- easylist/easylist_adservers.txt
Block adserver at https://asianleak.com/
Screenshot:
> A:[NSFW] https://asianleak.com/

- easylist/easylist_adservers.txt
Block adservers at https://internetchicks.com/
Screenshots:
> A: [NSFW] https://internetchicks.com/

- easylist/easylist_specific_hide.txt
Hide popups at https://mangadna.com/
Screenshot:
> A: https://mangadna.com/

- easylist_cookie/easylist_cookie_general_block.txt
https://www.jatehuoltoa.fi
https://publicwww.com/websites/%22sf-tagomo-privacy.js%22/
> A: jatehuoltoa.fi (generic cookie block)

- easylist/easylist_adservers.txt
Block adserver at https://www.kiss-anime.org/
Screenshot:
> A: https://www.kiss-anime.org/

- easylist/easylist_adservers.txt
Block adserver at https://www.y2meta.com/
Screenshot:
> A: https://www.y2meta.com/

- easylist/easylist_specific_hide.txt
Hide top banner ad at https://hdmovies4u.live/
Screenshot:
> A: https://hdmovies4u.live/

- easylist/easylist_specific_hide.txt
- fanboy-addon/fanboy_annoyance_specific_hide.txt
> A: https://www.amazon.co.jp/gp/cart/view.html?ref_=nav_cart

- easylist/easylist_adservers.txt
Block adserver at https://bazenation.com/
Screenshot:
> A: https://bazenation.com/

- easylist/easylist_adservers.txt
Block adserver at https://ww2.d123movies.to/
Screenshot:
> A: https://ww2.d123movies.to/

- easylist_adult/adult_specific_block.txt
Block banners at https://easyporn.xxx/
**Test as Mobile**
Screenshot:
> A: [NSFW] https://easyporn.xxx/

- easylist_adult/adult_specific_hide.txt
hide banner at https://www.uiporn.com/
Screenshot:
> A:[NSFW] https://www.uiporn.com/

- easylist_adult/adult_specific_hide.txt
Hide placeholder at https://gaysex.tv/
Screenshot:
> A: [NSFW] https://gaysex.tv/

- easylist_adult/adult_specific_block.txt
Block scripts related to popup banners at https://pornstargold.com/
Screenshot:
> A: [NSFW] https://pornstargold.com/

- easylist_adult/adult_specific_hide.txt
Hide partners banner at https://hclips.com/
Ps: snippet needed to stop admanager (popunders - check console tab):
`hclips.com#$#abort-current-inline-script mz`
Screenshot:
> A: [NSFW] https://hclips.com/

- easylist/easylist_adservers.txt
- easylist/easylist_specific_hide.txt
Block redirects + Hide popups at https://wwvv.vanime.co/
Screenshots:
> A: https://wwvv.vanime.co/

- easylist/easylist_adservers.txt
Block adserver at https://mangakik.com/
Screenshot:
> A: https://mangakik.com/

- easylist/easylist_adservers.txt
Block adserver at https://biggestchef.com/
Screenshot:
> A: https://biggestchef.com/

- easylist/easylist_adservers.txt
Block adservers at https://ww1.123moviesh.to/
Screenshot:
> A: https://ww1.123moviesh.to/

- easylist/easylist_adservers.txt
Block adserver at https://xvideos.wptri.com/
Screenshots:
> A: [NSFW] https://xvideos.wptri.com/

- easylist/easylist_adservers.txt
Block adserver responsible for redirects at https://manhuaus.com/
Screenshots:
> A: https://manhuaus.com/

- easylist/easylist_adservers.txt
Block adserver at https://ww2.123moviesfree.love/
Screenshots :
> A: https://ww2.123moviesfree.love/

- easylist/easylist_adservers.txt
Block adserver responsible for redirect popups at https://animasu.vip/
**Tested as mobile**
Screenshot:
> A: https://animasu.vip/

- easylist/easylist_adservers.txt
Block adserver responsible for redirects and banners between the comics
**Tested as mobile**
Screenshots:
> A: https://m.mangabat.com/

- easylist/easylist_adservers.txt
Block adserver responsible for redirect popups at https://www.freeomovie.to/
Screenshot:
> A: [NSFW] https://www.freeomovie.to/

- easylist_cookie/easylist_cookie_specific_hide.txt
> A: hbomax.com (specific cookie hide)

- easyprivacy/easyprivacy_allowlist.txt
**Problem**
- login impossible 
**SS**
- https://i.ibb.co/rtNvn4p/image.jpg
> P: https://easy-firmware.com/index.php?a=login

- easylist_cookie/easylist_cookie_specific_hide.txt
> A: notion.so (specific cookie hide)

- easylist/easylist_adservers.txt
Block adserver at https://www.animefrenzy.org/
Screenshot:
> A: https://www.animefrenzy.org/

- easylist/easylist_adservers.txt
Block adserver at https://kimoitv.com/
Screenshot:
> A: https://kimoitv.com/

- easylist/easylist_thirdparty.txt
Block popups/popunders at https://daftsex.com/
Screenshot:
> A: [NSFW] https://daftsex.com/

- easylist/easylist_adservers.txt
Block adserver at https://onepiece-mangaonline.com/
Screenshot:
> A: https://onepiece-mangaonline.com/

- easylist/easylist_thirdparty.txt
Block hosted adserver at https://www.watchonlinemovies77.com.pk/
Screenshot:
> A: https://www.watchonlinemovies77.com.pk/

- easylist/easylist_adservers.txt
- easylist/easylist_specific_hide.txt
Block adserver + hide banners at https://animexin.xyz/
Screenshots:
> A: https://animexin.xyz/

- easylist/easylist_specific_hide.txt
Hide popups at https://4anime.gg/
Screenshot:
> A: https://4anime.gg/

- easylist/easylist_adservers.txt
Block adserver at https://watchprettylittleliarsonline.com/
Screenshot:
> A: https://watchprettylittleliarsonline.com/

- easylist/easylist_adservers.txt
Block adserver at https://watchtheofficetv.com/
Screenshot:
> A: https://watchtheofficetv.com/

- easylist/easylist_adservers.txt
Block adserver at https://readmanganato.com/
Screenshot:
> A: https://readmanganato.com/

- easyprivacy/easyprivacy_general.txt
Add `tealium.co.jp` to exceptions.
`https://docs.tealium.co.jp/`
> P: https://docs.tealium.co.jp/

- easylist/easylist_specific_hide.txt
found in url: [ehitavada.com](https://www.ehitavada.com/)
**Reported by User: true**
Issue : https://reports.adblockplus.org/2e1348c0-2c9d-4090-9259-a6f664686e60#secret=0c546dc91145db46f316183db1341ca3
> A:ehitavada.com

- easylist/easylist_adservers.txt
Block adservers at https://5.182.209.164/
Screenshots:
> A: https://5.182.209.164/

- easylist/easylist_adservers.txt
Block adserver at https://w-123movies.com/
Screenshot:
> A: https://w-123movies.com/

- easylist/easylist_specific_hide.txt
Hide banner at http://stonetoss.com/
Screenshot:
> A: http://stonetoss.com/

- easylist/easylist_specific_block_popup.txt
They don't work and only filter user content
> obsolete rules removed

- easylist_cookie/easylist_cookie_specific_hide.txt
> A: unitedtalent.com (specific cookie hide)

- easylist/easylist_specific_hide.txt
> A: cityam.com (ad placeholders)

- easylist/easylist_adservers.txt
Block adservers at https://www.animelandtv.me/
Screenshot:
> A: https://www.animelandtv.me/

- easylist/easylist_adservers.txt
Block adservers at https://streamta.pe/e/9j1ppMPWr0Ha0MQ/ready
Screenshots:
> A: https://streamta.pe/

- easylist/easylist_adservers.txt
Block adserver at https://mangatuli.com/
Screenshot:
> A: https://mangatuli.com/

- easylist/easylist_adservers.txt
Block adserver at https://ww2.demonslayerepisodes.com/
Screenshot:
> A: https://ww2.demonslayerepisodes.com/

- easylist/easylist_adservers.txt
Block adserver at https://123chill.net/
Screenshot:
> A: https://123chill.net/

- easylist/easylist_adservers.txt
Block adservers at https://www.heavy-r.com/
Screenshots:
> A: [NSFW] https://www.heavy-r.com/

- easylist/easylist_specific_hide.txt
Hide popups at https://www.dulu.to/
Screenshot:
> A: https://www.dulu.to/

- easylist/easylist_adservers.txt
Block adserver at https://tinyzonetv.to/
Screenshot:
> A: https://tinyzonetv.to/

- easylist/easylist_adservers.txt
Block adservers at https://watchseries.ma/
Screenshot:
> A: https://watchseries.ma/

- easylist/easylist_adservers.txt
Block adserver at https://www.animeworld.tv/
Screenshot:
> A: https://www.animeworld.tv/

- easylist/easylist_adservers.txt
Block adserver at https://wiflix.pw/
Screenshot:
> A: https://wiflix.pw/

- easyprivacy/easyprivacy_allowlist_international.txt
> P: https://www.nittsu.com/Tracking/ja/Tracking/Enter

- easylist/easylist_specific_hide_abp.txt
Hide sponsored password manager section
Homepage
After entering email
https://www.troyhunt.com/have-i-been-pwned-is-now-partnering-with-1password/
> 1Password pays to get their product in front of people via HIBP
> A: https://haveibeenpwned.com/

- easylist/easylist_specific_hide.txt
Hide modal at https://193.178.172.113/
Screenshot:
> A: https://193.178.172.113/

- easylist/easylist_specific_hide.txt
Hide top banner at https://primcloud.careers/
Screenshot:
> A: https://primcloud.careers/

- easyprivacy/easyprivacy_allowlist_international.txt
https://www.apu.fi/
Same problem as was here: https://github.com/easylist/easylist/pull/8295
> P: apu.fi (section won't load)

- easylist/easylist_adservers.txt
Block adserver at https://www.xmegadrive.com/
Screenshot:
> A: [NSFW] https://www.xmegadrive.com/

- easylist/easylist_adservers.txt
Block adservers at https://azm.to/
Screenshot:
> A: https://azm.to/

- easylist/easylist_adservers.txt
Block adserver at https://www.mangaworld.in/
Screenshot:
> A: https://www.mangaworld.in/

- easylist/easylist_adservers.txt
Block adserver at https://mrworldpremiere.tv/
Screenshot:
> A: https://mrworldpremiere.tv/

- easylist/easylist_adservers.txt
Block adserver at https://www.sxyprn.com/
Screenshot:
> A: [NSFW] https://www.sxyprn.com/

- easylist/easylist_adservers.txt
Block adserver at http://givemenbastreams.com/
Screenshot:
> A: http://givemenbastreams.com/

- easylist/easylist_adservers.txt
Block adserver at https://kissasian.la/
Screenshot:
> A: https://kissasian.la/

- easylist/easylist_adservers.txt
Block adserver at https://123moviesgo.club/
Screenshot:
> A: https://123moviesgo.club/

- easylist/easylist_adservers.txt
Block adserver at https://kissasians.org/
Screenshot:
> A: https://kissasians.org/

- easylist/easylist_adservers.txt
Block adserver at http://w12.mangafreak.net/
Screenshot:
> A: http://w12.mangafreak.net/

- easylist/easylist_adservers.txt
Block adservers at https://javmovs.com/
Screenshot:
> A: [NSFW] https://javmovs.com/

- easylist/easylist_adservers.txt
Block adserver at https://aotonline.co/
Screenshot:
> A: https://aotonline.co/

- easylist_adult/adult_specific_hide.txt
hide placeholders at https://m.tnaflix.com/
**Mobile**
Screenshot:
> A: [NSFW] https://m.tnaflix.com/

- easylist_adult/adult_specific_block.txt
Block popunders at https://tubxporn.xxx/
Screenshot:
> A: [NSFW] https://tubxporn.xxx/
